AzureFunctions.Client/app/components/app.component.ts, AzureFunctions.Client/app/services/functions.service.ts, AzureFunctions.Client/app/services/ifunctions.service.ts, AzureFunctions.Client/app/services/mock-functions.service.ts, AzureFunctions/Code/UserSettings.cs, AzureFunctions/Common/Constants.cs
If the app component detects that we're in an iframe, it will wire-up callbacks so that the host can speak to the iframe.  For now we're only passing in a simple bearer token, but we can expand on that as new functionality is required.
=> Added support to receive token from iframe host window

AzureFunctions.Client/templates/function-integrate-v2.component.html
In __Integrate__ tab (Trigger --> Input --> Output), replaced decent-but-overstretched-arrows with better looking arrows:
__BEFORE__
__AFTER__
Tested in Edge (25.10586) and Chrome (49.0.something).
=> Fix Integrate tab SVG arrows

AzureFunctions.Client/templates/top-bar.component.html
Hiding the Monitoring tab on the Function App - temporarily (mostly for GA as well) until the APIs are updated.
=> DCR: Hiding the Monitoring tab for App level

AzureFunctions.Client/templates/function-dev.component.html
Addressing a pet peeve of mine. Just getting rid of a width=90% inline style so that the editor, logs, and run now take up more of the viewport instead of leaving dead space.
=> Removing whitespace in develop tab

AzureFunctions/ResourcesPortal/Resources.Designer.cs, AzureFunctions/ResourcesPortal/Resources.resx, AzureFunctions/ResourcesPortal/ja-JP/AzureFunctions/ResourcesPortal/Resources.resx, AzureFunctions/ResourcesPortal/ko-KR/AzureFunctions/ResourcesPortal/Resources.resx, AzureFunctions/ResourcesPortal/nl-NL/AzureFunctions/ResourcesPortal/Resources.resx, AzureFunctions/ResourcesPortal/pl-PL/AzureFunctions/ResourcesPortal/Resources.resx, AzureFunctions/ResourcesPortal/qps-ploc/AzureFunctions/ResourcesPortal/Resources.resx, AzureFunctions/ResourcesPortal/ru-RU/AzureFunctions/ResourcesPortal/Resources.resx, AzureFunctions/ResourcesPortal/sv-SE/AzureFunctions/ResourcesPortal/Resources.resx, AzureFunctions/ResourcesPortal/tr-TR/AzureFunctions/ResourcesPortal/Resources.resx, AzureFunctions/ResourcesPortal/zh-CN/AzureFunctions/ResourcesPortal/Resources.resx, AzureFunctions/ResourcesPortal/zh-TW/AzureFunctions/ResourcesPortal/Resources.resx
Spotted this while trying out the GitHub excellent web hook templates in the portal.
:heart:
=> Fix capitalization of GitHub in translations

AzureFunctions.Client/app/components/function-dev.component.ts
Fixes this stack
`
"TypeError: Cannot read property 'functionKey' of undefined
    at FunctionDevComponent.get [as functionInvokeUrl] (https://functions-next.azure.com/sfx/app.js?v=fe2781ed:22469:81)
    at DebugAppView._View_FunctionDevComponent3.detectChangesInternal (FunctionDevComponent.template.js:659:45)
`
=> check for host secrets to be null to avoid race condition between getting the secrets and trying to display them

AzureFunctions.Client/app/components/function-monitor.component.ts, AzureFunctions.Client/app/components/table-function-monitor.component.ts, AzureFunctions.Client/app/pipes/table-function-monitor.pipe.ts, AzureFunctions.Client/app/services/function-monitor.service.ts, AzureFunctions.Client/templates/table-function-monitor.html
Has fixes for the following
If a function has not run before, we don't know the functionId for it.  #731 
Functions portal: Display error messages  #622 
Monitor tab: remove 'running time' text  #678
=> Monitoring GA fixes

AzureFunctions.AngularClient/src/app/shared/function-app.ts
there are 3 changes here:
* `function-integrate-v2.component.ts` changes are to fix a bug when running locally or without --prod in general. The issue is that a value changes too quickly and you get an error from angular saying that a value changed after it was checked.  This happen if you have an unsupported `function.json` file, say if you have an unknown type for a binding in there.
* `monaco-editor.directive.ts` are needed due to the upgrade of angular cli. it writes the output into a folder called `ng` not `ng2app`.
* `function-app.ts` this change is to fix localize method there to properly localize objects.
=> fix localise method in function-app.ts

AzureFunctions.AngularClient/src/polyfills.ts
Should fix the bug where it won't run in IE11. We enabled the IE11 polyfills in `polyfills.ts`
Please test this in IE11
Technically, the error before was in `object.assign.apply`. So we may only need `import 'core-js/es6/object';`. Let's first test it with all of these enabled. Then, if that works, then we can try just this one file .... which is better so we bundle less. It's not a huge amount though .... so I recommend just enabling all of these polyfills for now.
=> enabled ie11 polyfills

AzureFunctions.AngularClient/src/app/shared/function-app.ts
`NoCorsHttpService` retries the same http request through the backend.
=> Switch some calls to _cacheService to NoCorsHttpService instead

AzureFunctions.AngularClient/src/app/shared/models/binding.ts
I found a misspelling in a property. It appears nothing else was using it. Please verify and merge
=> shcema --> schema

AzureFunctions.AngularClient/src/app/app.component.ts, AzureFunctions.AngularClient/src/app/shared/services/background-tasks.service.ts, AzureFunctions.AngularClient/src/app/shared/services/user.service.ts
Standalone mode relies on Windows auth, so calls to getToken will fail.  I've updated the code to handle this but it's a bit messy.  I've logged an engineering bug to get this fixed up for all scenario's:
https://github.com/projectkudu/AzureFunctionsPortal/issues/1276
=> Added initialization handling for Standalone mode

AzureFunctions.AngularClient/src/app/site/site-summary/site-summary.component.html
Hiding the restart button completely instead of disabling it in order to reduce the confusion
=> #1327: Hide restart command for Function App & slots

AzureFunctions.AngularClient/src/app/shared/services/authz.service.ts
Every so often, ARM will crap out and start returning 429 (too many requests) errors on calls to check RBAC permission.  If that happens, let's just assume that the request succeeds and make a best effort to load the UI.
=> Should RBAC check succeeds if request returns 429

AzureFunctions.AngularClient/src/app/side-nav/side-nav.component.ts, AzureFunctions.AngularClient/src/app/tree-view/app-node.ts, AzureFunctions.AngularClient/src/app/tree-view/apps-node.ts, AzureFunctions.AngularClient/src/app/tree-view/functions-node.ts, AzureFunctions.AngularClient/src/app/tree-view/proxies-node.ts, AzureFunctions.AngularClient/src/app/tree-view/proxy-node.ts, AzureFunctions.AngularClient/src/app/tree-view/slots-node.ts, AzureFunctions.AngularClient/src/app/tree-view/tree-node.ts, AzureFunctions.AngularClient/src/app/tree-view/tree-view.component.html, AzureFunctions.AngularClient/src/app/tree-view/tree-view.component.scss, AzureFunctions.AngularClient/src/app/tree-view/tree-view.component.ts
Currently the TreeView component has a 1 to many relationship with Tree-Nodes.  In order to support keyboard navigation, we need to be able to isolate the UI which represents each node in the tree.  The current design makes this difficult so I reorganized it a bit so that there will be a 1:1 relationship between TreeView components and TreeNode objects.  Overall  I think the new design is also bit simpler.
I tested the Try experience with Chrome, and the normal Ibiza experience with Chrome, Firefox, and Edge and it seems to be fine.
=> Reorganizing treeview to make it easier to support keyboard navigation

AzureFunctions.AngularClient/src/app/shared/function-app.ts
"ng build --prod" on dev works without a hitch but on master it fails.
It's wired.
=> Fix build (ng build --prod)

AzureFunctions.AngularClient/src/app/shared/services/slots.service.ts
Slots create was copying all appsettings & updating the webisteContentShare with slotName + GUID, however the back end is already taking care of this so removing the logic from portal
=> [HOTFIX]: Unable to create Slots for non-dynamic apps

AzureFunctions.AngularClient/src/app/shared/Utilities/url.ts, AzureFunctions.AngularClient/src/app/shared/function-app.ts, AzureFunctions.AngularClient/src/app/shared/services/portal.service.ts
Related to #1443
If we pass a query string on portal load, we need to make sure we're parsing the trustedAuthority properly or postMessages back to Ibiza won't work.
=> Adding support in portal service to handle query strings

AzureFunctions.AngularClient/src/app/search-box/search-box.component.html, AzureFunctions.AngularClient/src/app/search-box/search-box.component.ts, AzureFunctions.AngularClient/src/app/shared/models/constants.ts, AzureFunctions.AngularClient/src/app/side-nav/side-nav.component.html, AzureFunctions.AngularClient/src/app/side-nav/side-nav.component.scss, AzureFunctions.AngularClient/src/app/side-nav/side-nav.component.ts, AzureFunctions.AngularClient/src/app/tree-view/apps-node.ts, AzureFunctions.AngularClient/src/app/tree-view/tree-node-iterator.ts, AzureFunctions.AngularClient/src/app/tree-view/tree-node.ts, AzureFunctions.AngularClient/src/app/tree-view/tree-view.component.html, AzureFunctions.AngularClient/src/app/tree-view/tree-view.component.scss, AzureFunctions.AngularClient/src/app/tree-view/tree-view.component.spec.ts, AzureFunctions.AngularClient/src/sass/common/_variables.scss
If you click or tab to a node in the tree nav, it will take focus.  From there, you can use the up/down arrow to move up/down in the tree.  Or left/right arrows to collapse/expand a node in the tree.  These actions follow the rules defined for ARIA TreeView navigation controls (https://www.w3.org/WAI/GL/wiki/Using_ARIA_trees).  While it doesn't implement all of the possible actions, it does cover the main ones.
Also for now I'm just focusing on keyboard navigation and am planning on getting to the screen ready support later.
=> Fixes: 1411 - [Accessibility] Add keyboard navigation to side nav

AzureFunctions.AngularClient/src/app/site/site-manage/site-manage.component.ts
We have a portal release earlier today that was updated to use the new overview blade - since function still points to the old blade, when we click All settings from 'platform features', the menu blade doesn't show up. The fix is to launch the new overview blade when clicking 'All Settings'
=> FW:[HOTFIX] pointing all settings to the new overview blade

AzureFunctions.AngularClient/src/app/api-new/api-new.component.ts, AzureFunctions.AngularClient/src/app/function-new/function-new.component.ts, AzureFunctions.AngularClient/src/app/slot-new/slot-new.component.ts
If a user refreshes the app after opening the "new function" experience, it will create a new set of nodes in the tree.  However the "new function" component already has a reference to the old "Functions" node, so when it adds a node to it at the end, it doesn't reflect in the UI.
I worked around the problem by making sure we have the latest reference in the tree before adding the new node.  However this doesn't seem like a great solution.  I have to think a bit more on what would be a better solution but for now this seems to work.
=> Fixes #1255 - Refreshed function list could not update new created function automatically

AzureFunctions.AngularClient/src/app/tree-view/apps-node.ts
If you have 2 subs selected, then you select only 1 sub, the tree doesn't update to have less items.  This is a regression from my previous commit #1518
=> Fix issue where selecting less subs doesn't update tree properly

AzureFunctions/Authentication/SecurityManager.cs, AzureFunctions/Global.asax.cs
- LocalAuthProvider is a very primitive implementation. This commit contains changes to start using the FrontEndAuthProvider instead of LocalAuthProvider for OnPrem, just like we do for Azure.
Background:
- The FrontEndAuthProvider relies on either the X-MS-* headers or the 'portal-token' header for authentication
- The X-MS-* are sent by the front end
- 'portal-token' is sent only when running in an iframe within the Azure Portal
- As per the current implementation, unauthenticated calls to protected endpoints (APIs) return 403 and unauthenticated calls to unprotected endpoints that are not APIs (static content) result in a redirect to the marketing page or the signin page. This commit changes this behavior.
Commit description:
- For OnPrem, as the Functions portal will always be hosted …
=> Use FrontEndAuthProvider instead of LocalAuthProvider for OnPrem

AzureFunctions.AngularClient/AzureFunctions.AngularClient.csproj, AzureFunctions.AngularClient/src/app/apps-list/apps-list.component.html, AzureFunctions.AngularClient/src/app/controls/tbl/tbl-th/tbl-th.component.scss, AzureFunctions.AngularClient/src/app/controls/tbl/tbl-th/tbl-th.component.ts, AzureFunctions.AngularClient/src/app/controls/tbl/tbl.component.ts, AzureFunctions.AngularClient/src/app/shared/Utilities/dom.ts, AzureFunctions.AngularClient/src/app/side-nav/side-nav.component.ts, AzureFunctions.AngularClient/src/sass/controls/_tbl.scss
Fixes: #1498  - [Accessibility] Add keyboard navigation to apps list component
1. Hitting enter on a sortable header will sort the column.
2. Use up/down/left/right navigation keys to move around in table
3. Focusing on a cell with a control will highlight the first "tab-able" control.  (Currently only support single control per cell)
4. Hitting enter on a link within a cell will open that link.
=> [Accessibility] Add keyboard navigation to tbl component

AzureFunctions.AngularClient/src/app/apps-list/apps-list.component.html, AzureFunctions.AngularClient/src/app/apps-list/apps-list.component.ts, AzureFunctions.AngularClient/src/app/controls/tbl/tbl.component.ts, AzureFunctions.AngularClient/src/app/shared/Utilities/dom.ts, AzureFunctions.AngularClient/src/app/shared/models/constants.ts, AzureFunctions.AngularClient/src/sass/base/_base.scss
The Tbl component will now read off each cell.  To get this to work, I had to change the way that I focus on cells.  The way that it works now is when you select a cell, we'll change the tabindex to 0 so that it's "focus-able", and then focus on it.  When you move away, we'll change the tabindex of the current cell to -1 and choose the next cell.
I had to also add some extra logic to handle some of the funky behaviors of a screen reader where you can get "stuck" within a cell.  So if you hit "escape" when you've selected a control within a cell, it will change the focus to select the cell itself instead.
=> Fixes #1558 - [Accessbility] Add screen reader support to apps list component

AzureFunctions.AngularClient/src/app/app.component.ts, AzureFunctions.AngularClient/src/app/function-dev/function-dev.component.ts, AzureFunctions.AngularClient/src/app/main/main.component.html, AzureFunctions.AngularClient/src/app/main/main.component.scss, AzureFunctions.AngularClient/src/app/main/main.component.ts, AzureFunctions.AngularClient/src/app/shared/Utilities/logger.ts, AzureFunctions.AngularClient/src/app/shared/directives/monaco-editor.directive.ts, AzureFunctions.AngularClient/src/app/shared/function-app.ts, AzureFunctions.AngularClient/src/app/shared/models/constants.ts, AzureFunctions.AngularClient/src/app/shared/models/localStorage/local-storage.ts, AzureFunctions.AngularClient/src/app/shared/resourceDescriptors.ts, AzureFunctions.AngularClient/src/app/shared/services/background-tasks.service.ts, AzureFunctions.AngularClient/src/app/shared/services/local-storage.service.ts, AzureFunctions.AngularClient/src/app/shared/services/portal.service.ts, AzureFunctions.AngularClient/src/app/shared/services/user.service.ts, AzureFunctions.AngularClient/src/app/top-bar/top-bar.component.html, AzureFunctions.AngularClient/src/app/top-bar/top-bar.component.scss, AzureFunctions.AngularClient/src/app/top-bar/top-bar.component.ts, AzureFunctions.AngularClient/src/app/tree-view/function-node.ts, AzureFunctions.AngularClient/src/app/tree-view/tree-node.ts, AzureFunctions.AngularClient/src/app/tree-view/tree-view.component.html, AzureFunctions.AngularClient/src/app/tree-view/tree-view.component.scss, AzureFunctions.AngularClient/src/app/tree-view/tree-view.component.ts, AzureFunctions.AngularClient/src/sass/controls/_monaco.scss
This PR is for the implementation of opening a function in a new tab. When a function is opened in a new tab, the child window receives startup information from the parent window and adds the resource ID passed through the URL. This line of communication can later be used in notifying the parent or child window to update its code when changes have been made in the other. As shown in the images below, a function can be opened by clicking the button that appears when you hover over a function. The tab opened allows access to the function file opened as well as all the files in its file explorer and maximizes the use of screen real estate. This is currently hidden with a query string until more feedback in gathered on the feature. The query string to enable it is 'appsvc.feature=tabbed'
=> Adding ability to open a function in a new browser tab

AzureFunctions.AngularClient/src/app/multi-drop-down/multi-drop-down.component.ts, AzureFunctions.AngularClient/src/app/search-box/search-box.component.html, AzureFunctions.AngularClient/src/app/search-box/search-box.component.ts, AzureFunctions.AngularClient/src/app/shared/Utilities/dom.ts, AzureFunctions.AngularClient/src/app/shared/models/constants.ts, AzureFunctions.AngularClient/src/app/shared/models/portal-resources.ts, AzureFunctions.AngularClient/src/app/side-nav/side-nav.component.html, AzureFunctions.AngularClient/src/app/side-nav/side-nav.component.ts, AzureFunctions.AngularClient/src/app/tree-view/apps-node.ts, AzureFunctions.AngularClient/src/app/tree-view/tree-node.ts, AzureFunctions.AngularClient/src/app/tree-view/tree-view.component.html, AzureFunctions.AngularClient/src/app/tree-view/tree-view.component.scss, AzureFunctions.AngularClient/src/app/tree-view/tree-view.component.ts, AzureFunctions/ResourcesPortal/Resources.resx
Follow aria rules for tree view - https://www.w3.org/TR/wai-aria-practices/#TreeView
Example here - https://www.w3.org/TR/wai-aria-practices/examples/treeview/treeview-2/treeview-2b.html
Changes:
1. Moved keyboard navigation into tree view and away from sidenav.  This is to allow each node to have its own individual tabindex.
2. Added aria roles to match rules defined by links above
3. Fixed some auto scroll issues
=> [Accessibility] Add screen reader support for side nav

AzureFunctions.AngularClient/src/app/api-details/api-details.component.ts, AzureFunctions.AngularClient/src/app/api-new/api-new.component.ts, AzureFunctions.AngularClient/src/app/apps-list/apps-list.component.ts, AzureFunctions.AngularClient/src/app/breadcrumbs/breadcrumbs.component.ts, AzureFunctions.AngularClient/src/app/create-function-wrapper/create-function-wrapper.component.ts, AzureFunctions.AngularClient/src/app/function-edit/function-edit.component.ts, AzureFunctions.AngularClient/src/app/function-integrate-v2/function-integrate-v2.component.ts, AzureFunctions.AngularClient/src/app/function-manage/function-manage.component.ts, AzureFunctions.AngularClient/src/app/function-new/function-new.component.ts, AzureFunctions.AngularClient/src/app/function-quickstart/function-quickstart.component.ts, AzureFunctions.AngularClient/src/app/functions-list/functions-list.component.ts, AzureFunctions.AngularClient/src/app/main/main.component.ts, AzureFunctions.AngularClient/src/app/proxies-list/proxies-list.component.ts, AzureFunctions.AngularClient/src/app/side-nav/side-nav.component.ts, AzureFunctions.AngularClient/src/app/site/create-app/create-app.component.ts, AzureFunctions.AngularClient/src/app/site/function-runtime/function-runtime.component.ts, AzureFunctions.AngularClient/src/app/site/site-config/site-config.component.ts, AzureFunctions.AngularClient/src/app/site/site-dashboard/site-dashboard.component.ts, AzureFunctions.AngularClient/src/app/site/site-manage/site-manage.component.ts, AzureFunctions.AngularClient/src/app/site/site-summary/site-summary.component.ts, AzureFunctions.AngularClient/src/app/site/swagger-definition/swagger-definition.component.ts, AzureFunctions.AngularClient/src/app/slot-new/slot-new.component.ts, AzureFunctions.AngularClient/src/app/slots-list/slots-list.component.ts, AzureFunctions.AngularClient/src/app/tree-view/models/tree-view-info.ts
I added some timers to make sure that we're also calculating the equivalent of "full-ready" for any tabbed features at the app-level.  There's a lot of changes here because I changed the definition of TreeViewInfo, but the only files that have real changes are:
1. Site-dashboard.component.ts
2. site-summary.component.ts
3. site-manage.component.ts
4. function-runtime.component.ts
5. api-definition.component.ts
=> Updated app-level timers to include full-ready timings

AzureFunctions.AngularClient/.angular-cli.json, AzureFunctions.AngularClient/src/app/apps-list/apps-list.component.html, AzureFunctions.AngularClient/src/app/controls/tbl/tbl.component.ts, AzureFunctions.AngularClient/src/sass/base/_base.scss, AzureFunctions.AngularClient/src/sass/base/_typography.scss
Fixed an issue where shift-tab wouldn't change focus to the previous control in the tab order.  The problem was that since the table always intercepted the focus, it would never allow you to go to a previous control from a cell.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/azure-functions-ux/1575)
=> Fixing issue where shift-tab doesn't work for tbl components

AzureFunctions.AngularClient/src/app/controls/tbl/tbl.component.ts
The "focus" event gets called whether you tab into a table or click into it, but we cannot distinguish the difference between them.  Since the onFocus callback would always set focus on the first cell in the table, it would intercept any click events made on any of the cells in the table.
The fix was to remove the focus event from being thrown at the table level.  Instead, we'll make the first cell "tab-able" whenever we update the table so that it happens once during initialization.  Now the click event will flow through properly for any cell that's clicked.
=> Fixes #1608 - Cannot disable a function

AzureFunctions.AngularClient/src/app/controls/tbl/tbl.component.ts, AzureFunctions.AngularClient/src/app/tree-view/tree-node.ts
For the breadcrumbs issue, the problem was that the tree node path changed so that the root node would have an undefined title.  So adding a null check where we build the path fixes the bread-crumbs.
I also added a fix for the Tbl component so that you can click on the first column in a table.  The issue here was that the onClick callback was interpreting a 0 index as false.
=> Fixes #1609 - Bread-crumbs are broken

AzureFunctions.AngularClient/src/app/apps-list/apps-list.component.html, AzureFunctions.AngularClient/src/app/apps-list/apps-list.component.ts, AzureFunctions.AngularClient/src/app/multi-drop-down/multi-drop-down.component.ts, AzureFunctions.AngularClient/src/app/side-nav/side-nav.component.html, AzureFunctions.AngularClient/src/app/side-nav/side-nav.component.ts
Fixes bug where changing your selection within the drop-down many times before clicking out can cause the default "# items" or "all items" to be displayed instead of the correct descriptor ("# subscriptions", "all locations", etc.)
=> Fix Multi-Drop-Down Bug

AzureFunctions.AngularClient/src/app/site/site-config/general-settings/general-settings.component.html, AzureFunctions.AngularClient/src/app/site/site-config/general-settings/general-settings.component.ts, AzureFunctions.AngularClient/src/app/site/site-config/site-config.component.scss
=> Fixing GeneralSettingsComponent so that permissions shields don't cover "General settings" and "Debugging" headings

AzureFunctions.AngularClient/src/app/run-http/run-http.component.ts
Here is an attempt to fix #1666 that does not enable dash in query string parameters and headers names.
=> Enable dash in the query string parameters and headers, fix #1666

AzureFunctions.AngularClient/src/app/site/function-runtime/function-runtime.component.ts, AzureFunctions.AngularClient/src/app/site/site-enabled-features/site-enabled-features.component.ts, AzureFunctions.AngularClient/src/app/site/site-manage/site-manage.component.ts
Whenever you click on "application settings" anywhere in the Functions UI, it will now open the app settings tab instead of opening a new blade.
=> Enable application setting tab by default

AzureFunctions.AngularClient/src/app/app.module.ts, AzureFunctions.AngularClient/src/app/shared/Utilities/logger.ts, AzureFunctions.AngularClient/src/app/shared/directives/check-scenario.directive.ts, AzureFunctions.AngularClient/src/app/shared/models/constants.ts, AzureFunctions.AngularClient/src/app/shared/services/scenario/azure.environment.ts, AzureFunctions.AngularClient/src/app/shared/services/scenario/dynamic-site.environment.ts, AzureFunctions.AngularClient/src/app/shared/services/scenario/national-cloud.environment.ts, AzureFunctions.AngularClient/src/app/shared/services/scenario/scenario.models.ts, AzureFunctions.AngularClient/src/app/shared/services/scenario/scenario.service.ts, AzureFunctions.AngularClient/src/app/shared/services/scenario/site-slot.environment.ts, AzureFunctions.AngularClient/src/app/shared/services/scenario/stand-alone.environment.ts, AzureFunctions.AngularClient/src/app/site/site-dashboard/site-dashboard.component.html, AzureFunctions.AngularClient/src/app/site/site-dashboard/site-dashboard.component.ts, AzureFunctions.AngularClient/src/app/site/site-manage/site-manage.component.ts, AzureFunctions.AngularClient/src/app/site/site-summary/site-summary.component.html, AzureFunctions.AngularClient/src/app/site/site-summary/site-summary.component.ts, AzureFunctions.AngularClient/src/polyfills/window.ts
The Functions portal will soon have to be able to run in many different environment types that have different capabilities and constraints.  To help keep our view logic clean, I'm adding a new ScenarioService which will allow us to define view logic behaviors that are specific to every environment type.
**Examples of Usage**
*Checking if a scenario is enabled/disabled* – In this example, we only show the “Platform features” tab for a site if we’re running in Azure and disable for Standalone (aka Functions runtime).  Adding a simple check around the tab creation will handle this.  Notice that the call to “checkScenario” is synchronous:
if (this._scenarioService.checkScenario(ScenarioIds.addSiteFeaturesTab).status === 'enabled') {
this.tabInfos.push(this._getTabInfo(SiteTabIds.features, …
=> Fixes #1598 - Add a utility to make it easier to handle different environments (like on-prem) in code

AzureFunctions.AngularClient/src/app/app.module.ts, AzureFunctions.AngularClient/src/app/shared/Utilities/url.ts, AzureFunctions.AngularClient/src/app/shared/models/constants.ts, AzureFunctions.AngularClient/src/app/shared/services/log.service.ts, AzureFunctions.AngularClient/src/app/shared/services/scenario/scenario.service.ts, AzureFunctions.AngularClient/src/app/site/site-dashboard/site-dashboard.component.ts
I'm adding a general purpose logging service which will hopefully help to standardize how we do logging and help with troubleshooting.
There's 4 log levels: Error, Warning (default), debug, and verbose, which can be controlled with a query string like so: "?appsvc.log.level=debug".  Error and Warning messages will always get logged to App Insights, while debug and verbose will only get logged to the browser console.
In addition to controlling log levels, you can also specify which categories you'd like to log.  For instance, if I specify the query string: "?appsvc.log.category=cat1,cat2", then only log messages that match cat1 and cat2 will be logged.
=> Adding a logging service

AzureFunctions.AngularClient/src/app/apps-list/apps-list.component.html, AzureFunctions.AngularClient/src/app/apps-list/apps-list.component.ts, AzureFunctions.AngularClient/src/app/side-nav/side-nav.component.ts, AzureFunctions.AngularClient/src/app/tree-view/apps-node.ts
Added a refresh button to the "Function apps" node in the tree.  For now the button will only show up if you've selected the Function apps node in the tree.  This is mainly because we need to do more work in order to make sure that you can properly restore the selection state if you're currently selected on something deep in the tree, like the Function Dev component.
=> Fixes #1697 - Function apps list should have a refresh button

AzureFunctions.AngularClient/src/app/function-dev/function-dev.component.ts
this happens  when switching between functions of different dev views.
Fixes #1637
=> fix ExpressionChangedAfterItHasBeenCheckedError

AzureFunctions.AngularClient/src/app/functions-list/functions-list.component.html, AzureFunctions.AngularClient/src/app/shared/models/portal-resources.ts, AzureFunctions.AngularClient/src/sass/controls/_tbl.scss, AzureFunctions/ResourcesPortal/Resources.Designer.cs, AzureFunctions/ResourcesPortal/Resources.resx
- Updating the delete icons to use anchor elements instead of img elements, so they are detected as tabbable elements. (When using img elements, the the TblComponent was not detecting the icons as tabable elements. Therefore they would not receive focus or have "enter" keypress events applied to them.)
- Setting the aria-label attribute for the delete icons.
- Setting the role attribute as "button" for the delete icons.
=> Accessibility fixes for delete icons in FunctionsListComponent 

AzureFunctions.AngularClient/src/app/shared/models/arm/arm-obj.ts, AzureFunctions.AngularClient/src/app/site/site-config/general-settings/general-settings.component.ts
If a user has MSI enabled for their app and they try to save their changes in the "Application Settings" tab, it will fail.  The reason is because the site API returns a new "identity" property in the ARM envelope, but if you try to send it back on your PUT request, it will fail because it thinks that you're trying to update it.  My fix is to make sure that we never send the identity property back in our PUT request.
=> HOTFIX - Cannot save in Application Settings tab if site has MSI enabled

AzureFunctions.AngularClient/src/app/function-new/function-new.component.ts
Currently you can create a function even if a function of that name already exists.
This change disables the create button in that case.
=> Bug fix: create button disable

AzureFunctions.AngularClient/src/app/function-quickstart/function-quickstart.component.html, AzureFunctions.AngularClient/src/app/function-quickstart/function-quickstart.component.scss
The default English doesn't look quite as nice because it's no longer a perfect circle, but at least now it can expand if the content is long.  The only way to make it a perfect circle for English and be expandable would be if I made the circle taller which I don't want to do.
Also verified in dark theme.
**Short text**
**Long text**
=> Fixes #1704 - The or text when creating a new Function may not fit if localized

AzureFunctions.AngularClient/src/app/app.component.html, AzureFunctions.AngularClient/src/app/busy-state/busy-state-scope-manager.ts, AzureFunctions.AngularClient/src/app/busy-state/busy-state.component.html, AzureFunctions.AngularClient/src/app/busy-state/busy-state.component.scss, AzureFunctions.AngularClient/src/app/busy-state/busy-state.component.ts, AzureFunctions.AngularClient/src/app/function-keys/function-keys.component.html, AzureFunctions.AngularClient/src/app/ibiza-feature/app-settings-shell/app-settings-shell.component.html, AzureFunctions.AngularClient/src/app/ibiza-feature/app-settings-shell/app-settings-shell.component.ts, AzureFunctions.AngularClient/src/app/ibiza-feature/ibiza-feature.component.ts, AzureFunctions.AngularClient/src/app/main/main.component.html, AzureFunctions.AngularClient/src/app/main/main.component.ts, AzureFunctions.AngularClient/src/app/shared/models/broadcast-event.ts, AzureFunctions.AngularClient/src/app/shared/models/constants.ts, AzureFunctions.AngularClient/src/app/shared/shared.module.ts, AzureFunctions.AngularClient/src/app/site/function-runtime/function-runtime.component.ts, AzureFunctions.AngularClient/src/app/site/site-config-standalone/site-config-standalone.component.ts, AzureFunctions.AngularClient/src/app/site/site-config/app-settings/app-settings.component.ts, AzureFunctions.AngularClient/src/app/site/site-config/connection-strings/connection-strings.component.ts, AzureFunctions.AngularClient/src/app/site/site-config/general-settings/general-settings.component.ts, AzureFunctions.AngularClient/src/app/site/site-config/site-config.component.ts, AzureFunctions.AngularClient/src/app/site/site-dashboard/site-tab/site-tab.component.ts, AzureFunctions.AngularClient/src/app/site/site-manage/site-manage.component.ts, AzureFunctions.AngularClient/src/app/site/site-summary/site-summary.component.ts, AzureFunctions.AngularClient/src/app/site/site.module.ts, AzureFunctions.AngularClient/src/app/try-landing/try-landing.component.html
**3 main changes being made to how busy state works**
1. BusyStateScopedManager will now use the broadcast service to communicate with a given BusyStateComponent based on the name of the BusyStateComponent.
2. The BusyStateComponent will also debounce state changes which should help reduce flickering and asserts being thrown which say that your state is changing too fast.
3. I updated the BusyStateComponent so that you can pass in the class you want it to use, instead of hardcoding style logic inside of the component itself.
Ideally all of our code should now be using the BusyStateScopedManager but that's a larger change and we can make those changes going forward..
=> Removing hard-dependencies between site tab features and BusyStateComponent

AzureFunctions.AngularClient/src/app/site/function-runtime/function-runtime.component.html, AzureFunctions.AngularClient/src/app/site/function-runtime/function-runtime.component.ts
resolves #1731 
Slots options stay visible and disabled toggled on.
=> slots preview is visible when slots on

AzureFunctions.AngularClient/src/app/app.component.ts, AzureFunctions.AngularClient/src/app/main/main.component.html, AzureFunctions.AngularClient/src/app/main/main.component.ts
There's a race condition between lazy loading the apps list component and initializing the resource strings. This means that you'll sometime wind up with strings that look like the image below.  For now, I'm changing the lazy load initialization logic so that we don't download any of the child modules until we've completed init.  This isn't great for performance but it's a simple fix.  Long-term, I'd like to think of a way where we could do both at the same time.
=> Resource strings sometimes don't load properly for apps list component

AzureFunctions.AngularClient/src/app/app.component.ts, AzureFunctions.AngularClient/src/app/app.module.ts, AzureFunctions.AngularClient/src/app/main/main.component.html, AzureFunctions.AngularClient/src/app/main/main.component.ts
Apparently the change that I made earlier to fix the resource string loading caused a regression when loading the site config component for Ibiza scenario's.  I'm still not 100% sure why, but apparently my previous change caused the SiteConfig component to load before the authentication token was initialized for Ibiza scenario's.  This caused the component to fail horribly with a ton of 401's.
While I still don't understand what was wrong, I found a cleaner way to handle route loading when waiting for something to load.  So I created a new Resolve class which allows you to prevent a route from loading until an async operation has completed, which is a much cleaner approach to route loading.
=> Fixing issue where site config component no longer load for Ibiza scenario's

AzureFunctions.AngularClient/src/app/shared/directives/is-dirty.directive.ts, AzureFunctions.AngularClient/src/app/shared/models/portal.ts, AzureFunctions.AngularClient/src/app/shared/services/portal.service.ts, AzureFunctions.AngularClient/src/app/shared/shared.module.ts, AzureFunctions.AngularClient/src/app/site/site-config/site-config.component.html, AzureFunctions.AngularClient/src/app/site/site-config/site-config.component.ts, AzureFunctions/ResourcesPortal/Resources.resx
I added a new directive called "is-dirty" which should make it easy to handle dirty state operations for forms.  For now, my guidance is to keep the dirty message empty for regular dirty states, but set it to an explicit warning that you may lose changes during a save operation.
=> Adding support for updating Ibiza dirty state

AzureFunctions.AngularClient/src/app/shared/services/slots.service.ts, AzureFunctions.AngularClient/src/app/site/site-config/general-settings/general-settings.component.html
AI has an issue where they return a "[]" instead of a proper JSON response if there are no AI resources in your subscription. Since we're expecting JSON, we fail to parse the response properly and crash the monitor blade.
Another scenario that could trigger this is if the user has the AI key setup but it points to an AI resource in a different subscription. In that case, it's possible that they'll run into this problem again. That one is a bit less likely, so I've logged a separate issue for it #1915.
=> Fixes #1914 - Function monitor dashboard may not load if there are no AI resources in subscription

AzureFunctions.AngularClient/src/app/api/api-details/api-details.component.ts, AzureFunctions.AngularClient/src/app/api/api-new/api-new.component.ts, AzureFunctions.AngularClient/src/app/apps-list/apps-list.component.ts, AzureFunctions.AngularClient/src/app/create-function-wrapper/create-function-wrapper.component.ts, AzureFunctions.AngularClient/src/app/function-edit/function-edit.component.ts, AzureFunctions.AngularClient/src/app/functions-list/functions-list.component.ts, AzureFunctions.AngularClient/src/app/proxies-list/proxies-list.component.ts, AzureFunctions.AngularClient/src/app/shared/models/broadcast-event.ts, AzureFunctions.AngularClient/src/app/shared/models/constants.ts, AzureFunctions.AngularClient/src/app/shared/services/broadcast.service.ts, AzureFunctions.AngularClient/src/app/shared/services/log.service.ts, AzureFunctions.AngularClient/src/app/side-nav/side-nav.component.ts, AzureFunctions.AngularClient/src/app/site/site-dashboard/site-dashboard.component.ts, AzureFunctions.AngularClient/src/app/slot-new/slot-new.component.ts, AzureFunctions.AngularClient/src/app/slots-list/slots-list.component.ts
Originally I was trying to cut down on the number of streams that we had to keep track of for the new broadcastEvent and getEvent API's.  But it turns out to be more complicated because some streams want you to keep track of many events (like busy state events from different managers), while other really only want the latest.  I couldn't find a way to do this using filtering, so I just went back to having multiple streams.
=> Fixing tree navigation issues by adding separate event streams for each event type for the new broadcast apis

AzureFunctions.AngularClient/src/app/function-dev/function-dev.component.ts, AzureFunctions.AngularClient/src/app/site/site-dashboard/site-dashboard.component.ts
My broadcast changes modified the timing of when things are loaded and a few components appear to be affected by this.  
1. The site dashboard was trying to read some properties on viewinfo before they were ready.  This only gets exposed if you have tabs open, you navigate away, then come back to the app node which tries to reopen the tabs.
2. The function dev component may throw a null ref if you navigate to it too quickly.  It seems like this should have always been an issue but I wasn't able to reproduce in prod. Anyway I did a simple fix here, though the code itself is precarious and I think it needs a deeper rewrite.
=> Fix issue where tab crashes and function dev throws exception on tree navigation

AzureFunctions.AngularClient/src/app/site/site-config/app-settings/app-settings.component.ts, AzureFunctions.AngularClient/src/app/site/site-config/connection-strings/connection-strings.component.ts, AzureFunctions.AngularClient/src/app/site/site-config/default-documents/default-documents.component.ts, AzureFunctions.AngularClient/src/app/site/site-config/general-settings/general-settings.component.ts, AzureFunctions.AngularClient/src/app/site/site-config/handler-mappings/handler-mappings.component.ts, AzureFunctions.AngularClient/src/app/site/site-config/site-config.component.ts, AzureFunctions.AngularClient/src/app/site/site-config/virtual-directories/virtual-directories.component.ts
- Fixes #1958 by no longer hiding the PHP version dropdown in the General Settings section for function apps.
- Avoids unnecessary PUT/PATCH calls for config sections that haven't been updated.
(Note: This is a temporary solution to fix issue #1958. There is already a issue open for a proper solution that will solve both of the issues addressed by this change.)
=> Fixes and updates to site config save operation

AzureFunctions.AngularClient/src/app/radio-selector/radio-selector.component.html, AzureFunctions.AngularClient/src/app/radio-selector/radio-selector.component.scss, AzureFunctions.AngularClient/src/app/radio-selector/radio-selector.component.ts
This includes the following changes to RadioSelectorComponent:
- Added keyboard accessibility
- Added ARIA attributes for accessibility
- Style fixes
When updating the styles, I was aiming to be consistent with the following two controls from Office UI Fabric:
- https://developer.microsoft.com/en-us/fabric#/components/choicegroup
- https://developer.microsoft.com/en-us/fabric#/components/toggle
Below are five sets of screen captures that illustrate the updated styles for the control in all its possible states for both the light and dark theme.
* **Set 1**
* control is disabled
* control is pristine
* "2015" is the selected option
* hover/focus have no effect
* **Set 2**
* control is enabled
* control is pristine
* "2015" is the selected option
* no items have hover/focus
* **Set 3**
* …
=> Accessibility and style updates for RadioSelectorComponent

AzureFunctions.AngularClient/src/app/shared/models/constants.ts, AzureFunctions.AngularClient/src/app/shared/services/scenario/stand-alone.environment.ts, AzureFunctions.AngularClient/src/app/side-nav/side-nav.component.html, AzureFunctions.AngularClient/src/app/side-nav/side-nav.component.scss, AzureFunctions.AngularClient/src/app/side-nav/side-nav.component.ts, AzureFunctions.AngularClient/src/app/site/create-app/create-app.component.html, AzureFunctions.AngularClient/src/app/site/create-app/create-app.component.ts, AzureFunctions.AngularClient/src/app/subscription/create-subscription/create-subscription.component.scss, AzureFunctions.AngularClient/src/app/subscription/create-subscription/create-subscription.component.ts, AzureFunctions.AngularClient/src/app/top-bar/top-bar.component.scss
1. workaround for error thrown after creating subscription  "ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked" 
2. Name and Subscription field in Create app resized.
3. Creating subscription with empty display name is not allowed. 
4.Creating app with empty name is not allowed.
5. Header is now on top of sidenav and dashboard
=> Some fixes for Standalone Function portal

AzureFunctions.AngularClient/src/app/edit-mode-warning/edit-mode-warning.component.html, AzureFunctions.AngularClient/src/app/edit-mode-warning/edit-mode-warning.component.ts, AzureFunctions.AngularClient/src/app/shared/models/function-app-edit-mode.ts, AzureFunctions.AngularClient/src/app/shared/services/functions-service.ts, AzureFunctions/ResourcesPortal/Resources.resx
Add read/write mode and warning for VS generated functions
resolves #1913
=> Add read/write mode and warning for VS generated functions

AzureFunctions.AngularClient/src/app/pop-over/pop-over.component.html, AzureFunctions.AngularClient/src/app/pop-over/pop-over.component.scss, AzureFunctions.AngularClient/src/app/pop-over/pop-over.component.ts, AzureFunctions.AngularClient/src/app/site/site-config/general-settings/general-settings.component.html
This allows us to set the popovers in General Settings to open to the right instead of above/below, so we avoid the situation where the popover extends beyond the left boundary of the iframe.
Before:
After:
=> Update PopOverComponent to support left/right positioning.

AzureFunctions.AngularClient/src/app/function/binding-input-v2/binding-input-v2.component.html, AzureFunctions.AngularClient/src/app/function/binding-input-v2/binding-input-v2.component.scss
=> fix new link for try function

AzureFunctions.AngularClient/src/app/multi-drop-down/multi-drop-down.component.html, AzureFunctions.AngularClient/src/app/multi-drop-down/multi-drop-down.component.scss, AzureFunctions.AngularClient/src/app/multi-drop-down/multi-drop-down.component.ts, AzureFunctions.AngularClient/src/sass/common/_variables.scss
(Fixes #1738)
I closed the related PR (Accessibility updates for MultiDropDownComponent #1751) because I decided to use aria-activedescendant to handle moving the "focus".
Updates:
- Control collapses if display text or arrow are clicked.
- Control does not lose track of focus when an option is clicked.
- Navigation to top or bottom of list using "Home" and "End" keys is supported.
- The selected state for a given option is indicated by styles instead of using checkbox elements.
- The "Select all" option is automatically selected if all other options are set to selected.
- Aria attributes have been added.
Below are the old vs. updated styles (both Light and Dark theme) for the following scenarios:
- Component is collapsed and has focus
- Component is expanded and display box has focus
- …
=> Accessibility and styling updates for MultiDropDownComponent

AzureFunctions.AngularClient/src/app/apps-list/apps-list.component.html, AzureFunctions.AngularClient/src/app/controls/activate-with-keys/activate-with-keys.directive.ts, AzureFunctions.AngularClient/src/app/controls/slide-toggle/slide-toggle.component.html, AzureFunctions.AngularClient/src/app/controls/slide-toggle/slide-toggle.component.scss, AzureFunctions.AngularClient/src/app/controls/slide-toggle/slide-toggle.component.ts, AzureFunctions.AngularClient/src/app/controls/tbl/tbl-th/tbl-th.component.ts, AzureFunctions.AngularClient/src/app/controls/tbl/tbl.component.ts, AzureFunctions.AngularClient/src/app/functions-list/functions-list.component.html, AzureFunctions.AngularClient/src/app/functions-list/functions-list.component.scss, AzureFunctions.AngularClient/src/app/logic-apps/logic-apps.component.html, AzureFunctions.AngularClient/src/app/proxies-list/proxies-list.component.html, AzureFunctions.AngularClient/src/app/shared/Utilities/dom.ts, AzureFunctions.AngularClient/src/app/shared/shared.module.ts, AzureFunctions.AngularClient/src/app/slots-list/slots-list.component.html
Changes:
- Updated styles for SlideToggleComponent (fixes #1798)
- This is supposed to match https://developer.microsoft.com/en-us/fabric#/components/toggle, but there are some deviations. For colors, I used the closest-matching colors from our existing color scheme. Similarly, for :hover and :focus styling, I kept things consistent with our existing conventions.
- Fixed issue in TblComponent that was causing click() to be called twice when "Enter" was pressed on a button element.
- Fixed issue in TblComponent where clicking inside a cell would always move focus to the first tab-able element in the cell, event if the element that was click on was tab-able.
- Minor accessibility and styling updates for icon buttons. (The icon buttons inside the table in FunctionsListComponent were not …
=> Updating styling for SlideToggleComponent (fixes #1798)

AzureFunctions.AngularClient/src/app/side-nav/side-nav.component.ts, AzureFunctions.AngularClient/src/app/tree-view/apps-node.ts
Any updates to the startupInfo object is causing 2 issues at the moment in the side nav.
**1. The list of subscriptions gets cleared out** - This is an artifact of how the tree used to work and is no longer necessary after tree simplification.  Combining this with Ahmed's change to [revert AppsNode back to previous logic should fix this.](https://github.com/Azure/azure-functions-ux/commit/36ce372fbff73b6a237c1677a239df5386134928)
**2. The search term was getting cleared out** - This is a regression from fixing #1563.  I fixed this to make sure we only clear out the search term stream only if it wasn't already set.  We still need to clear out the search term on init which is why it's there in the first place.  @hartra344 - Can you verify that I didn't regress the fix that I made for this …
=> Fix tree from resetting on updates to startupinfo

AzureFunctions.AngularClient/src/app/download-function-app-content/download-function-app-content.component.html
using a screen reader to close button will say 'close'
tested on edge and chrome with windows narrator
fixes http://vstfrd:8080/Azure/RD/_workitems?id=10622615&_a=edit&triage=true
=> add close label for screen readers

AzureFunctions.AngularClient/src/app/shared/services/ai.service.ts
most adblocker and tracker blockers will block App Insights script from loading, which would make `appInsight` undefined reference.
=> Check typeof appInsight before accessing it

AzureFunctions.AngularClient/src/app/download-function-app-content/download-function-app-content.component.html
Screen readers will read label while on checkbox.
Tested on chrome / edge with windows narrator
fixes http://vstfrd:8080/Azure/RD/_workitems?id=10622642&_a=edit&triage=true
=> Add check box label in download app for screen readers

AzureFunctions/Authentication/FrontEndAuthProvider.cs
`X-MS-CLIENT-PRINCIPAL-NAME` is only populated when running in azure
=> Check referer before checking X-MS-CLIENT-PRINCIPAL-NAME

AzureFunctions.AngularClient/src/app/drop-down/drop-down.component.html, AzureFunctions.AngularClient/src/app/drop-down/drop-down.component.ts
It looks like we can't completely get rid of the empty/disabled drop-down option mentioned in (#2060). It will still appear (in Edge) for drop down elements that don't have any option pre-selected.
=> Making sure selected option in DropDownComponent matches the selected option in the native select element (fixes #2060)

AzureFunctions.AngularClient/src/app/api/api-details/api-details.component.ts, AzureFunctions.AngularClient/src/app/shared/services/function-app.service.ts
For the proxy save issue, it looks like the order/timing of how the request/response child component is being loaded has changed. A simple low-risk (albeit hacky) solution is to just add a setTimeout when we try to reference it.
For the master key missing issue, it looks like after @ahmelsayed updated the FunctionAppService, he forgot to add back in any references to master key requests. I added it back it and it seems to be working now.
=> Fixes #2228, Fixes #2230 - Proxy save not working and master key missing

AzureFunctions.AngularClient/src/app/function/function-new/function-new.component.html, AzureFunctions.AngularClient/src/app/function/function-new/function-new.component.scss, AzureFunctions.AngularClient/src/app/function/function-new/function-new.component.ts, AzureFunctions.AngularClient/src/app/shared/models/portal-resources.ts, AzureFunctions/ResourcesPortal/Resources.resx
=> Experimental Language Toggle

AzureFunctions.AngularClient/src/app/function/embedded/embedded-function-editor/embedded-function-editor.component.ts, AzureFunctions.AngularClient/src/app/function/embedded/models/entity.ts, AzureFunctions.AngularClient/src/app/function/function-new-detail/function-new-detail.component.ts, AzureFunctions.AngularClient/src/app/functions-list/functions-list.component.ts, AzureFunctions.AngularClient/src/app/shared/models/error-ids.ts, AzureFunctions.AngularClient/src/app/shared/models/portal.ts, AzureFunctions.AngularClient/src/app/shared/services/embedded.service.ts, AzureFunctions.AngularClient/src/app/shared/shared.module.ts
Added the "embedded" service to clean up some common calls.
Updated the entities URL to handle namespaces
=> Handling namespace for embedded scenario

AzureFunctions/Web.config
Our current ASP.Net rewrite rules are matching the **"api/"** string in deep links like "https://functions.azure.com/feature/subscriptions/{sub}/resourcegroups/{rg}/providers/microsoft.web/sites/myapi/settings" and are allowing them to passthrough to our API controller instead of rewriting them to "https://functions.azure.com/".  Since we are a single page app, it's important for all requests that aren't API requests or for static content, to be rewritten to the root app so that Angular routing can do its own magic to load the proper UI components.  Since there aren't any API's that match the full path of the URL, we get a 404.
=> Fixes #2243 - Update URL rewrite rules so that API calls only match if path starts with /api and not just contains 'api/'

AzureFunctions.AngularClient/src/app/shared/components/errorable-component.ts, AzureFunctions.AngularClient/src/app/shared/components/feature-component.ts, AzureFunctions.AngularClient/src/app/shared/models/arm/arm-obj.ts, AzureFunctions.AngularClient/src/app/shared/models/constants.ts, AzureFunctions.AngularClient/src/app/shared/services/log.service.ts, AzureFunctions.AngularClient/src/app/shared/services/telemetry.service.ts, AzureFunctions.AngularClient/src/app/shared/shared.module.ts, AzureFunctions.AngularClient/src/app/site/site-config/app-settings/app-settings.component.ts, AzureFunctions.AngularClient/src/app/site/site-config/connection-strings/connection-strings.component.ts, AzureFunctions.AngularClient/src/app/site/site-config/default-documents/default-documents.component.ts, AzureFunctions.AngularClient/src/app/site/site-config/general-settings/general-settings.component.ts, AzureFunctions.AngularClient/src/app/site/site-config/handler-mappings/handler-mappings.component.ts, AzureFunctions.AngularClient/src/app/site/site-config/site-config.component.html, AzureFunctions.AngularClient/src/app/site/site-config/site-config.component.ts, AzureFunctions.AngularClient/src/app/site/site-config/virtual-directories/virtual-directories.component.ts
I created a new base component called FeatureComponent which takes care of logging completion timer telemetry for us.  Typically when you build a "feature", it's a collection of individual components.  Since your UI may not be done loading until several of those child components are done loading, it's difficult to know when we're really "done".
When building a component within a feature, you just need to inherit from FeatureComponent and set the featureName property.  Each FeatureComponent will log completion for that component to the TelemetryService, which keeps track of all FeatureComponents with the same name.  Once all FeatureComponents are done loading, it'll log the telemetry completion in Ibiza.
Eventually I'm thinking that I could actually merge this class in with the base …
=> Adding telemetry for AppSettings and creating base FeatureComponent

AzureFunctions.AngularClient/src/app/function-integrate-v2/function-integrate-v2.component.ts
Fixes #2293 
Fixes the error message being displayed and redirects to the create page. 
However, the create page should automatically open the proper template sidebar and populate the fields from the integrate tab. Will file a new issue for this.
=> Create from Integrate Tab

AzureFunctions.AngularClient/src/app/function-keys/function-keys.component.html
when on click to show/hide screen-reader reads "button click to show/hide"
tested in chrome / edge with narrator
fixes http://vstfrd:8080/Azure/RD/_workitems?id=10654520&_a=edit&triage=true
=> add role and label to click to show/click to hide

AzureFunctions.AngularClient/src/app/shared/components/feature-component.ts, AzureFunctions.AngularClient/src/app/shared/services/telemetry.service.ts
As discussed, I added a new timer to complete the trace for '/feature/{name}/construct'.
=> Added timer to track when a feature's first constructor gets called

AzureFunctions.AngularClient/src/app/api/api-new/api-new.component.ts, AzureFunctions.AngularClient/src/app/shared/conditional-http-client.ts, AzureFunctions.AngularClient/src/app/shared/models/error-ids.ts, AzureFunctions.AngularClient/src/app/shared/services/function-app.service.ts
As discussed offline, if a user throws a string in conditional http client, then we'll treat that as the message with an "unknown-error" errorId.  If they want to be explicit about the error, then they need to specify an HttpError type.
=> Fixes #2267 - Updating conditional http client to handle complex error types being thrown

AzureFunctions.AngularClient/src/app/shared/components/feature-component.ts, AzureFunctions.AngularClient/src/app/shared/conditional-http-client.ts, AzureFunctions.AngularClient/src/app/shared/models/constants.ts, AzureFunctions.AngularClient/src/app/shared/services/authz.service.ts, AzureFunctions.AngularClient/src/app/shared/services/site.service.ts, AzureFunctions.AngularClient/src/app/shared/services/telemetry.service.ts, AzureFunctions.AngularClient/src/app/site/site-config/app-settings/app-settings.component.ts, AzureFunctions.AngularClient/src/app/site/site-config/connection-strings/connection-strings.component.ts, AzureFunctions.AngularClient/src/app/site/site-config/default-documents/default-documents.component.ts, AzureFunctions.AngularClient/src/app/site/site-config/general-settings/general-settings.component.ts, AzureFunctions.AngularClient/src/app/site/site-config/handler-mappings/handler-mappings.component.ts, AzureFunctions.AngularClient/src/app/site/site-config/site-config.component.ts, AzureFunctions.AngularClient/src/app/site/site-config/virtual-directories/virtual-directories.component.ts
In order to get this to work properly, I had to update FeatureComponent to support clearing the busy state before the input observable completed.  To do this, I did:
1. Moved the BusyStateManager to the base FeatureComponent so that you can just call this.setbusy() or this.clearBusy() from the component.
2. Automatically set the busy state when we get a new input, and automatically clear it when the component has finished loading.  This means that for most components, you no longer need to explicitly call setBusy or clearBusy during initialization.
3. Added another base function called this.clearBusyEarly() which will clear the busy state early before the setup observable has completed.  This is useful if a developer wants to enable their UI early, but still want to run other async setup …
=> Updating site-config to do permission/lock checks after initial load

AzureFunctions.AngularClient/src/app/function-keys/function-keys.component.html
Add role=link to renew/revoke in manage blade
reader now reads "(keyname) renew, link" and " (keyname) revoke, link"
tested in chrome and edge with narrator
original bug only occurred in edge
fixes http://vstfrd:8080/Azure/RD/_workitems?id=10654586&triage=true&_a=edit
=> add role link to revoke renew

AzureFunctions.AngularClient/src/app/function-keys/function-keys.component.html, AzureFunctions.AngularClient/src/app/function-keys/function-keys.component.ts
add labels to actions in manage blade
actions in manage blade will read "table name, key name, action, link/button"
tested in chrome and edge with screen reader
fixes http://vstfrd:8080/Azure/RD/_workitems?id=10654901&triage=true&_a=edit
=>  add labels to actions in manage blade

AzureFunctions.AngularClient/src/app/edit-mode-warning/edit-mode-warning.component.html, AzureFunctions.AngularClient/src/app/edit-mode-warning/edit-mode-warning.component.ts, AzureFunctions.AngularClient/src/app/shared/Utilities/edit-mode.helper.ts, AzureFunctions.AngularClient/src/app/shared/models/constants.ts, AzureFunctions.AngularClient/src/app/shared/models/function-app-edit-mode.ts, AzureFunctions.AngularClient/src/app/shared/services/function-app.service.ts, AzureFunctions/ResourcesPortal/Resources.Designer.cs, AzureFunctions/ResourcesPortal/Resources.resx
@davidebbo can you review the warning message
> Your app is currently in read only mode because you are using Run-From-Zip. When using Run-From-Zip the file system is read only and no changes can be made to the files. To make any changes update the content in your zip file and WEBSITE_USE_ZIP app setting.
=> Set app to readonly when WEBSITE_USE_ZIP is defined

AzureFunctions/ResourcesPortal/Resources.resx
is enable but missing the expected storage
=> Fixes #2367: Updating the warning message shown in the banner when slots

AzureFunctions.AngularClient/src/app/site/site-config/site-config.component.html, AzureFunctions.AngularClient/src/app/site/site-config/site-config.component.scss
This only addresses the blade scenario. For the app settings tab in the functions portal, the command bar will still move with the rest of the content when scrolling.
=> Updating to app settings blade to keep command bar at top of blade when scrolling. (fixes #2281)

AzureFunctions.AngularClient/src/app/api/request-respose-override/request-respose-override.component.html, AzureFunctions.AngularClient/src/app/controls/pair-list/pair-list.component.html
Clean up the proxy UI headers/query grid. Was going through the WI to close and realized this should have been done in the previous CR.
Verified it continues to work in the run-http UI as intended..
=> Clean up the proxy UI headers/query grid

AzureFunctions.AngularClient/src/app/proxies-list/proxies-list.component.html, AzureFunctions.AngularClient/src/app/proxies-list/proxies-list.component.ts, AzureFunctions.AngularClient/src/app/shared/models/error-ids.ts, AzureFunctions.AngularClient/src/app/shared/models/portal-resources.ts, AzureFunctions.AngularClient/src/app/shared/services/function-app.service.ts, AzureFunctions.AngularClient/src/app/tree-view/proxies-node.ts, AzureFunctions/ResourcesPortal/Resources.resx
If proxies.json files contains errors (malformed json), show the error to the user with a link to the advanced editor. In the current scenario the UI does not display the error and allows the user to create a new proxy. Unfortunately the creation of new proxy just hangs as there is already a malformed proxies.json file.
**In case of**
**Before**
**After**
=> Handle errors in proxies.json gracefully

AzureFunctions.AngularClient/src/app/function-monitor/function-monitor.component.ts
Fix the function name spelling. Currently due to the misspelling the link from the component html is broken.
=> Fix function name spelling.

AzureFunctions.AngularClient/src/app/shared/services/portal.service.ts
Making sure we send the appropriate postMessage signature for the type of blade that we've been opened from.
=> HOTFIX: Fixing iframe signature that we send to Ibiza

AzureFunctions.AngularClient/src/app/file-explorer/file-explorer.component.scss, AzureFunctions.AngularClient/src/app/function-dev/function-dev.component.html, AzureFunctions.AngularClient/src/app/function-dev/function-dev.component.scss, AzureFunctions.AngularClient/src/app/function-integrate-v2/function-integrate-v2.component.scss, AzureFunctions.AngularClient/src/app/table-function-monitor/table-function-monitor.component.html, AzureFunctions.AngularClient/src/app/table-function-monitor/table-function-monitor.component.scss
Some simple bug fixes related to:
https://app.zenhub.com/workspace/o/azure/azure-functions-ux/issues/789
http://vstfrd:8080/Azure/RD/AAPT%20-%20Experiences%20-%20Websites/_workitems?_a=edit&id=10686852&triage=true
The long file names are truncated
Long inputs and outputs are truncated rather than overlapping each other
In case of a selection, in this table the ">" icon is replaced with the whole text being bold. Having the ">" was causing narrator issues, discussed this solution with @btardif
=> Some simple bug fixes

client/src/app/busy-state/busy-state.component.scss, client/src/app/shared/models/portal-resources.ts, client/src/app/site/site-manage/site-manage.component.ts, client/src/app/site/spec-picker/price-spec-manager/isolated-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/plan-price-spec-manager.ts, client/src/app/site/spec-picker/price-spec-manager/price-spec-group.ts, client/src/app/site/spec-picker/price-spec-manager/price-spec.ts, client/src/app/site/spec-picker/spec-list/spec-list.component.ts, client/src/app/site/spec-picker/spec-picker.component.html, client/src/app/site/spec-picker/spec-picker.component.scss, client/src/app/site/spec-picker/spec-picker.component.ts, client/src/sass/common/_variables.scss, server/Resources/Resources.resx
1. Each group can have its own banner now.  This means that you can show a different discount message when you switch between Dev/Test and Isolated groups.
2. I now use Ibiza notifications for update status
3. I made sure to disable isolated sku's for dreamspark
4. Fixed flex box wrap issues when window gets too small
5. And a few other small issues.
=> [SpecPicker] Adding individual banner to each group.  Also several other bug fixes

client/src/app/shared/models/constants.ts, client/src/app/shared/models/portal-resources.ts, client/src/app/site/site-manage/site-manage.component.ts, server/Resources/Resources.resx, yarn.lock
Related to https://app.zenhub.com/workspace/o/azure/azure-functions-ux/issues/702
Naming the feature item "Metrics" instead of "Monitoring", also using the same icon as Quotas as I noticed the same icon being used in LA blades as well.
Clicking the "Metrics" link will open the Azure Monitoring view Metrics blade:
User would need to select specific metric to display on the graph:
=> Add metrics feature to monitoring section

client/src/app/controls/flex-list/flex-list.directive.ts, client/src/app/controls/right-tabs/right-tabs.component.ts, client/src/app/shared/models/portal-resources.ts, client/src/app/shared/shared.module.ts, client/src/app/site/site-dashboard/site-tab/site-tab.component.ts, client/src/app/site/spec-picker/price-spec-manager/premiumv2-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/price-spec-group.ts, client/src/app/site/spec-picker/spec-list/spec-list.component.html, client/src/app/site/spec-picker/spec-list/spec-list.component.ts, client/src/app/site/spec-picker/spec-picker.component.html, client/src/app/site/spec-picker/spec-picker.component.ts, client/src/sass/base/_base.scss, server/Resources/Resources.resx
1. Added keyboard/screenreader support to spec group tabs
2. Added new flex-list directive to handle keyboard navigation for the items in a flex box.  This is used for navigating the list of specs.
=> Fixes #2480 - Add accessibility support to spec picker

client/src/app/log-streaming/log-streaming.component.ts
Small update to ignore timer clicks if there is already an ongoing polling request for logs.
Before I was using a `switchMap` to cancel the old request if there is a new one due. The problem there is that a new request is always going to be due in 2 seconds, and if the worker is slow or overloaded, it can take more than 2 seconds to get the logs. In that case we will end up in a request/cancel loop and won't be able to catch up.
/cc @davidebbo
=> Wait on existing polling request if it takes longer than 2 seconds.

client/src/app/shared/models/constants.ts, client/src/app/shared/models/portal-resources.ts, client/src/app/shared/models/server-farm.ts, client/src/app/shared/services/plan.service.ts, client/src/app/site/spec-picker/price-spec-manager/basic-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/isolated-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/plan-price-spec-manager.ts, client/src/app/site/spec-picker/price-spec-manager/premium-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/premiumv2-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/price-spec-detail.ts, client/src/app/site/spec-picker/price-spec-manager/price-spec-group.ts, client/src/app/site/spec-picker/price-spec-manager/standard-plan-price-spec.ts, client/src/app/site/spec-picker/spec-feature-list/spec-feature-list.component.html, client/src/app/site/spec-picker/spec-picker.component.html, client/src/app/site/spec-picker/spec-picker.component.scss, client/src/app/site/spec-picker/spec-picker.component.ts, server/Resources/Resources.resx
Scale operations on an Isolated plan return a different HTTP status code than regular plans.  Isolated scale operations also take way longer than regular plans so we need to handle them in the UI differently.  The approach I decided to take was to submit the scale job like normal, but then show a banner that says "scale operation in progress" while it's being scaled (see below).
Note: The GIF has a bug at the end where the apply button gets enabled when you click on another SKU, but I fixed it so that it stays disabled during a scale operation.
=> Fix issue where UI doesn't handle scaling an isolated SKU.  Plus other bug fixes

client/src/app/function/extension-checker/extension-checker.component.html, client/src/app/function/extension-checker/extension-checker.component.ts
Can sometimes take a few seconds to load sidebar if extensions needed to be fetched. Add busy state so it does not appear empty
=> Add busy state when opening create sidebar

client/src/app/shared/services/plan.service.ts, client/src/app/site/spec-picker/price-spec-manager/plan-price-spec-manager.ts
Apparently this API isn't ready for BUILD, so we're going back to the Windows billing api for everything.
=> Reverting changes to allow linux vs windows pricing

client/src/app/function-monitor/monitor-configure/monitor-configure.component.ts
The user will be able to configure the application insights, just not go to the classic view. This change is needed as the logs to web jobs are only written for V1 windows apps.
=> prevent users of V2 app to switch to classic view.

client/src/app/shared/models/portal-resources.ts, client/src/app/site/spec-picker/price-spec-manager/plan-price-spec-manager.ts, server/Resources/Resources.resx
If you open an existing plan, or if you pass in a default sku for create scenarios, then we need to make sure that we're properly selecting it after initialization.
=> SpecPicker - Ensure current sku is selected by default. Fixes #2667, Fixes #2664

client/src/app/api/api-details/api-details.component.ts, client/src/app/api/api-new/api-new.component.ts, client/src/app/binding/binding.component.ts, client/src/app/function-monitor/function-monitor.component.ts, client/src/app/function-quickstart/function-quickstart.component.ts, client/src/app/function/binding-v2/binding-v2.component.ts, client/src/app/function/function-new/function-new.component.ts, client/src/app/shared/services/function-app.service.ts
We seem to be too aggressive in issuing requests that could be perfectly fine if cached. I'm not sure why some of these were changed to ignore cache to begin with like in https://github.com/Azure/azure-functions-ux/pull/2555 
/cc @davidebbo
=> Don't force ignoring cache if there is no need to

client/src/app/function-monitor/monitor-applicationinsights/monitor-applicationinsights.component.html, client/src/app/shared/models/application-insights.ts, client/src/app/shared/services/application-insights.service.ts
Replace True/False with icons. Make it so you would have to close the details blade to to get to the next log item.
=> Cleanup the monitor view a little.

client/src/app/shared/models/portal-resources.ts, client/src/app/site/swagger-definition/swagger-definition.component.html, client/src/app/site/swagger-definition/swagger-definition.component.scss, client/src/app/site/swagger-definition/swagger-definition.component.ts
Word wrap link in pre tag.
Disable 'export to powerapps+flow' button till the Swagger is saved.
=> Styling changes to make the API Definition page better.

client/src/app/site/container-settings/services/container-validation.service.ts
inlcuding the auth header is causing a 403 to be thrown in the antares layer. the token is already being included in the body of the POST, which is how the proxy call is using it.
=> Remove the authorization header from the pass throught container validation api

client/src/app/function/function-new/function-new.component.ts, client/src/app/site/function-runtime/function-runtime.component.ts
- In function app settings tab, remove FUNCTIONS_WORKER_RUNTIME when downgrading to V1
- In function creation page, only use FUNCTIONS_WORKER_RUNTIME if runtime is V2
fixes #3231
=> Downgrade to V1 scenario

client/src/app/function/extension-checker/extension-checker.component.html, server/Resources/Resources.resx
=> Extension styling

client/src/app/extension-install/base-extension-install-component.ts, client/src/app/extension-install/extension-install.component.html, client/src/app/extension-install/extension-install.component.ts, client/src/app/function/extension-checker/extension-checker.component.html, client/src/app/function/extension-checker/extension-checker.component.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> Move extension install logic to base component

client/yarn.lock, server/yarn.lock, yarn.lock
Upgrading to yarn 1.10.1 is causing an update to the yarn.lock file.
=> upgrade yarn to 1.10.1

client/src/app/shared/models/constants.ts, client/src/app/shared/models/portal-resources.ts, client/src/app/site/spec-picker/price-spec-manager/basic-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/elastic-premium-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/free-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/isolated-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/premium-container-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/premium-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/premiumv2-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/shared-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/standard-plan-price-spec.ts, server/Resources/Resources.resx
(https://msazure.visualstudio.com/Antares/_workitems/edit/3117963)
=> Update pricing descriptions to support D1v2 replacement for A2 for all pricing plans

client/src/app/function-dev/function-dev.component.html, client/src/app/function-dev/function-dev.component.ts, client/src/app/shared/models/constants.ts, client/src/app/shared/models/portal-resources.ts, client/src/sass/controls/_buttons.scss, server/Resources/Resources.resx
(https://msazure.visualstudio.com/Antares/_workitems/edit/3124726)
=> Show only infobox in test panel and disable Run button for GitHub webhook functions

client/src/app/site/spec-picker/spec-feature-list/spec-feature-list.component.html, client/src/app/site/spec-picker/spec-picker.component.html, client/src/app/site/spec-picker/spec-picker.component.scss
[Screen Reader - Azure Web - Pricing tier] Incorrect role is defined for 'See additinal options/See only recommended options' on pricing tier blade.
(https://msazure.visualstudio.com/Antares/_workitems/edit/3118152)
[Screen Reader - App Service Plan][MAS 1.3.1]: ARIA attributes must conform to valid values.
(https://msazure.visualstudio.com/Antares/_workitems/edit/3118181)
[Screen Reader -Isolated -Advanced networking and Scale ] Narrator is not reading the name properly of learn more link correctly under Isolated blade.
(https://msazure.visualstudio.com/Antares/_workitems/edit/3118145)
[Note]: using the labelledBy + aria-label combination -> the way the screen reader reads it is the labelledBy id's text then aria-label text and then says link since its a link
=> Accessibility bugs

client/src/app/site/spec-picker/spec-list/spec-list.component.html, client/src/app/site/spec-picker/spec-picker.component.html
[Screen Reader - Pricing tier - Dev/Test (For less demanding workloads)] Heading attributes is not correctly defined on the Dev/Test blade.
(https://msazure.visualstudio.com/Antares/_workitems/edit/3118158)
[Keyboard Navigation - Azure Web - Pricing tier] Keyboard focus is not moving to the Recommended pricing tiers like 'F1 and D1 and B1' on the pricing Tier blade.
(https://msazure.visualstudio.com/Antares/_workitems/edit/3118159)
[Screen Reader - Azure Web - Pricing tier] Name, Role & State are not defined for 'Recommend pricing tiers' like 'F1 and D1 and B1' on pricing tier blade.
(https://msazure.visualstudio.com/Antares/_workitems/edit/3118151)
=> Accessibility bug fixes

client/src/app/site/container-settings/container-settings-manager.ts
related to:
https://msazure.visualstudio.com/Antares/_workitems/edit/3184992
https://msazure.visualstudio.com/Antares/_workitems/edit/3185001
Basically quick start has no concept of startup file, unlike the rest of the image source types.
=> Prevent retrieving startup file(app command) information for quickstart.

client/src/app/pop-over/pop-over.component.html
(https://msazure.visualstudio.com/Antares/_workitems/edit/3118264)
Bug 3118264: [Screen Reader -External (Build Provider : App Service Kudu build server)-Configure]: MAS 4.1.1: id attribute value must be unique.
(https://msazure.visualstudio.com/Antares/_workitems/edit/3118277)
Bug 3118277: [Screen Reader - FTP ]:MAS 4.1.1: id attribute value must be unique
=> Removing 'id' attribute from buttom element in PopOverComponent

client/src/app/site/container-settings/container-image-source/container-image-source-dockerhub/container-image-source-dockerhub.component.html
The issue we're running in to with the form control integration is when the common controls are not re-rendered we are running in to a timing issue of how validation is applied and the textbox is getting disabled. The two ways to solve this is to add a setTimeout to the form itself OR when switching the radio selectors (going from public to private) re-render the textbox. 
The re-render is already being done when switching the container type or the image source... so this is not a new concept for containers.
=> Instead of sharing, re-render common html elements.

server/gulpfile.js
This fixes the table and blob binding extension issue
=> Updating templates to 2.0.0-10296

client/src/app/feature-group/feature-item.ts, client/src/app/shared/models/portal.ts, client/src/app/site/site-manage/site-manage.component.ts
Managed service identity should open as context pane since leaf blade
(https://msazure.visualstudio.com/Antares/_workitems/edit/3122214)
CORS should open as context pane since leaf blade
(https://msazure.visualstudio.com/Antares/_workitems/edit/3122218)
[The openasContextpane option is already there on the Ibiza side]
=> Open MSI and CORS settings blade as context pane since leaf blades

client/src/app/site/spec-picker/price-spec-manager/plan-price-spec-manager.ts
(https://msazure.visualstudio.com/Antares/_workitems/edit/3294344)
=> [Ibiza][DreamSpark] The disabled Standard1/Isolated1 SKU can be selected when create a Web App for DreamSpark

client/src/app/shared/models/constants.ts, client/src/app/shared/services/scenario/onprem.environment.ts, client/src/app/site/site-config/general-settings/general-settings.component.html, client/src/app/site/site-config/general-settings/general-settings.component.ts
New spec picker is not supported yet for azure stack. Using old spec
=> FW: Use old spec picker for azure stack

.github/CODEOWNERS
Reference - https://blog.github.com/2017-07-06-introducing-code-owners/
This will automatically add reviewers, I'm just getting lazy to add each member at a time as a reviewer.
=> Add codeowners file to automatically add reviewers

client/src/app/shared/services/scenario/dynamic-site.environment.ts
Currently the AppSettings blade will fail to load due to a null ref error for a site in limited state.
=> Add null check for sites in limited state. The Sku value is null.

client/src/app/site/site-config/general-settings/general-settings.component.ts
Updating GeneralSettingsComponent to use "Integrated" and "Classic" instead of 0 and 1 when saving managedPipelineMode
(fixes https://msazure.visualstudio.com/Antares/_workitems/edit/3610361)
=> Updating GeneralSettingsComponent to use "Integrated" and "Classic" instead of 0 and 1 when saving managedPipelineMode

client/src/app/site/container-settings/container-image-source/container-image-source-acr/container-image-source-acr.component.ts
With the recent changes to paginate the ACR repositories and tags, the concept of appending items to their respective arrays was introduced. This missed the initialization of items array to an empty set.
=> Hotfix the default selection of ACR repository and tags.

client/src/app/site/slots/deployment-slots/deployment-slots.component.ts
Currently, the Deployment Slots UI will delete an existing routing rule (or fail to add a new routing rule) if the user sets the reroutePercentage for the rule to either 0 or null/undefined.
With these changes, the UI will honor reroutePercentage=0 and will update/create routing rules accordingly.
If a user wants to delete an existing rule, they can still do so by clearing the value in the "TRAFFIC %" textbox (setting it null/undefined) instead of setting it to 0.
=> AB#3988746 Allow users to set routing rules with 0% reroutePercentage

server/Resources/Resources.resx
converted most instances of "slots" to "deployment slots" this is the official term for the feature.
changes all instances of "read-only" to "read only" because consistence is good.
reviewed all read only messages and tried to make them a bit more consistent.
=> Updating read only and deployment slot messages

client/src/app/site/deployment-center/deployment-center-setup/step-configure/configure-vsts-build/windows-frameworks/windows-frameworks.component.ts
https://github.com/Azure/azure-functions-ux/issues/3847
Made the flaskProjectName field mandatory if Flask is selected in frameworks dropdown
=> Bug fix for Issue #3847 - Deployment Center

client/src/app/site/spec-picker/spec-list/spec-list.component.html, client/src/app/site/spec-picker/spec-picker.component.html
[Screen Reader - Azure Web App - Change tags] State "Selected/unselected" not defined for all buttons under Dev/Test and production tab items.
[Keyboard Navigation - Azure Web App - Change tags]keyboard focus is moving to the noninteractive controls like headings 'Recommended pricing tiers...' under production tab.
=> AB #4523981 AB #4523931 AB #4524105 AB #4524086

client-react/src/utils/LogService.ts, client/src/app/shared/services/log.service.ts, client/src/app/site/spec-picker/price-spec-manager/plan-price-spec-manager.ts
Currently, the data gets converted to json on the aiservice side before it logs it and messes it up since all callers are passing in a string to our logservice.
Eg.: 
If we pass in "Failed to get/set price for specs: ${e}"
Gets logged as:
{
"0": "F",
"1": "a",
"2": "i",
"3": "l",
"4": "e",
"5": "d",
"6": "",
"7": "t",
"8": "o",
"9": "",
"10": "g",
"11": "e",
"12": "t",
"13": "/",
"14": "s",
"15": "e",
"16": "t",
"17": "",
"18": "p",
"19": "r",
"20": "i",
"21": "c",
"22": "e",
"23": "",
"24": "f",
"25": "o",
"26": "r",
"27": "",
"28": "s",
"29": "p",
"30": "e",
"31": "c",
"32": "s",
"33": ":",
"34": "",
"35": "T",
"36": "y",
"37": "p",
"38": "e",
"39": "E",
"40": "r",
"41": "r",
"42": "o",
"43": "r",
"44": ":",
"45": "",
"46": "C",
"47": "a",
"48": "n",
"49": "n",
"50": "o",
"51": "t", …
=> AB #4665153 Fix logService for Angular and React so that data is displayed properly in our telemetry

client-react/src/components/FieldWrapper/FieldWrapper.tsx, client-react/src/components/FormControlWrapper/FormControlWrapper.tsx, client-react/src/pages/app/change-app-plan/ChangeAppPlan.tsx, client-react/src/pages/app/change-app-plan/CreateOrSelectResourceGroup.tsx, client-react/src/pages/app/change-app-plan/CreatePlan.tsx
Added a broadcast message to update the website cache in Ibiza once an app is changed to a new plan.  Also added a new component called "FieldWrapper" which makes it easier to handle dynamic input field layout with consistent label and tooltip styles.
=> AB#4675469 - Added field wrapper component and fixed issue where changing plan doesn't update essentials

client/src/app/site/deployment-center/deployment-center-setup/wizard-logic/azure-devops.service.ts
Setting msaPassthrough as false for newAccounts and save unnecessary iteration cycles for all accounts.
Issue - #4000
=> Setting msaPassthrough as false for newAccounts

client/src/app/shared/models/arm/hosting-environment.ts, client/src/app/shared/models/constants.ts, client/src/app/shared/preconditions.ts, client/src/app/shared/services/scenario/app-on-ase.environment.ts, client/src/app/shared/services/site.service.ts
To ensure we get the right type for comparison, force a call with the 2016-09-01 api version
=> OGF Test Pass Fix

client/src/app/site/spec-picker/spec-picker.component.scss
=> AB#4803601 [Safari] It cannot show the frame correctly when select ASP's pricing tire

client/src/app/site/deployment-center/deployment-center-setup/step-complete/step-complete.component.ts, client/src/app/site/deployment-center/deployment-center-setup/step-configure/configure-external/configure-external.component.html
There are certain cases reported where the call to save is going through multiple times in a rapid burst. With the logs we have not been able to identify what would cause this. The current theory is that there might be something happening due to the busy state manager.. hopefully this will fix the issue.
=> AB#4941153 Add debounce logic fpr saving deployment config.

client/src/app/shared/models/constants.ts, client/src/app/shared/models/portal-resources.ts, client/src/app/site/deployment-center/deployment-center-setup/validators/vsts-validators.ts, client/src/app/site/deployment-center/deployment-center-setup/wizard-logic/deployment-center-state-manager.ts, server/Resources/Resources.resx
Fixes #4040
Currently VSTS access token is fetched when component is created. But user can choose to click "finish" at a later time. This can result in stale token.
Also, we see some invalid token errors in Azure DevOps service while configuring CD. Hence adding better validation and error logging for token in UX.
Fixes #4045 
Add a validation for checking whether Pipelines service is enabled for user selected Azure DevOps project.
=> Fix Deployment center bugs #4040 and #4045

client/src/app/shared/url-templates.ts
URL change got introduced with the key update's hotfix we did day before yesterday.
=> AB#5084350 [ICM 138326185] Fix get proxies URL for v1 functions

client/src/app/shared/services/function-app.service.ts
This is reverting Travis's fix.  His issue was that we were always sending the ARM token in every request to our FE and our FE was failing to parse that token in some cases.  I tested this and it looks like that header got removed organically somewhere recently so this shouldn't be an issue anymore.
=> [Functions] Fix issue where passthrough API is not getting called if run action in editor fails due to CORS

client/src/app/site/site-manage/site-manage.component.ts
**Before: No dropdowns have any value**
**After: Resource and Metric namespace have preselected values**
=> AB#5107315 Pass ResourceId parameter to open Metrics blade with the resource preselectedfrom FunctionApp

client/src/app/shared/services/function-app.service.ts, client/src/app/tree-view/function-node.ts
Runtime version needs to be a property of URL templates for access at context and templates level.
=> Key fix for url template files

client/src/app/function-quickstart/function-quickstart.component.ts, client/src/app/function/function-new-detail/function-new-detail.component.ts, client/src/app/shared/services/function.service.ts, client/src/app/site/quickstart/step-create-portal-function/step-create-portal-function.component.ts
DOTNET_USE_POLLING_FILE_WATCHER=true has been fully deployed, so this restart is no longer needed!
Fixes AB#5136429
=> Remove Linux app restart on function creation

client/src/app/site/spec-picker/price-spec-manager/basic-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/elastic-premium-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/free-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/isolated-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/plan-price-spec-manager.ts, client/src/app/site/spec-picker/price-spec-manager/premium-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/premiumv2-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/shared-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/standard-plan-price-spec.ts
I have created a separate WI to update the React side in S125 (will do it along with the other work left for the spec picker move to React)
=> AB#5160316 [FunctionAppFullScreenCreate][Fusion] Update spec picker to support showing only Elastic Premium sku's scenario

client-react/src/models/batch-models.ts, client-react/src/models/portal-models.ts, client-react/src/portal-communicator.ts
Adding new RPC call which will allow you to send long-running ARM requests thru the iframe boundary.  The benefit of this is that the hosting Ibiza extension can complete the long-running job for you.  Since the extension is a long-lived entity, it should be able to complete any long-running job so that if the user closes their iframe blade, it will still complete.
=> [React] Adding new iframe RPC call for ARM async update requests

client-react/src/pages/app/app-settings/ApplicationSettings/ApplicationSettings.tsx, client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStrings.tsx
Fixes AB#4766364
This change makes sure that the screen reader reads the `Name` field  whenever it is updated for Application-Settings or Connection-Strings before reading any other focused element.
=> Force Screen Reader to read the updated Name field in Application Setting or Connection String

client/src/app/tree-view/proxies-node.ts
Basically when the function app is newly created there is not proxy file, so it is totally valid to have a not found error. This just means we need to allow the user to click the '+New Proxy' button. Right now they would need to either click the '+' button in left nav OR update through 'advanced editor'.
=> AB#5197769 Show New Proxy button if the error is proxy not found.

client/src/app/site/deployment-center/provider-dashboards/vso-Dashboard/vso-dashboard.component.html, client/src/app/site/deployment-center/provider-dashboards/vso-Dashboard/vso-dashboard.component.ts
fixes AB#4989512
Before
After
Also removing the clickability to go to that specific slot from the deployment dashboard as it will end up creating infinite journeys. you're already in slots, just need to click the overview button.
=> Update deployment center to show the actual app where the code is being deployed to. This inlcudes the slot name in it.

client/src/app/shared/models/portal-resources.ts, client/src/app/site/deployment-center/deployment-center-setup/step-source-control/step-source-control.component.html, client/src/app/site/deployment-center/deployment-center-setup/step-source-control/step-source-control.component.ts, server/Resources/Resources.resx
fixes AB#4955281
This is a super edge case scenario and very rare. But we have had an instance where the /sourcecontrols API was failing and we repeated asked users to re-authenticate. Instead show a message.
There really isn't a better way to put an error message here. Fortunately we are logging the event, so if the users contact us we will be able to identify exactly what failed.
If all works fine, you should see:
Currently on failure you see (notice github is asking for authorization again):
With the fix you will see an error message:
=> Show error message if user level /sourcecontrols API fails

client-react/src/models/portal-models.ts, client-react/src/pages/app/app-settings/AppSettingsDataLoader.tsx, client-react/src/pages/app/change-app-plan/ChangeAppPlan.tsx, client-react/src/portal-communicator.ts, client/src/app/feature-group/feature-item.ts, client/src/app/function-edit/function-edit.component.ts, client/src/app/function-monitor/monitor-applicationinsights/monitor-applicationinsights.component.ts, client/src/app/shared/models/portal.ts, client/src/app/shared/services/portal.service.ts, client/src/app/site/function-runtime/function-runtime.component.ts, client/src/app/site/site-config/general-settings/general-settings.component.ts, client/src/app/site/site-config/mount-storage/mount-storage.component.ts, client/src/app/site/site-dashboard/site-dashboard.component.ts, client/src/app/site/site-manage/site-manage.component.ts, client/src/app/site/site-summary/site-summary.component.ts, client/src/app/slot-new/slot-new.component.ts
I noticed that figuring out how to open a FrameBlade from Fusion can be confusing because the required structure of detailBladeInputs property isn't obvious.
The structure needs to look like below, with a required 'id' property and an optional 'data' property containing some object.
```
detailBladeInputs : {
id: string,
data?: <some object>,
}
```
However, a common mistake is to just use the data object directly, like below.
```
detailBladeInputs : <some object>
```
I think we can eliminate this confusion by adding explicit interfaces and functions specific to opening a FrameBlade.
=> Adding explicit interface for opening FrameBlades from Fusion

client-react/src/images/Functions/double-arrow-left-right.svg, client-react/src/images/Functions/single-arrow-left-right.svg, client-react/src/pages/app/functions/integrate/FunctionIntegrate.tsx
Here's my first attempt at adding arrows to the functions integrate page.  We can play around with the look of the arrows and figure out proper min and max-widths.  For shrinking, we still need to figure out what it looks like in a responsive design.
@refortie & @agruning - Please take a look.
=> Adding arrows to functions integrate

client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMounts.tsx, server/Resources/Resources.resx
The backend only supports the creation of 5 mounts at a time. Even though the APIs will return a 200, it will be inaccessible and on reload vanish from our list.
=> Disable creation when there are 5 mounts specified

client/src/app/site/site-summary/site-summary.component.ts
This reverts commit b53c8efe42c077f6eb56d90034f827eaff06db73.
**Will re-add this in S126 since we want it to go just before Ignite - wait till 10/28**
=> Revert "AB#5488629 Remove Poweshell Preview status bar from function app overview (#4200)"

client/src/app/shared/services/scenario/national-cloud.environment.ts, client/src/app/site/deployment-center/deployment-center-setup/step-source-control/step-source-control.component.ts
fixes AB#5550541 for National Clouds.
=> Only invoke the sourcecontrols API if at least one token based sourcecontrol source is available.

client-react/src/images/Functions/double-arrow-left-right.svg, client-react/src/images/Functions/single-arrow-left-right.svg, client-react/src/pages/app/functions/integrate/BindingsDiagram/BindingCard.tsx, client-react/src/pages/app/functions/integrate/BindingsDiagram/BindingDiagram.styles.ts, client-react/src/pages/app/functions/integrate/FunctionIntegrate.style.ts, client-react/src/pages/app/functions/integrate/FunctionIntegrate.tsx, client-react/src/theme/SemanticColorsExtended.ts, client-react/src/theme/dark.ts, client-react/src/theme/light.ts
Implements AB#5543870
Add some basic theme-based styling to the page to make it visible in all modes. We don't have final styling from the designers, but this should be enough to continue development in the area
Before dark theme:
Light theme:
Dark theme:
=> Integrate page theme first pass

client-react/src/pages/app/app-settings/AppSettings.service.ts, client-react/src/pages/app/app-settings/AppSettingsDataLoader.tsx
Fixes: https://msazure.visualstudio.com/Antares/_workitems/edit/5584673
=> AB#5584673 Updating AppSettingsDataLoader to not block on fetchAzureStorageAccounts() call

client/src/app/function-monitor/function-monitor.component.ts, client/src/app/function-monitor/monitor-classic/monitor-classic.component.ts, client/src/app/shared/models/function-monitor.ts
During one of my recent changes, the check to identify if AI is allowed in an environment got merged with with whether or not the AI resource exists. This caused a bug where users who had opted not to setup AI during creates were left in a state where they could not provision an AI instance. 
**BEFORE (V1 or V2 app without AI during create)**
**AFTER (v1 app)**
If you decide to swith to classic view:
**AFTER (v2 app)**
Note: not able to switch to classic view.
**Once AI is configured**
=> Fixed the AI splash screen and upsell from the classic view

client/src/app/controls/group-tabs/group-tabs.component.html, client/src/app/controls/group-tabs/group-tabs.component.scss, client/src/app/controls/group-tabs/group-tabs.component.ts, client/src/app/site/container-settings/container-settings-manager.ts
fixes AB#5603287
@btardif let me know if this works.
Basically only show K8 tab IFF the user has it already configured, otherwise hide it from the settings. We've already removed it from creates. 
Spec picker tabs are unaffected
Container settings with K8
Container setting without K8
=> Gracefully deprecate K8 from container settings

client-react/src/components/form-controls/TextFieldNoFormik.tsx, client-react/src/components/form-controls/formControl.override.styles.tsx
**width > 1000px**
Before
After
**width <= 1000px**
Before
After
**width > 1000px**
Before
After
**width <= 1000px**
Before
After
=> AB#5785169 Fixing ReactiveFormControl to fill width of parent

client/src/app/function-monitor/monitor-applicationinsights/monitor-applicationinsights.component.html, client/src/app/function-monitor/monitor-details/monitor-details.component.html
fixes AB#5998162
Before
After
this is due to a request from the daily sad mail that the icon was confusing.
=> Update icons to app insight icon

client-react/src/ApiHelpers/FunctionsService.ts, client-react/src/pages/app/functions/quickstart/FunctionQuickstart.data.ts, client-react/src/pages/app/functions/quickstart/FunctionQuickstart.tsx, server/src/constants.ts, server/src/functions/functions.controller.ts, server/src/functions/functions.service.ts
This reverts commit 463a3fde2360fd169bc85e32fc40dca5c031127d.
Revert this again since it seems to be causing functions-next to return status 500.
=> Revert "Quickstart language support added (Re-added :P) (#4517)"

client/src/app/site/deployment-center/provider-dashboards/github-action-dashboard/github-action-dashboard.component.ts
During the disconnect scenario there is a race condition where the disconnect call has gone through and the dashboard also has just begun a refresh and the call returns null sourcecontrols information due to the disconnect. This check will help prevent an error showing up on the console due to this.
=> Add null check while rendering the dashboard.

client/src/app/shared/services/application-insights.service.ts
NOTE: this does not affect our public clouds at all, but due to the JEDI timeline requirements and proceeding work on the functions portal we do need this to go out in our next national clouds deployment.
=> Add AI API urls for national clouds

client/src/app/shared/models/portal-resources.ts, client/src/app/site/deployment-center/deployment-center-setup/deployment-center-setup.component.scss, client/src/app/site/deployment-center/deployment-center-setup/step-complete/step-complete.component.html, client/src/app/site/deployment-center/deployment-center-setup/step-complete/step-complete.component.ts, client/src/app/site/deployment-center/deployment-center-setup/step-configure/configure-github/configure-github.component.html, client/src/app/site/deployment-center/deployment-center-setup/step-configure/configure-github/configure-github.component.ts, client/src/app/site/deployment-center/deployment-center-setup/step-configure/configure-github/stack-selector/stack-selector.component.html, client/src/app/site/deployment-center/deployment-center-setup/wizard-logic/github.service.ts, server/Resources/Resources.resx
Fixes AB#6287684
Fixes AB#6287563
Fixes AB#6223484
If the user has a .github/workflows folder than the assumption is that they have some kind of a workflow configuration setup.
So now, if the user has the exact app workflow configuration file (could be due to disconnect and reconnect scenario), we prompt the user to see if we should overwrite that exact file and/or use that exact configuration.
If not the above case, than check if the user has a .github/workflows folder. If so, than they have some configuration in place. We should let the user know that is the case and give them an option to either continue by adding our configuration or using their existing one.
If there is an exact file name match
If there are no configurations
=> Clean up the CSS and add check for ANY workflow configuration

client-react/src/pages/app/functions/integrate/BindingsDiagram/BindingCard.tsx, client-react/src/pages/app/functions/integrate/FunctionIntegrate.tsx
Refresh the integrate page if we fail to create/update/delete so we get the actual state of the app
Fixes AB:6278904
=> [Ibizafication][Integrate] Refresh the integrate page if we fail to update bindings

client-react/src/pages/app/functions/common/ResourceDropdown.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Ignore the juttering cursor, recording didn't link my remote desktop
=> [Ibizafication][Integrate] Show an error message when the expected app setting is missing

client-react/src/pages/app/functions/integrate/FunctionIntegrate.tsx
Fixes AB#6216688
Although we set the editor to close before we cleared the old binding, the animation on closing meant that the user would see the Create Binding title flash. Removed unnecessary calls to remove binding to update, we set the binding properly every time we open the panel, so we shouldn't need to clear out the old one
=> [Ibizafication][Integrate] Closing editor shouldn't show Create binding title

client-react/src/components/FormControlWrapper/FormControlWrapper.tsx
Fixes AB#6217147
Images have width set extra short to show off functionality
Create:
Integrate:
Pivot:
Multiline true for text boxes, false for dropdowns
=> [Ibizafication] Labels should overflow

client-react/src/pages/app/functions/function/integrate/binding-card/BindingCard.styles.ts, client-react/src/theme/dark.ts
Fixes AB#6559512
Need to increase the contrast between the link color and the card body background
Before:
After:
=> [Ibizafication][Integrate][WCAG] Increase contrast in card body color

server/src/stacks/stacks.webapp.create.service.ts
No need for a hotfix here as this is not currently used in the creates.
=> Mirror changes on the runtime stacks API

client-react/src/components/FormControlWrapper/FormControlWrapper.tsx
It looks like a recent change to the FormControlWrapper class broke the alignment for horizontal wrappers.  The fix I've made makes it slightly better, though I think to really fix the vertical alignment of the info bubble, should probably redo some of the changes that regressed this.
This is what's in canary today:
Here's what it looks like after my fix:
I also verified that this doesn't break the integrate blade:
=> Fixing info bubble alignment for horizontal layout of FormControlWrapper

client/src/app/site/spec-picker/spec-picker.component.scss, client/src/sass/common/_variables.scss
Fixes AB#6428322
Before:
After:
Contrast ratio tool:
=> AB#6428322 Accessibility issues - Fix colors

client-react/src/components/ConfirmDialog/ConfirmDialog.styles.ts, client-react/src/pages/app/app-settings/FunctionRuntimeSettings/RuntimeVersion.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes [AB#6455986](https://msazure.visualstudio.com/Antares/_workitems/edit/6455986)
**BEFORE:**
- If app has functions, the warning is always shown, even if the user isn't trying to switch to a runtime version with breaking changes.
- The breaking versions are disabled in the dropdown with no explanation. 
**AFTER:**
- The breaking versions are not disabled in the dropdown.
- If a breaking version is selected from the dropdown, a confirmation dialogue is shown.
- The warning message (with updated text) is shown only if the breaking version dialog is confirmed.
=> AB#6455986 Adding confirmation dialogue when switching runtime versions

client-react/src/components/CustomBanner/CustomBanner.styles.ts, client-react/src/components/CustomBanner/CustomBanner.tsx
- Updates
- Let banner height grow if text overflows, instead of letting text wrap beyond the bottom of the banner.
- Don't wrap text around icon
- **Screenshots**
- **Long string + Reflow Min + Fabric UI Icon**
- Text wraps beyond the height of the banner
- Large gap between icon and text
- First line of text is indented
**BEFORE**
**AFTER**
- **Long string + Reflow Min + Custom Icon**
- Text wraps beyond the height of the banner
- Text wraps around icon
**BEFORE**
**AFTER**
- **Long string + Reflow Off + Fabric UI Icon**
- Large gap between icon and text
**BEFORE**
**AFTER**
- **Long string + Reflow Off + Custom Icon**
- No issues
**BEFORE**
**AFTER**
- **Short string + Reflow Min + Fabric UI Icon**
- Large gap between icon and text
**BEFORE**
**AFTER**
- **Short string + Reflow Min + …
=> Fixing text overflow and text wrapping in CustomBanner

client-react/src/pages/app/deployment-center/DeploymentCenterFtps.tsx
The features are functional.. but just saw the warning and added the key to prevent it.
https://reactjs.org/docs/lists-and-keys.html#keys
=> Add keys to allow react unique identification of arrayed elements

client/src/app/site/deployment-center/deployment-center-setup/wizard-logic/github.service.ts
This was only tested for Java on Windows where the indexOf is always greater than 0 as TOMCAT is the middle element... but since we enabled this for linux, TOMCAT is the prefix causing the index to be 0.
Also no need to hotfix as it is already like this in prod.
=> Deployment Center - Update the condition to be more accurate or Java on Linux

client/src/app/site/slots/add-slot/add-slot.component.html, client/src/app/site/slots/swap-slots/swap-slots.component.html
Revert "Updating AddSlotComponent and SwapSlotsComponent to use <drop-down/> instead of <ng-select/> and setting aria-label attributes"
This reverts commit c0d43c5e48054b50fdf05e44fd5cb6ae49a536cc.
=> [HOTFIX] Switch AddSlotComponent and SwapSlotsComponent back to using <ng-select/>

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerFormBuilder.ts
Just noticed that the current condition shows and error message on load of the textbox. this update only triggers the error message IF password is being typed and it does not meet the regex standards.
=> Upate password validation condition to only trigger once the password is being typed.

client-react/src/models/functions/function-binding.ts, client-react/src/pages/app/functions/common/BindingFormBuilder.tsx, client-react/src/pages/app/functions/create/CreateCard.tsx, client-react/src/pages/app/functions/function/integrate/BindingPanel/BindingCreator.tsx, client-react/src/pages/app/functions/function/integrate/BindingPanel/BindingEditor.tsx, client-react/src/pages/app/functions/function/integrate/FunctionIntegrate.tsx, client-react/src/pages/app/functions/function/integrate/FunctionIntegrate.utils.ts, client-react/src/pages/app/functions/function/integrate/FunctionIntegrateConstants.ts, client-react/src/pages/app/functions/function/integrate/binding-card/InputBindingCard.tsx, client-react/src/pages/app/functions/function/integrate/binding-card/OutputBindingCard.tsx, client-react/src/pages/app/functions/function/integrate/binding-card/TriggerBindingCard.tsx, client-react/src/utils/string.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
We will now place the trigger based on the type, not just the direction and also show a banner when we run into a situation with a compiled function and no input/output bindings
=> [Ibizafication][Integrate] Show message for compiled functions and missing bindings

client-react/src/components/CustomBanner/CustomBanner.tsx
Fixes AB#7024510
Original issue was fixed in the past, but we need to turn on multiline so that we don't ellipses in small, but not quite small enough for reflow.
Before:
After:
=> [Ibizafication] Turn on multiline for all banners

client/src/app/site/spec-picker/spec-picker.component.scss, client/src/sass/common/_variables.scss
Fixes #7126417
**Before**:
No focus indicator on the sku's
**After**:
Focus indicator is shown as you move around using arrow keys
=> AB#7126417 [Visual Requirements - App Service web - App Service Plan - Production] Focus indicator is not visible on the pricing tier buttons.

client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/DeploymentCenterCommandBar.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterDataLoader.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubDataLoader.tsx
Fixes ab#7308736
Note: will do separate PR for making sure Command Bar remains upon refresh but in an inactive state
=> Implemented Deployment Center refresh for client-react

client-react/src/utils/LogService.ts
Just realized that the identifiers shows up as [object Object] instead of the json string.
=> Update the identifiers object to be stringified JSON to show up in the AI based logs in Kusto

client-react/src/components/form-controls/DropDownnoFormik.tsx, client-react/src/components/form-controls/ReactiveFormControl.tsx, client-react/src/components/form-controls/TextFieldNoFormik.tsx, client-react/src/components/form-controls/formControl.override.styles.tsx, client-react/src/pages/app/functions/common/BindingFormBuilder.tsx, client-react/src/pages/app/functions/common/CreateFunctionFormBuilder.tsx
Part of AB#6559426
Updating the ReactiveFormControl to have all the functionality of FormControlWrapper. Also setting BindingFormBuilder to use it exclusively.
Followup PRs will change the rest of the uses of FormControlWrapper to start using ReactiveFormControl instead.
Function Create
Before
After
Function Integrate
Before
After
Change App Service Plan (Should be no change)
Before
After
Function Keys (Should be no change)
After
=> [Ibizafication] Remove FormControlWrapper pt1 - Update ReactiveFormControl

client-react/src/pages/app/functions/function/integrate/BindingPanel/BindingCreator.tsx, client-react/src/pages/app/functions/function/integrate/BindingPanel/BindingEditor.tsx
* Fixes missing aria label on drop down
Fixes AB#6559428
Fixes AB#6559479
Before
After
=> [Ibizafication][WCAG][Integrate] Convert binding type to use ReactiveFormControl

client/src/app/controls/group-tabs/group-tabs.component.html, client/src/app/controls/group-tabs/group-tabs.component.scss, client/src/app/site/spec-picker/spec-feature-list/spec-feature-list.component.html, client/src/app/site/spec-picker/spec-list/spec-list.component.html, client/src/app/site/spec-picker/spec-picker.component.html, client/src/app/site/spec-picker/spec-picker.component.scss
Nothing changes visually. Just made sure we don't have multiple h1 tags on the page
Before:
After:
=> AB#7117858 [Screen reader - App Service web - App Service Plan - Production] There is more than one Heading 1 (three in number) defined on the page.

client-react/src/pages/app/functions/function/integrate/binding-card/BindingCard.tsx
Fixes AB#7363182
Instead of empty fields we want to remove them entirely from the object we save. Some optional fields can't handle having empty strings
Also this will be necessary for when we add in optional drop down options, we will want to remove the blank entries from the model then as well See AB#7429210 for that
=> [Integrate] Delete fields with empty values

client-react/src/models/pricingtier.ts, client-react/src/models/site/compute-mode.ts, client/src/app/shared/models/arm/pricingtier.ts, client/src/app/shared/models/arm/site.ts, client/src/app/site/spec-picker/price-spec-manager/price-spec-group.ts
It was a bug that the backend returned integer for enum values on api version 2018-11-01. It should return string. With that fixed. The entity receiving the data need to be changed too
=> ComputeMode, SpecGroup, SpecSection are now strings passed from backend

server/src/stacks/webapp/2020-05-01/stacks/config/linux/node.ts
Was already marked deprecated in 2020-06-01, updating value for 2020-05-01
Fixes AB#7371174
=> [Stacks][WebApp] Mark nodelts as deprecated

client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx, client-react/src/pages/app/functions/function/function-log/FunctionLogCommandBar.tsx
More work for AB#7613298
1) Track when customer expands log panel so we can see what percentage of users who open logs are switching to Filed-Based
2) Track if customer switches back to App Insights Logs from File-Based
=> [Functions][Logs] Add more event tracking for logs in editor

client/src/app/site/slots/swap-slots/swap-slots.component.html, client/src/app/site/slots/swap-slots/swap-slots.component.ts
Fixes AB#5561926
Part of the UI broke when using the 2 stage slot swap. The issue was due to how angular interpreted the boolean value of the drop down (translated it into a string), instead of trying to handle that in old code, decided to go with changing the data to string instead since it just powers controls and isn't saved anywhere
=> [Slots] Fixed issues relating to using boolean values

client-react/src/ApiHelpers/SiteService.ts, client-react/src/models/site/site.ts, client-react/src/pages/app/app-settings/AppSettings.types.ts, client-react/src/pages/app/app-settings/AppSettingsDataLoader.tsx, client-react/src/pages/app/app-settings/AppSettingsFormData.ts, client-react/src/pages/app/app-settings/GeneralSettings/Platform.tsx, client-react/src/pages/app/deployment-center/DeploymentCenter.data.ts, client-react/src/pages/app/deployment-center/DeploymentCenterContext.ts, client-react/src/pages/app/deployment-center/DeploymentCenterDataLoader.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterFtps.tsx, client-react/src/utils/FwLinks.ts, client/src/app/shared/models/arm/site.ts, client/src/app/shared/models/constants.ts, client/src/app/shared/models/portal-resources.ts, client/src/app/shared/services/site.service.ts, client/src/app/site/deployment-center/provider-dashboards/credentials-dashboard/credentials-dashboard.component.html, client/src/app/site/deployment-center/provider-dashboards/credentials-dashboard/credentials-dashboard.component.ts, client/src/app/site/deployment-center/provider-dashboards/deployment-credentials/deployment-credentials.component.html, client/src/app/site/deployment-center/provider-dashboards/deployment-credentials/deployment-credentials.component.ts, server/Resources/Resources.resx
Fixes AB#6735725
Currently users can use an API/CLI to set provider level policies to block FTP connections. In this case, regardless of what the config value is, we should show that the FTP option is disabled and hide the FTP credentials. App Service API team has created a resource level API which indicates the FTP policy that should be followed by the UX.
** Configuration **
** Deployment Center **
** Classic deployment center **
yes! the ftp url shows up... removing that is a lot more work than necessary:
=> Disable FTP options IF disable policy is set

client-react/src/pages/app/app-settings/Sections/PathMappingsPivot.tsx
=> [BYOS] Storage Mounts don't show dirty state on tab

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeBuildRuntimeAndVersion.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.ts, client-react/src/pages/app/deployment-center/utility/GitHubActionUtility.ts, client-react/src/utils/stacks-utils.ts, client/src/app/shared/models/constants.ts, client/src/app/shared/models/portal-resources.ts, client/src/app/site/deployment-center/deployment-center-setup/step-build-provider/step-build-provider.component.ts, client/src/app/site/deployment-center/deployment-center-setup/step-complete/step-complete.component.ts, client/src/app/site/deployment-center/deployment-center-setup/step-configure/configure-github/stack-selector/stack-selector.component.html, client/src/app/site/deployment-center/deployment-center-setup/step-configure/configure-github/stack-selector/stack-selector.component.ts, client/src/app/site/deployment-center/deployment-center-setup/step-source-control/step-source-control.component.ts, client/src/app/site/deployment-center/deployment-center-setup/wizard-logic/deployment-center-state-manager.ts, client/src/app/site/deployment-center/deployment-center-setup/wizard-logic/github.service.ts, server/Resources/Resources.resx, server/src/stacks/webapp/2020-05-01/stacks/create/aspDotnet.ts, server/src/stacks/webapp/2020-06-01/stacks/aspDotnet.ts, server/src/tests/Stacks/WebApp/2020-05-01/validations.ts
fixes AB#7881869
fixes AB#7816083
Remove the 'preview' tags from GitHub Action. This requires following changes:
1. Add ASP.NET Support
2. Move to webapp deploy action from v1 to v2
3. Remove the actual 'preview' tag
=> Transition GitHub Action out of 'preview' mode

server/src/stacks/functionapp/2020-05-01/stacks/powershell.ts, server/src/stacks/functionapp/2020-06-01/stacks/powershell.ts
Set isDeprecated flag to true for PowerShell 6
cc: @pragnagopa @stefanushinardi @gzuber @anirudhgarg
=> Set isDeprecated flag to true for PowerShell 6

client/src/app/shared/services/ai.service.ts, client/src/app/shared/services/log.service.ts, client/src/app/shared/services/portal.service.ts
fixes AB#7927056
fixes AB#7927080
Currently we have either Ibiza sessionId OR AI autogenerated sessionId, so '927b92d7e0e040a4a7e9bfe33590d3d8' or 'pTuOd'
Also the resource Ids either start with /ng-min/feature or not. 
This PR will standardize the logs emitted by Angular similar to how the logs are emitted for React.
=> Update the angular traces to contain identifier fields in our clienTelemetery logs

client-react/src/SiteState.ts, client-react/src/pages/app/SiteRouter.tsx, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/DeploymentCenterContext.ts, client-react/src/pages/app/deployment-center/DeploymentCenterDataLoader.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterFtps.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterPublishingContext.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeBuildConfiguredView.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeBuildRuntimeAndVersion.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeCommandBar.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeDataLoader.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodePivot.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerDataLoader.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerPivot.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubConfiguredView.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubProvider.tsx
While going through and understanding the changes needed to enable the container scenario, I realized that currently at the top level we a very tightly coupled with container and code scenarios. This PR does not contain any addition or removal of functionality, but only re-structing of things. The restructure has caused three major changes:
1. Moving the FTP credentials and publishing profile data and functions which are shared in ALL scenarios to its own context - PublishingContext.
2. Introducing CodeDataLoader and ContainerDataLoader. Currently parent dataloader was making network calls for both code and container scenarios and also building the formdata and yup validation schema for both. With this change, it is first decided the type of app we are working with and only going down …
=> Get Deployment Center Preview ready for container based updates

client/src/app/api/api-details/api-details.component.ts, client/src/app/api/api-new/api-new.component.ts, client/src/app/shared/models/constants.ts, client/src/app/shared/models/functions-version-info.ts, client/src/app/shared/services/function-app.service.ts, client/src/app/shared/services/site.service.ts, client/src/app/shared/url-templates.ts, client/src/app/tree-view/proxies-node.ts
Fixes AB#7858844
In order to use the correct VFS API, we need the RuntimeVersion of the app, and thus the getHostStatus call.
=> [Proxies] Update proxies experience to use VFS APIs

client/src/app/shared/models/serverFarmSku.ts, client/src/app/site/spec-picker/price-spec-manager/elastic-premium-plan-price-spec.ts
Fixes AB#5992610
Before:
After:
=> AB#5992610 [S145] Update Elastic Premium prices to use new meterIds in spec picker keeping the multiplier hardcoded

client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/DeploymentCenterFormBuilder.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeCommandBar.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeFormBuilder.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerDockeHubSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerFormBuilder.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerPrivateRegistrySettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSettings.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubWorkflowConfig.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubWorkflowConfigPreview.tsx, client-react/src/pages/app/deployment-center/utility/GitHubActionUtility.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
This PR wires up the GitHub Action workflow process with the existing container forms. Following are the overall states/scenarios:
No GitHub action
Gather the serverUrl, username, password, image, and tag
GitHub branch is clean, no workflows exist
Gather the serverurl, username, password, and image
GitHub branch has workflows, but overwrite option is selected
Gather the serverurl, username, password, and image
GitHub branch has workflow, but use existing or use available option is selected
Gather the serverurl, username, and password
In case of ACR - the serverurl and credentials are mapped via the registry dropdown
In case of dockerhub, the server url is assumed to be index.docker.io.
With the preview side panel
=> Wire up the container forms with GitHub Action workflow process

client/src/app/site/deployment-center/deployment-center-setup/step-source-control/step-source-control.component.ts
There was a bug reported earlier where for linux ASP function apps the deployment center is trying to query for githubAction workflows. This is currently not supported for FunctionApps. For now setting the default value for build provider back to kudu to be on the safe side as that option is universally operational.
=> HOTFIX: reset the default provider in classic deployment center to kudu

client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerContinuousDeploymentSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerFormBuilder.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSettings.tsx
Customers will have an option to setup a continuous deployment pipeline if they choose to do so without having to use github actions.
The option is available for all container source types. But it is not available if you choose to setup deployments via github actions.
=> Add continuous deployment option for non-github action based setup.

client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrDataLoader.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerCommandBar.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerDockeHubSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerFormBuilder.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerPrivateRegistrySettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSettings.tsx, client-react/src/utils/CommonConstants.ts
There are three types of registry sources - acr, dockerHub, and privateRegistry. Each have their own way of forming serverUrl, username, password, image, and tag. Initially I had implemented a common form data to be used across all three sources. Now from past experience, users tend to switch between each source while setting up and expect the whatever values they have selected in each source is persisted till they save. Due to this requirement, we need to have separate formdata properties for each of the sources. Thus this PR.
=> [DeploymentCenterV2] Persist the form state of each registry source

client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubAccount.tsx
Fixes AB#8180312
Before:
After:
=> [Deployment Center V2] Move GitHub description banner to description

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerFormBuilder.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSettingsConfiguredView.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSettingsReadOnlyView.tsx
If the container is wired up via GitHub Action. Than on reload the page should load the readonly view with an option to disconnect rather than an editable form.
=> Add the readonly view for github action based container setup

client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/DeploymentCenterFormBuilder.ts, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubDataLoader.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubProvider.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubWorkflowConfigSelector.tsx
Preserve the selected dropdown values when switching between tabs.
=> Auto populate pre-selected fields for GitHub provider on tab switching

client-react/src/utils/stacks-utils.ts
Fixes AB#8195697
Fixes AB#8196063
Default Stack:
Configured View:
=> [Deployment Center V2] Showing Java 8 stack and runtime

client-react/src/ApiHelpers/SiteService.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.data.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx, client-react/src/pages/app/deployment-center/utility/GitHubActionUtility.ts
After a ton of discussion with @ehamai we found a solution where we can simple update the metadata and scmtype for a site with the source control information. This allows the source controls and site config APIs to return the correct payload post-save. It also preserves the user data for future disconnect scenarios. 
With this change once the source controls api is fixed, we can simply remove the change.
=> Implement workaround in case the original source controls API fails.

client-react/src/ApiHelpers/SiteService.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.data.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSource.tsx, client-react/src/pages/app/deployment-center/utility/GitHubActionUtility.ts, client/src/app/site/deployment-center/deployment-center-setup/wizard-logic/deployment-center-state-manager.ts
There are three separate commits in this file:
Fixing the discard button for deployment center preview:
https://github.com/Azure/azure-functions-ux/commit/c7652c649d273465a12e767bc737e47717c4e300
Implementing the API workaround for deployment center preview:
https://github.com/Azure/azure-functions-ux/commit/a24925c0c632095fe549bf0b7482032c10ddb719
Hotfixing the API workaround for deployment center classic:
https://github.com/Azure/azure-functions-ux/commit/da67fb3ec058f17d929fc84735a57aacdc11a5b7
When pushing this change to the release-s148 branch we should make sure to NOT squash and preserve individual commits.
=> [DO NOT SQUASH] Cherry-pick recent changes for deployment center fixes

client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSettings.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubWorkflowConfigPreview.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubWorkflowConfigSelector.tsx
This is pretty much doing the same thing as before except in some cases the content remained "sticky" depending on which useEffects got fired. So in this change, the useEffects affect the "Preview" button enablement/disablement.. but once the Workflow Preview panel opens, it calls the parent component to generate and return the contents. With this the panel is always computing the latest content structure based on the parent component selections. So there is 100% accuracy.
=> Update the workflow content preview and generation logic

client/src/app/site/console/shared/components/abstract.windows.component.ts
Fixes [AB#7664885](https://msazure.visualstudio.com/Antares/_workitems/edit/7664885)
=> AB#7664885 Updating console to use '\' instead of 'site\wwwroot' as root directory for Xenon appst

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSettings.tsx
GitHub action is only supported for linux containers.
Windows containers:
Linux containers:
=> Hide source selection options for windows container.

client-react/src/ApiHelpers/AppKeysService.ts
Fixes AB#8308705
Host key is an untracked resource and can use the untracked resource object to inherit parent location
=> [CRI] Create Host Key with UntrackedArmObj request

client-react/src/theme/CustomOfficeFabric/AzurePortal/Dropdown.styles.ts
Fixes AB#8180317
This will also affect other places where Dropdown is used (Configuration, etc.)
Open to making the headers one size smaller... which would change the blue part to look like
Before:
After:
=> Changing Dropdown Size

client-react/public/index.html, server/src/home/home/home.service.dev.tsx, server/src/home/home/home.service.prod.tsx, server/src/home/home/views/home.tsx, server/src/server.ts, server/src/shared/config/config.service.ts, server/src/types/config.ts
The change here is to allow us to inject server-side information into a global config object for React similar to how we do it for Angular-based experiences.  
For local development, we already load a static index.html file but now it will also have default values for Azure development.  For apps deployed to Azure, this static index.html file will get transformed in-memory when the Node process starts up to contain app setting values which are configured on each web app hosting fusion.  This implies that we'll also have to update our deployment pipelines to inject this information as app settings.
Once we have all of the server-side changes deployed world-wide for this sprint, then it should be safe to add client-side dependencies on the new global config.
=> Adding server-evaluated global config for React experiences

client-react/src/models/site/config.ts, client-react/src/pages/app/app-settings/AppSettingsFormData.ts
=> Mark node and php version as null on saving config when these values are empty

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerDockerHubSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerFormBuilder.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerPrivateRegistrySettings.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Hint text updated for windows containers
The slash is preserved for docker hub images
There is a detailed error message being shown
=> Fix the container hint text, dockerhub render, and show detailed error messages.

client-react/src/ApiHelpers/DropboxService.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceAndBuild.tsx, client-react/src/pages/app/deployment-center/dropbox-provider/DeploymentCenterDropboxConfiguredView.tsx, client-react/src/pages/app/deployment-center/dropbox-provider/DeploymentCenterDropboxDataLoader.tsx
Fixes AB#8463584
Note: similarly to GitHub, Bitbucket, and OneDrive I am not able to provide a screen shot for the OAuth flow itself as we can't test it locally. Since the code is almost identical to those 3 it should work in the canary environment... but if it does not than I will remove Dropbox from the dropdown.
=> [Dropbox] Dropbox Authorization

client-react/src/ApiHelpers/HttpClient.ts, client-react/src/portal-communicator.ts, client-react/src/react-app-env.d.ts, client-react/src/utils/LogService.ts, server/src/shared/http/wellknownheaders.ts, server/src/storage/storage.controller.ts
Adding better logging to our storage APIs on the server as well as returning a better http code and message if possible.  
Also adding standard headers for all HTTP requests from the client to include requestId and sessionId.
=> Adding server-side logging for storage controller

client/src/app/shared/models/portal-resources.ts, client/src/app/shared/models/serverFarmSku.ts, client/src/app/site/spec-picker/price-spec-manager/isolatedv2-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/plan-price-spec-manager.ts, client/src/app/site/spec-picker/price-spec-manager/premiumv2-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/price-spec-group.ts, server/Resources/Resources.resx
Fixes AB#8665326
**Note: **
**Not supported scenario -> new app in new ASEv3**
**Scenarios:**
1. Existing ASEv3 resource -> only show IV2 sku's
2. Existing ASEv2 resource -> only show Isolated sku's
3. Create new ASP in existing ASEv3 -> only show IV2 sku's (screenshot will be available once I make the Ibiza side changes which will include setting allowAseV3Creation flag and passing to specpicker. This flag will also be used for new app in new ase scenario when supported)
4. Create new ASP in existing ASEv2 -> only show Isolated sku's (existing scenario. See screenshot below where we don't show IV2 skus)
=> AB#8665326 [I2][Spec Picker][Fusion] Add Support for IV2 skus

client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.ts, client-react/src/pages/app/deployment-center/utility/GitHubActionUtility.ts, client-react/src/utils/stacks-utils.ts, client/src/app/shared/models/constants.ts, client/src/app/shared/services/runtimestack.service.ts, client/src/app/site/deployment-center/deployment-center-setup/step-configure/configure-github/stack-selector/stack-selector.component.html, client/src/app/site/deployment-center/deployment-center-setup/step-configure/configure-github/stack-selector/stack-selector.component.ts, client/src/app/site/deployment-center/deployment-center-setup/wizard-logic/deployment-center-state-manager.ts, client/src/app/site/deployment-center/deployment-center-setup/wizard-logic/github.service.ts, server/src/stacks/2020-05-01/service/StackService.ts, server/src/stacks/2020-05-01/stacks/web-app-stacks/create/AspDotnet.ts, server/src/stacks/stacks.controller.ts, server/src/tests/Stacks/2020-05-01/web-app/validations.ts
* initial changes
* enable dotnet 5 in deployment center.
* update some stuff.
* address some of the PR comments.
* update test cases
* Add the concept of showing hidden stacks in the old api version.
=> Introduce .net 5 for classic and preview deployment center. (#5523)

client/src/app/site/spec-picker/price-spec-manager/isolatedv2-plan-price-spec.ts
Fixes AB#8710702
**NOTE: There is no price as billing meters are not ready yet.**
Before:
After:
=> AB#8710702 [Fusion] Isolated v2 cards show the wrong vm series - match PV3 since underneath they are the same

client/src/app/site/spec-picker/price-spec-manager/price-spec-group.ts
Fixes AB#7062492 
**Create scenario:**
Before:
After:
**Existing ASP -> scale up scenario - NO change**
Before:
After:
=> AB#7062492 Consider removing S2/ S3 form SKU Picker for new ASP since P1v2 and P2v2 offer better perf at the same price point

server/src/deployment-center/github/github.controller.ts
=> [GitHub Actions\Create] Get client id from configservice

client/src/app/site/spec-picker/price-spec-manager/price-spec-group.ts
=> AB#8826878 [Spec picker] Revert the experiment to hide S2 and S3 skus

client/src/app/site/spec-picker/price-spec-manager/price-spec-group.ts
Co-authored-by: Shibani Medhekar <shibanimedhekar@TestVM08.Redmond.corp.microsoft.com>
=> AB#8826878 [Spec picker] Revert the experiment to hide S2 and S3 skus (#5560)

server/src/stacks/2020-05-01/stacks/web-app-stacks/create/Node.ts, server/src/stacks/2020-06-01/stacks/web-app-stacks/Node.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Node.ts
Node 14 is working with our GitHub Actions flow. On Windows though, we need to make a small change. Right now the Windows workflow is setting the "version" param on the Node setup action to `14-lts`. The action does not understand this syntax.
So if we can update the Windows workflow to set `14.x` like the Linux one, then we're good to go:
I *believe* this change will fix it, but will need Mitren to check that the DC will honor the "recommendedVerison" for Windows workflows.
=> Set "recommendedVersion" for Node14 on Windows

server/src/stacks/2020-05-01/stacks/function-app-stacks/Python.ts, server/src/stacks/2020-06-01/stacks/function-app-stacks/Python.ts, server/src/stacks/2020-10-01/stacks/function-app-stacks/Python.ts, server/src/tests/Stacks/2020-05-01/function-app/validations.ts
cc: @pragnagopa 
We expect to release Python 3.9 for Azure Functions in December. This is a placeholder for the Python 3.9 stack in backend API.
Related PR:
[PragnaGopa Stack] https://github.com/pragnagopa/azure-functions-supported-runtime-stacks/pull/24
[Azure CLI] https://github.com/Azure/azure-cli/pull/16020
=> [Stacks][Function App]Enable function app Python 3.9 in preview and hidden

client-react/src/components/ErrorLogger.tsx, client-react/src/models/portal-models.ts, client-react/src/models/telemetry.ts, client-react/src/portal-communicator.ts
For now, I'm opting to leave the React-side of the world as a direct call on the PortalCommunicator class.  I thought about introducing a new Telemetry class which wraps the communicator, but it doesn't seem to make as much sense in the React side of the world since it's just a passthrough to an existing Telemetry instance in the Ibiza side of the world.  So it would just be another layer of complication on-top of this already complicated problem.
=> Task 8647397: Add iframe API in React to log to new telemetry class

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeBuildRuntimeAndVersion.tsx
fixes AB#8818532
generate the github recommended version mapping while populating the runtime version instead of doing a look up later. This simplifies the code and addresses the referenced bug.
=> Deployment Center. Simplify recommended version selection

client/src/app/site/spec-picker/price-spec-manager/free-plan-price-spec.ts
Fixes AB#8965964
Will send a PR separately on the Ibiza side to disable Linux for free subs and filtering out existing Free ASP from dropdown for Linux.
Linux FunctionApp create:
Windows FunctionApp create:
Linux WebApp create:
Windows WebApp create:
=> AB#8965964 Hide free sku from spec picker for Linux FunctionApp creates

server/src/stacks/2020-05-01/stacks/function-app-stacks/Python.ts, server/src/stacks/2020-06-01/stacks/function-app-stacks/Python.ts, server/src/stacks/2020-10-01/stacks/function-app-stacks/Python.ts
We expect to release Python 3.9 for Azure Functions in preview mode early January, 2021
cc: @anirudhgarg @vrdmr @pragnagopa @stefanushinardi
=> [Stacks][Function App]Unhide function app Python 3.9

client-react/src/pages/app/deployment-center/DeploymentCenterFormBuilder.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client-react/src/pages/app/deployment-center/external-provider/DeploymentCenterExternalConfiguredView.tsx
Turns out we have several existing apps with 'http' and the backend API allows this too.
Before:
After:
=> Enable external git to have http based protocol.

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodePivot.tsx, client-react/src/utils/scenario-checker/dynamic-linux.environment.ts, client-react/src/utils/scenario-checker/scenario-ids.ts
fixes AB#9058474
We currently have an email thread with the function team to get a timeline on when this can be enabled. As of right now, the calls to fetch logs always fails.
non-consumption:
consumption:
=> Hide logs for consumption linux function apps

server/src/stacks/2020-10-01/service/FunctionAppUtility.ts, server/src/stacks/2020-10-01/service/StackService.ts, server/src/stacks/2020-10-01/service/WebAppUtility.ts, server/src/stacks/stacks.controller.ts, server/src/stacks/validations.ts, server/src/tests/Stacks/2020-10-01/function-app/tests.ts, server/src/tests/Stacks/2020-10-01/web-app/tests.ts, server/src/tests/Stacks/2020-10-01/web-app/validations.ts
Sample url - https://localhost:44400/stacks/functionAppStacks?os=windows&removeHiddenStacks=true&removeDeprecatedStacks=true&removeNonGitHubActionStacks=true&api-version=2020-10-01
Currently this is not used by the client, I will another PR that focuses on the client side changes. Also this is for stacks that are supported from 2020-10-01 API version.
=> Add an optional query string to the stacks api to filter out non-githubaction stacks

client/src/app/site/spec-picker/price-spec-manager/free-plan-price-spec.ts
Fixes AB#9219848 
Will send a PR separately on the Ibiza side to allow only Consumption for Free and Dreamspark subscriptions for both Linux and Windows.
=> AB#9219848 [Spec Picker] Hide free sku from spec picker for all (Linux as well as Windows) FunctionApp creates

client-react/src/ApiHelpers/ACRService.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrDataLoader.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
fixes AB#9258239
fixes AB#9266341
The only scenario that I am able to replicate is credential where the ACR registry is not admin enabled. For all the other ones, the error object in the logs is null and we are not showing the error message on the screen in case of a failure. This change updates our logging strategy and shows additional messages on the screen in case of failures. There really aren't any screenshots I can share, till I understand through logs how to identify these issues.
=> Additional logging and error messages for ACR scenarios.

server/src/stacks/2020-05-01/stacks/web-app-stacks/config/linux/Php.ts, server/src/stacks/2020-05-01/stacks/web-app-stacks/config/windows/Php.ts, server/src/stacks/2020-06-01/stacks/web-app-stacks/Php.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Php.ts
PHP 7.2 has reached EOL and Byron sent out reminders to customers to upgrade their sites to 7.4. ANT 93 will upgrade everyone from 7.2 to 7.4. The intent is to hide PHP 7.2 as an option on Windows and Linux.
=> Mark PHP 7.2 as deprecated

client-react/src/components/CustomPanel/CustomPanel.styles.ts, client-react/src/components/CustomPanel/CustomPanel.tsx
fixes AB#8964875
fixes AB#8964940
The UX look and feel has not changed at all.
=> Make the close (X) button tab-able and add an event handler for enter and spacebar.

client-react/src/pages/app/deployment-center/DeploymentCenter.styles.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx
fixes AB#8965071
Before:
After:
Also the reflow is not affected
=> Remove ghost tab stop from configured view

server/src/stacks/2020-06-01/stacks/web-app-stacks/Java.ts, server/src/stacks/2020-06-01/stacks/web-app-stacks/JavaContainers.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Java.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/JavaContainers.ts
https://azure.github.io/AppService/2021/01/06/java-stacks-update.html
On Windows, this adds the following runtimes:
- Tomcat 9.0.38
- Tomcat 8.5.58
- Java 11.0.8
- Java 8.0.265
- Java 7.0.272
And on Linux...
- Auto Update for JBoss EAP 7.x on Java 8 and 11
- Java 11.0.9
- Tomcat 9.0.41
- Tomcat 8.5.61
=> New Java versions added in ANT 91, 92

client-react/src/pages/app/deployment-center/DeploymentCenter.styles.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/DeploymentCenterCommandBar.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeLogsTimer.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerLogs.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerPivot.tsx, server/Resources/Resources.resx
Fixes AB#
Code Logs (GitHub Actions):
Code Logs (non-GitHub Actions):
Container Logs:
=> [DeploymentCenterV2] Refresh button moved to logs tab

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerFormBuilder.ts
fixes AB#9322899
Fixes the image/tag sync issue between classic and new experience.
When switching from private to public in the new experience, the correct settings are retained.
=> Fix dockerHub bugs in deployment center related to image/tag/credentials.

client/src/app/shared/models/arm/billingMeter.ts, client/src/app/site/spec-picker/price-spec-manager/elastic-premium-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/plan-price-spec-manager.ts
Fixes AB#8027994
**Before**:
**After**:
=> AB#8027994 Update Elastic Premium prices to use the multiplier from billingMeters API and remove hardcoding

server/src/stacks/2020-06-01/stacks/web-app-stacks/Java.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Java.ts
The EOL date for Java 7 is much farther out than I assumed (egg on my face).  The intent of this PR is to show Java 7 on creates and configures. On configures only Java 7 auto-update, 1.7.0_272, 1.7.0_262 should be shown. Hope I got this right! :P 
Java 7 is only available on Windows.
=> Unhide Java 7

client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx
=> [FunctionEditor] Show read-only banner first instead of generic Runtime unreachable

server/src/stacks/2020-06-01/stacks/web-app-stacks/JavaContainers.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/JavaContainers.ts
- This PR adds JBoss 7.3, which is a pinned version that works for Java 8 and 11
- Also, the 2020-06-01 version had a pinned version (7.2) under the "java8Runtime"  property for an **auto-update** option (line 109)
=> Add JBoss EAP 7.3 as a pinned version

server/src/stacks/2020-06-01/stacks/web-app-stacks/Node.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Node.ts
Sanchit, jenny confirmed that Node 14 has been promoted out of "Early Access" on Linux
Marie confirmed that the same goes for Windows
=> Remove "Early Access" for Node 14

client-react/src/SiteState.ts, client-react/src/pages/app/SiteRouter.tsx, client-react/src/utils/CommonConstants.ts, client-react/src/utils/arm-utils.ts, client-react/src/utils/scenario-checker/kube-app.environment.ts, client-react/src/utils/scenario-checker/scenario-ids.ts, client-react/src/utils/scenario-checker/scenario.service.ts
fixes AB#9522246
fixes AB#9522282 
**Introduce isKubeApp on siteStateContext**
This is a temporary feature flag till kind property is available via the API. Adding this in because eventually when the kind property is available, isKubeApp will still be needed on the siteStateContext. 
Sample url - https://portal.azure.com/?feature.customportal=false&websitesextension_functionslocal=true&websitesextension_ext=appsvc.treatAsKubeApp%3Dtrue#home
**Introduce KubeApp ScenarioChecker**
This is needed to enable/disable and/or hide/show options in the Deployment Center.
=> Introduce isKubeApp property on the siteStateContext along with the ScenarioChecker.

client-react/src/pages/app/deployment-center/DeploymentCenterConstants.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeBuildCallout.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodePivot.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.ts, client-react/src/pages/app/deployment-center/utility/GitHubActionUtility.ts, client-react/src/utils/scenario-checker/kube-app.environment.ts
fixes AB#9522377
** NOTE ** Saves do not work yet.
** NOTE ** use websitesextension_ext=appsvc.treatAsKubeApp%3Dtrue in the URL.
In this PR the deployment center page will load with Settings and Logs tabs. FTPs tab is omitted. The Settings tab load is driven by reading Metadata values rather than siteConfig.scmType value. (we might be able to get away with just using the scmType, but I need to experiment with that a little more).
The main part of this PR is to remove the FTPs tab and also any non supported options for deployment, so anything other than GitHub Action.
=> Setup up screen for deployment center updated for K8se apps.

.vscode/settings.json, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubConfiguredView.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.ts, client-react/src/pages/app/deployment-center/utility/GitHubActionUtility.ts
fixes AB#9531489
fixes AB#9532080
With this change, for Kube apps, the save operation will update the metadata directly and pull data from the metadata. For non-kube apps the current process will work as is.
=> Load the configured view and update using metadata

client-react/src/ApiHelpers/SiteService.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubConfiguredView.tsx, client-react/src/pages/app/deployment-center/utility/GitHubActionUtility.ts
Metadata properties could be null.. this will be fixed in the API in a future iteration.
The scmType is still null, so accounting for that.
=> Make updates to account for latest ARC API fixes.

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx
I realized while testing that this component is getting re-rendered multiple times and it is very hard to debug any issues. But putting things in their own useEffect hooks it is much easier to follow through the changes and it optimizes which components in the page get reloaded.
=> Clean up deploymentCenterCodeSettings component

server/src/stacks/2020-06-01/stacks/web-app-stacks/JavaContainers.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/JavaContainers.ts
The pinned JBoss versions had short strings in the "value" property (ex: `value: "7.2"` while other stacks have strings like  "10.4.5") so the create blade determined these were auto-update stacks. I've added ".x" to the pinned versions so it adheres to what the create blade is already doing.
This is what I hope to get: 
Finally, JBoss 7.2 uses an old base OS that RedHat asked us to change going forward so I'm marking that as deprecated to keep people off of it.
=> Expand pinned version string

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerDockerHubSettings.tsx
fixes AB#9683995
This will make sure the username/password are sent over in the request payload when setting the action workflow.
=> Set the docker access type to private if GitHub Action is selected.

client/src/app/shared/models/portal-resources.ts, client/src/app/shared/models/serverFarmSku.ts, client/src/app/site/spec-picker/price-spec-manager/basic-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/free-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/isolated-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/isolatedv2-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/plan-price-spec-manager.ts, client/src/app/site/spec-picker/price-spec-manager/premium-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/price-spec-group.ts, client/src/app/site/spec-picker/price-spec-manager/shared-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/standard-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/workflow-standard-plan-price-spec.ts, server/Resources/Resources.resx
Fixes AB#9300051
WorkflowStandard is a new sku ONLY for LAv2 apps. The plan kind will still be "elastic" for both Elastic Premium and Workflow Standard sku since they are under the hood the same except pricing.
I did not add an explicit feature flag on this change on the Fusion side as we will have a feature flag on the Ibiza side change (working on that next) which will pass in the new "isWorkflowStandard" as true only when flag is ON and only for LAv2 creates.
For scaleup, since this new sku is not released yet, there will be no plans with this sku anyways.
**Create scenario:**
WorkflowStandard sku's should be visible only for LAv2 create
**Scale up scenario:**
WorkflowStandard sku's should be visible only for LAv2 apps that have existing sku as Workflow standard sku. No other sku's are …
=> AB#9300051 [Behind feature flag] Update spec picker to support new WorkflowStandard skus for LAv2 ONLY

client/src/app/site/spec-picker/price-spec-manager/premiumv2-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/premiumv3-plan-price-spec.ts
Missed these two in my previous change - PR for reference https://github.com/Azure/azure-functions-ux/pull/5902
=> Hide PV2 and PV3 sku's for new plan scenario for WorkflowStandard sku type

client/src/app/site/slots/deployment-slots/deployment-slots.component.ts
Fixes AB#9868434
We are fixing a small bug where we were relying on a shallow copy to update and also we are going to hide the TIP rules in the UX for now since even with the bugfix the API won't return us the data we need
Non-ARC
ARC
=> [ARC][Slots] TIP rules for ARC

client-react/src/components/CustomPanel/CustomPanel.styles.ts, client-react/src/components/CustomPanel/CustomPanel.tsx
Fixes AB#9528733
* Tab stops work correctly
* Closes on click, space bar, or enter
Current
Fixed
------
Unhovered
Hovered
Focused
=> Update close (X button) styling to match the rest of the portal

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrDataLoader.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerFormBuilder.ts
When we save the image and/or tag in the new DC, we're changing it all to lowercase instead of leaving it as-is.  It looks like ACR is case-sensitive so it's causing the Docker pull at runtime to fail.
Fixes AB #9817722
=> [DC] Make ACR Tag case sensitive

client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEdit.tsx, client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEditAdvanced.tsx, client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEditBasic.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Handled the blade crash problem by updating the functionality of thet get request on blob containers and file shares of the storage account that has vnet restriction. The error messages were updated to inform cx to use advanced mode to add/edit storage mount.
Here are all the changes:
1. Removed the duplicated validation on share name field.
2. It makes more sense to display the error messge at storage container control than the storage account control. So the error messages are moved to storage container.
3. Removed the reason from the error messages because it could contain some raw error message from the api response.
4. Added message to the error message to inform cx to use the advanced mode if the storage account has vnet restriction.
5. Update the error message based on the storage …
=> [App Setting][BYOS] Handle Add/Edit Azure Storage Mount Blade Crash

server/src/stacks/2020-05-01/stacks/web-app-stacks/config/linux/Python.ts, server/src/stacks/2020-05-01/stacks/web-app-stacks/create/Python.ts, server/src/stacks/2020-06-01/stacks/function-app-stacks/Node.ts, server/src/stacks/2020-06-01/stacks/web-app-stacks/Node.ts, server/src/stacks/2020-06-01/stacks/web-app-stacks/Python.ts, server/src/stacks/2020-06-01/stacks/web-app-stacks/Ruby.ts, server/src/stacks/2020-10-01/stacks/function-app-stacks/Node.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Node.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Python.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Ruby.ts, server/src/tests/Stacks/2020-05-01/web-app/validations.ts
Fixes [AB#8723232](https://msazure.visualstudio.com/Antares/_workitems/edit/8723232)
Fixes [AB#9878062](https://msazure.visualstudio.com/Antares/_workitems/edit/9878062)
Fixes [AB#10015742](https://msazure.visualstudio.com/Antares/_workitems/edit/10015742)
=> Adding Python 3.9 as early access and marking Node 10 and Ruby 2.5 as deprecated

client/src/app/controls/group-tabs/group-tabs.component.scss
Fixes AB#9578003
Before without setting the values with just defaults:
After:
Light mode
Dark mode
=> AB#9578003 [Visual Requirement - App Services - Dev/Test]: Luminosity ratio is less than required non -text contrast (3:1) for focus indicator.

client/src/app/site/spec-picker/price-spec-manager/basic-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/dV2series-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/dV3series-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/elastic-premium-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/free-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/isolated-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/isolatedv2-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/plan-price-spec-manager.ts, client/src/app/site/spec-picker/price-spec-manager/premium-container-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/premium-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/premiumv2-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/premiumv3-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/price-spec-group.ts, client/src/app/site/spec-picker/price-spec-manager/price-spec-manager.spec.ts, client/src/app/site/spec-picker/price-spec-manager/price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/shared-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/standard-plan-price-spec.ts
Fixes AB#8725350
**Only PremiumV3 and IsolatedV2 sku's are allowed for a plan which has atleast one JBoss site.** 
**The changes on the Portal side for create scenario are not done yet, so only adding screenshots for scaleup scenario:**
=> AB#8725350 [SKU Picker] [Create + ScaleUp] Limit the SKUs shown when JBoss is on the App Service Plan

client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.ts, client-react/src/pages/app/deployment-center/utility/GitHubActionUtility.ts, client/src/app/controls/group-tabs/group-tabs.component.scss, server/src/stacks/2020-05-01/models/WebAppStackModel.ts, server/src/stacks/2020-05-01/stacks/web-app-stacks/create/Php.ts, server/src/stacks/2020-06-01/models/AppStackModel.ts, server/src/stacks/2020-06-01/stacks/web-app-stacks/Php.ts, server/src/stacks/2020-10-01/models/AppStackModel.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Php.ts, server/src/tests/Stacks/2020-05-01/web-app/validations.ts, server/src/tests/Stacks/2020-10-01/web-app/validations.ts, server/src/workflows/2020-12-01/WorkflowService.ts, server/src/workflows/2020-12-01/web-app-configs/php-linux.config.yml, server/src/workflows/2020-12-01/web-app-configs/php-windows.config.yml, server/src/workflows/WorkflowModel.ts, server/src/workflows/workflow.controller.ts
Fixes AB#9798960
The server test is failing because the number of stacks that support GitHub Actions is changing as PHP is now added. I have updated the tests in this PR.
Tested windows 7.3, windows 7.4, linux 7.3, linux 7.4, all had successful GHA workflow runs as seen above and I was able to browse to all the sites.
=> [DC] Enable PHP for GitHub Actions

client/src/app/site/spec-picker/spec-list/spec-list.component.html
Fixes AB#9592796
Changed role on each card to be "radio" in stead of "radio button". Following the recommendation here that was in the bug - https://accessibilityinsights.io/info-examples/web/aria-roles/
**Before**:
**After**:
=> AB#9592796 [Programmatic Access - App Services - Dev/Test]: Ensures all elements with a role attribute use a valid value (#devtestB1)

server/src/stacks/2020-06-01/stacks/web-app-stacks/Java.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Java.ts
Fixes [AB#9595967](https://msazure.visualstudio.com/Antares/_workitems/edit/9595967)
=> Adding Java versions 1.7.0_292, 1.8.0_282 and 11.0.9 for Windows web apps

client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeBuildCallout.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeBuildConfiguredView.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeBuildRuntimeAndVersion.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceAndBuild.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.ts, client-react/src/utils/CommonConstants.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes [AB#8405224](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/8405224)
Fixes [AB#8405240](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/8405240)
Removes build dropdowns for Linux and Windows. Hides GitHub Actions as a build provider for Ruby apps as there are no workflow files for Ruby and no plans to onboard Ruby users to use GitHub Actions.
=> [DC] Remove build dropdowns

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerFormBuilder.ts
Fixes [AB#9906660](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/9906660)
Mooncake ACR uri is azurecr.cn so the previous check for azurecr.io needed to be updated.
=> [DC] Update ACR url check to accommodate Mooncake ACR url

client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEditBasic.tsx
Fixes [AB#10487619](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s169?workitem=10487614
When opening editing page of the storage mount with Basics configuration, switching to Advanced mode shows old access key. The problem is fixed by checking the current access key under Basics configuration to see if the initial values already has an access key under the storage account. If so, keep the original key, make an API call to get access keys otherwise.
=> AB#10487619 [BYOS] Storage Mount Showing Old Access Key

server/src/stacks/2020-10-01/models/FunctionAppStackModel.ts, server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts, server/src/tests/Stacks/2020-10-01/function-app/validations.ts
* Adding dotnet6 as hidden and early access for Function Apps
* PR feedback
Co-authored-by: Krrish Mittal <krrishmittal15@gmail.com>
=> [Cherry-pick] Adding dotnet6 as hidden and early access for Function Apps

client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEdit.tsx, client-react/src/utils/constants/ValidationRegex.ts
Fixes [AB#10559704](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s170?workitem=10559704) Enable windows container storage mount mount path validation at public cloud
=> AB#10559704 Enable windows container mount path validations at public cloud

server/src/stacks/2020-06-01/stacks/web-app-stacks/Java.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Java.ts
Notifications have gone out to existing users with Java 7 sites. Now that the EOL date is communicated, we should hide Java 7 to prevent users from taking dependencies on old software.
=> Hide Java 7

server/src/stacks/2020-06-01/stacks/web-app-stacks/Java.ts, server/src/stacks/2020-06-01/stacks/web-app-stacks/JavaContainers.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Java.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/JavaContainers.ts
ANT 95 is done on the workers now (Aug 31) so this is OK to merge in the current sprint.
Adds these runtimes to the stacks API:
- Java 11.0.11
- Java 1.8.0_292
- Tomcat 9.0.46
- Tomcat 8.5.66
=> Add Java versions in ANT 95 to the Stacks API

client-react/src/ApiHelpers/SiteService.ts, client-react/src/models/site/site.ts
Remove virtualNetworkSubnetId property when updating config/web to prevent permissions issue
=> [Configuration] remove virtualNetworkSubnetId property when updating config/web

client-react/src/ApiHelpers/SiteService.ts, client-react/src/models/site/site.ts
remove virtualNetworkSubnetId property when updating config/web
=> [Hotfix] Remove VirtualNetworkSubnetId property when updating config/web

client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubConfiguredView.tsx
FixesAB#[10025343 ](https://msazure.visualstudio.com/Antares/_workitems/edit/10025343)
Before fix: Link was only pointing to default branch
After fix: Link points to corresponding branch
Example branch: branchtest2
Example branch: branchtest1
=> [DC] Provide correct link to repo with branch

client-react/src/ApiHelpers/BitbucketService.ts, client-react/src/pages/app/deployment-center/bitbucket-provider/DeploymentCenterBitbucketDataLoader.tsx
FixesAB#[10996657 ](https://msazure.visualstudio.com/Antares/_workitems/edit/10996657)
Changed the error logging into verbose logging for failed getBitbucketBranchesResponse to stop throttling
Added break condition in while loop to stop after the first failure to prevent infinite calls
=> [DC] Limit number of failures in getBitbucketBranches logged

client-react/src/components/form-controls/ReactiveFormControl.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubDataLoader.tsx
FixesAB#[12508959 ](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s176?workitem=12508959)
Each keypress in ComboBox was being logged, removed it to only log after debounce time
Fixed Stack warning to use prop tokens.childrenGap instead of deprecated prop gap for ReactiveFormControl
=> [DC] Log keypresses after debounce, update Stack props

server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts
Fixes [AB#12528307](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/12528307)
Will cherry-pick to release_s175 for 11/8 hotfix once tested in canary
=> AB#12528307 [HOTFIX] - Unblock .NET 6 from Github actions on create

client-react/src/ApiHelpers/FunctionsService.ts, client-react/src/pages/app/functions/function/function-editor/FunctionEditorDataLoader.tsx, client-react/src/pages/app/functions/function/function-editor/function-test/FunctionTest.tsx, client-react/src/utils/CommonConstants.ts, client-react/src/utils/url.ts
With this PR we are making the following changes :
- Add passthrough calls back while running function
- Putting calls via-portal behind the feature -flag so that testing is simpler
- Putting CORS banner behind the feature flag
So, the behavior will be similar to as to what we have right now on portal
=> Put portal-call behind feature -flag

server/src/stacks/2020-10-01/service/StackService.ts, server/src/stacks/2020-10-01/stacks/date-utilities.ts, server/src/stacks/2020-10-01/stacks/function-app-stacks/Powershell.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Java.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Node.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Php.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Python.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Ruby.ts, server/src/stacks/stacks.controller.ts, server/src/stacks/versions.ts
For API version 2021-01-01 and higher, return endOfLifeDate in ISO format (e.g. "2020-10-04T07:00:00.000Z") instead of the current format (e.g. "Sun Oct 04 2020 00:00:00 GMT+0000 (Greenwich Mean Time)").
=> Updating functionAppStacks and webAppStacks API to use ISO date formats

server/src/stacks/2020-10-01/service/StackService.ts, server/src/stacks/2020-10-01/stacks/date-utilities.ts, server/src/stacks/2020-10-01/stacks/function-app-stacks/Powershell.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Java.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Node.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Php.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Python.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Ruby.ts, server/src/stacks/stacks.controller.ts, server/src/stacks/versions.ts
For API version 2021-01-01 and higher, return endOfLifeDate in ISO format (e.g. "2020-10-04T07:00:00.000Z") instead of the current format (e.g. "Sun Oct 04 2020 00:00:00 GMT+0000 (Greenwich Mean Time)").
Cherry-pick from #6364
=> [CP] Updating functionAppStacks and webAppStacks API to use ISO date formats

server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts
Co-authored-by: Shibani Medhekar <shibanimedhekar@alfrankl-main.redmond.corp.microsoft.com>
=> Make .Net 6 the default stack selection for creates (#6369)

client-react/src/pages/app/deployment-center/DeploymentCenter.styles.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrDataLoader.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrSettings.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Task [12677408](https://msazure.visualstudio.com/Antares/_workitems/edit/12677408)
**Before**: 
**After**:
Accessibility consideration:
- Add identity link not reachable through tabbing, also makes screen reader unable to read it
=> [DC] Add link to identity blade in managed identities dropdown

server/src/stacks/2020-06-01/stacks/web-app-stacks/Node.ts, server/src/stacks/2020-06-01/stacks/web-app-stacks/Python.ts, server/src/stacks/2020-06-01/stacks/web-app-stacks/Ruby.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Node.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Python.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Ruby.ts, server/src/tests/Stacks/2020-06-01/web-app/validations.ts, server/src/tests/Stacks/2020-10-01/web-app/validations.ts
Fixes [AB#10469540](https://msazure.visualstudio.com/Antares/_workitems/edit/10469540) - Python 3.9 (Baked in Stack) ANT96
Fixes [AB#10469640](https://msazure.visualstudio.com/Antares/_workitems/edit/10469640) - Add RUBY 2.7 as Baked In
Fixes [AB#10469604](https://msazure.visualstudio.com/Antares/_workitems/edit/10469604) - NODE 16 (EARLY ACCESS) behind hide key
=> Stacks updates for ANT96

client-react/src/utils/scenario-checker/container.environment.ts
Reverts Azure/azure-functions-ux#6394
Received last minute notice that the backend is not quite ready for the change yet.
=> Revert "AB#12573650 GA BYOS for windows container"

client-react/src/ApiHelpers/ACRService.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.data.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrDataLoader.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerFormBuilder.ts, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.ts, client-react/src/utils/CommonConstants.ts, server/src/deployment-center/acr/acr.controller.ts
Task [12677090](https://msazure.visualstudio.com/Antares/_workitems/edit/12677090)
- Gets role assignments on ACR scope for the selected user-assigned managed identity
- If it has ACR Pull permissions, great :)
- If not, we assign it ACR Pull permissions
**Role assignments before:**
Checking to see if yo-user-assigned-mi2 has AcrPull permissions, which it doesn't, so it sets AcrPull permissions.
**Role assignments after:**
=> [DC] Check for ACRPull Permissions and set for user if not present

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceKuduConfiguredView.tsx
Fixes [AB#12740633](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/12740633)
Removes the patch and only does it for LocalGit. Sourcecontrols API will set the ScmType.
=> [DC] Remove patch on site config during Kudu disconnect

client-react/src/utils/CommonConstants.ts, client-react/src/utils/scenario-checker/linux-site.environment.ts, server/Resources/Resources.resx
Completed testing for https://github.com/Azure/azure-functions-ux/pull/6312 and removing the feature flag
Fixed addIdentity link string in Identity ComboBox
Before: 
After:
=> [DC] Unhide enabling azure repos for linux and fix add identity string

server/Resources/Resources.resx
**Fixed spelling here:**
**Before:**
=> 12843728 [Daily Feedback] [Config Blade] Exclusion path spelling miss on the config blade

client-react/src/ApiHelpers/ACRService.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.data.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx, client-react/src/utils/CommonConstants.ts
Task [12677872 ](https://msazure.visualstudio.com/Antares/_workitems/edit/12677872)
**Changes summary:**
- If System Assigned identity type has been selected, it will check to see if System Assigned identity is enabled.
- If not enabled, it will enable through a PATCH call, making sure any added User Assigned identities are also included.
- hasAcrPullPermission previously returned false all the time because in the forEach bracket of roleAssignments returned true within that bracket instead of the entire function (replaced with hasAcrPullPermission boolean)
**Tested:**
- When no managed identities are assigned to app
- When only user assigned identities are assigned to app
- When system assigned identity is already enabled on app
=> [DC] Enable System Assigned Identity and fix hasAcrPullPermission return value

server/src/stacks/2020-06-01/stacks/function-app-stacks/Powershell.ts, server/src/stacks/2020-10-01/stacks/function-app-stacks/Powershell.ts
This PR contains the following changes:
* Removed Preview from PowerShell on Linux stack definition for 2020-06-01 
* Removed Preview from PowerShell on Linux stack definition for 2020-10-01
=> Remove preview from PowerShell on Linux runtime

client-react/src/ApiHelpers/ACRService.ts
FixesAB#[12875797 ](https://msazure.visualstudio.com/Antares/_workitems/edit/12875797)
Telemetry throttling thought to be produced by while loop in _dispatchSpecificPageableRequest(), which is used in getAcrRegistries, getAcrRepositories, and getAcrTags
=> [DC] Add break condition in while loop for ACR requests

server/src/stacks/2020-06-01/stacks/web-app-stacks/Node.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Node.ts
=> [HOTFIX] Unhide Node 16 LTS for Windows and remove earlyAccess flag for Linux

server/src/stacks/2020-06-01/stacks/web-app-stacks/Java.ts, server/src/stacks/2020-06-01/stacks/web-app-stacks/JavaContainers.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Java.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/JavaContainers.ts
Add entries for these stacks:
- Java 1.8.0_302 and 11.0.12
- Tomcat 8.5.69 and 9.0.52
Also, add "Apache" branding to Tomcat, and "Red Hat" branding to JBoss
(JBoss 7.3.8 was added in ANT 96, but only for the Auto-Update 7.3 lane. There's no entry for it in Available Stacks. Starting in ANT 97 we will update the available stacks for JBoss to match Tomcat's format: we'll Jave an auto-update lane for "JBoss 7" which will patch version options (7.3.8, 7.3.9, 7.4.0, 7.4.1, etc.)
=> ANT 96 Java stacks update

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx
Task [11716779](https://msazure.visualstudio.com/Antares/_workitems/edit/11716779)
**Before:**
- if user included server url for image and tag, the fx version would have the server url appended twice
for server url: https://mcr.microsoft.com
for image and tag: mcr.microsoft.com/windows/servercore/iis:windowsservercore-20H2
**Without https://**
**With https://**
**After:**
- for with and without https:// or http:// 
Also tested with ACR registry source
=> [DC] Remove server url from full image and tag if present

client-react/src/theme/light.ts
FixesAB #[13113757](https://msazure.visualstudio.com/Antares/_workitems/edit/13113757)
**Before:**
**Light**
**Dark**  (making sure it's readable, and it already was)
**After:
DC buttons**
**Create App Plan buttons** (making sure other pages' buttons when disabled are readable)
Function blade buttons when disabled
=> Update primary and default buttons to use disabledText color when disabled

client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx, client-react/src/pages/app/functions/function/function-editor/FunctionEditorCommandBar.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
If the selected file is empty (file size is 0), we display warning message. Reset the warning message if:
- User selected non-empty file
- User clicks other commands (Save, Discard, Refresh, Test + Code and Get function URL)
**Selected invalid file has file name:**
**Generic warning:**
**GIF:**
=> 12677951[Daily mail] Uploading empty functions.json file breaks code+test

client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEdit.tsx, client-react/src/utils/CommonConstants.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes: [AB#12989832](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s182?workitem=12989832)
=> AB#12989832 BYOS - Fix mount path prefix for windows code + enable mount path validations for windows container on national clouds

client/src/app/site/spec-picker/spec-picker.component.scss
[AB#12447585](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s182?workitem=12447585)
Change link button and apply button contrast color to black and white(dark theme) for increase luminosity ratio of the focus indicator to go above 3:1
=> AB#12447585 [Spec Picker] [Accessibility] Change button and link color contrast ratio

client-react/src/components/ConfirmDialog/ConfirmDialog.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceKuduConfiguredView.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
FixesAB#[13195106 ](https://msazure.visualstudio.com/Antares/_workitems/edit/13195106)
**Before:**
**After:**
Hide immediately after pressing ok
Disable ok button and hide cancel button, replace ok with disconnecting
=> [DC] Hide dialog immediately after pressing OK for disconnecting Kudu apps

server/src/proxy/proxy.controller.ts
Fixes [AB#13257707](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/13257707)
=> [Functions] Passthrough API only accepts a “content-type” header of “application/json

server/src/stacks/2020-10-01/stacks/function-app-stacks/Powershell.ts, server/src/tests/Stacks/2020-10-01/function-app/validations.ts
This PR contains the following changes:
* Add V4 `hidden` and `preview` PowerShell 7.2 stack definition for function apps as 
* Update PowerShell validation stacks to include 7.2
=> Add V4 PowerShell 7.2 stack definition for function apps

client/src/app/site/spec-picker/spec-picker.component.html, client/src/app/site/spec-picker/spec-picker.component.scss
Fixes [AB#12446369](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s183?workitem=12446369)
Users with low vision and keyboard users will get confused to access information if the button is appearing as a link which is visual as a link but performing as a button.
=> AB#12446369 Accessibility - change 'add additional options' link to a button

package-lock.json, package.json
Add support for TypeScript 3.7 features including [optional chaining](https://devblogs.microsoft.com/typescript/announcing-typescript-3-7/#optional-chaining) and [nullish coalescing](https://devblogs.microsoft.com/typescript/announcing-typescript-3-7/#nullish-coalescing).
=> chore: Update prettier to 1.19.1

client-react/src/utils/app-state-utils.tsx
Address `@typescript-eslint/no-unused-expressions` lint error.
=> fix: Return `FunctionAppEditMode.ReadOnlyLock` when resource has read-only lock

client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubProvider.tsx
Address `@typescript-eslint/no-unused-expressions` lint error.
=> fix: Call instead of declaring no-op function in Deployment Center GitHub Provider click handler

client/src/app/api/api-details/api-details.component.ts
This is a bug introduced by this PR >>>  https://github.com/Azure/azure-functions-ux/pull/6523
It is giving error if we try to call .finally on .concatMap. I moved finally call within .contactMap to handle at least "save" scenario.
This was the error shown in the console log:
=> 13766742[FunctionApp V1/V2][Stage]:Unable to Save the API Proxy after Editing

client/src/app/api/api-details/api-details.component.ts
Actual problem seems to be our Angular code does not support 'finally'. Therefore, we modified 'subscribe' method and passed second function which should take error.
=> Revise: 13766742 [FunctionApp V1/V2][Stage]:Unable to Save the API Proxy after Editing

server/src/storage/storage.service.ts
Fix `no-unused-vars` lint warning in line 1.
=> fix: Address `prefer-const` lint errors in /server

client-react/src/components/ConfirmDialog/ConfirmDialog.styles.ts, client-react/src/components/ConfirmDialog/ConfirmDialog.tsx, client-react/src/components/CustomBanner/CustomBanner.styles.ts, client-react/src/pages/app/functions/function/integrate/FunctionIntegrate.style.ts
Use Fluent UI type definitions to improve type declarations.
=> fix: Address `prefer-as-const` lint errors in /client-react

client-react/src/components/shimmer/BasicShimmerLines.tsx
Set default value of optional `repeatShimmer` prop to 1.
=> fix: Fix duplicate type name in basic shimmer lines component

server/src/stacks/2020-06-01/stacks/web-app-stacks/JavaContainers.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/JavaContainers.ts
Adds Java 17 support for Tomcat 9.0.54. This was missed in my original PR.
=> Java Stacks Bug Fix

client/src/app/controls/group-tabs/group-tabs.component.scss
=> AB#12436048 Make texts within the parent component

client-react/src/components/form-controls/TextFieldNoFormik.tsx, client-react/src/components/form-controls/formControl.override.styles.tsx, client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEdit.tsx
Keep the padding left if the field does not have prefix
Before:
After:
=> Update the styles of text field with prefix

client-react/src/pages/static-app/StaticSiteUtility.tsx, client-react/src/pages/static-app/configuration/Configuration.data.ts
Updating how to display Prod/Non-stable and stable environment's value.
**Left side is AFTER and right side is BEFORE:**
=> Config Menu Change Only - 10023302 [SWA] - Additional Changes request- stable environments

client-react/src/pages/app/app-settings/ApplicationSettings/AppSettingAddEdit.tsx
Fixes: [AB#13923254](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s185?workitem=13923254)
Remove the check on equality of app setting reference secret name and app setting name
Before:
After:
=> AB#13923254 Remove the check on equality of secret name and setting name

client-react/src/pages/static-app/StaticSiteUtility.tsx
If `pullRequestTitle` value exists (which mean it is non-stable env), we would like to display `#{env name} - {pullRequestTitle}`.
**AFTER**
**BEFORE**
=> Configuration Blade string change - 10023302 [SWA] - Additional Changes request - stable environments

server/src/stacks/2020-06-01/stacks/web-app-stacks/Ruby.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Ruby.ts
Fixes [AB#13875370](https://msazure.visualstudio.com/Antares/_workitems/edit/13875370)
=> Marking Ruby 2.6 as deprecated

client-react/src/components/form-controls/ComboBox.tsx, client-react/src/components/form-controls/ComboBoxnoFormik.tsx, client-react/src/components/form-controls/RadioButton.tsx, client-react/src/components/form-controls/RadioButtonNoFormik.tsx, client-react/src/components/form-controls/TextFieldNoFormik.tsx
Removal of label and theme props to components resulted in adding another label for ComboBox, RadioButton, and TextField controls
**Before:**
**After:**
=> Revert ComboBox, RadioButton, and TextField changes for styling

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerDockerHubSettings.tsx
FixesAB#[14124282](https://msazure.visualstudio.com/Antares/_workitems/edit/14124282)
- Using an obsolete image + tag name
- Removing placeholder text completely as all Windows images are now in MCR
**Before:** 
**After:**
=> [DC] Remove placeholder text for image and tag for windows containers

client-react/src/pages/app/app-settings/FunctionRuntimeSettings/RuntimeVersionNew.tsx
[#13984110](https://msazure.visualstudio.com/Antares/_workitems/edit/13984110/)
=> Show version number for custom runtime version in parentheses

server/src/stacks/2020-06-01/stacks/web-app-stacks/AspDotnet.ts, server/src/stacks/2020-06-01/stacks/web-app-stacks/Node.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Node.ts
Fixes [AB#10469592](https://msazure.visualstudio.com/Antares/_workitems/edit/10469592)
Fixes [AB#10469461](https://msazure.visualstudio.com/Antares/_workitems/edit/10469461)
=> Marking .Net 5 and Node 12 as deprecated

client-react/src/pages/app/functions/function/function-editor/FunctionEditor.data.ts, client-react/src/pages/app/functions/function/function-editor/FunctionEditorCommandBar.tsx, client-react/src/utils/CommonConstants.ts
Customize the functions URL we build for system key for the new `authenticationEventTrigger` type trigger.
Example
https://authenticationeventtrigger.azurewebsites.net/runtime/webhooks/customauthenticationextension?functionName=[REDACTED]&code=[REDACTED]
=> Customize system key function URL for authentication event triggers

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx
Linter detected this bug as a `prefer-const` error in line 640. The code never changed `containerConfigurationSucceeded` to indicate failure.
=> fix: Report error if container configuration did not succeed

client-react/src/components/form-controls/ComboBox.tsx, client-react/src/components/form-controls/DropDown.tsx, client-react/src/components/form-controls/TextField.tsx, client-react/src/components/form-controls/Toggle.tsx
[#10184885](https://msazure.visualstudio.com/Antares/_workitems/edit/10184885/)
Show error message on Formik fields only when they are touched (focus lost or form submitting).
=> Show error message after incomplete save

client-react/src/pages/app/functions/function/function-editor/FunctionEditor.data.ts, client-react/src/pages/app/functions/function/function-editor/FunctionEditorCommandBar.tsx, client-react/src/pages/app/functions/function/function-editor/FunctionEditorDataLoader.tsx
Use webhook endpoint for Authentication trigger test runs.
- Pass input as-is (when validated as JSON) without packaging it into an `input` property.
=> Fix URL used when testing Authentication Event triggers

client-react/src/pages/app/app-settings/FunctionRuntimeSettings/RuntimeScaleMonitoring.tsx
Fixes [AB#14496559](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/14496559)
NOTE: Updating this such that any future Function runtime introductions doesn't require the change. Old versions still support this with the exception of v1. Also, not being supported is a rare phenomenon in comparison to newer versions being introduced and being supported.
=> [Configuration][Function Settings] Runtime Scale Monitoring should be supported for v4

SECURITY.md
Please accept this contribution adding the standard Microsoft SECURITY.MD :lock: file to help the community understand the security policy and how to safely report security issues. GitHub uses the presence of this file to light-up security reminders and a link to the file. This pull request commits the latest official SECURITY.MD file from https://github.com/microsoft/repo-templates/blob/main/shared/SECURITY.md.
Microsoft teams can [learn more about this effort and share feedback](https://docs.opensource.microsoft.com/releasing/maintain/templates/) within the open source guidance available internally.
=> Add Microsoft SECURITY.md

client-react/src/components/form-controls/ComboBox.tsx, client-react/src/models/functions/binding.ts, client-react/src/pages/app/functions/common/BindingFormBuilder.styles.ts, client-react/src/pages/app/functions/common/BindingFormBuilder.tsx, client-react/src/pages/app/functions/common/Common.styles.ts, client-react/src/pages/app/functions/common/CosmosDbFunctionFormBuilder.styles.ts, client-react/src/pages/app/functions/common/CosmosDbFunctionFormBuilder.tsx, client-react/src/pages/app/functions/common/CosmosDbResourceDropdown.styles.ts, client-react/src/pages/app/functions/common/CosmosDbResourceDropdown.tsx, client-react/src/pages/app/functions/common/CreateFunctionFormBuilder.tsx, client-react/src/pages/app/functions/common/callout-content/BindingCalloutContent.tsx, client-react/src/pages/app/functions/common/callout/NewCosmosDbAccountCallout.tsx, client-react/src/pages/app/functions/common/combobox-with-link/ComboBoxWithLink.styles.ts, client-react/src/pages/app/functions/common/combobox-with-link/cosmos-db/CosmosDbContainerComboBox.tsx, client-react/src/pages/app/functions/common/combobox-with-link/cosmos-db/CosmosDbDatabaseComboBox.tsx, client-react/src/pages/app/functions/new-create-preview/FunctionCreateDataLoader.tsx, client-react/src/pages/app/functions/new-create-preview/portal-create/TemplateDetail.tsx, client-react/src/pages/app/functions/new-create-preview/portal-create/TemplateList.tsx, client-react/src/utils/ArmTemplateHelper.ts, client-react/src/utils/CosmosDbArmTemplateHelper.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Refactor common code to support the custom Cosmos DB form builder to be enableable in the next PR.
- `BindingFormBuilder`
- `CreateFunctionFormBuilder`
- `FunctionCreateDataLoader`
- `TemplateDetail`
- `TemplateList`
Automatic
Manual
=> [Function Collateral] Create new Cosmos DB trigger (1)

client/src/app/shared/Utilities/arm-utils.ts, client/src/app/site/spec-picker/spec-picker.component.ts
Ibiza side code change PR: https://msazure.visualstudio.com/One/_git/AAPT-Antares-AntUX/pullrequest/6253979
Even though one side of code changes goes to prod sooner than the other, Web App create experience will not break. However, user will be blocked from creating new ASEv3 or new ASP on existing ASEv3 until both Fusion and Ibiza changes go into prod.
=> 14818314[ASEv3][USSec] Enable ASEv3 in US Sec and allow ASEv3 create from Web App create

client-react/src/pages/app/functions/common/BindingFormBuilder.tsx
[#14811716](https://msazure.visualstudio.com/Antares/_workitems/edit/14811716)
=> Ensure Authorization Level is populated for read-only Python triggers

server/src/stacks/2020-05-01/stacks/function-app-stacks/Node.ts, server/src/stacks/2020-06-01/stacks/function-app-stacks/Node.ts, server/src/stacks/2020-10-01/stacks/function-app-stacks/Node.ts, server/src/tests/Stacks/2020-05-01/function-app/validations.ts, server/src/tests/Stacks/2020-06-01/function-app/validations.ts, server/src/tests/Stacks/2020-10-01/function-app/validations.ts
Related to https://github.com/Azure/azure-functions-nodejs-worker/issues/562
=> Add Node 18 as a hidden & preview function app stack

server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts
There's a lot of breaking changes between .NET 7 preview releases (relative to .NET 5 or 6 preview releases). So we want to "pin" this version in the workflow to Preview 5 so that it matches the runtime version. The runtime version is currently on Preview 5, but the SDK release feed is on Preview 6. So if we continue using the "7.0.x" string, the build with Preview 6 won't work on with the runtime on Preview 5. This also means we'll need to update this string when we update the runtime to Preview 6.
Co-authored-by: Krrish Mittal <krrishmittal15@gmail.com>
=> Fix mis-matched Preview releases between GHA and runtime (#6766)

client-react/src/pages/app/functions/common/useCreateFunctionFormBuilderFactory.ts, client-react/src/utils/CommonConstants.ts
[#10559782](https://msazure.visualstudio.com/Antares/_workitems/edit/10559782/)
Add experimentation flighting IDs and check if flighting is enabled before using new Cosmos DB resource creation UX.
=> [Functions Collateral] Set up an experiment with Cosmos DB create

client/src/app/site/spec-picker/price-spec-manager/isolatedv2-plan-price-spec.ts
Currently, I am hiding a spec picker isolated v2 section if ASEv3 is not GAed. However, we should show if user selects the existing ASEv3 as a current location even though ASEv3 is not GAed in the env.
=> 15125121[ASEv3][Mooncake] Spec picker blade does not show IsolatedV2 pricing for the existing ASE

client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Undo the removal of two strings in #6771 
- `seeAllOptions`
- `seeRecommendedOptions`
=> [Spec Picker] Undo resource string removal

server/src/deployment-center/github/github.controller.ts
Updated inputs to create user/organization repo from GitHub template. Previously had parameters not needed in the call. Using [this API](https://docs.github.com/en/rest/repos/repos#create-a-repository-using-a-template) as reference
=> [Starshot] Update call to create repo from GitHub template

client-react/src/pages/app/functions/app-keys/AppKeys.styles.ts, client-react/src/pages/app/functions/app-keys/HostKeys.tsx, client-react/src/pages/app/functions/app-keys/SystemKeys.tsx
Fixes [AB#15250813](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/15250813)
Also made a change to reuse styles and make sure the key is deleted only on explicit click on continue rather than just callout dismiss.
=> AB#15250813 Show confirmation dialog when deleting system app keys for functionApp

client-react/src/pages/app/deployment-center/DeploymentCenter.data.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx
Task [12451262](https://msazure.visualstudio.com/Antares/_workitems/edit/12451262)
- Setting vnetImagePullEnabled = true always for acr image pulls, current default is false
- Few scenarios require the property to be set to false, so in those cases, we'll route customers to CLI/ARM for special configurations
=> [DC] Set VnetImagePullEnabled for ACR image pulls to true

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrDataLoader.tsx
FixesAB#[14097241](https://msazure.visualstudio.com/Antares/_workitems/edit/14097241)
FetchRegistries was being called 3 times in the initial load because the call was dependent on siteDescriptor (called in fetchData) and subscription, which is already dependent on siteDescriptor. It was also dependent on acrUseManagedIdentities. The call should only be dependent on subscription changes.
=> [DC] Reduce number of calls to fetchRegistries

client-react/src/pages/app/functions/common/callout/storageAccountPivot/StorageAccountPivot.tsx
[BUG 15286519] 
Before: 
When trying to create a new storage in Function -> integration -> input -> New storage. It created n-number of different storage instances which are unnecessary. 
After:
It creates a new instance only when one already isn't there, and when trying to create multiple one. Clicking ok, will point to the first instance created and not create any new one. There is still the okay bug. I am working on that.
=> [Function integration] Delete multiple instances of same storage account

client-react/src/pages/app/functions/common/callout/storageAccountPivot/StorageAccountPivot.tsx
Fixes[#15052455](https://msazure.visualstudio.com/Antares/_workitems/edit/15052455) The ok button when creating new storage account wasn't closing the dialog box as expected. 
Repro Steps:
1. Login the portal on Windows or Mac.
2. Open anyone ‘Function App’ resource -> Navigate to Functions blade -> Create a function and open it.
3. Open the 'Integration' blade of the function -> Click the 'add input'/ 'add output' link into details page.
4. Select a new storage account from popup after clicking new link -> Click ok button.
5. Click drop down and change to another storage account -> Click ok button from popup after clicking new link
6. Check if the ok button can work well.
https://user-images.githubusercontent.com/45466137/186778057-0e297d66-a6f6-4b58-8da7-c3dada12abfb.mp4
=> [Function Integration] Ok button add input Bug

client-react/src/ApiHelpers/AuthService.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrDataLoader.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerFormBuilder.ts
FixesAB#[15363412](https://msazure.visualstudio.com/Antares/_workitems/edit/15363412) and [15366215](https://msazure.visualstudio.com/Antares/_workitems/edit/15366215)
- Fixed so that fetchImage and fetchTag are only called when admin credentials are selected (acrUseManagedIdentity was not updating immediately from setState, so now using direct comparison in useEffect) 
- Should reduce number of calls to getTag and getRepositories if they fail
=> [DC] Prevent fetchTag calls if fetchImages fails

client-react/src/utils/scenario-checker/linux-site.environment.ts, client-react/src/utils/scenario-checker/national-cloud.environment.ts, client-react/src/utils/scenario-checker/windows-code.environment.ts
* Only show http 20 proxy in linux fxn apps
* Aggregate show/hide http 2.0 logic into linux-site
* Add back kube-env check
Co-authored-by: REDMOND\tmauldin <tmauldin@microsoft.com>
=> [CP] Hide http2.0 proxy for fxn apps

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx
FixesAB#[15412681](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s196?workitem=15412681)
If registry source is not ACR, then reset acrUseManagedIdentityCreds and acrUserManagedIdentityId to false and ''.
=> [DC] Set acrUseManagedIdentityCreds property to false for other registry sources

server/src/stacks/2020-10-01/stacks/web-app-stacks/Golang.ts
Fixing 2 issues with go settings in Available stacks API:
1) Go 1.19 should be flagged as experimental
2) Go 1.18 has 2 flags (experimental) and (early access) we should only have 1 flag and in this case experimental takes precedence.
=> Go 1.19 should be flagged as experimental

server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts
Reverts Azure/azure-functions-ux#6864
Need to revert this change as backend needs new .NET7 image for this.
=> Revert "Enable AI for .NET7"

server/src/stacks/2020-06-01/stacks/web-app-stacks/DotnetCore.ts, server/src/stacks/2020-06-01/stacks/web-app-stacks/Java.ts, server/src/stacks/2020-06-01/stacks/web-app-stacks/Node.ts, server/src/stacks/2020-06-01/stacks/web-app-stacks/Php.ts, server/src/stacks/2020-06-01/stacks/web-app-stacks/Python.ts, server/src/stacks/2020-06-01/stacks/web-app-stacks/Ruby.ts, server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts, server/src/stacks/2020-10-01/stacks/function-app-stacks/Java.ts, server/src/stacks/2020-10-01/stacks/function-app-stacks/Node.ts, server/src/stacks/2020-10-01/stacks/function-app-stacks/Powershell.ts, server/src/stacks/2020-10-01/stacks/function-app-stacks/Python.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Java.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Node.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Php.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Ruby.ts
* Update EOL dates since the Date method is 0 based so we need to set it to one month earlier than what is expected
* Update EOL for Java
* Update Node
* Update Powershell
* Update Python
* Update Dotnet webapp
* Update Java webapp
* Update Node webapps
* Update Php webapps
* Update Ruby webapps
* Update Dotnetcore
* Update Java
* Update node
* Update php
* Update python
* Update Ruby
=> Update EOL dates since the Date method is 0 based so we need to set it to one month earlier than what is expected (#6879)

server/src/stacks/2020-10-01/stacks/function-app-stacks/Node.ts, server/src/stacks/2020-10-01/stacks/function-app-stacks/Powershell.ts, server/src/stacks/2020-10-01/stacks/function-app-stacks/Python.ts
We're retiring Node 12 past the community EOL, so it's an exception. Correcting date to when we actually stop support.
cc @pragnagopa / @nzthiago
=> Update Node.ts end of support date

gulpfile.js, package-lock.json, package.json
v3 no longer runs our tasks on Node.js 14 (or later) so update to v4.
- `npx gulp build-fusion-url`
- `npx gulp inline-react-code-coverage`
Downgrade package-lock.json to lockfile v1 since we still require Node.js 14 (and npm 6) because of `node-sass`.
=> chore: Update gulp to fix gulp tasks

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrDataLoader.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx
FixesAB#[15624693](https://msazure.visualstudio.com/Antares/_workitems/edit/15624693) and [14097225](https://msazure.visualstudio.com/Antares/_workitems/edit/14097225)
- Values for ACR image and tag were not being cleared when switching registries
- Added in a check for registryIdentifiers to preserve initial form values in useEffect
- Refreshing on 'Discard' because formProps.initialValues was being overwritten
- ^ This helps with the overall issue of form sometimes not repopulating on resetForm()
**Before:**
**After:**
=> [DC] Clear values for ACR image and tag when switching registries, refresh on discard

client-react/src/ApiHelpers/ServerFarmService.ts, client-react/src/pages/app/change-app-plan/ChangeAppPlan.styles.ts, client-react/src/pages/app/change-app-plan/ChangeAppPlan.tsx, client-react/src/pages/app/change-app-plan/ChangeAppPlan.types.ts, client-react/src/pages/app/change-app-plan/ChangeAppPlanDestinationPlanDetails.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Solution for (AB#[14920888](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s198?workitem=14920888))
Adding a checkbox option to delete an unused app plan when on the change app plan service bl
ade.
=> AB#14920888 Allow for App Plan deletion after change

client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/DeploymentCenterCommandBar.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeBuildRuntimeAndVersion.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx
FixesAB#[15679933 ](https://msazure.visualstudio.com/Antares/_workitems/edit/15679933)
- Save button is enabled with controls are dirty and form values are valid (for both Code and Container form)
- Making runtime stack required so that it is part of validation
**Before:**
**After:**
=> [DC] Enable save button only when form values are valid

client-react/src/models/portal-models.ts, client-react/src/pages/app/functions/function/function-log/FunctionLog.tsx, client-react/src/pages/app/functions/function/function-log/FunctionLogFileStreamDataLoader.tsx, client-react/src/pages/app/log-stream/LogStream.tsx, client-react/src/pages/app/log-stream/LogStreamCommandBar.tsx, client-react/src/pages/app/log-stream/LogStreamData.ts, client-react/src/pages/app/log-stream/LogStreamDataLoader.tsx, client-react/src/pages/app/log-stream/LogStreamLogContainer.tsx, client-react/src/portal-communicator.ts, client-react/src/react-app-env.d.ts, client-react/src/utils/url.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes [AB#15777298](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/S199?workitem=15777298)
Disable function app file system logs and web app web server logs and application logs if the scm host domains are not in the trust domain list
Function app log stream
- File system logs (show disabled message)
- Application Insights logs (stay same)
Function app functions code+test
- File system logs (show disabled message)
- Application Insights logs (stay same)
Function app functions monitor
- File system logs (show disabled message)
- Application Insights logs (stay same)
Web app
- Application logs (show disabled message)
- Web server logs (show disabled message)
=> AB#15777298 Disable Log for requesting scm host names that are not white listed

server/src/stacks/2020-06-01/stacks/web-app-stacks/Java.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Java.ts
Updating [2020-06-01] and [2020-10-01] to turn on OnBD for Java for stacks that are not deprecated and that support App Insights
Change: isDefaultOff: false
=> Yutlin turning Java App Insights to OnBD

server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts
Fixes Azure/azure-functions-dotnet-worker#1120
=> Removed hidden flag for .NET 6 Isolated, .NET 7 Isolated in Stacks API.

server/src/stacks/2020-10-01/stacks/function-app-stacks/Powershell.ts
This PR contains the following changes:
* Adding `PowerShell 7.0` and `7.2` EOL dates as they are publish here: https://learn.microsoft.com/en-us/powershell/scripting/install/powershell-support-lifecycle?view=powershell-7.2#powershell-end-of-support-dates
*  Update EOL date for PowerShell 6.2 to `2022-9-30`
=> Add PowerShell 7.0 and 7.2 EOL dates

server/src/stacks/2020-06-01/stacks/web-app-stacks/AspDotnet.ts, server/src/stacks/2020-06-01/stacks/web-app-stacks/DotnetCore.ts, server/src/stacks/2020-06-01/stacks/web-app-stacks/Node.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Node.ts
Adding App Insights Property isDefaultOff to [2020-06-01] and [2020-10-01] for stacks that are not deprecated and that support App Insights
- .NET 6, .NET Core 3.1
- - OnBD for Windows and Linux
- ASP .NET 4.8, 3.5
- - OnBD for Windows
- Node 18, 16, 14
- - NOT OnBd for Windows and Linux
=> Yutlin adding App Insights isDefaultOff property

client-react/src/SiteState.ts, client-react/src/pages/app/SiteRouter.tsx, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrDataLoader.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.tsx
FixesAB#[15815579](https://msazure.visualstudio.com/Antares/_workitems/edit/15815579)
- Pull image over VNet value was not persisting after save because siteStateContext was not updating with the refresh
=> [DC] Refresh siteStateContext after save for vnetImagePullEnabled

client/.angular-cli.json, client/package-lock.json, client/package.json, client/src/app/controls/form-wizard/directives/wizard-step-title.directive.spec.ts, client/src/app/dev-guide/highlight.service.ts, client/src/app/shared/components/function-app-context-component.ts, client/src/app/shared/services/broadcast.service.ts, client/src/app/site/slots/add-slot/add-slot.component.ts, client/src/app/site/spec-picker/spec-list/spec-list.component.spec.ts
Update TypeScript to 2.9.2 to enable updating prismjs to 1.27.0.
[#13977088](https://msazure.visualstudio.com/Antares/_workitems/edit/13977088/)
=> chore: Update prismjs to 1.27.0 in /client

server/src/stacks/2020-06-01/stacks/web-app-stacks/Node.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Node.ts
Windows currently has Node as OnBD for App Insights, so updating "isDefaultOff" to keep the current prod behaviour.
=> Yutlin Windows Node App Insights Enable OnBD

client-react/src/pages/app/app-settings/GeneralSettings/LinuxStacks/LinuxStacks.tsx
Fixes [AB#15709969](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s201?workitem=15709969)
Based on custoemr's feedback, we make startup command resizable in case the command is pretty large such as Java fatjar
=> AB#15709969  Make startup command resizable

client-react/src/pages/app/functions/function/monitor/tabs/entities/FunctionEntities.tsx, client-react/src/pages/app/functions/function/monitor/tabs/orchestrations/FunctionOrchestrations.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Remove info message from Orchestrations tab.
**Before:**
**After:**
=> 15620874 Remove info banner inside orchestration/Entities tab for durable triggers

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSettings.tsx
[FixesAB#16188501](https://msazure.visualstudio.com/Antares/_workitems/edit/16188501)
- Previously, !formProps.values.privateRegistryUsername was used for accessing cross-subscription registries
- But now, we have the subscriptions dropdown in ACR settings, so this condition is no longer needed
**Before:**
**After:**
=> [DC] Show ACR settings only when ACR is selected as registry source

server/src/stacks/2020-05-01/stacks/function-app-stacks/Python.ts, server/src/stacks/2020-06-01/stacks/function-app-stacks/Python.ts, server/src/stacks/2020-10-01/stacks/function-app-stacks/Python.ts
Reverts Azure/azure-functions-ux#6895
Reverting this as backend is expected to be ready by Nov end
=> Revert "Unhide python 3.10 in stack"

client-react/src/pages/app/deployment-center/DeploymentCenterPublishingUser.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx
FixesAB#[16065060](https://msazure.visualstudio.com/Antares/_workitems/edit/16065060)
- Changed so that validation happens onBlur
- Error message was not showing under Textfields because getErrorMessage() requires component id and name to be the same
- May need to do this for other components in Deployment Center to show error messages and make invalid input more transparent
**Before:**
**After:**
=> [DC] Show validation error for username and password onBlur

server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts, server/src/tests/Stacks/2020-10-01/function-app/validations.ts
Resolves Azure/azure-functions-dotnet-worker/issues/994
=> Adding .NET Framework 4.8 support in Stacks API

client-react/src/pages/app/functions/function/monitor/FunctionMonitor.tsx, client-react/src/pages/app/functions/function/monitor/tabs/orchestrations/FunctionOrchestrations.tsx
If it is Orchestrator or Entity function, we would like to display "Orchestrations/Entity" tabs as the first tab all the time.
Also, I added a log to keep track how many people clicked AI query editor on Orchestrations tab.
=> 15492872Show Orchestration/Entity tab as the first tab and track AI query edit visit on Orchestrations tab

client-react/src/components/form-controls/ComboBox.tsx, client-react/src/components/form-controls/DropDown.tsx, client-react/src/components/form-controls/RadioButton.tsx, client-react/src/components/form-controls/TextField.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterPublishingUser.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.tsx
Task#[16260609](https://msazure.visualstudio.com/Antares/_workitems/edit/16260609)
**Notes:**
Currently, Formik seems to store form.touched() using the component's id as keys instead of its field name. This is because the field name is not being passed into the native Fluent UI components (some of which don't have a "name" attribute). This causes the getErrorMessage on these Formik components to not find the right form.errors() and display the error message. This could be mitigated by upgrading from Formik 1 to Formik 2 (however this will need to be discussed). For now, passing in a custom onBlur function to manually set the field as touched.
**Code Form GHA: ComboBox**
**Code Form External Git: TextField**
**Container Form ACR: TextField**
**Container Function App: TextField**
=> [DC] Validate fields and show error messages onBlur

server/package-lock.json, server/package.json, server/src/deployment-center/github/github.controller.ts
- `@types/chai` 4.3.4
- `@types/node` 16.18.3
- `@types/react` 17.0.52
- `@types/react-dom` 17.0.18
- `@typescript-eslint/eslint-plugin` 5.43.0
- `@typescript-eslint/parser` 5.43.0
- `chai` 4.3.7
- `eslint` 8.27.0
- `typescript` 4.9.3
Fix type mismatch error found when updating TypeScript.
=> chore: Update /server dependencies

client-react/src/pages/app/functions/function/function-editor/FunctionEditorFileSelectorBar.tsx
For new Programming mode, we are removing '\' since it should not implies a directory structure.
**New Programming model:**
=> 16474792 Remove '\' that implies a directory structure inside a Function

server/Resources/Resources.resx
Task#[12980767](https://msazure.visualstudio.com/Antares/_workitems/edit/12980767)
Before:
We were unable to connect to the Azure Pipeline that is connected to this Web App. This could mean it has been removed from the Azure Dev Ops Portal. If this has happened, you can disconnect this pipeline and set up a new deployment pipeline. 
After:
We were unable to connect to the Azure Pipeline that is connected to this Web App. This could mean it has been removed from the Azure Dev Ops Portal, **or you may not have permissions to access it**. If this has happened, you can disconnect this pipeline and set up a new deployment pipeline.
=> [DC] Update DevOps error message to include permissions access

client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeBuildCallout.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceAndBuild.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.tsx
FixesAB#[16946068](https://msazure.visualstudio.com/Antares/_workitems/edit/16946068)
**Before:**
**After:**
Populating runtime information 
But for now, removing GHA support for Go runtimes until we have a workflow file
=> [DC] Add Go support in runtime stack options and remove GHA support

server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts
Addresses Azure/azure-functions-dotnet-worker#1349.
=> Make .NET Framework 4.8 visible; add STS/LTS tags to .NET vers.

client-react/src/pages/app/app-settings/ErrorPages/ErrorPageGrid.tsx
The bug was if you uploaded a file and error Page was already configured, it the save button would still be disabled.
=> [Custom Error Pages] Fixes Dirty Error Pages

client-react/src/pages/app/deployment-center/DeploymentCenterCommandBar.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterFtps.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterPublishingUser.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
FixesAB#[17455444 ](https://msazure.visualstudio.com/Antares/_workitems/edit/17455444) and [17436506](https://msazure.visualstudio.com/Antares/_workitems/edit/17436506)
- Aria label was calling Sync command Redeploy command
- Added canRevealPassword and revealPasswordAriaLabel to password textfields 
- NOTE: Fluent does not have a method for adding hidePasswordAriaLabel
=> [DC] Fix aria label for sync command and add show password aria labels for FTPS and User Scope credentials

client-react/src/utils/scenario-checker/function-app.environment.ts
FixesAB#[17870704](https://msazure.visualstudio.com/Antares/_workitems/edit/17870704)
- Removing Docker Compose option for container function apps since functionality is not supported
**Before**
**After**
=> [DC] Hide Docker Compose option for container function apps

client/src/app/site/slots/common.scss, client/src/app/site/slots/deployment-slots/deployment-slots.component.html
=> [Accessibility Bug][Deployment Slots]

client-react/.eslintrc.js, client-react/package.json, client-react/src/ApiHelpers/ACRService.ts, client-react/src/ApiHelpers/AppKeysService.ts, client-react/src/ApiHelpers/KeyVaultService.ts, client-react/src/ApiHelpers/SiteService.ts, client-react/src/ApiHelpers/static-site/EnvironmentService.ts, client-react/src/components/CustomPanel/CustomPanel.tsx, client-react/src/components/ErrorLogger.tsx, client-react/src/components/MarkdownComponents/MarkdownComponents.tsx, client-react/src/components/form-controls/SearchBox.tsx, client-react/src/pages/app/app-settings/AppSettings.types.ts, client-react/src/pages/app/app-settings/AppSettingsFormData.ts, client-react/src/pages/app/app-settings/ErrorPages/ErrorPageFileUpload.tsx, client-react/src/pages/app/app-settings/GeneralSettings/Platform.tsx, client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/JavaStack.tsx, client-react/src/pages/app/app-settings/GeneralSettings/stacks/function-app/FunctionAppStackSettings.tsx, client-react/src/pages/app/change-app-plan/ChangeAppPlanHeader.tsx, client-react/src/pages/app/deployment-center/bitbucket-provider/DeploymentCenterBitbucketConfiguredView.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerPivot.tsx, client-react/src/pages/app/deployment-center/dropbox-provider/DeploymentCenterDropboxConfiguredView.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubConfiguredView.tsx, client-react/src/pages/app/deployment-center/onedrive-provider/DeploymentCenterOneDriveConfiguredView.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.tsx, client-react/src/pages/app/functions/common/callout/storageAccountPivot/StorageAccountPivot.tsx, client-react/src/pages/container-app/console/ConsoleDataLoader.tsx, client-react/src/pages/container-app/log-stream/LogStreamDataLoader.tsx, client-react/src/pages/static-app/configuration/ConfigurationSnippets.tsx, client-react/src/pages/static-app/skupicker/StaticSiteSkuPicker.tsx, client-react/src/polyfills.ts
[#17890321](https://dev.azure.com/msazure/Antares/_workitems/edit/17890321/)
Change the `npm run lint` command to show only errors with `--quiet`.
Fix these lint errors before turning the rules back on:
- `@typescript-eslint/ban-types`
- `@typescript-eslint/no-empty-function`
- `@typescript-eslint/no-unused-vars`
- `react-hooks/rules-of-hooks`
=> chore: Update ESLint configuration for PR builds

client-react/src/pages/app/functions/new-create-preview/FunctionCreateDataLoader.tsx, client-react/src/pages/app/functions/new-create-preview/useProgrammingModel.tsx, client-react/src/utils/CommonConstants.ts, client-react/src/utils/FwLinks.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
[AB#17979056](https://dev.azure.com/msazure/Antares/_workitems/edit/17979056/)
Add dropdown to enable users to select programming models.
Add `enableNewProgrammingModel` feature flag and hide new dropdown behind it.
=> [Functions][Python] Add v2 programming model dropdown to Create Function

client-react/package-lock.json, client/src/app/shared/models/portal-resources.ts, client/src/app/site/console/shared/components/abstract.console.component.ts, client/src/app/site/console/shared/components/abstract.windows.component.ts, client/src/app/site/console/shared/components/error.component.ts, client/src/app/site/console/shared/components/message.component.ts, client/src/app/site/console/shared/templates/abstract.console.component.html, server/Resources/Resources.resx
Solution for (AB#[17534566](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s212?workitem=17534566)) and (AB#[17534609](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s212?workitem=17534609))
Adding an aria label for the console container text area and aria-live to the users typed commands/feedback . Allows user input and console responses to be read out loud by screen readers
=> AB#17534566 and AB#17534609: Adding screen reading and aria labels to the console blade

client-react/src/models/portal-models.ts, client-react/src/pages/app/functions/function/function-editor/useFunctionEditorQueries.ts, client-react/src/utils/FwLinks.ts, client-react/src/utils/SiteHelper.ts, client-react/src/utils/app-state-utils.tsx
[AB#18154547](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/18154547), [AB#18154619](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/18154619)
Make the editors (Code+Test and Integration) read-only for v2 programming model Python functions.
Fix React hook dependencies in `useFunctionEditorQueries` hooks.
=> [Functions][Python] Ensure Code+Test works in v2 programming model

client-react/src/models/portal-models.ts, client-react/src/pages/app/functions/function/function-editor/FunctionEditorDataLoader.tsx, client-react/src/pages/app/functions/function/function-editor/useFunctionEditorQueries.ts, client-react/src/pages/app/functions/function/integrate/FunctionIntegrate.tsx, client-react/src/pages/app/functions/function/integrate/FunctionIntegrateDataLoader.tsx, client-react/src/utils/FwLinks.ts, client-react/src/utils/SiteHelper.ts, client-react/src/utils/app-state-utils.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Show error banner which, when clicked, opens the Download app content blade if either Code + Test or Integrate is unable to fetch function info due to 404 errors.
This could happen if the user made mistakes while creating or editing v2 programming model Python functions.
Revert "[Functions][Python] Ensure Code+Test works in v2 programming model (#7176)" (commit hash `cb6f31da9`)
=> [Functions][Python] Re-enable Portal editing for v2 Python functions

client-react/package-lock.json, client-react/src/pages/app/app-settings/AppSettings.types.ts, client-react/src/pages/app/app-settings/GeneralSettings/ClientCert/ClientCert.tsx, client-react/src/pages/app/app-settings/GeneralSettings/Platform.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Solution for AB#[16368791](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s214?workitem=16368791)
-Adding an information line under the HTTP version selector to explain that incoming client certificates must be ignored when HTTP version is 2.0
-Setting the Client certificate mode to Ignore and greying out the Incoming client certificates section when HTTP version 2.0 is selected
=> AB#16368791 Updating Client certificate mode when using HTTP 2.0

client-react/src/pages/app/functions/new-create-preview/portal-create-v2/ExistingFileDropdown.tsx, client-react/src/pages/app/functions/new-create-preview/portal-create-v2/Helpers.ts, client-react/src/pages/app/functions/new-create-preview/portal-create-v2/NewFileTextField.tsx, client-react/src/pages/app/functions/new-create-preview/portal-create-v2/TemplateDetail.tsx, client-react/src/pages/app/functions/new-create-preview/portal-create-v2/useFields.ts, client-react/src/pages/app/functions/new-create-preview/portal-create-v2/useFileMutator.ts, client-react/src/pages/app/functions/new-create-preview/portal-create-v2/useFormContainer.ts, client-react/src/pages/app/functions/new-create-preview/portal-create-v2/useFunctionAppFileDetector.ts, client-react/src/pages/app/functions/new-create-preview/portal-create-v2/useFunctionCreator.ts, client-react/src/pages/app/functions/new-create-preview/portal-create-v2/useTemplateDetail.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
[AB#19990968](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/19990968), [AB#19991047](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/19991047)
- Add "job type" dropdown input for selecting how to create the new function.
- Append new function to existing app
- Append new function to existing blueprint
- Create app with new function
- Create blueprint with new function
- Add "new file" text field input for entering new blueprint filenames.
- Add "existing file" dropdown input for selecting an existing blueprint.
Append to existing blueprint
Create new blueprint
=> [Functions][Python] Add support for blueprints

.vscode/extensions.json
Recommend the ESLint VS Code extension instead of the TSLint one.
=> Change recommended VS Code extensions

client-react/src/pages/app/functions/function/integrate/FunctionIntegrate.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
[AB#22618416](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/22618416)
Enable making the Integration tab read-only for v2 programming model Python functions.
Do not rely on `readOnly` since v2 programming model Python functions are editable elsewhere.
=> [Functions] Make Integration read-only for v2 Python functions

client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx
[AB#22862169](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/22862169)
Disable Test/Run for v2 Python functions until the issue causing the worker to crash during function invocations using the admin API is resolved.
=> [Functions] Disable Test/Run for v2 Python functions

client-react/src/components/DisplayTableWithEmptyMessage/DisplayTableWithEmptyMessage.tsx, client-react/src/components/shimmer/BasicShimmerLines.tsx, client-react/src/components/shimmer/CustomElementsShimmer.tsx, client-react/src/components/shimmer/Shimmer.styles.ts, client-react/src/components/shimmer/Shimmer.types.tsx
To fix shimmers without breaking other controls that have come to depend on styles not working as intended, scope the shimmer theme override to just the components requiring shimmer.
=> Fix shimmers (take 2)

client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx, client-react/src/pages/app/functions/function/function-editor/FunctionEditorCommandBar.tsx
Change default file from `functions.metadata` to `host.json` in Code/Test for .NET Isolated apps.
- Unlike `host.json`, `functions.metadata` is not always available for .NET Isolated apps.
Disable Upload button for .NET Isolated apps.
**Screenshot**
=> [Functions] .NET Isolated changes

client-react/src/components/InfoTooltip/InfoTooltip.tsx, client-react/src/pages/app/app-settings/AppSettings.styles.ts, client-react/src/pages/app/app-settings/AppSettings.types.ts, client-react/src/pages/app/app-settings/AppSettingsDataLoader.tsx, client-react/src/pages/app/app-settings/AppSettingsFormData.ts, client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMounts.tsx, client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEdit.tsx, client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEditAdvanced.tsx, client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEditBasic.tsx, client-react/src/utils/CommonConstants.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes [AB#16820690](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s217?workitem=16820690)
1. Add app setting dropdown if the configuration is in advanced, the storage type is azure file shares.
2.  Show banner message is deployment setting is true but the selected app setting is not sticky.
3.  Remove unnecessary error message field input as formik control already handles the error message display.
=> AB#16820690 Add key vault reference for byos

client-react/src/pages/app/functions/function/function-editor/function-test/FunctionTest.tsx
[AB#24516433](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/24516433)
This fixes the issue reported in MPAC for PowerShell 7.2 in the v4 runtime too. See the email thread "MPAC bug - WebsitesExtension - When using default HttpTrigger (PowerShell 7.2) generated by Azure Portal, and run it on Azure Portal (Code + Test -> Test/Run), the value of $name is not passed at the first time." for details.
=> Fix error when running Generic C# Webhook Trigger in v1 runtime.

client-react/src/pages/app/functions/function/hooks/useFunctionsQuery.ts, client-react/src/pages/app/functions/function/hooks/useSiteConfigQuery.ts, client-react/src/pages/app/functions/function/integrate/FunctionIntegrate.tsx, client-react/src/pages/app/functions/new-create-preview/portal-create-v2/useFields.ts, client-react/src/pages/app/functions/new-create-preview/portal-create-v2/useFormContainer.ts, client-react/src/pages/app/functions/new-create-preview/portal-create-v2/useFunctionAppFileDetector.ts, client-react/src/pages/app/functions/new-create-preview/portal-create-v2/useFunctionCreator.ts, client-react/src/pages/app/functions/new-create-preview/useProgrammingModel.tsx, client-react/src/utils/CommonConstants.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
[AB#24523087](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/24523087)
Use `enableNewNodeEditMode` feature flag to hide these features:
- Enable Code+Test editing of v4 Node.js functions.
- Make Integration read-only for v4 Node.js function bindings.
- Use v2 Template APIs to create v4 Node.js functions.
=> [v4 Node] Breakdown: Make v4 programming model Node.js apps editable

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrDataLoader.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSettings.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.tsx
FixesAB#[10409912](https://msazure.visualstudio.com/Antares/_workitems/edit/10409912)
- For a user who chooses to enter a cross-subscription ACR (that they don't have RBAC permissions for but have the credentials for) as a Private Registry in Creates, we want to show their configuration in Deployment Center as a Private Registry
**Before**
**After**
=> [DC] Show cross-sub ACR with no read access as private registry

server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts, server/src/tests/Stacks/2020-10-01/web-app/validations.ts
Added .Net 8 preview as a major version with linux and windows settings for web apps
=> Adding .NET 8 preview as hidden for Web Apps

server/src/stacks/2020-10-01/stacks/web-app-stacks/Java.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/JavaContainers.ts
Adds the following versions to the Java stacks and Java containers:
Java
• Adoptium Temurin 8u345-b01
• MSFT OpenJDK 11.0.16.1
• MSFT OpenJDK 17.0.4.1
Tomcat
• 8.5.82 with Java 8 and Java 11
• 9.0.65 with Java 8, Java 11 and Java 17
• 10.0.23 with Java 8, Java 11 and Java 17
JBoss EAP
• 7.4.5 with Java 17
• 7.4.7 with Java 8, Java 11 and Java 17
=> ANT100 Java stack updates

server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts
Added `isDefaultOff` flag in app insights settings for dotnet 8 Linux and windows runtime settings.
=> Update appinsights settings for dotnet 8

client-react/src/components/DisplayTableWithCommandBar/DisplayTableWithCommandBar.tsx, client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMounts.tsx, client-react/src/pages/app/app-settings/HandlerMappings/HandlerMappings.tsx, client-react/src/pages/app/app-settings/VirtualApplications/VirtualApplications.tsx
Fixes: [AB#17484539](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s222?workitem=17484539)
Set focus on the command item when the context pane is closed
=> AB#17484539 Path mapping - Set command bar focus when closing the panel

client-react/src/components/UpsellBanner/UpsellBanner.tsx, client-react/src/pages/app/app-settings/AppSettings.tsx, client-react/src/utils/CommonConstants.ts, client-react/src/utils/FwLinks.ts, client-react/src/utils/arm-utils.ts, client-react/src/utils/scenario-checker/premium.environment.ts
The up sell for custom error pages should only be shown when a cx isn't on a premium or isolated v2 plan.
Also adding a learn more link.
=> AB#22895557 Updating upsell for custom error pages with ASEv3/2

server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts
Dotnet 8 preview 7 changes are available on Linux web apps. Adding this PR to enable dotnet 8 for Linux Apps.
=> Remove isHidden for dotnet 8 on Linux Apps.

client-react/src/pages/app/deployment-center/DeploymentCenterCommandBar.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Adding a command button to deployment center that opens diagnostics specifically for function apps until the correct web apps id becomes public
Function apps
=> Adding trouble shoot to the deployment center blade command buttons

server/package-lock.json, server/package.json
Eliminate `is_js` dependency by updating `request-ip`.
=> [MQ] Update `request-ip` to 3.3.0

client-react/src/models/site/config.ts, client-react/src/pages/app/app-settings/AppSettings.types.ts, client-react/src/pages/app/app-settings/AppSettingsDataLoader.tsx, client-react/src/pages/app/app-settings/AppSettingsFormData.ts, client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEditAdvanced.tsx, client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEditBasic.tsx, client-react/src/pages/app/app-settings/AzureStorageMounts/StorageProtocol.tsx
Usually UX determines if the storage mount is NFS or SMB based on the access key vault. But backend team somehow add prootocal property into their response value which also have different cases than what we are using 'Smb' vs 'SMB'. This causes the issue that the storage container does not  show any dropdown items. We update it by checking the equality with  case insensitive. Also set the default to smb is the feature flag is off.
=> [BYOS] Path mount value could have protocol property and it is in a different case

server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts
Dotnet 8 preview 7 changes are available on Windows web apps. Adding this PR to enable dotnet 8 for Windows Apps.
=> Remove isHidden for dotnet 8 on Windows Apps

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceAndBuild.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerDataLoader.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerFormBuilder.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSettingsReadOnlyView.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSource.tsx, client-react/src/pages/app/deployment-center/devops-provider/DeploymentCenterVstsBuildConfiguredView.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Task#[25085962](https://msazure.visualstudio.com/Antares/_workitems/edit/25085962)
FixesAB#[25232212](https://msazure.visualstudio.com/Antares/_workitems/edit/25232212)
- For classic Azure Pipelines, they don't have the build information, so just remove the repo information from view
- For containers, show the registry settings like we would for normal containers
**Before**
Containers DevOps view
Read only container view
Code set up view (cannot save changes)
**After**
Containers DevOps view
Read only container view
Code set up view (configured views should still show)
=> [DC] Handle no write permissions case and show container settings readonly view

client-react/src/utils/dependency/Dependency.ts
FixesAB#[25320207](https://msazure.visualstudio.com/Antares/_workitems/edit/25320207) 
- If tags was an empty object, it would still try to delete the hidden tag from it, so it was causing an unnecessary amount of patchSite calls
=> [DC] Delete hidden ACR tag only when necessary

client-react/src/pages/app/app-settings/GeneralSettings/Platform.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes: [AB#25572236](https://msazure.visualstudio.com/Antares/_workitems/edit/25572236)
1. Default https 2.0 proxy to off
2. Show three options
=> AB#25572236 Http2Proxy - show off/on/gPRCOnly options

client/src/app/site/site-config/general-settings/general-settings.component.ts, client/src/app/site/slots/deployment-slots/deployment-slots.component.ts
[AB#25507523](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/25507523)
[SIRT] When upgrading from Basic to Production Tier App Service, we get the older view for "Spec Picker"
Update `general-settings` too even though it is unused.
=> [Spec Picker] Open new spec picker from Deployment Slots UI

client-react/src/ApiHelpers/EventHubService.ts, client-react/src/ApiHelpers/ServiceBusService.ts, client-react/src/utils/CommonConstants.ts
[Task 25524278](https://msazure.visualstudio.com/Antares/_workitems/edit/25524278): [Functions] Update API version used to access Event Hub RP
=> [FunctionApps] Update event hub api version to 2021-11-01

server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts
Now that .NET 8 is GA and the end of support date is set on https://dotnet.microsoft.com/en-us/download/dotnet, updating the value for Functions.
=> updating .NET 8 end of support date

server/package-lock.json, server/package.json
[AB#25891035](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/25891035)
Address [security vulnerability ](https://security.snyk.io/vuln/SNYK-JS-AXIOS-6032459) by updating `axios` to 1.6.2.
#7470
=> Update axios to 1.6.2 in /server

server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts
Setting .NET 8 as on by default and enabled for Linux and Windows
=> Update Dotnet.ts to enable .NET 8 App Insights Support

server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts
We realized a couple of days ago that a few Windows stamp are not on the latest bits so we cannot remove the Early Access flag for windows just yet. @mattchenderson / @surgupta-msft  fyi
=> Revert .NET 8 Windows early access flag removal

client-react/src/ApiHelpers/ManagedIdentityService.ts, client-react/src/components/form-controls/formControl.override.styles.tsx, client-react/src/pages/app/deployment-center/DeploymentCenter.data.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/DeploymentCenterConstants.ts, client-react/src/pages/app/deployment-center/DeploymentCenterFormBuilder.ts, client-react/src/pages/app/deployment-center/authentication/DeploymentCenterAuthenticationSettings.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.tsx, client-react/src/utils/CommonConstants.ts, client-react/src/utils/FwLinks.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Task#[25767588](https://msazure.visualstudio.com/Antares/_workitems/edit/25767588)
- As of now, no way to check for write permissions on site for identity, so we must manually check role assignments for Owner, Contributor, or Website Contributor role on the scope of subscription (inherited), resource group (inherited), and app
**Case 1:** No roleAssignment/write permission, No managedIdentity/write permission
- Does not have option to create new identity, and user must select an identity with sufficient permissions
**Case 2:** No roleAssignment/write permission, Yes managedIdentity/write permission
- Does not have option to create new identity (because they can't assign rbac anyway), and user must select an identity with sufficient permissions
**Case 3:** Yes roleAssignment/write …
=> [DC][OIDC] Add ability to select existing identities

client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/DeploymentCenterFormBuilder.ts, client-react/src/pages/app/deployment-center/authentication/DeploymentCenterAuthenticationSettings.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceAndBuild.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrDataLoader.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.tsx, client-react/src/utils/location.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
FixesAB#[26315354](https://msazure.visualstudio.com/Antares/_workitems/edit/26315354)
- To fix the "The request format was unexpected: Support for federated identity credentials not enabled"
- https://learn.microsoft.com/en-us/entra/workload-id/workload-identity-federation-considerations#unsupported-regions-user-assigned-managed-identities
-  Listed regions:
- Germany North
- Sweden South
- Sweden Central
- East Asia
- Qatar Central
- Brazil Southeast
- Malaysia South
- Poland Central
- Removed ability to create new identity if the app is located in an unsupported region
=> [DC][OIDC] Remove support for identities in unsupported regions for federated credential creation

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerFormBuilder.ts
FixesAB#[26364085](https://msazure.visualstudio.com/Antares/_workitems/edit/26364085)
- Save button was not enabled because there was a validation error on authType for containers now that OIDC is the default
=> [DC] Set default auth type to publish profile for containers, save scm settings

client-react/src/pages/app/deployment-center/DeploymentCenterFormBuilder.ts
FixesAB#[26390859](https://msazure.visualstudio.com/Antares/_workitems/edit/26390859)
- We should only be validating on authType and authIdentity when we're dealing with a Code GHA app
=> [DC] Only add authType and authIdentity validation for GHA case

server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts
Reverts Azure/azure-functions-ux#7506
Stamps are ready to remove early access for windows
=> Revert "Revert .NET 8 Windows early access flag removal"

client-react/src/components/form-controls/formControl.override.styles.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterFormBuilder.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceAndBuild.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.tsx, server/Resources/Resources.resx
FixesAB#[26479839](https://msazure.visualstudio.com/Antares/_workitems/edit/26479839)
=> [DC] Check on GHA BuildProvider, fix role assignment check, and punycode non-ASCII characters

server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts
Updating the default from .NET 6 using the in-process model to .NET 8 using the isolated worker model.
To prevent confusion, this PR also makes sure to add qualifiers for the in-process model.
.NET Framework 4.8 notably doesn't have any specification of it being the isolated worker model. I'm leaving that to prevent long strings and because we do not want to inadvertently conflate "isolated" with a brand term of .NET's. We might be able to restructure these strings a bit if we wanted to add it (add a ", " or something) separately in the future. This is considered out of scope for this PR.
=> updating Functions .NET default

client-react/src/pages/app/deployment-center/DeploymentCenterFormBuilder.ts
FixesAB#[26615427](https://msazure.visualstudio.com/Antares/_workitems/edit/26615427)
Save button was enabling because we were changing authType from OIDC -> Publish Profile for all non-GHA scenarios
**Before**
**After**
=> [DC] Default auth type to publish profile and change only for GHA

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeFormBuilder.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerFormBuilder.ts
FixesAB#[26631629](https://msazure.visualstudio.com/Antares/_workitems/edit/26631629)
Deployment Center blade was not loading because ARC apps don't have basic publishing credentials
=> [DC] Handle ARC case for basic publishing credentials check

client-react/src/pages/app/app-settings/GeneralSettings/Platform.tsx, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/DeploymentCenterCommandBar.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterDataLoader.tsx, client-react/src/pages/app/deployment-center/authentication/DeploymentCenterFtps.tsx, client-react/src/pages/app/deployment-center/authentication/DeploymentCenterPublishingUser.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodePivot.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerPivot.tsx, client-react/src/pages/app/deployment-center/publish-profile/DeploymentCenterPublishProfilePanel.tsx, client-react/src/utils/FwLinks.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Task#[26718903](https://msazure.visualstudio.com/Antares/_workitems/edit/26718903)
- When either ftp or scm basic auth is enabled, manage publish profile will work; otherwise, show dialog saying basic auth is disabled
- FTP Credentials Tab will always be shown, but if ftp basic auth is disabled, all controls will be disabled and warning banner will show
=> [DC] Disable Manage Publish Profile Button and bring back FTP Credentials Tab

client-react/src/ApiHelpers/ArmHelper.ts, client-react/src/ArmHelper.types.ts
FixesAB#[26728497](https://msazure.visualstudio.com/Antares/_workitems/edit/26728497)
- In OIDC flow, we create user assigned identity and then immediately try to add federated credentials, but the created user-assigned identity was returning with 201 status code and location header
- Need to poll on location before trying to do a PUT operation on newly created resource
=> Poll ARM after async operations with provisioning states and locations

server/src/stacks/2020-10-01/stacks/function-app-stacks/Powershell.ts
Unhide PowerShell 7.4 runtime for Windows only.
=> Unhide PowerShell 7.4 runtime for Windows only

server/src/stacks/2020-10-01/stacks/function-app-stacks/Powershell.ts
Cherry-picked https://github.com/Azure/azure-functions-ux/pull/7590 to the `release-s234` branch.
=> Unhide PowerShell 7.4 runtime for Windows only (#7590)

server/src/stacks/2020-10-01/service/StackService.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/JavaContainers.ts
Adding EOL dates (the property `endOfLifeDate`) for Tomcat versions 8.5 and 10.0. This PR is implemented in the same way as the plain Java stacks in `Java.ts` where two versions of the object (one with ISO dates and one without) are available.
The diff looks huge in the web but it's actually not that big if whitespace is omitted (e.g. in VS Code)
=> Add EOL dates for Tomcat 8.5 and 10.0

client-react/src/mocks/ArmMocks.ts, client-react/src/models/site/config.ts, client-react/src/pages/app/app-settings/FunctionRuntimeSettings/RuntimeScaleMonitoring.tsx
Use 2022-03-01 name (`minimumElasticInstanceCount`) instead of 2018-11-01 name (`reservedInstanceCount`).
[AB#27264546](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/27264546)
=> [Functions] Unable to enable/disable runtime scale monitoring

server/src/deployment-center/github/github.controller.ts
It was supposed to be POST for a call between PaaS and Fusion.
=> revise - 27185980[Starshot][Route] Add Get github content API call

client/package-lock.json
Address [CVE-2024-29041](https://www.cve.org/CVERecord?id=CVE-2024-29041).
#7633
=> Bump express to 4.19.2 in /client

server/src/deployment-center/github/github.controller.ts
This is for GitHub content update API. 
`_commitGitHubFile` is exactly same as `_commitFile` function except the prop type. `_commitFile` is expecting to have workflow file.
=> 27576526[Startshot][Route] Add GtiHub repository API call

client-react/package-lock.json, client-react/package.json
- `@types/yup` 0.28.3
- `yup` 0.28.5
Fix `property-expr` vulnerability by updating to 2.0.6 (via `yup` update).
=> Bump yup to 0.28.5 in /client-react

client-react/src/pages/app/app-settings/AppSettingsDataLoader.tsx
=> AB#27799522: Query the location and stack based stacks api call for dotnet-isolated with stack value as dotnet

server/src/stacks/2020-10-01/stacks/web-app-stacks/Php.ts
Currently, PHP|8.3 is behind the flag and now testing is done so removing this flag.
And this change will be included in the next release cycle.
**Testing Steps**
1. Accessed the portal with the flag websitesextension_showHiddenStacks=true.
2. Created the app successfully.
3. Scm portal also loaded successfully.
4. Was able to deploy sample app successfully.
Portal URL
[Create Web App - Microsoft Azure](https://ms.portal.azure.com/?feature.canmodifystamps=true&WebsitesExtension=canary&feature.fastmanifest=false&nocdn=force&websitesextension_functionsnext=true&WebsitesExtension_useReactFrameBlade=true&websitesextension_newchangeasp=true&feature.fullscreenblades=true&websitesextension_loglevel=verbose&Microsoft_Azure_PaasServerless_functionsnext=true&Microsoft_Azure_PaasServerless=canary&web …
=> Enable PHP|8.3 for all

client-react/src/pages/app/app-settings/GeneralSettings/stacks/function-app/FunctionAppStackSettings.data.ts
=> AB# 27922292: [BugBash][FunctionApp][FlexConsumption] Unsupported Stack versions shown in the configuration

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx
FixesAB#[28002083](https://msazure.visualstudio.com/Antares/_workitems/edit/28002083)
Function apps requires: `repo:${values.org}/${values.repo}:ref:refs/heads/${values.branch}`
Web apps requires: `repo:${values.org}/${values.repo}:environment:production`
=> [DC] Fix subject for user-assigned identity for function app oidc setup

client-react/src/pages/app/app-settings/GeneralSettings/stacks/function-app/FunctionAppStackSettings.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes: [AB#28002495](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/Dilithium/CY24Q2/2Wk/2Wk05%20(Jun%2002%20-%20Jun%2015)?workitem=28002495)
1. Make sure when selectin .NET in process for windows function app stack setting, it does not default o .NET isolated
2. Currently we hide stack setting when it is invalid. Fix it by showing it with warning/error messages.
=> AB#28002495 Enable dotnet in process selection for function app stack settings

client-react/src/pages/app/deployment-center/DeploymentCenter.styles.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/DeploymentCenterConstants.ts, client-react/src/pages/app/deployment-center/DeploymentCenterFormBuilder.ts, client-react/src/pages/app/deployment-center/bitbucket-provider/DeploymentCenterBitbucketAccount.tsx, client-react/src/pages/app/deployment-center/external-provider/DeploymentCenterExternalProvider.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubAccount.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Task#[26238721](https://msazure.visualstudio.com/Antares/_workitems/edit/26238721)
When setting up Private External Git using a GitHub or Bitbucket repo, Source Controls just pulls the user source control token to authenticate, so the textfields are unnecessary. Instead, we're replacing with an Oauth button to make sure they're signed in.
**If user has source control token (signed in)**
**Authorize button**
=> [DC] Add Oauth button when using GitHub or Bitbucket repo + External Git

server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts
Drafting for when we're at the point of being able to release this. We'll start with just Windows.
=> unhiding .NET 8 in-proc for Windows

server/src/stacks/2020-10-01/stacks/web-app-stacks/JavaContainers.ts
This PR adds the missing `java21Runtime` property for the versions of Tomcat 9.0 which have a Java 21 runtime.
=> Add missing java21Runtime property for latest Tomcat 9 versions

server/src/stacks/2020-10-01/stacks/web-app-stacks/JavaContainers.ts, server/src/tests/Stacks/2020-10-01/web-app/validations.ts
This PR adds 2 hidden entries for the upcoming JBoss 8 release on App Service.
=> Add hidden entries for JBoss 8 on JavaContainers

server/package-lock.json
Address [CVE-2024-37890](https://nvd.nist.gov/vuln/detail/CVE-2024-37890) by updating from 7.5.9 to 7.5.10.
Resolve merge conflicts in #7704.
=> Bump ws to 7.5.10 in /server

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.tsx
FixesAB#[26799615](https://msazure.visualstudio.com/Antares/_workitems/edit/26799615) and [27324172](https://msazure.visualstudio.com/Antares/_workitems/edit/27324172)
Save and Discard buttons were getting enabled after saving and then user goes from Logs to Settings tab.
When switching tabs, the form reverts as if scmType is None, causing the non-configured view to load and authType switched from oidc to publish profile.
Now, reset the form whenever we do the load the setup view and there are no FTPS setting changes.
=> [DC] Reset form when loading setup view

server/src/stacks/2020-10-01/stacks/web-app-stacks/JavaContainers.ts
This PR fixes an issue where the new versions for JBoss 8 are being combined with the list of entries for JBoss 7 in the Configuration blade because they share a common identifier that I forgot to change in #7690 
By using a different identifier, only minor versions of JBoss 8 will show when JBoss 8 is selected, and only minor versions of JBoss 7 will show when JBoss 7 is selected. This is the same approach used by the Tomcat container versions.
=> Use a new internal ID for JBoss 8 so it's not merged the JBoss 7 entries

client-react/src/utils/stacks-utils.tsx
Fixes: [AB#28114775](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/Dilithium/CY24Q3/Monthly/07%20Jul%20(Jun%2030%20-%20Jul%2027)?workitem=28114775)
The input date is ISO date string but when displaying it in the manner, it is shown as the local date based on the input because using toLocaleDateString(). For example, the input is 5/11/2024 and it is shown as 5/10/2024. Fixing it by add { timezone: 'UTC'} to toLocaleDateString
=> AB#28114775 Update end of life date format to make sure it is the same date as the input

server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts
Draft PR for when this does become available. At time of opening this PR, this should remain hidden.
=> unhiding .NET 8 in-proc for Linux

server/gulpfile.js
Remove not required change to gulpfile.js which caused a Fusion build break.
=> Undo gulpfile change causing Fusion build break

client-react/src/models/site/config.ts, client-react/src/pages/app/app-settings/AppSettingsFormData.ts, client-react/src/pages/app/app-settings/GeneralSettings/LinuxStacks/JavaStack.tsx
Fixes: [AB#28784815](https://msazure.visualstudio.com/Antares/_workitems/edit/28784815)
=> AB#28784815 use camel case for clustering enabled property's name

server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts
Dotnet 9 preview in Linux App Service has reached stage 2 in the rollout.
This PR is to remove the isHidden flag for Linux and enable the preview option in the portal for the customers. 
Validation: 
1. Created a web app with Dotnet 9 preview as selected stack and Linux as OS.
2. Deployed the dotnet 9 app through zip deploy.
3. The app was up and running using Dotnet 9 preview libraries
4.
=> Dotnet 9 Preview: Removing isHidden flag for Linux runtime

client-react/src/pages/static-app/configuration/ConfigurationForm.tsx
This PR removes the unnecessary 'App settings moved' notification from the snippets blade as this is already in the configuration blade where it is needed. 
Before:
After:
=> Removing app settings moved banner

server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts, server/src/tests/Stacks/2020-10-01/function-app/validations.ts
Adding hidden support for .NET 9 so that when we're ready to enable the previews, we'll just flip those hidden states.
EOL date guess informed by current state of https://github.com/dotnet/core/blob/main/releases.md, though the official support policy does not include anything for this version yet.
This PR contributes to but does not satisfy https://github.com/Azure/azure-functions-dotnet-worker/issues/2562. To complete that, we will need to change the hidden state.
=> preparing for .NET 9 on Functions

client-react/src/pages/app/deployment-center/DeploymentCenterFormBuilder.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeDataLoader.tsx, client-react/src/pages/app/deployment-center/external-provider/DeploymentCenterExternalProvider.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
FixesAB#[28962074](https://msazure.visualstudio.com/Antares/_workitems/edit/28962074)
We don't support GitHub and Bitbucket OAuth in National Clouds, so we need to remove support for that when user selects a private GitHub/Bitbucket repo + External Git
**Before**
**After**
=> [DC] Remove private external GitHub repo and Bitbucket repo support in National Clouds

server/src/stacks/2020-10-01/stacks/function-app-stacks/Java.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Java.ts
We ship Eclipse Temurin in our Azure App Service runtimes using Java 8. This PR updates the Java 8 EOL date to **November 30, 2026** based on the page at https://adoptium.net/support/ which states Java 8 will be available until "_At least Nov 2026_".
=> Update the Java 8 EOL date to the date from Eclipse Temurin

server/src/stacks/2020-10-01/stacks/function-app-stacks/Node.ts, server/src/tests/Stacks/2020-10-01/function-app/validations.ts
Related to https://github.com/Azure/azure-functions-nodejs-library/issues/252
Since this is hidden, this is ready to merge whenever.
=> Add Node.js v22 as a hidden and preview function app stack

server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts
1. Add dotnet 8
2.  Deprecate dotnet core (3.1,2.1)
3. Update app insights settings
=> Update OnPrem dotnet stacks

server/src/stacks/2020-10-01/stacks/web-app-stacks/JavaContainers.ts
This PR updates the `displayText` property of JBoss BYO License variants on JavaContainers.ts so that the Azure Portal UI shows the entries in a separate category from the regular JBoss entries.
Also, added the entry for the BYOL variant of JBoss 8.0.2.1 which was missing.
What we're aiming for is as on the following mock-up:
=> Update displayText props of JBoss BYOL variants to solve portal UI issue

server/src/stacks/2020-10-01/stacks/function-app-stacks/Java.ts
Updating MS Build of OpenJDK Java 11 EOL date to September 2027 for Functions.
=> Updating Java 11 EOL to September 2027

server/src/stacks/2020-10-01/stacks/web-app-stacks/Java.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/JavaContainers.ts
Updating portal versions for
Java 8u422, 11.0.24, 17.0.12, and 21.0.4
Tomcat 8.5.100, 9.0.93, 10.1.28
JBossEAP 7.4.18, 8.0.2.1
=> New versions of Java/Tomcat/JBoss stacks for ANT103

client-react/src/ApiHelpers/RuntimeStackService.ts
Use non-arm getFunctionAppConfigurationStacks call for OnPrem to fix the issue configuration page of function app in OnPrem couldn't be loaded
=> Use non-arm getFunctionAppConfigurationStacks call for OnPrem

client-react/src/ApiHelpers/RuntimeStackService.ts
Use non-arm getFunctionAppConfigurationStacks call for OnPrem to fix the issue configuration page of function app in OnPrem couldn't be loaded
=> Use non-arm getFunctionAppConfigurationStacks call for OnPrem (#7839)

server/src/stacks/2020-10-01/stacks/web-app-stacks/Python.ts
Add support for Python 3.12 App Insights, but off by default.
=> Update Python.ts for 3.12 App Insights

tools/pipelines/build/canary.yml
Ok works, tested in private branch and the BuildVer.txt in the artifacts shows the actual build version
=> Update canary.yml for Azure Pipelines

client-react/src/components/CipherSuite/MinTLSCipherSuiteSelector.styles.ts, client-react/src/components/CipherSuite/MinTLSCipherSuiteSelector.tsx, client-react/src/pages/app/app-settings/GeneralSettings/Platform.tsx, client-react/src/utils/FwLinks.ts, client-react/src/utils/arm-utils.ts, client-react/src/utils/scenario-checker/azure.environment.ts, client-react/src/utils/scenario-checker/elastic-premium.environment.ts, client-react/src/utils/scenario-checker/premium.environment.ts, client-react/src/utils/scenario-checker/workflow-app.environment.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
- Enabled it for all apps except kube, non standard workflow, and any apps that has free or standard sku.
- Fixed the bug that when the input is null, the field shows the default value but the dropdown is empty.
> Before
> After
- Add default tag if the cipher suite is the least secure one. And change the 'change' text to uppercase to conform the link text convention.
- Disable change button when the user does not have certain permission
- Add more info and a doc link to explain the potential issue of configuring min tls cipher suite with isolated app.
> Isolated app:
> Non isolated app:
- Add extra padding to fix the issue that the last min tls cipher suite is hidden 
> Before: (The last one is hidden behind the footer and no scroll bar on the panel level)
> After:
=> [AppService][Configuration] Min tls cipher suite GA 

server/src/stacks/2020-10-01/stacks/web-app-stacks/Java.ts
There was a delay in the update to Java for some space restrictions on the worker a couple months back and the PR for the fix never went through [Pull request 10545996: Add new versions of Java and Tomcat on rapid - Repos (visualstudio.com)](https://msazure.visualstudio.com/One/_git/AAPT-Antares-RapidUpdateFeed/pullrequest/10545996?iteration=3&base=2). [Task 28645036: [Jan RU] Prepare RU for Java SE and Tomcat on Windows - Boards (visualstudio.com)](https://msazure.visualstudio.com/Antares/_workitems/edit/28645036/).
Reverting Windows changes for https://github.com/Azure/azure-functions-ux/pull/7780/files and fixing Java 17.0.12 typo for Linux.
=> Remove Latest Pinned Windows Java Versions and Fix Java 17.0.12 typo

server/src/stacks/2020-10-01/stacks/web-app-stacks/Java.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/JavaContainers.ts
* Cherry-pick of the changes from #7869 (commit 9e498e3d07f400fdb111d3c86a10148d5b08f095) into the release-s246 branch to fix entries for Java on Windows and Linux
* Unhide the JBoss BYO License entries
Original description from #7869:
> There was a delay in the update to Java for some space restrictions on the worker a couple months back and the PR for the fix never went through [Pull request 10545996: Add new versions of Java and Tomcat on rapid - Repos (visualstudio.com)](https://msazure.visualstudio.com/One/_git/AAPT-Antares-RapidUpdateFeed/pullrequest/10545996?iteration=3&base=2). [Task 28645036: [Jan RU] Prepare RU for Java SE and Tomcat on Windows - Boards (visualstudio.com)](https://msazure.visualstudio.com/Antares/_workitems/edit/28645036/).
> Reverting Windows changes for …
=> Remove Windows java (#7869), unhide JBoss BYO License entries

server/src/stacks/2020-10-01/stacks/web-app-stacks/JavaContainers.ts
This PR unhides the entries related to JBoss BYO License. Same as in #7873 but this time merging against `dev`.
=> Unhide the JBoss BYO License entries

server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts
This PR removes the isPreview:true flag for .NET 9 for both Linux and Windows
=> Removing isPreview Flag for Dotnet 9 (Linux & Windows)

server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts
This should go in in coordination with https://github.com/Azure/azure-functions-ux/pull/7875
=> Removing preview for .NET 9 (Functions)

client-react/package-lock.json, client-react/package.json, client-react/src/pages/App.tsx, client-react/src/pages/LandingPage/LandingPage.tsx, client-react/src/pages/app/SiteRouter.tsx, client-react/src/pages/container-app/ContainerAppEnvironmentRouter.tsx, client-react/src/pages/container-app/ContainerAppRouter.tsx, client-react/src/pages/static-app/StaticSiteRouter.tsx, server/package-lock.json, server/src/tests/Stacks/2020-10-01/function-app/validations.ts
Update lockfile version from 1 to 3 to ensure compatibility with npm used with Node.js 18 (and later).
- Add "overrides" entry for react@17.0.2.
- Replace @reach/router with @gatsbyjs/reach-router for React 17 compatibility.
=> [Fusion] Update lockfile version to 3

server/src/stacks/2020-10-01/stacks/web-app-stacks/JavaContainers.ts
Tomcat 9.0.93, 9.0.90 and 9.0.88 were added in #7831 but are not yet ready for Windows sites so this PR will hide them from the dropdown menu in the portal for the time being.
=> Hide Tomcat 8.5.100, 9.0.93, 9.0.90, 9.0.88, 10.1.23, 10.1.25 and 10.1.28 for Windows sites

server/src/stacks/2020-10-01/stacks/function-app-stacks/Java.ts
This PR changes the isPreview values for Java21 on Windows and Linux to false.
- The Windows option is kept hidden for now.
=> azure functions: java21 GA

server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts
Fixing a typo we should have caught and removing the comment from preview time around the EOL date.
=> Fixing release type and confirming EOL

server/src/workflows/2022-10-01/WorkflowService.ts, server/src/workflows/2022-10-01/container-configs/container-functions-linux.config.yml, server/src/workflows/2022-10-01/container-configs/container-webapp-linux.config.yml, server/src/workflows/2022-10-01/function-app-configs/node-linux.config.yml, server/src/workflows/2022-10-01/function-app-configs/node-windows.config.yml, server/src/workflows/2022-10-01/function-app-configs/python-linux.config.yml, server/src/workflows/2022-10-01/web-app-configs/aspnet-windows.config.yml, server/src/workflows/2022-10-01/web-app-configs/dotnetcore-linux.config.yml, server/src/workflows/2022-10-01/web-app-configs/dotnetcore-windows.config.yml, server/src/workflows/2022-10-01/web-app-configs/java-jar-linux.config.yml, server/src/workflows/2022-10-01/web-app-configs/java-jar-windows.config.yml, server/src/workflows/2022-10-01/web-app-configs/java-war-linux.config.yml, server/src/workflows/2022-10-01/web-app-configs/java-war-windows.config.yml, server/src/workflows/2022-10-01/web-app-configs/node-linux-oryx.config.yml, server/src/workflows/2022-10-01/web-app-configs/node-linux.config.yml, server/src/workflows/2022-10-01/web-app-configs/node-windows.config.yml, server/src/workflows/2022-10-01/web-app-configs/php-linux.config.yml, server/src/workflows/2022-10-01/web-app-configs/php-windows.config.yml, server/src/workflows/2022-10-01/web-app-configs/python-linux.config.yml, server/src/workflows/2022-10-01/web-app-configs/wordpress-linux.config.yml
Fixes [AB#30196660](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/30196660)
=> Add contents: read permission

server/src/stacks/2020-10-01/stacks/web-app-stacks/JavaContainers.ts
Hide Tomcat 8.5.100, 9.0.93, 9.0.90, 9.0.88, 10.1.23, 10.1.25 and 10.1.28 for Windows sites (#7897)
=> Hide Tomcat 8.5.100, 9.0.93, 9.0.90, 9.0.88, 10.1.23, 10.1.25 and 10.1.28 for Windows sites (#7897)

client-react/src/pages/container-app/console/ConsoleDataLoader.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
This pull request introduces several changes to the `ConsoleDataLoader` component in the `client-react` project to support a new debug mode, along with corresponding updates to resource files. The most important changes include adding new properties to the `ConsoleDataLoaderProps` interface, modifying the logic to handle different modes, and updating the UI to reflect the new debug mode.
* Added `mode` and `endpoint` properties to `ConsoleDataLoaderProps` and updated logic to use these properties. (`client-react/src/pages/container-app/console/ConsoleDataLoader.tsx`)
* Modified the `toggleHideDialog` and `getWsUrl` functions to use the new `endpoint` property instead of `execEndpoint`. (`client-react/src/pages/container-app/console/ConsoleDataLoader.tsx`) …
=> Support debug console for Azure Container Apps

client-react/src/models/site/site.ts, client-react/src/pages/app/app-settings/AppSettingsDataLoader.tsx, client-react/src/pages/app/app-settings/AppSettingsFormData.ts, client-react/src/pages/app/app-settings/GeneralSettings/ClientCert/ClientCert.tsx, client-react/src/pages/app/app-settings/GeneralSettings/Platform.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes: [AB#29764273](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/Selenium/CY24Q4/Monthly/11%20Nov%20(Oct%2027%20-%20Nov%2030)?workitem=29764273)
1. Change client cert mode value to reflect the underlying value to avoid any confusion:
Before: Optional -> Allow, OptionalInteractiveUser -> Optinal
Now: Optional -> Optional, OptionalInteractiveUser -> Optional Interactive User
2. Disable optional interactive user if http version is 2 and the min TLS version is 1.3. If the currently selected mode is optional interactive user, then switch it to ignore. A warning message is shown to explains why optional interactive user is disabled
=> AB#29764273 [Configuration]Disable optional interactive user for http 20 or min tls version 1.3
