Azure/azure-functions-ux

AzureFunctions.Client/AzureFunctions.Client.csproj
AzureFunctions.Client/app/components/app.component.ts
AzureFunctions.Client/app/components/dashboard.component.ts
AzureFunctions.Client/app/components/function-configure.component.ts
AzureFunctions.Client/app/components/function-dev.component.ts
AzureFunctions.Client/app/components/function-edit.component.ts
AzureFunctions.Client/app/components/function-integrate-v2.component.ts
AzureFunctions.Client/app/components/log-streaming.component.ts
AzureFunctions.Client/app/components/sidebar.component.ts
AzureFunctions.Client/app/components/top-bar.component.ts
AzureFunctions.Client/app/models/function-container.ts
AzureFunctions.Client/app/models/publishing-credentials.ts
AzureFunctions.Client/app/services/arm.service.ts
AzureFunctions.Client/app/services/functions.service.ts
AzureFunctions.Client/app/services/iarm.service.ts
AzureFunctions.Client/app/services/ifunctions.service.ts
AzureFunctions.Client/app/services/iportal.service.ts
AzureFunctions.Client/app/services/mock-functions.service.ts
AzureFunctions.Client/app/services/portal.service.ts
AzureFunctions.Client/app/services/user.service.ts
AzureFunctions.Client/index.html
AzureFunctions.Client/tsconfig.json

Changing the getting started flow

---

AzureFunctions.Client/templates/tutorial.component.html

Including updated copy provided by the UX and voice team.

updating copy for quickstart tour

---

AzureFunctions.Client/AzureFunctions.Client.csproj
AzureFunctions.Client/app/boot.ts
AzureFunctions.Client/app/components/app-monitoring.component.ts
AzureFunctions.Client/app/components/app.component.ts
AzureFunctions.Client/app/models/appMonitoring-consumption.ts
AzureFunctions.Client/app/services/appMonitoring.service.ts
AzureFunctions.Client/app/services/iappMonitoring.service.ts
AzureFunctions.Client/config.js
AzureFunctions.Client/index.html
AzureFunctions.Client/package.json
AzureFunctions.Client/prod.html
AzureFunctions.Client/stage.html
AzureFunctions.Client/styles/app-monitoring.style.css
AzureFunctions.Client/templates/app-monitoring.component.html

this takes care of https://github.com/projectkudu/WebJobsPortal/issues/128

Function App Monitoring tab consumption chart

---

AzureFunctions.Client/app/components/template-picker.component.ts

fixed #246, fixed #227, fixed #223

Multiple fix for temlpate-picker, fixed #246, fixed #227, fixed #223

---

AzureFunctions.Client/prod.html
AzureFunctions.Client/stage.html
AzureFunctions.Client/templates/getting-started.component.html

add link to create in azure portal

---

AzureFunctions.Client/app/components/dashboard.component.ts
AzureFunctions.Client/app/components/error-list.component.ts
AzureFunctions.Client/app/components/function-new.component.ts
AzureFunctions.Client/app/components/intro.component.ts
AzureFunctions.Client/app/components/log-streaming.component.ts
AzureFunctions.Client/app/handlers/functions.exception-handler.ts
AzureFunctions.Client/app/models/error-event.ts
AzureFunctions.Client/app/models/error-item.ts
AzureFunctions.Client/app/services/broadcast.service.ts
AzureFunctions.Client/app/services/functions.service.ts
AzureFunctions.Client/app/services/portal.service.ts

Log details in portal.service and display timestamp

---

AzureFunctions.Tests/AzureFunctions.Tests.csproj
AzureFunctions.Tests/FrontEndAuthProviderFacts.cs
AzureFunctions.Tests/Properties/AssemblyInfo.cs
AzureFunctions.Tests/packages.config
AzureFunctions.sln
AzureFunctions/Authentication/ClaimTypes.cs
AzureFunctions/Authentication/FrontEndAuthProvider.cs
AzureFunctions/AzureFunctions.csproj

Change handling jwt tokens in FrontEndAuthProvider to use System.IdentityModel. Fixes #373

---

AzureFunctions.Client/app/components/try-now.component.ts
AzureFunctions.Client/templates/try-now.component.html

window.location.href, hides the new window in Ibiza mode

Open Redirect to Free Trial Link in new window

---

AzureFunctions.Client/app/components/app.component.ts

@alrod, @ahmelsayed : This try mode check here was incorrect.

Fixes #459 . No redirects to Ibiza

---

AzureFunctions.Client/AzureFunctions.Client.csproj
AzureFunctions.Client/app/boot.ts
AzureFunctions.Client/app/components/aggregate-block.component.ts
AzureFunctions.Client/app/components/function-monitor.component.ts
AzureFunctions.Client/app/components/table-function-monitor.component.ts
AzureFunctions.Client/app/models/function-monitor.ts
AzureFunctions.Client/app/models/portal-resources.ts
AzureFunctions.Client/app/pipes/aggregate-block.pipe.ts
AzureFunctions.Client/app/pipes/table-function-monitor.pipe.ts
AzureFunctions.Client/app/services/function-monitor.service.ts
AzureFunctions.Client/package.json
AzureFunctions.Client/styles/aggregate-block.style.css
AzureFunctions.Client/styles/function-monitor.style.css
AzureFunctions.Client/styles/table-function-monitor.style.css
AzureFunctions.Client/templates/aggregate-block.component.html
AzureFunctions.Client/templates/function-monitoring.component.html
AzureFunctions.Client/templates/table-function-monitor.html
AzureFunctions/ResourcesPortal/Resources.Designer.cs
AzureFunctions/ResourcesPortal/Resources.resx

This updates the function monitor tab as per the spec view.
Contains : aggregate tabs for overall success and errors,
Table for the Invocation log 
On clicking a row on the above table, Invocation details grid & the Output component are displayed.
the Invocation Log data is polled every minute. 
On selecting a new function all the data should be updated for the selected function
Still Pending: 
Merge with the latest dev - DONE
confirm all the text headers with the PM - DONE
update the hardcoded text to use localization model - DONE

Function Monitoring view

---

AzureFunctions.Client/app/components/function-monitor.component.ts
AzureFunctions.Client/app/components/table-function-monitor.component.ts
AzureFunctions.Client/app/models/portal-resources.ts
AzureFunctions.Client/templates/table-function-monitor.html
AzureFunctions/ResourcesPortal/Resources.Designer.cs
AzureFunctions/ResourcesPortal/Resources.resx

Adding a Busy state to the table-function Monitoring and the aggregate block shows "Loading..." text by default.

Bug:#533-Monitoring shouldn't block on all data being loaded

---

AzureFunctions.Client/app/directives/monaco-editor.directive.ts
AzureFunctions.Client/app/models/function-info.ts

Recognizing the `ts` extension and setting the language to TypeScript

Adding TypeScript language

---

AzureFunctions.Client/app/components/trial-expired.component.ts
AzureFunctions.Client/app/components/try-now.component.ts
AzureFunctions.Client/app/services/ai.service.ts
AzureFunctions.Client/app/services/functions.service.ts

Tested locally with host file blocking of mixpanel.

Harden check for mixpanel load.

---

AzureFunctions.Client/app/services/functions.service.ts

Speed up try function load times #808

---

AzureFunctions.AngularClient/src/app/function-monitor/function-monitor.component.css
AzureFunctions.AngularClient/src/app/function-monitor/function-monitor.component.ts
AzureFunctions.AngularClient/src/app/shared/models/function-monitor.ts
AzureFunctions.AngularClient/src/app/shared/services/function-monitor.service.ts
AzureFunctions.AngularClient/src/app/table-function-monitor/table-function-monitor.component.css
AzureFunctions.AngularClient/src/app/table-function-monitor/table-function-monitor.pipe.ts

Bug: #843 : Monitoring tab should support the new 'Never Finished' Status

Work: #844 : Performance: use /timeline APIs for getting function stats.

---

AzureFunctions/ResourcesPortal/Resources.Designer.cs
AzureFunctions/ResourcesPortal/Resources.resx

Improve strings in Platform Features list

---

AzureFunctions.AngularClient/src/app/site/swagger-definition/swagger-definition.component.scss

Styling fix for swagger-definition blade

---

README.md

I was trying to setup my laptop and wasn't able to get it to work properly.  Then I noticed you added a yarn lock.  After doing a yarn install, it seemed to install everything correctly so I'm guessing this is the right way to do this now.  Let me know if it isn't.

Added instructions for yarn

---

AzureFunctions.AngularClient/src/app/shared/function-app.ts
AzureFunctions.AngularClient/src/app/site/function-runtime/function-runtime.component.ts

We had a few issues with merging the angular4 branch. I had to cherry pick a bunch of commits that didn't make it, and these are the last changes needed to get the build to work

Fix merge issues

---

AzureFunctions.AngularClient/src/app/shared/models/portal-resources.ts
AzureFunctions.AngularClient/src/app/shared/services/portal.service.ts
AzureFunctions.AngularClient/src/app/site/site-manage/site-manage.component.ts
AzureFunctions/ResourcesPortal/Resources.resx

Also fixed portal notification so that it works when you're not in an iframe

Fixes #1222 - OGF: Search string for deployment string needs to be updated

---

AzureFunctions.AngularClient/AzureFunctions.AngularClient.csproj
AzureFunctions.AngularClient/src/app/apps-list/apps-list.component.html
AzureFunctions.AngularClient/src/app/apps-list/apps-list.component.scss
AzureFunctions.AngularClient/src/app/shared/models/portal-resources.ts
AzureFunctions.AngularClient/src/images/learn-more.svg
AzureFunctions.AngularClient/src/sass/controls/_tbl.scss
AzureFunctions/ResourcesPortal/Resources.Designer.cs
AzureFunctions/ResourcesPortal/Resources.resx

http://vstfrd:8080/web/wi.aspx?pcguid=da67359a-080e-44ae-89d6-fe0624058810&id=9190551

Functions emptybrowse experience for function Apps

---

AzureFunctions.AngularClient/src/app/app.module.ts
AzureFunctions.AngularClient/src/app/shared/services/arm.service.ts

Refactored the providers to be deterministic so we can use AOT on them and always get both options of `ArmService` and `TryArmService` put in the bundle.
Also, fixed TsLint issues, to make it easier to read the file we are fixing here.

tslint fixes and AOT fixes for "try" service providers

---

AzureFunctions.AngularClient/src/app/shared/function-app.ts

Updating to use the new GET api instead of the POST that is creating race conditions when querying for a  new masterKey

#1296 Updating to use the new GET call for obtaining mater key

---

AzureFunctions/ResourcesPortal/Resources.resx

Changing the text so that its relevant even when app insights is enabled

Text update: app insights banner text

---

AzureFunctions.AngularClient/AzureFunctions.AngularClient.csproj
AzureFunctions.AngularClient/src/app/app.module.ts
AzureFunctions.AngularClient/src/app/binding/binding.component.css
AzureFunctions.AngularClient/src/app/functions-list/functions-list.component.html
AzureFunctions.AngularClient/src/app/functions-list/functions-list.component.scss
AzureFunctions.AngularClient/src/app/functions-list/functions-list.component.ts
AzureFunctions.AngularClient/src/app/search-box/search-box.component.html
AzureFunctions.AngularClient/src/app/search-box/search-box.component.scss
AzureFunctions.AngularClient/src/app/search-box/search-box.component.spec.ts
AzureFunctions.AngularClient/src/app/search-box/search-box.component.ts
AzureFunctions.AngularClient/src/app/side-nav/side-nav.component.html
AzureFunctions.AngularClient/src/app/side-nav/side-nav.component.scss
AzureFunctions.AngularClient/src/sass/controls/_input.scss
AzureFunctions/ResourcesPortal/Resources.Designer.cs
AzureFunctions/ResourcesPortal/Resources.resx

Add enable/disable, search, and delete to All Functions page. 

---

AzureFunctions.AngularClient/AzureFunctions.AngularClient.csproj
AzureFunctions.AngularClient/src/app/app.component.ts
AzureFunctions.AngularClient/src/app/app.module.ts
AzureFunctions.AngularClient/src/app/getting-started/getting-started.component.ts
AzureFunctions.AngularClient/src/app/shared/models/constants.ts
AzureFunctions.AngularClient/src/app/shared/models/portal.ts
AzureFunctions.AngularClient/src/app/shared/services/arm-try.service.ts
AzureFunctions.AngularClient/src/app/shared/services/arm.service-helper.ts
AzureFunctions.AngularClient/src/app/shared/services/arm.service.ts
AzureFunctions.AngularClient/src/app/shared/services/background-tasks.service.ts
AzureFunctions.AngularClient/src/app/shared/services/config.service.ts
AzureFunctions.AngularClient/src/app/shared/services/language.service-helper.ts
AzureFunctions.AngularClient/src/app/shared/services/language.service.ts
AzureFunctions.AngularClient/src/app/shared/services/portal.service.ts
AzureFunctions.AngularClient/src/app/shared/services/user.service.ts
AzureFunctions.AngularClient/src/app/side-nav/side-nav.component.ts
AzureFunctions.AngularClient/src/app/site/create-app/create-app.component.ts
AzureFunctions.AngularClient/src/app/site/function-runtime/function-runtime.component.ts
AzureFunctions.AngularClient/src/app/site/site-summary/site-summary.component.ts
AzureFunctions.AngularClient/src/polyfills.ts
AzureFunctions/Controllers/AzureFunctionsController.cs
AzureFunctions/Default.cshtml

Changed getStartupInfo on the UserService to be a single endpoint to initialize the following:
1. Token
2. User-Info (For no-iframe scenario's)
3. Subscriptions
4. Default resource strings

Fixes #1276 - Need to standardize initialization logic

---

AzureFunctions.AngularClient/src/app/functions-list/functions-list.component.html
AzureFunctions.AngularClient/src/app/functions-list/functions-list.component.ts
AzureFunctions.AngularClient/src/app/tree-view/function-node.ts

Add text (disabled) for disabled functions. Closes #1291

---

AzureFunctions.AngularClient/src/app/binding/binding.component.ts
AzureFunctions.AngularClient/src/app/pickers/event-hub/event-hub.component.html
AzureFunctions.AngularClient/src/app/pickers/event-hub/event-hub.component.scss
AzureFunctions.AngularClient/src/app/pickers/event-hub/event-hub.component.ts
AzureFunctions.AngularClient/src/app/shared/models/portal-resources.ts
AzureFunctions/ResourcesPortal/Resources.Designer.cs
AzureFunctions/ResourcesPortal/Resources.resx

Allow user to select an IOT hub when using Event Hub Trigger. Fixes #1414

---

AzureFunctions.AngularClient/AzureFunctions.AngularClient.csproj
AzureFunctions.AngularClient/src/app/app.module.ts
AzureFunctions.AngularClient/src/app/download-function-app-content/download-function-app-content.component.html
AzureFunctions.AngularClient/src/app/download-function-app-content/download-function-app-content.component.scss
AzureFunctions.AngularClient/src/app/download-function-app-content/download-function-app-content.component.spec.ts
AzureFunctions.AngularClient/src/app/download-function-app-content/download-function-app-content.component.ts
AzureFunctions.AngularClient/src/app/radio-selector/radio-selector.component.scss
AzureFunctions.AngularClient/src/app/shared/directives/monaco-editor.directive.ts
AzureFunctions.AngularClient/src/app/shared/function-app.ts
AzureFunctions.AngularClient/src/app/shared/models/portal-resources.ts
AzureFunctions.AngularClient/src/app/site/site-summary/site-summary.component.html
AzureFunctions.AngularClient/src/app/site/site-summary/site-summary.component.ts
AzureFunctions/ResourcesPortal/Resources.Designer.cs
AzureFunctions/ResourcesPortal/Resources.resx

Add a button for generating Visual Studio project. Closes #985

---

AzureFunctions.AngularClient/src/app/shared/Utilities/url.ts
AzureFunctions.AngularClient/src/app/shared/services/portal.service.ts

Making sure to decode the entire URL that's passed to us from Ibiza.  We're actually already decoding each query value, but this will ensure that we do this for everything else as well.

Added URL decoding for URL that's passed to us from Ibiza

---

AzureFunctions.AngularClient/src/app/radio-selector/radio-selector.component.scss
AzureFunctions/ResourcesPortal/Resources.resx

Removing (preview) from API definition and moving it into tab

---

AzureFunctions/ResourcesPortal/cs-CZ/AzureFunctions/ResourcesPortal/Resources.resx
AzureFunctions/ResourcesPortal/de-DE/AzureFunctions/ResourcesPortal/Resources.resx
AzureFunctions/ResourcesPortal/es-ES/AzureFunctions/ResourcesPortal/Resources.resx
AzureFunctions/ResourcesPortal/fr-FR/AzureFunctions/ResourcesPortal/Resources.resx
AzureFunctions/ResourcesPortal/hu-HU/AzureFunctions/ResourcesPortal/Resources.resx
AzureFunctions/ResourcesPortal/it-IT/AzureFunctions/ResourcesPortal/Resources.resx
AzureFunctions/ResourcesPortal/ja-JP/AzureFunctions/ResourcesPortal/Resources.resx
AzureFunctions/ResourcesPortal/ko-KR/AzureFunctions/ResourcesPortal/Resources.resx
AzureFunctions/ResourcesPortal/nl-NL/AzureFunctions/ResourcesPortal/Resources.resx
AzureFunctions/ResourcesPortal/pl-PL/AzureFunctions/ResourcesPortal/Resources.resx
AzureFunctions/ResourcesPortal/pt-BR/AzureFunctions/ResourcesPortal/Resources.resx
AzureFunctions/ResourcesPortal/pt-PT/AzureFunctions/ResourcesPortal/Resources.resx
AzureFunctions/ResourcesPortal/qps-ploc/AzureFunctions/ResourcesPortal/Resources.resx
AzureFunctions/ResourcesPortal/ru-RU/AzureFunctions/ResourcesPortal/Resources.resx
AzureFunctions/ResourcesPortal/sv-SE/AzureFunctions/ResourcesPortal/Resources.resx
AzureFunctions/ResourcesPortal/tr-TR/AzureFunctions/ResourcesPortal/Resources.resx
AzureFunctions/ResourcesPortal/zh-CN/AzureFunctions/ResourcesPortal/Resources.resx
AzureFunctions/ResourcesPortal/zh-TW/AzureFunctions/ResourcesPortal/Resources.resx

We haven't updated resource files quite a while.

Update resource files

---

AzureFunctions.AngularClient/AzureFunctions.AngularClient.csproj
AzureFunctions.AngularClient/src/app/api-details/api-details.component.css
AzureFunctions.AngularClient/src/app/api-details/api-details.component.html
AzureFunctions.AngularClient/src/app/api-details/api-details.component.ts
AzureFunctions.AngularClient/src/app/api-new/api-new.component.html
AzureFunctions.AngularClient/src/app/api-new/api-new.component.scss
AzureFunctions.AngularClient/src/app/api-new/api-new.component.ts
AzureFunctions.AngularClient/src/app/site/site-dashboard/site-dashboard.component.ts
AzureFunctions/ResourcesPortal/Resources.Designer.cs
AzureFunctions/ResourcesPortal/Resources.resx

Minor proxy alignments with integrate tab

---

AzureFunctions.AngularClient/src/app/multi-drop-down/multi-drop-down.component.html
AzureFunctions.AngularClient/src/app/multi-drop-down/multi-drop-down.component.scss
AzureFunctions.AngularClient/src/app/multi-drop-down/multi-drop-down.component.ts
AzureFunctions.AngularClient/src/app/shared/models/constants.ts
AzureFunctions.AngularClient/src/app/shared/models/drop-down-element.ts
AzureFunctions.AngularClient/src/app/shared/models/portal-resources.ts
AzureFunctions.AngularClient/src/app/side-nav/side-nav.component.html
AzureFunctions.AngularClient/src/app/side-nav/side-nav.component.ts
AzureFunctions.AngularClient/src/app/tree-view/tree-view.component.scss
AzureFunctions.AngularClient/src/sass/base/_base.scss
AzureFunctions/ResourcesPortal/Resources.resx

Down arrow - Moves focused item down
Up arrow - Moves focused item up
Enter/Space - Selects the focused item
Escape - Closes the dropdown but keeps control focused
Tab - Closes the dropdown and moves focus to next control

Fixes #1495 - [Accessibility] Add keyboard navigation to subscription dropdown

---

AzureFunctions.AngularClient/src/app/function-dev/function-dev.component.ts
AzureFunctions.AngularClient/src/app/shared/models/portal-resources.ts
AzureFunctions/ResourcesPortal/Resources.Designer.cs
AzureFunctions/ResourcesPortal/Resources.resx

Fixes #1188 Provide visual indication function save succeeded

---

AzureFunctions.AngularClient/src/app/function-dev/function-dev.component.html
AzureFunctions.AngularClient/src/app/shared/directives/monaco-editor.directive.ts

Use CTLR-ENTER to run function

Fix #371: Added function run shortcut

---

AzureFunctions.AngularClient/src/app/site/site-manage/site-manage.component.html

Making "back" text for inplace experiment clickable

---

AzureFunctions.AngularClient/src/app/site/swagger-definition/swagger-definition.component.html
AzureFunctions.AngularClient/src/app/site/swagger-definition/swagger-definition.component.scss
AzureFunctions.AngularClient/src/app/site/swagger-definition/swagger-definition.component.ts

API Definitions (Improvement): Clear busy state quickly  

---

AzureFunctions.AngularClient/src/app/apps-list/apps-list.component.html
AzureFunctions.AngularClient/src/app/apps-list/apps-list.component.scss
AzureFunctions.AngularClient/src/app/apps-list/apps-list.component.ts
AzureFunctions.AngularClient/src/app/controls/tbl/tbl-th/tbl-th.component.ts
AzureFunctions.AngularClient/src/app/controls/tbl/tbl.component.ts
AzureFunctions.AngularClient/src/app/functions-list/functions-list.component.html
AzureFunctions.AngularClient/src/app/shared/models/portal-resources.ts
AzureFunctions.AngularClient/src/app/site/site-config/site-config.component.ts
AzureFunctions/ResourcesPortal/Resources.resx

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/azure-functions-ux/1611)

Fixes #1599 - Improve the Function apps browse list

---

AzureFunctions.AngularClient/src/app/binding-input/binding-input.component.html
AzureFunctions.AngularClient/src/app/binding-input/binding-input.component.ts
AzureFunctions.AngularClient/src/app/binding/binding.component.ts
AzureFunctions.AngularClient/src/app/function-new/function-new.component.html
AzureFunctions.AngularClient/src/app/function-new/function-new.component.ts
AzureFunctions.AngularClient/src/app/pickers/microsoft-graph/microsoft-graph-helper.ts
AzureFunctions.AngularClient/src/app/shared/function-app.ts
AzureFunctions.AngularClient/src/app/shared/models/binding.ts
AzureFunctions.AngularClient/src/app/shared/models/function-template.ts
AzureFunctions.AngularClient/src/app/shared/models/microsoft-graph.ts
AzureFunctions.AngularClient/src/app/shared/models/portal-resources.ts
AzureFunctions.AngularClient/src/app/shared/models/portal.ts
AzureFunctions.AngularClient/src/app/shared/models/template-picker.ts
AzureFunctions.AngularClient/src/app/shared/services/cache.service.ts
AzureFunctions.AngularClient/src/app/shared/services/user.service.ts
AzureFunctions.AngularClient/src/app/template-picker/template-picker.component.html
AzureFunctions.AngularClient/src/app/template-picker/template-picker.component.ts
AzureFunctions.AngularClient/yarn.lock
AzureFunctions/ResourcesPortal/Resources.resx

Created a new 'express aad registration' button for bindings and templates that require an AAD application. Basically re-doing the Easy Auth blade in typescript while reducing the number of clicks + auto-setting permissions.

AAD express button, uses ibiza graph token

---

AzureFunctions.AngularClient/src/app/controls/command-bar/command/command.component.html
AzureFunctions.AngularClient/src/app/controls/command-bar/command/command.component.ts
AzureFunctions.AngularClient/src/app/shared/models/localStorage/enabled-features.ts
AzureFunctions.AngularClient/src/app/site/site-enabled-features/site-enabled-features.component.html
AzureFunctions.AngularClient/src/app/site/site-enabled-features/site-enabled-features.component.ts
AzureFunctions.AngularClient/src/app/site/site-summary/site-summary.component.html
AzureFunctions.AngularClient/src/app/site/site-summary/site-summary.component.ts

Fixes #1586 - Accessibility & Screen Reader for Function App Overview

---

AzureFunctions.AngularClient/src/app/feature-group/feature-group.component.html
AzureFunctions.AngularClient/src/app/feature-group/feature-group.component.ts
AzureFunctions.AngularClient/src/app/feature-group/feature-group.ts
AzureFunctions.AngularClient/src/app/feature-group/feature-item.ts
AzureFunctions.AngularClient/src/app/pop-over/pop-over.component.html

Fixes #1590 - Add Accessibility for Platform Features 

---

AzureFunctions.AngularClient/src/app/try-landing/try-landing.component.ts

"Sign in with XXX" buttons on try functions page are not working #1682.
Ive update the tryappservice api to retunr loginurl header in lowercase to match this

Fix  #1682 Try Functions not working

---

AzureFunctions.AngularClient/src/app/binding-input/binding-input.component.html
AzureFunctions.AngularClient/src/app/binding-input/binding-input.component.ts
AzureFunctions.AngularClient/src/app/pop-over/pop-over.component.html
AzureFunctions.AngularClient/src/app/pop-over/pop-over.component.scss
AzureFunctions.AngularClient/src/app/pop-over/pop-over.component.ts

Integrate (Regex Validation): Showing warning instead of error for invalid input, allows user to save

---

AzureFunctions.AngularClient/src/app/pop-over/pop-over.component.html
AzureFunctions.AngularClient/src/app/pop-over/pop-over.component.ts
AzureFunctions.AngularClient/src/app/site/swagger-definition/swagger-definition.component.html
AzureFunctions.AngularClient/src/app/site/swagger-definition/swagger-definition.component.ts

Bug fix: Shift + tab opens the target URL for pop-over component
Press Tab to move through components
Press Enter or Space to perform underlying action

API Definition: Accessibility

---

AzureFunctions.AngularClient/src/app/function-keys/function-keys.component.html
AzureFunctions.AngularClient/src/app/shared/models/portal-resources.ts
AzureFunctions/ResourcesPortal/Resources.resx

Add click to hide - fixes #1086

---

AzureFunctions.AngularClient/src/app/getting-started/getting-started.component.ts
AzureFunctions.AngularClient/src/app/shared/models/constants.ts
AzureFunctions.AngularClient/src/app/shared/models/portal-resources.ts
AzureFunctions.AngularClient/src/app/shared/services/config.service.ts
AzureFunctions.AngularClient/src/app/shared/services/functions.service.ts
AzureFunctions.AngularClient/src/app/site/function-runtime/function-runtime.component.ts
AzureFunctions.AngularClient/src/app/tree-view/app-node.ts
AzureFunctions.AngularClient/src/polyfills/window.ts
AzureFunctions/Code/Settings.cs
AzureFunctions/Contracts/ISettings.cs
AzureFunctions/Controllers/AzureFunctionsController.cs
AzureFunctions/Global.asax.cs
AzureFunctions/Views/_Base.cshtml
common/models/functions-version-info.ts
server/src/actions/user-account.ts
server/src/config.ts
server/src/server.ts
server/src/views/_base/head.pug

Fix setting FUNCTIONS_EXTENSION_VERSION during create flow

---

AzureFunctions.AngularClient/src/app/busy-state/busy-state.component.ts

debounce calls to setBusyState to prevent jarring UI updates

---

AzureFunctions.AngularClient/src/app/function-keys/function-keys.component.html
AzureFunctions.AngularClient/src/app/function-keys/function-keys.component.ts
AzureFunctions.AngularClient/src/app/shared/Utilities/internal-load-balancer.ts
AzureFunctions.AngularClient/src/app/shared/function-app.ts
AzureFunctions.AngularClient/src/app/shared/models/arm/hosting-environment.ts
AzureFunctions.AngularClient/src/app/shared/models/arm/site.ts
AzureFunctions.AngularClient/src/app/tree-view/app-node.ts
AzureFunctions.AngularClient/src/app/tree-view/base-functions-proxies-node.ts
AzureFunctions.AngularClient/src/app/tree-view/functions-node.ts
AzureFunctions.AngularClient/src/app/tree-view/proxies-node.ts
AzureFunctions.AngularClient/src/app/tree-view/tree-node.ts
AzureFunctions.AngularClient/src/app/tree-view/tree-view.component.html
common/utilities/internal-load-balancer.ts
server/src/actions/proxy.ts

@ehamai I still need to move strings to resx, but can you take a look at the basic logic for blocking the 2 nodes when in ILB ASE? Is this the correct way of using the tree apis to achieve this?
Fixes #1718
Fixes #1517

Handle ILB ASE apps better

---

AzureFunctions.AngularClient/src/app/feature-group/feature-group.component.html
AzureFunctions.AngularClient/src/app/feature-group/feature-group.component.ts

Icon display fix

---

AzureFunctions.AngularClient/.angular-cli.json
AzureFunctions.AngularClient/src/app/getting-started/getting-started.component.scss
AzureFunctions.AngularClient/src/app/top-bar/top-bar.component.scss
AzureFunctions.AngularClient/yarn.lock

Add z-indices to css classes
fix issue https://github.com/Azure/azure-functions-ux/issues/1754

fix tenants list layout issue

---

AzureFunctions.AngularClient/.angular-cli.json
AzureFunctions.AngularClient/src/app/getting-started/getting-started.component.scss
AzureFunctions.AngularClient/src/app/top-bar/top-bar.component.scss

Reverts Azure/azure-functions-ux#1761
unable to click on drop downs

Revert "fix tenants list layout issue"

---

AzureFunctions.AngularClient/src/app/busy-state/busy-state-scope-manager.ts
AzureFunctions.AngularClient/src/app/busy-state/busy-state.component.ts
AzureFunctions.AngularClient/src/app/main/main.component.ts

I'm also removing the debounce logic when setting busy state.

Enabling loader when lazy loading a chunk

---

AzureFunctions.AngularClient/src/app/shared/models/portal-resources.ts
AzureFunctions.AngularClient/src/app/site/site-manage/site-manage.component.ts
AzureFunctions.AngularClient/src/images/toolbox.svg
AzureFunctions/ResourcesPortal/Resources.resx

Adding link in platform features to open the MSI blade (DON'T MERGE UNTIL IBIZA IS READY)

---

AzureFunctions.AngularClient/src/app/aad-registration/aad-registration.component.ts
AzureFunctions.AngularClient/src/app/function-monitor/function-monitor.component.css
AzureFunctions.AngularClient/src/app/function-monitor/function-monitor.component.html
AzureFunctions.AngularClient/src/app/function-monitor/function-monitor.component.scss
AzureFunctions.AngularClient/src/app/function-monitor/function-monitor.component.ts
AzureFunctions.AngularClient/src/app/main/main.component.ts
AzureFunctions.AngularClient/src/app/pickers/microsoft-graph/microsoft-graph-helper.ts
AzureFunctions.AngularClient/src/app/shared/function-app.ts
AzureFunctions.AngularClient/src/app/shared/models/constants.ts
AzureFunctions.AngularClient/src/app/shared/models/portal-resources.ts
AzureFunctions.AngularClient/src/app/shared/services/arm.service.ts
AzureFunctions.AngularClient/src/app/shared/services/slots.service.ts
AzureFunctions.AngularClient/src/app/shared/shared.module.ts
AzureFunctions.AngularClient/src/app/shared/validators/slotNameValidator.ts
AzureFunctions.AngularClient/src/app/side-nav/side-nav.component.ts
AzureFunctions.AngularClient/src/app/site/function-runtime/function-runtime.component.ts
AzureFunctions.AngularClient/src/app/site/site-enabled-features/site-enabled-features.component.ts
AzureFunctions.AngularClient/src/app/site/site-summary/site-summary.component.ts
AzureFunctions.AngularClient/src/app/slot-new/slot-new.component.ts
AzureFunctions.AngularClient/src/app/tree-view/app-node.ts
AzureFunctions.AngularClient/src/app/try-landing/try-landing.component.ts
AzureFunctions/Code/DiagnosticsManager.cs
AzureFunctions/ResourcesPortal/Resources.Designer.cs
AzureFunctions/ResourcesPortal/Resources.resx

APP INSIGHTS + Dashboard
APP INSIGHTS
Dashboard

Gracefully handle missing dashboard. Fixes #1763.

---

AzureFunctions.AngularClient/src/app/file-explorer/file-explorer.component.html
AzureFunctions.AngularClient/src/app/file-explorer/file-explorer.component.scss
AzureFunctions.AngularClient/src/app/function-monitor/function-monitor.component.html

Fixes #1819 - [Dark Theme] File explorer highlighting is too bright

---

.travis.yml

Example: https://travis-ci.org/hartra344/azure-functions-ux/builds/279782655

Add support for TravisCI builds for pull requrest validation

---

AzureFunctions.AngularClient/src/app/binding-input/binding-input.component.html
AzureFunctions.AngularClient/src/app/binding-input/binding-input.component.ts
AzureFunctions.AngularClient/src/app/binding/binding.component.ts
AzureFunctions.AngularClient/src/app/functions.module.ts
AzureFunctions.AngularClient/src/app/pickers/notification-hub/notification-hub.component.html
AzureFunctions.AngularClient/src/app/pickers/notification-hub/notification-hub.component.spec.ts
AzureFunctions.AngularClient/src/app/pickers/notification-hub/notification-hub.component.ts
AzureFunctions.AngularClient/src/app/shared/models/binding.ts
AzureFunctions.AngularClient/src/app/shared/models/portal-resources.ts
AzureFunctions.AngularClient/src/app/shared/services/arm.service.ts
AzureFunctions/ResourcesPortal/Resources.Designer.cs
AzureFunctions/ResourcesPortal/Resources.resx

New picker for Notification Hubs

New picker for Notification Hubs (#1727)

---

AzureFunctions.AngularClient/src/app/controls/textbox/textbox.component.ts
AzureFunctions.AngularClient/src/app/dev-guide/dev-guide.component.html
AzureFunctions.AngularClient/src/app/dev-guide/dev-guide.component.scss
AzureFunctions.AngularClient/src/app/dev-guide/dev-guide.module.ts
AzureFunctions.AngularClient/src/app/dev-guide/editable-tbl-example/editable-tbl-example.component.html
AzureFunctions.AngularClient/src/app/dev-guide/editable-tbl-example/editable-tbl-example.component.scss
AzureFunctions.AngularClient/src/app/dev-guide/editable-tbl-example/editable-tbl-example.component.ts
AzureFunctions.AngularClient/src/app/dev-guide/tbl-example/tbl-example.component.html
AzureFunctions.AngularClient/src/app/dev-guide/tbl-example/tbl-example.component.ts
AzureFunctions.AngularClient/src/app/dev-guide/textbox-example/textbox-example.component.scss
AzureFunctions.AngularClient/src/sass/controls/_tbl.scss

Added table examples to dev guide

---

AzureFunctions.AngularClient/src/app/edit-mode-warning/edit-mode-warning.component.html
AzureFunctions.AngularClient/src/app/edit-mode-warning/edit-mode-warning.component.ts
AzureFunctions.AngularClient/src/app/shared/Utilities/edit-mode.helper.ts
AzureFunctions.AngularClient/src/app/shared/function-app.ts
AzureFunctions.AngularClient/src/app/shared/models/constants.ts
AzureFunctions.AngularClient/src/app/shared/models/function-app-edit-mode.ts
AzureFunctions/ResourcesPortal/Resources.resx
server/src/actions/resources.en.json

add warning for functions generated by visual studios

---

AzureFunctions.AngularClient/src/app/feature-group/feature-item.ts
AzureFunctions.AngularClient/src/app/shared/models/constants.ts
AzureFunctions.AngularClient/src/app/shared/models/portal-resources.ts
AzureFunctions.AngularClient/src/app/shared/services/scenario/azure.environment.ts
AzureFunctions.AngularClient/src/app/shared/services/scenario/dynamic-site.environment.ts
AzureFunctions.AngularClient/src/app/shared/services/scenario/linux-site.environment.ts
AzureFunctions.AngularClient/src/app/shared/services/scenario/scenario.service.ts
AzureFunctions.AngularClient/src/app/shared/services/scenario/site-slot.environment.ts
AzureFunctions.AngularClient/src/app/shared/services/scenario/stand-alone.environment.ts
AzureFunctions.AngularClient/src/app/site/site-manage/site-manage.component.ts
AzureFunctions.AngularClient/yarn.lock
AzureFunctions/ResourcesPortal/Resources.resx

For linux, the list of site features will look like this:

Disabling features that don't work on linux

---

AzureFunctions.AngularClient/src/app/function-monitor/function-monitor.component.ts
AzureFunctions.AngularClient/src/app/shared/models/constants.ts

A customer is having issues loading the Function monitor component. It looks like we're swallowing exceptions that are being thrown in that component which is masking how bad this issue really is. I think i know what the issue is, but it would be good to get confirmation.

HOTFIX - Adding logging to for Function monitor error handling

---

AzureFunctions.AngularClient/src/app/functions-list/functions-list.component.html
AzureFunctions.AngularClient/src/app/functions-list/functions-list.component.scss

Fixes #1881 - Delete function icon on Functions list page is missing

---

AzureFunctions.AngularClient/src/app/edit-mode-warning/edit-mode-warning.component.html

resolves https://github.com/Azure/azure-functions-ux/issues/1889

opens learn more link in a new window

---

AzureFunctions.AngularClient/src/app/main/main.component.html
AzureFunctions.AngularClient/src/app/main/main.component.scss
AzureFunctions.AngularClient/src/app/main/main.component.ts
AzureFunctions.AngularClient/src/sass/base/_typography.scss

BUG: 10523282:[Functions]Azure Azure Functions Runtime title disappear when scrolling down

Asfarok function10523282

---

AzureFunctions/ResourcesPortal/Resources.Designer.cs
AzureFunctions/ResourcesPortal/Resources.resx

Fixing Australia Southeast typo

Updating Typo

---

AzureFunctions.AngularClient/src/app/shared/function-app.ts

VS generated functions can become read/write

---

AzureFunctions.AngularClient/src/app/shared/Utilities/jwt.ts
AzureFunctions.AngularClient/src/app/shared/services/portal.service.ts

This is to help us troubleshoot token expiration issues.

Fixes: #1850 - Add logging for whenever we get a new token

---

AzureFunctions.AngularClient/src/app/create-function-wrapper/create-function-wrapper.component.ts
AzureFunctions.AngularClient/src/app/shared/services/functions-service.ts
AzureFunctions.AngularClient/src/app/shared/services/scenario/scenario.service.ts
AzureFunctions.AngularClient/src/app/tree-view/app-node.ts
AzureFunctions.AngularClient/src/app/tree-view/tree-node.ts

Fixes #1987 where the tree nav wasn't loading for the Try scenario.
Also adds back in app scoping (>>) capability, and fixes logic to ensure that we load the Functions quickstart page if no functions exist.

Fixes #1987 for Try nav tree not loading, as well as other tree issues

---

AzureFunctions.AngularClient/src/app/shared/function-app.ts
AzureFunctions.AngularClient/src/app/shared/no-cors-http-service.ts

Don't cache post requests by default in NoCorsHttpService

---

AzureFunctions.AngularClient/src/app/radio-selector/radio-selector.component.html
AzureFunctions.AngularClient/src/app/radio-selector/radio-selector.component.scss
AzureFunctions.AngularClient/src/app/radio-selector/radio-selector.component.ts
AzureFunctions.AngularClient/src/app/site/function-runtime/function-runtime.component.html
AzureFunctions.AngularClient/src/app/site/function-runtime/function-runtime.component.ts

Prevent unnecessary PUT calls in FunctionRuntimeComponent (fixes #1933)

---

AzureFunctions.AngularClient/src/app/function/binding-input-v2/binding-input-v2.component.html
AzureFunctions.AngularClient/src/app/function/binding-input-v2/binding-input-v2.component.scss
AzureFunctions.AngularClient/src/app/function/binding-input-v2/binding-input-v2.component.ts
AzureFunctions.AngularClient/src/app/function/function-new-detail/function-new-detail.component.html
AzureFunctions.AngularClient/src/app/function/function-new-detail/function-new-detail.component.scss
AzureFunctions.AngularClient/src/app/function/function-new/function-new.component.html
AzureFunctions.AngularClient/src/app/function/function-new/function-new.component.scss
AzureFunctions.AngularClient/src/app/function/function-new/function-new.component.ts
AzureFunctions.AngularClient/src/app/shared/models/portal-resources.ts
server/gulpfile.js

fixes #2034 
fixes #2035 
fixes #2036 
fixes #2039 
in progress #2041

create bug fixes

---

AzureFunctions.AngularClient/src/app/busy-state/busy-state.component.scss
AzureFunctions.AngularClient/src/app/drop-down/drop-down.component.scss
AzureFunctions.AngularClient/src/app/function/binding-input-v2/binding-input-v2.component.html
AzureFunctions.AngularClient/src/app/function/binding-input-v2/binding-input-v2.component.scss
AzureFunctions.AngularClient/src/app/function/binding-input-v2/binding-input-v2.component.ts
AzureFunctions.AngularClient/src/app/function/function-new/function-new.component.html
AzureFunctions.AngularClient/src/app/function/function-new/function-new.component.scss
AzureFunctions.AngularClient/src/app/function/function-new/function-new.component.ts
AzureFunctions.AngularClient/src/app/shared/models/binding-input.ts
AzureFunctions.AngularClient/src/sass/pages/_sidebar.scss
AzureFunctions/ResourcesPortal/Resources.resx

do not merge yet - will add the last few as they are solved :)
thurs 11/16
--------------
fixes #2040 
fixes #2041 
fixes #2052 
fixes #2053 
fixes #2056 
fixes #2059
fri 11/17
--------------
fixes #2054 
fixes #2055 
fixes #2057 
fixes #2067

create bug bash fixes

---

AzureFunctions.AngularClient/src/app/function/binding-input-v2/binding-input-v2.component.html
AzureFunctions.AngularClient/src/app/function/binding-input-v2/binding-input-v2.component.ts
AzureFunctions.AngularClient/src/app/function/extension-install-detail/extension-install-detail.component.html
AzureFunctions.AngularClient/src/app/function/extension-install-detail/extension-install-detail.component.ts
AzureFunctions.AngularClient/src/app/function/function-new-detail/function-new-detail.component.html
AzureFunctions.AngularClient/src/app/function/function-new-detail/function-new-detail.component.ts
AzureFunctions.AngularClient/src/app/function/function-new/function-new.component.html
AzureFunctions.AngularClient/src/app/function/function-new/function-new.component.scss
AzureFunctions.AngularClient/src/app/function/function-new/function-new.component.ts
AzureFunctions.AngularClient/src/app/function/sidebar-picker/sidebar-picker.component.html
AzureFunctions.AngularClient/src/app/function/sidebar-picker/sidebar-picker.component.ts
AzureFunctions.AngularClient/src/app/shared/models/template-picker.ts
AzureFunctions.AngularClient/src/app/side-nav/side-nav.component.ts

Improve create function accessibility 

---

AzureFunctions.AngularClient/src/app/site/site-config/app-settings/app-settings.component.html
AzureFunctions.AngularClient/src/app/site/site-config/connection-strings/connection-strings.component.html
AzureFunctions.AngularClient/src/app/site/site-config/default-documents/default-documents.component.html
AzureFunctions.AngularClient/src/app/site/site-config/general-settings/general-settings.component.html
AzureFunctions.AngularClient/src/app/site/site-config/handler-mappings/handler-mappings.component.html
AzureFunctions.AngularClient/src/app/site/site-config/virtual-directories/virtual-directories.component.html

Only show "autoSwapNotSupportedFromProd" infobox for production slot

---

AzureFunctions.AngularClient/src/app/function/binding-input-v2/binding-input-v2.component.ts

Dropdown immediately updates when new connection is created

---

AzureFunctions.AngularClient/src/app/function/sidebar-picker/sidebar-picker.component.ts

Fixing V2 template install option

---

AzureFunctions.AngularClient/src/app/function-dev/function-dev.component.html
AzureFunctions.AngularClient/src/app/function-dev/function-dev.component.ts
AzureFunctions.AngularClient/src/app/log-streaming/log-streaming.component.html
AzureFunctions.AngularClient/src/app/log-streaming/log-streaming.component.ts
AzureFunctions.AngularClient/src/app/site/function-runtime/function-runtime.component.html
AzureFunctions.AngularClient/src/image/warning.svg
AzureFunctions/ResourcesPortal/Resources.Designer.cs
AzureFunctions/ResourcesPortal/Resources.resx

RDBug 10653801
[Keyboard Navigation - Azure Function - Code View] 'View All', 'Add function', 'Expand\Collapse' buttons under "Function Apps" are not accessible using keyboard
RDBug 10643949
[Keyboard Navigation - Azure Function - Code View] Name and role of "Copy logs" control is not defined under "Funtion Apps" blade
RDBug 10641606 
[Screen Reader - Azure Function - Function App Settings] Alt text is not defined for images present in "Function App Settings" blade

Accessibility fixes

---

AzureFunctions.AngularClient/src/app/multi-drop-down/multi-drop-down.component.html
AzureFunctions.AngularClient/src/app/shared/models/portal-resources.ts
AzureFunctions.AngularClient/src/app/site/site-dashboard/site-dashboard.component.html
AzureFunctions.AngularClient/src/app/site/site-dashboard/site-dashboard.component.ts
AzureFunctions.AngularClient/src/app/site/site-dashboard/site-tab/site-tab.component.ts
AzureFunctions/ResourcesPortal/Resources.resx

There's 3 accessibility fixes here:
1. You can now select and pin an app with keyboard navigation.
2. A screen reader will now say "Combobox" when getting focus on a multiselect dropdown
3. A screen reader will now say if a site tab is selected

Accessibility fixes for pin app, site tabs, and multi-dropdown

---

AzureFunctions.AngularClient/src/app/api/api-details/api-details.component.html
AzureFunctions.AngularClient/src/app/api/api-details/api-details.component.ts
AzureFunctions.AngularClient/src/app/extension-install/extension-install.component.ts
AzureFunctions.AngularClient/src/app/function-keys/function-keys.component.ts
AzureFunctions.AngularClient/src/app/function/extension-install-detail/extension-install-detail.component.ts
AzureFunctions.AngularClient/src/app/shared/directives/fn-write-access.directive.ts
AzureFunctions.AngularClient/src/app/shared/models/constants.ts
AzureFunctions.AngularClient/src/app/shared/models/extension-install-status.ts
AzureFunctions.AngularClient/src/app/shared/models/portal-resources.ts
AzureFunctions.AngularClient/src/app/shared/services/function-app.service.ts
AzureFunctions.AngularClient/src/app/site/function-runtime/function-runtime.component.ts
AzureFunctions.AngularClient/src/app/site/site-dashboard/site-dashboard.component.ts

Closes #2186, Closes #2185, Closes #2184, Closes  #2183, Closes #2182, Closes #2177, Closes #2188
@agruning can you please take a look at the changes to install extension component in this commit f570ce4ac92d84f58a2db5825aa7af74d328bd94? I need to talk to you about some other issue in that component though. It seems that after installation is done, it just takes you back to the view listing extensions to be installed, but this time it's empty and nothing to do. I tried in master and it's doing the same thing. I'm not sure what it's supposed to do after an extension installation is done.

Fixes for issues found during OGF run due to my changes. 

---

AzureFunctions.AngularClient/src/app/download-function-app-content/download-function-app-content.component.html
AzureFunctions.AngularClient/src/app/radio-selector/radio-selector.component.html
AzureFunctions.AngularClient/src/app/radio-selector/radio-selector.component.ts

when download app contents click, radio buttons are auto focused
tested in chrome and edge
fixes http://vstfrd:8080/Azure/RD/_workitems?id=10622725&_a=edit&triage=true

download app contents radio button auto focused

---

AzureFunctions.AngularClient/src/app/pickers/event-hub/event-hub.component.ts
AzureFunctions.AngularClient/src/app/shared/services/cache.service.ts
AzureFunctions.AngularClient/src/app/shared/services/function-app.service.ts
AzureFunctions.AngularClient/src/app/site/swagger-definition/swagger-definition.component.ts

Closes #2209, Closes #2208, Closes #2210

Fixes for OGF pass issues

---

AzureFunctions.AngularClient/src/app/download-function-app-content/download-function-app-content.component.html
AzureFunctions.AngularClient/src/app/download-function-app-content/download-function-app-content.component.ts
AzureFunctions.AngularClient/src/app/radio-selector/radio-selector.component.ts

download function app component can be navigated using tabs/shift+tab, esc closes modal
fixes http://vstfrd:8080/Azure/RD/_workitems?id=10622676&_a=edit&triage=true

Download app keyboard nav

---

AzureFunctions.AngularClient/src/app/side-nav/side-nav.component.ts
AzureFunctions.AngularClient/src/app/tree-view/tree-view.component.html
AzureFunctions.AngularClient/src/app/tree-view/tree-view.component.scss
AzureFunctions.AngularClient/src/app/tree-view/tree-view.component.ts

Fixing the fact that you can't see menu items anymore using keyboard navigation, as well as changing the role to a button.

Fixes #1592 - [Accessibility] Screen reader does not read tree node options when in focus

---

AzureFunctions.AngularClient/src/app/function/embedded/temp-templates.ts
AzureFunctions.AngularClient/src/app/shared/services/arm-embedded.service.ts

Replace single quotes with double quotes, remove retrieve option, filter out web and slot requests

Minor embedded updates

---

AzureFunctions.AngularClient/src/app/getting-started/getting-started.component.ts

Updating redirect URL's to latest query string format.

Updating Ibiza redirect URL's

---

AzureFunctions.AngularClient/src/app/function-monitor/function-monitor.component.html
AzureFunctions.AngularClient/src/app/function-monitor/function-monitor.component.ts
AzureFunctions.AngularClient/src/app/shared/models/constants.ts
AzureFunctions.AngularClient/src/app/shared/services/portal.service.ts
AzureFunctions.AngularClient/src/app/shared/services/scenario/national-cloud.environment.ts

Hiding AI from the monitor tab in national clouds, as well as disabling MSI in the site manage component.

Minor fixes to disable some features that don't work in national clouds

---

AzureFunctions.AngularClient/src/app/shared/models/portal-resources.ts
AzureFunctions/ResourcesPortal/Resources.resx

Add durable resources

---

AzureFunctions.AngularClient/src/app/shared/models/arm/connection-strings.ts
AzureFunctions.AngularClient/src/app/site/site-config/connection-strings/connection-strings.component.ts

Stop showing invalid connection string types, except when already configured (fixes #2248)

---

AzureFunctions.AngularClient/src/app/function-keys/function-keys.component.html
AzureFunctions.AngularClient/src/app/function-keys/function-keys.component.ts

In the manage blade, when add key is pressed, auto focus on new input box
fixes http://vstfrd:8080/Azure/RD/_workitems?id=10654843&_a=edit&triage=true

manage blade, focus on input when adding key

---

AzureFunctions.AngularClient/src/app/function-dev/function-dev.component.html
AzureFunctions.AngularClient/src/app/function-dev/function-dev.component.ts

focus on combo box when get function url clicked
fixes http://vstfrd:8080/Azure/RD/_workitems?id=10655280&_a=edit&triage=true

focus on combo box when get function url clicked

---

AzureFunctions.AngularClient/src/app/function/embedded/temp-templates.ts
AzureFunctions.AngularClient/src/app/shared/models/binding.ts

syncTrigger is xrmwebhooktrigger

Update sync binding

---

AzureFunctions.AngularClient/src/app/shared/components/feature-component.ts
AzureFunctions.AngularClient/src/app/shared/models/arm/site-extension.ts
AzureFunctions.AngularClient/src/app/shared/services/site.service.ts
AzureFunctions.AngularClient/src/app/shared/services/telemetry.service.ts
AzureFunctions.AngularClient/src/app/site/site-enabled-features/site-enabled-features.component.ts
AzureFunctions.AngularClient/src/app/site/site-manage/site-manage.component.ts
AzureFunctions.AngularClient/src/app/site/site-summary/site-summary.component.ts

Moving to FeatureComponent simplifies a few things like busy state management and timer tracking.  Eventually I'd like to merge FeatureComponent in with ErrorableComponent to become the new base class.

Updating site summary and site manage tabs to inherit from FeatureComponent

---

AzureFunctions.AngularClient/src/app/function/embedded/embedded-function-editor/embedded-function-editor.component.scss

@ehamai these changes fix css grid for IE11. it seems to work fine. I'm however not sure if you wanna take that in your component. I am still not sure if I'll update the existing function-dev component. I feel that it's significantly harder to do so, but I'll see what I can do.

Support IE11 in EmbeddedFunctionEditor

---

AzureFunctions.AngularClient/src/app/function-dev/function-dev.component.html
AzureFunctions.AngularClient/src/app/function-dev/function-dev.component.scss
AzureFunctions.AngularClient/src/app/function-dev/function-dev.component.ts

fixes https://github.com/Azure/azure-functions-ux/issues/2375

fix custom domain name and wrapping

---

AzureFunctions.AngularClient/src/app/api/api-details/api-details.component.ts
AzureFunctions.AngularClient/src/app/api/api-new/api-new.component.ts
AzureFunctions.AngularClient/src/app/create-function-wrapper/create-function-wrapper.component.ts
AzureFunctions.AngularClient/src/app/function-dev/function-dev.component.ts
AzureFunctions.AngularClient/src/app/function-edit/function-edit.component.ts
AzureFunctions.AngularClient/src/app/function-integrate-v2/function-integrate-v2.component.ts
AzureFunctions.AngularClient/src/app/function-integrate/function-integrate.component.ts
AzureFunctions.AngularClient/src/app/function-manage/function-manage.component.ts
AzureFunctions.AngularClient/src/app/function-monitor/function-monitor.component.ts
AzureFunctions.AngularClient/src/app/functions-list/functions-list.component.ts
AzureFunctions.AngularClient/src/app/shared/components/base-function-component.ts
AzureFunctions.AngularClient/src/app/shared/components/feature-component.ts
AzureFunctions.AngularClient/src/app/shared/components/navigable-component.ts
AzureFunctions.AngularClient/src/app/site/site-dashboard/site-dashboard.component.ts
AzureFunctions.AngularClient/src/app/slot-new/slot-new.component.ts
AzureFunctions.AngularClient/src/app/slots-list/slots-list.component.ts

NavigableComponent now inherits from FeatureComponent.  The main benefits here are that we'll get performance tracking for each feature, as well as busy state management.
Later I'll also move FunctionAppContextComponent to inherit from it as well and merge ErrorableComponent into FeatureComponent.
One thing I have noticed, however, is that https://github.com/Azure/azure-functions-ux/issues/2352 appears to be causing the integrate dashboard to spin forever if you click too quickly.  I'm still looking to see why.

Updating NavigableComponent to inherit from FeatureComponent

---

AzureFunctions.AngularClient/src/app/site/site-enabled-features/site-enabled-features.component.ts

fixes https://github.com/Azure/azure-functions-ux/issues/2127
the bug is hard to reproduce, steps to repro bug:
- make new function app
- enable slots
- go to overview
- add a slot
- got to slot overview
- delete the slot
- add another slot
- go to slot overview
- repeat until bug occurs

remove duplicate Configured features links

---

AzureFunctions.AngularClient/src/app/function-quickstart/function-quickstart.component.html
AzureFunctions.AngularClient/src/app/function-quickstart/function-quickstart.component.ts

Hide F# and Java options and additional languages if in V2

Update v2 quickstart

---

AzureFunctions.AngularClient/src/app/table-function-monitor/table-function-monitor.component.html
AzureFunctions.AngularClient/src/app/table-function-monitor/table-function-monitor.component.ts

Add keyboard support for "refresh" button in the monitoring view.

Accessibility: add keyboard support for "refresh".

---

AzureFunctions.AngularClient/src/app/api/api-details/api-details.component.html
AzureFunctions.AngularClient/src/app/api/api-details/api-details.component.ts
AzureFunctions.AngularClient/src/app/api/api-new/api-new.component.html
AzureFunctions.AngularClient/src/app/api/api-new/api-new.component.scss
AzureFunctions.AngularClient/src/app/api/api-new/api-new.component.ts
AzureFunctions.AngularClient/src/app/api/request-respose-override/request-respose-override.component.html
AzureFunctions.AngularClient/src/app/api/request-respose-override/request-respose-override.component.scss
AzureFunctions.AngularClient/src/app/controls/pair-list/pair-list.component.html
AzureFunctions.AngularClient/src/app/controls/pair-list/pair-list.component.scss
AzureFunctions.AngularClient/src/app/controls/pair-list/pair-list.component.ts
AzureFunctions.AngularClient/src/app/pop-over/pop-over.component.scss
AzureFunctions.AngularClient/src/app/proxies-list/proxies-list.component.html
AzureFunctions.AngularClient/src/app/proxies-list/proxies-list.component.ts
AzureFunctions.AngularClient/src/app/proxies.module.ts
AzureFunctions.AngularClient/src/app/run-http/run-http.component.scss
AzureFunctions.AngularClient/src/app/tree-view/proxies-node.ts

Cleaning up the proxies create/edit UI:
- make inputs a little skinnier
- make commands consistent
- align spacing between inputs
- load the proxies list page on deletion

Clean up the proxies create/edit UI

---

AzureFunctions.AngularClient/src/app/table-function-monitor/table-function-monitor.component.html
AzureFunctions.AngularClient/src/app/table-function-monitor/table-function-monitor.component.ts

Enable keyboard navigation on invocation logs row.

Enable keyboard navigation on invocation logs row.

---

AzureFunctions.AngularClient/src/app/shared/models/constants.ts
AzureFunctions.AngularClient/src/app/shared/services/function-app.service.ts
AzureFunctions.AngularClient/src/app/shared/services/scenario/national-cloud.environment.ts
AzureFunctions.AngularClient/src/app/site/site-manage/site-manage.component.ts

2 bug fixes:
1. Logic apps will no longer show up in national clouds
2. We'll now clear the cache whenever you delete a function

Fixes #2256 and Fixes #2432 - Logic apps in national clouds and delete function bugs

---

AzureFunctions.AngularClient/src/app/drop-down/drop-down.component.scss
AzureFunctions.AngularClient/src/app/function/binding-input-v2/binding-input-v2.component.html
AzureFunctions.AngularClient/src/app/function/binding-input-v2/binding-input-v2.component.ts
AzureFunctions.AngularClient/src/app/function/function-new/function-new.component.scss
AzureFunctions.AngularClient/src/app/search-box/search-box.component.scss

Fixes #2504, #2429, #2415, and #2508

Search and drop down updates

---

AzureFunctions.AngularClient/src/app/function-quickstart/function-quickstart.component.html
AzureFunctions.AngularClient/src/app/function-quickstart/function-quickstart.component.ts
AzureFunctions.AngularClient/src/app/function/extension-checker/extension-checker.component.html
AzureFunctions.AngularClient/src/app/function/extension-checker/extension-checker.component.ts
AzureFunctions.AngularClient/src/app/function/function-new-detail/function-new-detail.component.html
AzureFunctions.AngularClient/src/app/function/function-new-detail/function-new-detail.component.ts
AzureFunctions.AngularClient/src/app/function/function-new/function-new.component.html
AzureFunctions.AngularClient/src/app/function/function-new/function-new.component.scss
AzureFunctions.AngularClient/src/app/function/function-new/function-new.component.ts
AzureFunctions.AngularClient/src/app/shared/models/constants.ts

If FUNCTIONS_LANGUAGE is set, only allow users to create functions of that language. Remove function language options from card footer and remove drop-down language option from create sidebar.
Also update quickstart page:

Function App Language - Create Functions

---

AzureFunctions.AngularClient/src/app/shared/models/constants.ts
AzureFunctions.AngularClient/src/app/shared/services/scenario/onprem.environment.ts
AzureFunctions.AngularClient/src/app/shared/services/scenario/stand-alone.environment.ts
AzureFunctions.AngularClient/src/app/tree-view/function-node.ts

AppInsight ARM call failure was responsible for broken monitoring page. disabled appinsights for onprem

RDBug 11793486:[U2] [FunctionsPortal] Function Monitor page is blank

---

AzureFunctions.AngularClient/src/app/function/function-new/function-new.component.html
AzureFunctions.AngularClient/src/app/function/function-new/function-new.component.ts

Remove language dropdown for create and populate scenario dropdown

Single language dropdown updates

---

AzureFunctions.AngularClient/package.json
AzureFunctions.AngularClient/src/sass/controls/_ng-selector.scss
AzureFunctions.AngularClient/yarn.lock

This version has my narrator accessibility changes. It also changes how placeholder values are hidden requiring a new css class behavior to hide it

Updating to latest version of ng-select

---

AzureFunctions.AngularClient/src/app/function-monitor/function-monitor.component.ts
AzureFunctions.AngularClient/src/app/shared/models/portal-resources.ts
AzureFunctions/ResourcesPortal/Resources.resx

Before (the UI just hangs at 'Loading...'):
After:

Monitoring fix to show error on UI if host call fails

---

client/src/app/function/extension-checker/extension-checker.component.html
client/src/app/function/extension-checker/extension-checker.component.ts
client/src/app/function/function-new/function-new.component.html

Pass context for create

---

client/src/app/aad-registration/aad-registration.component.ts
server/gulpfile.js

* Hotfix for set model after token loads
* update v1 version number

Master -> dev Hotfix for set model after token loads

---

client/tslint.json
tslint.json

This will make it blocked by codacy

add lodash to blacklisted imports

---

client/src/app/table-function-monitor/table-function-monitor.pipe.ts

hotfix: fix moment library

---

client/src/app/shared/services/authz.service.ts

Fix Slot Locks

---

client/src/app/function-monitor/function-monitor.component.ts
client/src/app/function-monitor/monitor-applicationinsights/monitor-applicationinsights.component.ts
client/src/app/function-monitor/monitor-classic/monitor-classic.component.html
client/src/app/function-monitor/monitor-classic/monitor-classic.component.ts
client/src/app/shared/models/constants.ts
client/src/app/shared/models/function-monitor.ts
client/src/app/shared/resourceDescriptors.ts
client/src/app/shared/services/application-insights.service.ts
client/src/app/shared/services/scenario/azure.environment.ts
client/src/app/shared/services/scenario/national-cloud.environment.ts
client/src/app/shared/services/scenario/onprem.environment.ts
client/src/app/shared/services/scenario/stand-alone.environment.ts

Thanks @exc3eed  for pointing this out 😃

Update the scenario status for all environments for AI based monitoring.

---

client/src/app/function-monitor/function-monitor.component.scss
client/src/app/function-monitor/monitor-applicationinsights/monitor-applicationinsights.component.html
client/src/app/function-monitor/monitor-applicationinsights/monitor-applicationinsights.component.scss
client/src/app/function-monitor/monitor-applicationinsights/monitor-applicationinsights.component.ts
client/src/app/function-monitor/monitor-details/monitor-details.component.scss
client/src/image/open-external.svg
client/src/sass/common/_variables.scss

Hover
Selected
Info Box / success/error icons

Fix up some acessibility items and dark theme items.

---

client/src/app/function/extension-checker/extension-checker.component.ts

handle busy error

---

client/src/app/function-monitor/monitor-applicationinsights/monitor-applicationinsights.component.html
client/src/app/shared/services/application-insights.service.ts

Also this allows the date to be sortable :)

Make the datetime more granular and add sorting capability.

---

client/src/app/function-monitor/function-monitor.component.ts
client/src/app/function-monitor/monitor-applicationinsights/monitor-applicationinsights.component.html
client/src/app/function-monitor/monitor-configure/monitor-configure.component.html
client/src/app/function-monitor/monitor-configure/monitor-configure.component.ts
client/src/app/shared/models/portal-resources.ts
client/src/sass/controls/_tbl.scss
server/Resources/Resources.resx

fix table styling
Linux Function App configure page
@btardif can I please get the forward links?

Fix the table styling, delay message, and linux function configuration page

---

server/Resources/Resources.resx

@mhoeger let me know if you think is more clear

Update extension install message

---

client/src/app/function-monitor/monitor-details/monitor-details.component.html
client/src/app/function-monitor/monitor-details/monitor-details.component.scss
client/src/app/function-monitor/monitor-details/monitor-details.component.ts

Add a close button on top right. This aligns with some of the other slide outs with the close buttons.

---

client/src/app/function-monitor/monitor-applicationinsights/monitor-applicationinsights.component.html
client/src/app/function-monitor/monitor-applicationinsights/monitor-applicationinsights.component.ts
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

Indicate number of results returned in query and provide a link to open in the AI query editor.

Move application insights link to essentials col

---

client/src/app/log-streaming/log-streaming.component.scss

Expand the logs pre tag.

---

client/src/app/shared/models/arm/site-config.ts
client/src/app/shared/models/portal-resources.ts
client/src/app/site/site-config/general-settings/general-settings.component.html
client/src/app/site/site-config/general-settings/general-settings.component.ts
server/Resources/Resources.resx

@btardif fixes [RDTask 1215339](http://vstfrd:8080/Azure/RD/_workitems/edit/12153391)

HTTP 2 toggle

---

client/src/app/shared/models/constants.ts
client/src/app/shared/services/scenario/national-cloud.environment.ts
client/src/app/site/site-config/general-settings/general-settings.component.ts

Hide HTTP 2 switch in national clouds

---

client/src/app/function-dev/function-dev.component.scss

Current behavior with minimized screen..
New behavior with minimized screen...
adds a scroll bar which allows one to scroll down to the run button on the bottom

Update CSS to work with smaller screen sizes. fixes #2709

---

client/src/app/pickers/microsoft-graph/microsoft-graph-helper.ts

Fixes https://github.com/Azure/azure-functions-templates/issues/686

Adding oauth2AllowImplicitFlow for MsGraph Aad Permissions set up

---

client/src/app/shared/models/portal-resources.ts
client/src/app/site/function-runtime/function-runtime.component.html
client/src/app/site/function-runtime/function-runtime.component.ts
server/Resources/Resources.resx

Add Unsupported Runtime Version Warning

---

client/src/app/site/function-runtime/function-runtime.component.ts

Propagate App Edit Mode

---

client/src/app/shared/models/arm/site.ts
client/src/app/shared/models/constants.ts
client/src/app/shared/models/portal-resources.ts
client/src/app/shared/services/scenario/scenario.service.ts
client/src/app/shared/services/scenario/xenon-site.environment.ts
client/src/app/site/site-config/general-settings/general-settings.component.ts
server/Resources/Resources.resx

RDBug 12687146:[Xenon] Disable options in settings blade that are not applicable for Xenon

RDBug 12687146:[Xenon] Disable options in settings blade that are not applicable for Xenon

---

client/karma.conf.js
client/package-lock.json
client/package.json
client/src/app/site/spec-picker/spec-list/spec-list.component.spec.ts

Forgot to include these in my last merge to dev.

Add spec-list test changes.

---

client/src/app/function-dev/function-dev.component.ts
client/src/app/function-quickstart/function-quickstart.component.ts
client/src/app/function/function-new-detail/function-new-detail.component.ts
client/src/app/shared/models/constants.ts
client/src/app/shared/models/portal-resources.ts
client/src/app/shared/services/cache.service.ts
client/src/app/shared/services/function-app.service.ts
client/src/app/shared/url-templates.ts
client/src/app/try-landing/try-landing.component.ts

Call restart for linux apps on code change

Use runtime masterKey for Linux Dynamic

---

client/src/app/function-quickstart/function-quickstart.component.html
client/src/app/function-quickstart/function-quickstart.component.ts

Java in v2 quickstart

---

server/Resources/Resources.resx

fixes [RDTask 12808878](http://vstfrd:8080/Azure/RD/_workitems/edit/12808878)

remove preview from MSI

---

client/src/app/shared/models/application-insights.ts
client/src/app/shared/services/application-insights.service.ts

For a function with errors being logged:
**Before**
**After**

update query to show exceptions

---

client/src/app/function-quickstart/function-quickstart.component.html

Disable Quickstart in Read-only

---

client/src/app/controls/table-cell/table-cell.component.scss
client/src/app/radio-selector/radio-selector.component.html
client/src/app/radio-selector/radio-selector.component.scss
client/src/app/radio-selector/radio-selector.component.ts
client/src/app/shared/models/portal-resources.ts
client/src/app/site/site-config/app-settings/app-settings.component.html
client/src/app/site/site-config/connection-strings/connection-strings.component.html
client/src/app/site/site-config/default-documents/default-documents.component.html
client/src/app/site/site-config/handler-mappings/handler-mappings.component.html
client/src/app/site/site-config/site-config.component.scss
client/src/app/site/site-config/virtual-directories/virtual-directories.component.html
client/src/app/site/site-config/virtual-directories/virtual-directories.component.ts
server/Resources/Resources.resx

Adding headers to grids in App Settings blade (fixes #2463)

---

client/src/app/shared/services/scenario/national-cloud.environment.ts

Remove event grid template from national clouds

---

client/src/app/site/site-manage/site-manage.component.ts

Fix feature group bug

---

client/src/app/binding-input/binding-input.component.html
client/src/app/binding-input/binding-input.component.ts
client/src/app/function/binding-input-v2/binding-input-v2.component.html
client/src/app/function/binding-input-v2/binding-input-v2.component.ts
client/src/app/functions.module.ts
client/src/app/pickers/cosmos-db/cosmos-db.component.html
client/src/app/pickers/cosmos-db/cosmos-db.component.ts
client/src/app/pickers/picker.scss
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

@btardif fixes[ RDBug 12510066](http://vstfrd:8080/Azure/RD/_workitems?id=12510066&_a=edit)

Remove getAllSubscriptions from DocDbPickerPart

---

client/src/app/shared/models/constants.ts

change node to nodejs

---

client/src/app/site/console/bash/bash.component.html
client/src/app/site/console/cmd/cmd.component.html
client/src/app/site/console/console.component.scss
client/src/app/site/console/powershell/powershell.component.html

fixes #2926

---

client/src/app/download-function-app-content/download-function-app-content.component.ts
client/src/app/shared/Utilities/file.ts

Fix download for Edge browser

---

client/src/app/site/function-runtime/function-runtime.component.ts

Add more checks for valid runtime version

---

client/src/app/binding-input/binding-input.component.html
client/src/app/binding-input/binding-input.component.ts
client/src/app/function/binding-input-v2/binding-input-v2.component.html
client/src/app/function/binding-input-v2/binding-input-v2.component.ts
client/src/app/shared/models/constants.ts

Picker names constants

---

server/Resources/Resources.resx

WebJobs string

---

client/src/app/function/function-new/function-new.component.ts
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

fixes #2711 
@fashaikh can you confirm site cert has been issued?

Community templates

---

client/src/app/function-console/function-console.component.ts
client/src/app/site/console/bash/bash.component.ts
client/src/app/site/console/shared/components/abstract.console.component.ts
client/src/app/site/console/shared/components/abstract.windows.component.ts

According to previous comments

Code refactored

---

client/src/app/shared/models/error-ids.ts
client/src/app/shared/models/portal-resources.ts
client/src/app/site/site-summary/site-summary.component.ts
client/src/app/tree-view/base-functions-proxies-node.ts
server/Resources/Resources.resx

Add scm site checks

---

client/src/app/error-list/error-list.component.ts
client/src/app/shared/models/error-event.ts
client/src/app/shared/models/portal-resources.ts
client/src/app/site/site-summary/site-summary.component.ts
server/Resources/Resources.resx

Update Azure Files error string, add hrefs to error events

---

client/src/app/function/function-new/function-new.component.ts

This reverts commit 599c9bd7c862d9f79a4a30165fc7d52fe96f16d1.

Revert "Community templates (#2980)"

---

client/src/app/shared/models/constants.ts
client/src/app/site/site-summary/site-summary.component.ts

Func storage learn more link

---

client/src/app/function/extension-checker/extension-checker.component.html
client/src/app/function/extension-checker/extension-checker.component.scss
client/src/app/function/extension-checker/extension-checker.component.ts
client/src/app/shared/models/constants.ts
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

Add extension installation documentation link

---

client/src/app/site/spec-picker/price-spec-manager/price-spec-group.ts
client/src/app/site/spec-picker/spec-picker.component.html
client/src/app/site/spec-picker/spec-picker.component.ts
server/Resources/Resources.resx

…… (#2984)
* update banner message and provide a forward link to the blog post (#2978)
* Trigger another build

S95 Deployment: Master -> Dev

---

client/src/app/function-monitor/monitor-details/monitor-details.component.html
client/src/sass/pages/_sidebar.scss

inlcude the datetime for monitor details

---

client/src/app/shared/services/function-app.service.ts

Fixes #3029 
Re: #2791 
This should be reverted once dotnet sdk is available

[Linux]: Filter out templates and bindings that require extensions

---

client/src/app/function/extension-checker/extension-checker.component.html
client/src/app/function/extension-checker/extension-checker.component.ts
client/src/app/shared/models/error-ids.ts
client/src/app/shared/models/host-status.ts
client/src/app/shared/models/portal-resources.ts
client/src/app/shared/services/function-app.service.ts
client/src/app/shared/url-templates.ts

Take host offline for extension installation

---

server/Resources/Resources.resx

Update run from zip readonly string

---

client/src/app/edit-mode-warning/edit-mode-warning.component.html
client/src/app/edit-mode-warning/edit-mode-warning.component.ts
client/src/app/shared/Utilities/arm-utils.ts
client/src/app/shared/Utilities/edit-mode.helper.ts
client/src/app/shared/models/function-app-edit-mode.ts
client/src/app/shared/models/portal-resources.ts
client/src/app/shared/services/function-app.service.ts
server/Resources/Resources.resx

Make BYOC function apps readonly

---

client/src/app/site/deployment-center/deployment-center-setup/wizard-logic/deployment-center-state-manager.ts
client/src/app/site/deployment-center/provider-dashboards/vso-Dashboard/vso-dashboard.component.ts

This is what is needed in order for VSTS to not break after wednesday

[DO NOT MERGE UNTIL the 9th] Vsts imrovements hotfix

---

client/src/app/shared/services/arm.service.ts

handle relese environment

---

client/src/app/function-edit/function-edit.component.ts
client/src/app/function-quickstart/function-quickstart.component.html
client/src/app/function-quickstart/function-quickstart.component.ts
client/src/app/site/function-runtime/function-runtime.component.ts

- Change ~2 (preview) to ~2
- Remove "pre-release" banner in functions editor
- fixes #3126 
- fixes #3125

Remove preview, V2 updates

---

server/src/actions/quickstart/coretoolsDeploymentCenter.md
server/src/actions/quickstart/coretoolsDirectPublish.md
server/src/actions/quickstart/mavenDeploymentCenter.md
server/src/actions/quickstart/mavenDirectPublish.md
server/src/actions/quickstart/vsDeploymentCenter.md
server/src/actions/quickstart/vsDirectPublish.md
server/src/actions/quickstart/vscodeDeploymentCenter.md
server/src/actions/quickstart/vscodeDirectPublish.md

Making adjustments to quickstart styling, including larger headers and spacing between sections.

Quickstart styling

---

client/src/app/site/container-settings/container-settings-manager.ts

Make login, password, and startup not required for private registry.

---

client/src/app/shared/models/constants.ts
client/src/app/site/container-settings/container-image-source/container-image-source-quickstart/container-image-source-quickstart.component.ts
client/src/app/site/container-settings/container-settings-manager.ts
client/src/app/site/container-settings/container-settings.ts
client/src/app/site/container-settings/services/container-samples.service.ts
server/Resources/Resources.resx

fixes #3162 
Also adds the capability to specific source URL for samples.

update quickstart samples

---

client/src/app/function/extension-checker/extension-checker.component.html
client/src/app/function/extension-checker/extension-checker.component.scss
client/src/app/function/function-new-detail/function-new-detail.component.html
client/src/app/function/function-new-detail/function-new-detail.component.scss
client/src/app/function/function-new/function-new.component.html
client/src/app/function/function-new/function-new.component.scss
client/src/app/function/function-new/function-new.component.ts
client/src/app/functions-list/functions-list.component.ts
client/src/app/site/deployment-center/deployment-center-setup/step-build-provider/step-build-provider.component.html
client/src/app/site/deployment-center/deployment-center-setup/step-source-control/step-source-control.component.html
client/src/app/site/deployment-center/deployment-center-setup/step-source-control/step-source-control.component.scss
client/src/app/site/quickstart/quickstart.component.scss
client/src/app/site/quickstart/step-choose-deployment-method/step-choose-deployment-method.component.html
client/src/app/site/quickstart/step-choose-dev-environment/step-choose-dev-environment.component.html
client/src/app/site/quickstart/step-create-portal-function/step-create-portal-function.component.html
client/src/sass/common/_variables.scss

Update cards to fluent styling

---

client/src/app/shared/models/constants.ts
client/src/app/site/site-config/general-settings/general-settings.component.html
client/src/app/site/site-config/general-settings/general-settings.component.ts
server/Resources/Resources.resx

Set attribute target="_blank" on 'Learn More' links for 'Stack' and 'Startup File' in Application Settings blade.

---

client/src/app/shared/models/arm/slots-diff.ts
client/src/app/shared/models/portal-resources.ts
client/src/app/shared/services/site.service.ts
client/src/app/site/deployment-slots/add-slot/add-slot.component.html
client/src/app/site/deployment-slots/add-slot/add-slot.component.ts
client/src/app/site/deployment-slots/common.scss
client/src/app/site/deployment-slots/deployment-slots.component.html
client/src/app/site/deployment-slots/deployment-slots.component.ts
client/src/app/site/deployment-slots/deployment-slots.module.ts
client/src/app/site/deployment-slots/swap-slots/swap-diff-table/swap-diff-table.component.html
client/src/app/site/deployment-slots/swap-slots/swap-diff-table/swap-diff-table.component.ts
client/src/app/site/deployment-slots/swap-slots/swap-slots.component.html
client/src/app/site/deployment-slots/swap-slots/swap-slots.component.scss
client/src/app/site/deployment-slots/swap-slots/swap-slots.component.ts
client/src/image/close.svg
client/src/sass/common/_variables.scss
server/Resources/Resources.resx

Making multi-phase swap less confusing in new slots experience

---

client/src/app/shared/models/portal-resources.ts
client/src/app/site/quickstart/quickstart.component.ts
client/src/app/site/quickstart/step-choose-deployment-method/step-choose-deployment-method.component.ts
client/src/app/site/quickstart/step-choose-dev-environment/step-choose-dev-environment.component.ts
client/src/app/site/quickstart/step-create-function-instructions/step-create-function-instructions.component.html
client/src/app/site/quickstart/step-create-function-instructions/step-create-function-instructions.component.ts
client/src/app/site/quickstart/step-create-function/step-create-function.component.ts
client/src/app/site/quickstart/step-create-portal-function/step-create-portal-function.component.ts
client/src/app/site/quickstart/wizard-logic/quickstart-models.ts
client/src/app/site/quickstart/wizard-logic/quickstart-state-manager.ts
server/Resources/Resources.resx

- No portal development option for linux consumption
- Update quickstart enter string
- Update finish button to include "go to deployment center" when valid
- String replacements for placeholders
- clean-up code

Quickstart Fit-and-Finish

---

client/src/app/edit-mode-warning/edit-mode-warning.component.html
client/src/app/edit-mode-warning/edit-mode-warning.component.ts
client/src/app/shared/Utilities/arm-utils.ts
client/src/app/shared/Utilities/edit-mode.helper.ts
client/src/app/shared/models/function-app-edit-mode.ts
client/src/app/shared/models/portal-resources.ts
client/src/app/shared/services/function-app.service.ts

Remove BYOC check since it is throwing false positives

Remove BYOC Readonly

---

client/src/app/site/function-runtime/function-runtime.component.html
client/src/app/site/function-runtime/function-runtime.component.ts

Don't disable Runtime toggle for edge cases

---

client/src/app/shared/models/portal-resources.ts
client/src/app/site/container-settings/container-configure/container-configure.component.html
client/src/app/site/container-settings/container-configure/container-configure.component.scss
client/src/app/site/container-settings/container-image-source/container-continuous-delivery/container-continuos-delivery.component.html
client/src/app/site/container-settings/container-image-source/container-continuous-delivery/container-continuos-delivery.component.ts
client/src/app/site/container-settings/container-image-source/container-image-source-acr/container-image-source-acr.component.html
client/src/app/site/container-settings/container-image-source/container-image-source-dockerhub/container-image-source-dockerhub.component.html
client/src/app/site/container-settings/container-image-source/container-image-source-privateregistry/container-image-source-privateregistry.component.html
client/src/app/site/container-settings/container-image-source/container-image-source-quickstart/container-image-source-quickstart.component.html
client/src/app/site/container-settings/container-image-source/container-image-source-quickstart/container-image-source-quickstart.component.scss
client/src/app/site/container-settings/container-image-source/container-image-source.component.html
client/src/app/site/container-settings/container-image-source/container-image-source.component.scss
client/src/app/site/container-settings/container-image-source/container-logs/container-logs.component.html
client/src/app/site/container-settings/container-settings.component.scss
client/src/app/site/container-settings/container-settings.ts
server/Resources/Resources.resx

fixes:
#3177 
#3175 
#3174 
#3131 
#3176 
#3178

fit and finish changes

---

client/src/app/site/container-settings/container-image-source/container-image-source-acr/container-image-source-acr.component.ts
client/src/app/site/container-settings/container-settings-manager.ts

Update forms to load default values only for the selected branch

---

client/src/app/site/site-config/general-settings/general-settings.component.ts

Updating GeneralSettingsComponent to never show "Runtime" section for Linux function apps

---

client/src/app/function/function-new/function-new.component.ts
client/src/app/site/quickstart/quickstart.component.ts

Runtime string updates

---

client/src/app/shared/models/constants.ts
client/src/app/shared/services/function-app.service.ts

Update read-only check for run from package

---

client/src/app/function-dev/function-dev.component.ts

New Event Grid create blade

---

client/src/app/error-list/error-list.component.css

Wrap error text

---

client/src/app/function/function-new-detail/function-new-detail.component.ts
client/src/app/function/function-new/function-new.component.ts
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx
server/Resources/cs-CZ/Server/Resources/Resources.resx
server/Resources/de-DE/Server/Resources/Resources.resx
server/Resources/es-ES/Server/Resources/Resources.resx
server/Resources/fr-FR/Server/Resources/Resources.resx
server/Resources/hu-HU/Server/Resources/Resources.resx
server/Resources/it-IT/Server/Resources/Resources.resx
server/Resources/ja-JP/Server/Resources/Resources.resx
server/Resources/ko-KR/Server/Resources/Resources.resx
server/Resources/nl-NL/Server/Resources/Resources.resx
server/Resources/pl-PL/Server/Resources/Resources.resx
server/Resources/pt-BR/Server/Resources/Resources.resx
server/Resources/pt-PT/Server/Resources/Resources.resx
server/Resources/qps-ploc/Server/Resources/Resources.resx
server/Resources/ru-RU/Server/Resources/Resources.resx
server/Resources/sv-SE/Server/Resources/Resources.resx
server/Resources/tr-TR/Server/Resources/Resources.resx
server/Resources/zh-CN/Server/Resources/Resources.resx
server/Resources/zh-TW/Server/Resources/Resources.resx
server/src/actions/resources.en.json

`functionNew_functionExsists` -> `functionNew_functionExists`

 Fix typo in resource key functionNew_functionExists

---

client/src/app/shared/models/portal-resources.ts
client/src/app/site/container-settings/container-image-source/container-image-source-quickstart/container-image-source-quickstart.component.html
client/src/app/site/container-settings/container-image-source/container-image-source-quickstart/container-image-source-quickstart.component.ts
client/src/app/site/container-settings/container-image-source/container-logs/container-logs.component.scss
client/src/app/site/container-settings/container-image-source/container-logs/container-logs.component.ts
client/src/app/site/container-settings/container-settings.ts
client/src/app/site/container-settings/services/container-samples.service.ts
server/Resources/Resources.resx

- Update existing samples
- Add new samples
- Add learn more link for each sample
- Organize the sample strings and configs a little better
- Update the height of the buttons so they do not get cut off in the container settings page

Update single container and multicontainer samples

---

client/src/app/controls/click-to-edit/click-to-edit.component.html
client/src/app/controls/click-to-edit/click-to-edit.component.ts
client/src/app/shared/models/portal-resources.ts
client/src/app/site/site-config/app-settings/app-settings.component.html
client/src/app/site/site-config/app-settings/app-settings.component.ts
client/src/app/site/site-config/connection-strings/connection-strings.component.html
client/src/app/site/site-config/connection-strings/connection-strings.component.ts
client/src/app/site/site-config/site-config.component.scss
server/Resources/Resources.resx

Add radio control for masking/displaying app setting and connection string values

---

client/src/app/controls/textbox/textbox.component.ts

This allows form state to be set to either dirty or pristine depending on the value changes.

Persist original value on the text box if a control is used.

---

client/src/app/site/spec-picker/price-spec-manager/plan-price-spec-manager.ts

(https://msazure.visualstudio.com/Antares/_workitems/edit/3122200)

Premium v2 vms are not available, the ux should show expanded view for show additional options

---

client/src/app/site/site-config/app-settings/app-settings.component.html
client/src/app/site/site-config/connection-strings/connection-strings.component.html

Updating app settings and connection strings tables so placeholder row spans all columns

---

client/src/app/controls/textbox/textbox.component.html
client/src/app/controls/textbox/textbox.component.ts
client/src/app/site/container-settings/container-image-source/container-image-source-acr/container-image-source-acr.component.html
client/src/app/site/container-settings/container-image-source/container-image-source-dockerhub/container-image-source-dockerhub.component.html
client/src/app/site/container-settings/container-image-source/container-image-source-privateregistry/container-image-source-privateregistry.component.html
client/src/app/site/container-settings/container-settings-manager.ts

https://msazure.visualstudio.com/Antares/_workitems/edit/3156644
Before
After

Show same required indicator for all inputs

---

client/src/app/controls/group-tabs/group-tabs.component.html
client/src/app/controls/group-tabs/group-tabs.component.ts
client/src/app/shared/shared.module.ts
client/src/app/site/container-settings/container-settings.module.ts
client/src/app/site/spec-picker/spec-picker.component.html
client/src/app/site/spec-picker/spec-picker.component.spec.ts
client/src/app/site/spec-picker/spec-picker.component.ts
client/src/app/site/spec-picker/spec-picker.module.ts

Resolves following:
https://msazure.visualstudio.com/Antares/_workitems/edit/3158544
https://msazure.visualstudio.com/Antares/_workitems/edit/3118155

Switch spec picker tabs to the group tab control.

---

client/src/app/shared/models/constants.ts
client/src/app/shared/models/portal-resources.ts
client/src/app/shared/resourceDescriptors.ts
client/src/app/site/spec-picker/price-spec-manager/basic-plan-price-spec.ts
client/src/app/site/spec-picker/price-spec-manager/elastic-premium-plan-price-spec.ts
client/src/app/site/spec-picker/price-spec-manager/free-plan-price-spec.ts
client/src/app/site/spec-picker/price-spec-manager/isolated-plan-price-spec.ts
client/src/app/site/spec-picker/price-spec-manager/plan-price-spec-manager.ts
client/src/app/site/spec-picker/price-spec-manager/premium-container-plan-price-spec.ts
client/src/app/site/spec-picker/price-spec-manager/premium-plan-price-spec.ts
client/src/app/site/spec-picker/price-spec-manager/premiumv2-plan-price-spec.ts
client/src/app/site/spec-picker/price-spec-manager/price-spec-manager.spec.ts
client/src/app/site/spec-picker/price-spec-manager/price-spec.ts
client/src/app/site/spec-picker/price-spec-manager/shared-plan-price-spec.ts
client/src/app/site/spec-picker/price-spec-manager/standard-plan-price-spec.ts
client/src/app/site/spec-picker/spec-picker.component.html
client/src/app/site/spec-picker/spec-picker.component.scss
client/src/app/site/spec-picker/spec-picker.component.spec.ts
client/src/app/site/spec-picker/spec-picker.component.ts
server/Resources/Resources.resx

(https://msazure.visualstudio.com/Antares/_workitems/edit/3182667)

Show warning for potential IP address changes when scaling to and from Pv2

---

client/src/app/site/spec-picker/price-spec-manager/basic-plan-price-spec.ts
client/src/app/site/spec-picker/price-spec-manager/dV2series-price-spec.ts
client/src/app/site/spec-picker/price-spec-manager/elastic-premium-plan-price-spec.ts
client/src/app/site/spec-picker/price-spec-manager/free-plan-price-spec.ts
client/src/app/site/spec-picker/price-spec-manager/isolated-plan-price-spec.ts
client/src/app/site/spec-picker/price-spec-manager/plan-price-spec-manager.ts
client/src/app/site/spec-picker/price-spec-manager/premium-plan-price-spec.ts
client/src/app/site/spec-picker/price-spec-manager/premiumv2-plan-price-spec.ts
client/src/app/site/spec-picker/price-spec-manager/price-spec-manager.spec.ts
client/src/app/site/spec-picker/price-spec-manager/price-spec.ts
client/src/app/site/spec-picker/price-spec-manager/shared-plan-price-spec.ts
client/src/app/site/spec-picker/price-spec-manager/standard-plan-price-spec.ts
client/src/app/site/spec-picker/spec-picker-shell/spec-picker-shell.component.ts
client/src/app/site/spec-picker/spec-picker.component.spec.ts
client/src/app/site/spec-picker/spec-picker.component.ts

(https://msazure.visualstudio.com/Antares/_workitems/edit/3188712)

Select the spec passed into spec picker as initial selection for pv2 upsell

---

client/src/app/shared/models/portal-resources.ts
client/src/app/site/swagger-definition/swagger-definition.component.html
server/Resources/Resources.resx

Fixes: TASK 3198100 Remove "beta" from V2
https://msazure.visualstudio.com/Antares/_workitems/edit/3198100

Change beta to V2

---

client/src/app/controls/group-tabs/group-tabs.component.html
client/src/app/controls/group-tabs/group-tabs.component.ts
client/src/app/shared/models/portal-resources.ts
client/src/app/site/container-settings/container-settings.ts
server/Resources/Resources.resx

Spec Picker:
Container Settings:

Include description for grouptabs.

---

client/src/app/site/site-manage/site-manage.component.ts

(https://msazure.visualstudio.com/Antares/_workitems/edit/3122211)

Tags should open as context pane since leaf blade

---

client/src/app/shared/models/arm/stacks.ts
client/src/app/shared/services/plan.service.ts
client/src/app/shared/services/site.service.ts
client/src/app/site/deployment-center/deployment-center-setup/step-configure/configure-vsts-build/linux-frameworks/linux-frameworks.component.ts
client/src/app/site/site-config/general-settings/general-settings.component.ts
client/src/app/site/spec-picker/price-spec-manager/plan-price-spec-manager.ts

Make changes to make sure we're passing in the Linux os flag to the getBillingMeters API call.  Also change to use SKU code to find meters instead of friendly  name.

Fix issue Pricing tier issue where Linux price is not accurate

---

client/src/app/shared/models/portal-resources.ts
client/src/app/tree-view/functions-node.ts
client/src/app/tree-view/proxies-node.ts
server/Resources/Resources.resx

(https://msazure.visualstudio.com/Antares/_workitems/edit/3122233)

Hide create proxy when readonly

---

client/src/app/site/function-runtime/function-runtime.component.html
client/src/app/slot-new/slot-new.component.ts

Fixes https://msazure.visualstudio.com/Antares/_workitems/edit/3122182

Enable slots in V2 by default

---

client-react/src/models/portal-models.ts
client-react/src/portal-communicator.ts
client-react/src/utils/BillingService.ts

(https://msazure.visualstudio.com/Antares/_workitems/edit/3302848)

Porting more things needed for spec-picker from portal-service into portal-communicator and port billing-service

---

client/src/app/shared/services/cache.service.ts
client/src/app/site/container-settings/container-image-source/container-logs/container-logs.component.html
client/src/app/site/container-settings/container-image-source/container-logs/container-logs.component.ts
client/src/app/site/container-settings/services/container-logs.service.ts

https://msazure.visualstudio.com/Antares/_workitems/edit/3122199
This downloads the detailed container log.

Download the container log zip

---

client-react/src/pages/app/spec-picker/SpecPickerFooter.tsx

(https://msazure.visualstudio.com/Antares/_workitems/edit/3302845)

Dumb Component for spec-picker footer

---

client-react/src/pages/app/spec-picker/SpecPickerExpander.tsx

(https://msazure.visualstudio.com/Antares/_workitems/edit/3302836)

Dumb component for spec-picker expander -> will have icon, text,

---

client-react/src/pages/app/spec-picker/SpecPickerPricingCard.tsx

(https://msazure.visualstudio.com/Antares/_workitems/edit/3302838)

Component for price card

---

client/src/app/site/spec-picker/price-spec-manager/plan-price-spec-manager.ts

(https://msazure.visualstudio.com/Antares/_workitems/edit/3416953)

Don't show price in price cards if getSpecCosts call returns statuscode which is not 0 in data

---

client/src/app/shared/models/constants.ts
client/src/app/shared/models/portal-resources.ts
client/src/app/site/container-settings/container-image-source/container-image-source-privateregistry/container-image-source-privateregistry.component.html
client/src/app/site/container-settings/container-image-source/container-image-source-privateregistry/container-image-source-privateregistry.component.ts
server/Resources/Resources.resx

https://msazure.visualstudio.com/Antares/_workitems/edit/3450523

Add a learn more link along with a description.

---

client/src/app/tree-view/base-functions-proxies-node.ts

fixes https://msazure.visualstudio.com/Antares/_workitems/edit/3469788

Update check orders

---

client/src/app/site/function-runtime/function-runtime.component.ts

Fixes: https://msazure.visualstudio.com/Antares/_workitems/edit/3464515

Add check to make sure version is defined

---

client/src/app/shared/models/arm/stacks.ts
client/src/app/shared/models/portal-resources.ts
client/src/app/site/site-config/general-settings/general-settings.component.html
client/src/app/site/site-config/general-settings/general-settings.component.ts
server/Resources/Resources.resx

Updating GeneralSettingsComponent to allow enabling Java without setting JavaWebContainer.

[DO NOT MERGE - NEEDS ANT78 CHANGES] Updating Java controls in GeneralSettingsComponent

---

server/src/server.ts

an extra source of information mostly for CSS to determine what region a customer is hitting when having a problem.

Add call for debug information to server

---

client-react/src/components/InformationCard/InformationCard.tsx
client-react/src/pages/app/spec-picker/SpecPickerFeatureList.tsx
client-react/src/pages/app/spec-picker/specs/FreePlanPriceSpec.ts
client-react/src/pages/app/spec-picker/specs/PriceSpec.ts
client-react/src/pages/app/spec-picker/specs/SharedPlanPriceSpec.ts
client-react/src/pages/app/spec-picker/specs/basic/BasicPlanPriceSpec.ts
client-react/src/pages/app/spec-picker/specs/elastic-premium/ElasticPremiumPlanPriceSpec.ts
client-react/src/pages/app/spec-picker/specs/isolated/IsolatedPlanPriceSpec.ts
client-react/src/pages/app/spec-picker/specs/premium-container/PremiumContainerPlanPriceSpec.ts
client-react/src/pages/app/spec-picker/specs/premium/PremiumPlanPriceSpec.ts
client-react/src/pages/app/spec-picker/specs/premiumv2/PremiumV2PlanPriceSpec.ts
client-react/src/pages/app/spec-picker/specs/standard/StandardPlanPriceSpec.ts

(https://msazure.visualstudio.com/Antares/_workitems/edit/3487648)

Component for spec picker feature list

---

client-react/src/pages/app/spec-picker/SpecPickerPricingCard.tsx
client-react/src/pages/app/spec-picker/SpecPickerPricingCardsContainer.tsx

(https://msazure.visualstudio.com/Antares/_workitems/edit/3302843)

Component for price cards container

---

client/src/app/shared/models/constants.ts
client/src/app/shared/models/portal-resources.ts
client/src/app/site/quickstart/quickstart.component.ts
client/src/app/site/quickstart/step-choose-dev-environment/step-choose-dev-environment.component.ts
client/src/app/site/quickstart/wizard-logic/quickstart-models.ts
server/Resources/Resources.resx

Fixes: https://msazure.visualstudio.com/Antares/_workitems/edit/3479004

Fusion powershell updates

---

client-react/src/models/BillingModels.ts
client-react/src/modules/service/billing/actions.ts
client-react/src/modules/service/billing/reducer.ts
client-react/src/modules/service/billing/thunks.ts

(https://msazure.visualstudio.com/Antares/_workitems/edit/3302851)

Thunk for billingMeter arm call

---

client/src/app/function-dev/function-dev.component.html
client/src/app/function-dev/function-dev.component.ts
client/src/app/shared/models/constants.ts
client/src/app/shared/models/functions-version-info.ts
client/src/app/shared/models/host.ts
client/src/app/shared/services/function-app.service.ts

(https://msazure.visualstudio.com/Antares/_workitems/edit/3506770)

"Get function URL" displays incorrect URL when routePrefix is Empty

---

client/src/app/controls/info-box/info-box.component.html
client/src/app/site/slots/deployment-slots/deployment-slots.component.html
client/src/app/site/slots/deployment-slots/deployment-slots.component.ts
server/Resources/Resources.resx

Updating DeploymentSlotsComponent to show banner instead of placeholder row when site has no slots

---

client-react/src/utils/scenario-checker/national-cloud.environment.ts
client/src/app/shared/models/constants.ts
client/src/app/shared/services/scenario/linux-site.environment.ts
client/src/app/site/site-manage/site-manage.component.ts

Fixes https://msazure.visualstudio.com/Antares/_workitems/edit/3512059

Remove disabled concept from MSI, add in National Clouds and Linux

---

client-react/src/utils/scenario-checker/scenario-ids.ts
client-react/src/utils/scenario-checker/xenon-site.environment.ts
client/src/app/shared/components/config-save-component.ts
client/src/app/shared/models/arm/site-config.ts
client/src/app/shared/models/constants.ts
client/src/app/shared/models/portal-resources.ts
client/src/app/shared/services/scenario/xenon-site.environment.ts
client/src/app/shared/services/site.service.ts
client/src/app/site/byos/byos-selector/byos-selector-advanced.component.html
client/src/app/site/byos/byos-selector/byos-selector-advanced.component.ts
client/src/app/site/byos/byos.component.html
client/src/app/site/byos/byos.component.ts
client/src/app/site/byos/byos.ts
client/src/app/site/site-config/mount-storage/mount-storage.component.html
client/src/app/site/site-config/mount-storage/mount-storage.component.ts
client/src/app/site/site-config/site-config.component.html
client/src/app/site/site-config/site-config.component.ts
server/Resources/Resources.resx

Introduce mount storage section in App Settings

---

client/src/app/extension-install/base-extension-install-component.ts

Fixes BUG 3507047: Function app remains in offline state after failed extension installation
https://msazure.visualstudio.com/Antares/_sprints/taskboard/Antares%20Team/Antares/UX/S103

Bring host online in extension error states

---

client/src/app/shared/models/portal-resources.ts
client/src/app/shared/services/scenario/national-cloud.environment.ts
client/src/app/shared/validators/uniqueStorageNameValidator.ts
client/src/app/site/byos/byos-manager.ts
client/src/app/site/byos/byos-selector/byos-selector.component.html
client/src/app/site/byos/byos.component.ts
client/src/app/site/site-config/mount-storage/mount-storage.component.html
client/src/app/site/site-config/mount-storage/mount-storage.component.ts
client/src/app/site/site-config/site-config.component.ts
server/Resources/Resources.resx

add DNS suffix for windows.
ability to edit path in line.
block in national clouds.

BYOS: Fix issues raised in the email thread

---

client-react/src/utils/scenario-checker/scenario-ids.ts
client/src/app/aad-registration/aad-registration.component.html
client/src/app/aad-registration/aad-registration.component.ts
client/src/app/shared/models/constants.ts
client/src/app/shared/services/scenario/national-cloud.environment.ts

Fixes BUG 3306817: [Fairfax] Error configuring AAD application
https://msazure.visualstudio.com/Antares/_workitems/edit/3306817

Remove AAD auto-configure for National Clouds

---

client/src/app/site/site-summary/site-summary.component.ts

fixes BUG 3551067: Quickstart Icon not shown on first Function App load
https://msazure.visualstudio.com/Antares/_workitems/edit/3551067

Load Quickstart Icon (Independent of Function Runtime)

---

client/src/app/site/site-config/site-config.component.ts

Updating SiteConfigComponent to use API version 2018-02-01 when calling PUT on /config/web

Updating SiteConfigComponent to use API version 2018-02-01 when calling PUT on /config/web

---

gulpfile.js
package.json
yarn.lock

Update gulpfile to generate encoded url for fusion query parameters

---

client-react/src/models/WebAppModels.d.ts
client-react/src/modules/index.ts
client-react/src/modules/site/config/appsettings/actions.ts
client-react/src/modules/site/config/appsettings/thunks.ts
client-react/src/modules/site/config/connectionstrings/thunks.ts
client-react/src/modules/site/config/metadata/thunks.ts
client-react/src/modules/site/config/slotConfigNames/actions.ts
client-react/src/modules/site/config/slotConfigNames/reducer.ts
client-react/src/modules/site/config/slotConfigNames/thunks.ts
client-react/src/modules/site/config/web/thunks.ts
client-react/src/modules/site/slots/thunks.ts
client-react/src/modules/site/thunks.ts
client-react/src/modules/types.ts
client-react/src/pages/app/app-settings/GeneralSettings/Platform.tsx
client-react/src/utils/CommonConstants.ts
tests/cypress/utilities/app-settings-utils.js

updating config flow to account for slot config names

---

server/Resources/Resources.resx

Resx Update

---

client/src/app/shared/models/arm/site.ts
client/src/app/shared/models/portal-resources.ts
client/src/app/shared/url-templates.ts
client/src/app/site/function-runtime/function-runtime.component.ts
client/src/app/site/site-enabled-features/site-enabled-features.component.ts
client/src/app/site/site-summary/site-summary.component.html
client/src/app/site/site-summary/site-summary.component.ts
client/src/app/tree-view/base-functions-proxies-node.ts
client/src/app/tree-view/functions-node.ts
client/src/app/tree-view/proxies-node.ts
server/Resources/Resources.resx

Gracefully show app in a limited state

---

client/src/app/controls/group-tabs/group-tabs.component.html
client/src/app/controls/group-tabs/group-tabs.component.scss
client/src/app/site/spec-picker/spec-feature-list/spec-feature-list.component.html
client/src/app/site/spec-picker/spec-feature-list/spec-feature-list.component.scss
client/src/app/site/spec-picker/spec-picker.component.html
client/src/app/site/spec-picker/spec-picker.component.scss

(https://msazure.visualstudio.com/Antares/_workitems/edit/3118158)
**Before change:**
**After change:**

[Screen Reader - Pricing tier - Dev/Test (For less demanding workloads)] Heading attributes is not correctly defined on the Dev/Test blade.

---

client/src/app/function/function-new/function-new.component.ts

Experimental templates from V1 Python have been removed from portal. Default to V2 templates for all scenarios

No python v1 experimental, v2 check

---

client/src/app/function-dev/function-dev.component.ts
client/src/app/run-http/run-http.component.ts

fixes - https://msazure.visualstudio.com/Antares/_workitems/edit/3122257

Set the key when re-navigating to the editor component.

---

client-react/src/pages/app/app-settings/AppSettings.types.ts
client-react/src/pages/app/app-settings/AppSettingsDataLoader.tsx
client-react/src/pages/app/app-settings/AppSettingsFormData.ts
client-react/src/pages/app/app-settings/ApplicationSettings/AppSettingAddEdit.tsx
client-react/src/pages/app/app-settings/ApplicationSettings/ApplicationSettings.tsx
client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStrings.tsx
client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStringsAddEdit.tsx
client-react/src/pages/app/app-settings/GeneralSettings/SlotAutoSwap.tsx
client-react/src/theme/dark.ts
client-react/src/theme/light.ts
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx
tests/cypress/fixtures/default/site.windows.slot.json
tests/cypress/fixtures/default/slots.json
tests/cypress/integration/app_settings/app_settings_no_write_production_on_slot.spec.js
tests/cypress/utilities/app-settings-utils.js

primarily blocking things in the case of write permissions on slot and only read permissions on production app as well and cleaning up the Auto Swap Setting

Additional work around slot setting pieces of application settings

---

client/src/app/shared/models/constants.ts
client/src/app/shared/services/site.service.ts
client/src/app/site/site-summary/site-summary.component.ts

revert back to older API version and match with Ibiza publish profile API version

revert back to older API version and match with Ibiza

---

client/src/app/site/deployment-center/deployment-center-setup/step-build-provider/step-build-provider.component.html
client/src/app/site/deployment-center/deployment-center-setup/step-source-control/step-source-control.component.html
client/src/app/site/deployment-center/deployment-center-setup/step-source-control/step-source-control.component.scss
client/src/app/site/spec-picker/spec-list/spec-list.component.html
client/src/app/site/spec-picker/spec-picker.component.scss

(https://msazure.visualstudio.com/Antares/_workitems/edit/3723271)
**Before:**
**After:**

BUG: 3723271 [Ibiza][LOC] Localized contents display outside of box in scaleup blade and deployment center

---

server/Resources/Resources.resx

@btardif @soninaren let me know what you think

Fixes AB#3799282 Clarify that app will go into offline mode duirng installation

---

client/src/app/site/spec-picker/spec-picker.component.html
client/src/app/site/spec-picker/spec-picker.component.ts

(https://msazure.visualstudio.com/Antares/_workitems/edit/3824417)
(https://msazure.visualstudio.com/Antares/_workitems/edit/3824422)

AB#3824417 AB#3824422 [Spec Picker] Need telemetry for Linux Basic SKU and Need to show the Basic free trial banner message

---

client/src/app/site/spec-picker/spec-picker.component.html

(https://msazure.visualstudio.com/Antares/_workitems/edit/3832447)

[Ibiza][Create]Pricing tier is blank when create one new ASP

---

client/src/app/site/spec-picker/spec-picker.component.ts

https://msazure.visualstudio.com/Antares/_workitems/edit/3839873

AB#3839873 [Ibiza][Scale] Apply button is not response when scale up for web app

---

client/src/app/site/container-settings/container-image-source/container-image-source-acr/container-image-source-acr.component.html
client/src/app/site/container-settings/container-image-source/container-image-source-acr/container-image-source-acr.component.ts

AB#3863630 Display error from the credential response.

---

client/src/app/edit-mode-warning/edit-mode-warning.component.html
client/src/app/edit-mode-warning/edit-mode-warning.component.ts
client/src/app/functions-list/functions-list.component.html
client/src/app/functions-list/functions-list.component.ts
client/src/app/shared/models/function-app-edit-mode.ts
client/src/app/shared/models/portal-resources.ts
client/src/app/shared/services/function-app.service.ts
client/src/app/site/quickstart/step-create-portal-function/step-create-portal-function.component.ts
server/Resources/Resources.resx

Also has V2 python edits
Also deleted some outdated embedded code :)

Fixes AB#3803402

---

client-react/src/pages/app/app-settings/ApplicationSettings/ApplicationSettings.tsx
client-react/src/react-app-env.d.ts
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

Add new coachmark for advanced edit of app settings

---

client/src/app/site/deployment-center/deployment-center-setup/step-configure/configure-vsts-build/configure-vsts-build.component.ts
client/src/app/site/deployment-center/deployment-center-setup/step-configure/configure-vsts-source/configure-vsts-source.component.ts
client/src/app/site/deployment-center/deployment-center-setup/validators/vsts-validators.ts
client/src/app/site/deployment-center/deployment-center-setup/wizard-logic/deployment-center-state-manager.ts

Fixing the MsaPassthrough header issue #3661

Fixing the MsaPassthrough header issue

---

client/src/app/site/slots/swap-slots/swap-diff-table/swap-diff-table.component.html
client/src/app/site/slots/swap-slots/swap-slots.component.scss

**Before - Light Theme**
**Before - Dark Theme**
**After - Light Theme**
**After - Dark Theme**

AB#3962649 Updating styling of diff tables in SlotSwapComponent to improve clarity

---

client-react/package.json
client-react/src/components/loading/loading-component.stories.tsx
client-react/src/components/loading/loading-component.tsx
client-react/src/components/monaco-editor/monaco-editor.tsx
client-react/src/pages/app/AppServiceRouter.tsx
client-react/src/pages/app/app-settings/AppSettingsDataLoader.tsx
server/gulpfile.js
yarn.lock

also includes PR #3680 because I was doing this on linux and needed to build

Reinstate lazy loading and optimize monaco loading

---

client-react/src/ApiHelpers/SiteService.ts
client-react/src/utils/CommonConstants.ts
client/src/app/function-edit/function-edit.component.ts
client/src/app/shared/services/function-app.service.ts
client/src/app/shared/services/site.service.ts
client/src/app/site/deployment-center/deployment-center-setup/wizard-logic/deployment-center-state-manager.ts
client/src/app/site/deployment-center/provider-dashboards/kudu-dashboard/kudu-dashboard.component.ts
client/src/app/site/deployment-center/provider-dashboards/vso-Dashboard/vso-dashboard.component.ts
client/src/app/site/slots/deployment-slots/deployment-slots.component.ts
client/src/app/site/swagger-definition/swagger-definition.component.ts

(https://msazure.visualstudio.com/Antares/_workitems/edit/3793420)

AB#3793420 [After ANT80 is done] [Fusion] Update site config api version to 20181101

---

client-react/src/ApiHelpers/SiteService.ts
client-react/src/models/WebAppModels.ts
client-react/src/pages/app/log-stream/LogStream.tsx
client-react/src/pages/app/log-stream/LogStream.types.ts
client-react/src/pages/app/log-stream/LogStreamCommandBar.tsx
client-react/src/pages/app/log-stream/LogStreamData.ts
client-react/src/pages/app/log-stream/LogStreamDataLoader.tsx
client-react/src/pages/app/log-stream/LogStreamLogContainer.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

Consume API for detecting disabled logs state

Work for AB#3788796

---

client/src/app/create-function-wrapper/create-function-wrapper.component.ts
client/src/app/function-quickstart/function-quickstart.component.html
client/src/app/function-quickstart/function-quickstart.component.ts

update v1/v2 logic for quickstart

Fixes AB#4041466

---

client/src/app/site/deployment-center/deployment-center-setup/wizard-logic/deployment-center-state-manager.ts

Fixes [AB#4113598](https://msazure.visualstudio.com/web/wi.aspx?pcguid=41bf5486-7392-4b7a-a7e3-a735c767e3b3&id=4113598)

Fix issue where Azure Repos don't respect selected branch

---

client/src/app/copy-pre/copy-pre.component.ts
client/src/app/shared/models/portal-resources.ts
client/src/app/site/container-settings/container-image-source/container-continuous-delivery/container-continuos-delivery.component.html
client/src/app/site/container-settings/container-image-source/container-image-source-acr/container-image-source-acr.component.ts

[AB#4136126](https://msazure.visualstudio.com/web/wi.aspx?pcguid=41bf5486-7392-4b7a-a7e3-a735c767e3b3&id=4136126) sort ACR repositories alphabetically.
[AB#4130479](https://msazure.visualstudio.com/web/wi.aspx?pcguid=41bf5486-7392-4b7a-a7e3-a735c767e3b3&id=4130479) Allow copy of the hidden URL if the copy button is clicked.

Bug fixes for container ACR Repository list and webhook URL copy

---

client-react/package.json
client-react/src/components/UpsellBanner/UpsellBanner.styles.ts
client-react/src/components/UpsellBanner/UpsellBanner.tsx
client-react/src/pages/app/app-settings/AppSettings.tsx
client-react/src/pages/app/app-settings/AppSettingsDataLoader.tsx
client-react/src/pages/app/app-settings/Contexts.ts
client-react/src/pages/app/app-settings/GeneralSettings/Platform.tsx
client-react/src/portal-communicator.ts
client-react/src/utils/CommonConstants.ts
client-react/src/utils/scenario-checker/azure.environment.ts
client-react/src/utils/scenario-checker/scenario-ids.ts
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

Fixes AB#3734573 [React][AppSettingsV3] Upsell experience

---

client/src/app/site/console/console.component.html
client/src/app/site/console/console.component.ts

**BEFORE**
The blade is just empty if the user doesn't have access.
**AFTER**

AB#4174459 Updating ConsoleComponent to show an error message if the user doesn't have sufficient access

---

client-react/src/models/WebAppModels.ts
client-react/src/utils/CommonConstants.ts
client/src/app/shared/models/arm/site-config.ts
client/src/app/shared/models/constants.ts
client/src/app/shared/models/portal-resources.ts
client/src/app/site/function-runtime/function-runtime.component.html
client/src/app/site/function-runtime/function-runtime.component.ts
server/Resources/Resources.resx

fixes [AB#4191597](https://msazure.visualstudio.com/web/wi.aspx?pcguid=41bf5486-7392-4b7a-a7e3-a735c767e3b3&id=4191597)

Show IP Restrictions banner

---

client/src/app/shared/models/constants.ts
client/src/app/shared/models/portal-resources.ts
client/src/app/site/function-runtime/function-runtime.component.html
client/src/app/site/function-runtime/function-runtime.component.ts
client/src/app/site/site-summary/site-summary.component.ts
server/Resources/Resources.resx

Function App Settings -> Site Summary for higher visibility

Update IP restrictions banner placement

---

client/src/app/shared/models/constants.ts
client/src/app/shared/models/portal-resources.ts
client/src/app/site/slots/deployment-slots/deployment-slots.component.html
client/src/app/site/slots/deployment-slots/deployment-slots.component.ts
server/Resources/Resources.resx

AB#4202776 Adding banner for TiP rules deprecation on non-production

---

client/src/app/shared/models/constants.ts
client/src/app/site/spec-picker/price-spec-manager/elastic-premium-plan-price-spec.ts

* Remove the "EnableElasticPremium" feature flag
* Adding elasticPremiumNotAvailableLearnMore FWLink

Merge master to dev

---

client/src/app/shared/services/function-app.service.ts

Fixes [AB#4074704](https://msazure.visualstudio.com/web/wi.aspx?pcguid=41bf5486-7392-4b7a-a7e3-a735c767e3b3&id=4074704)

Remove Linux Dynamic special handling for MACHINEKEY_DecryptionKey

---

client/src/app/shared/models/constants.ts
client/src/app/shared/models/portal-resources.ts
client/src/app/site/site-summary/site-summary.component.ts
server/Resources/Resources.resx

Fixes [AB#4208131](https://msazure.visualstudio.com/web/wi.aspx?pcguid=41bf5486-7392-4b7a-a7e3-a735c767e3b3&id=4208131)

Client cert warning

---

server/Resources/Resources.resx

Thanks @mattchenderson for the things I can't unsee 😛

Fix sentence casing in configuration

---

client-react/src/utils/CommonConstants.ts
client/src/app/shared/models/constants.ts
client/src/app/shared/models/portal-resources.ts
client/src/app/site/site-summary/site-summary.component.ts
server/Resources/Resources.resx

Fixes [AB#4247157](https://msazure.visualstudio.com/web/wi.aspx?pcguid=41bf5486-7392-4b7a-a7e3-a735c767e3b3&id=4247157)

Powershell preview banner

---

client/src/app/binding-event-grid/binding-event-grid.component.html

Fixes [AB#4354332](https://msazure.visualstudio.com/web/wi.aspx?pcguid=41bf5486-7392-4b7a-a7e3-a735c767e3b3&id=4354332)

Remove EventGrid sub link

---

client-react/src/components/form-controls/ReactiveFormControl.tsx
client-react/src/components/form-controls/formControl.override.styles.tsx
client-react/src/pages/app/app-settings/AppSettings.styles.ts
client-react/src/pages/app/app-settings/AppSettingsFormData.ts
client-react/src/pages/app/app-settings/ApplicationSettings/ApplicationSettings.tsx
client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStrings.tsx
client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStrings.utils.ts
client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStringsBulkEdit.tsx
client-react/src/pages/app/app-settings/ConnectionStrings/connectionStringTypes.ts
client-react/src/pages/app/app-settings/Sections/ApplicationSettingsPivot.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

Fixes [AB#4398555](https://msazure.visualstudio.com/web/wi.aspx?pcguid=41bf5486-7392-4b7a-a7e3-a735c767e3b3&id=4398555)
[AB#4351327](https://msazure.visualstudio.com/web/wi.aspx?pcguid=41bf5486-7392-4b7a-a7e3-a735c767e3b3&id=4351327)

Addressing user feedback on configuration

---

client/src/app/api/api-new/api-new.component.ts
client/src/app/create-function-wrapper/create-function-wrapper.component.ts
client/src/app/function-quickstart/function-quickstart.component.ts
client/src/app/function/function-new-detail/function-new-detail.component.ts
client/src/app/function/function-new/function-new.component.ts
client/src/app/main/main.component.ts
client/src/app/shared/models/binding-manager.ts
client/src/app/shared/models/function-info.ts
client/src/app/shared/services/function-app.service.ts
client/src/app/shared/services/function.service.ts
client/src/app/shared/services/site.service.ts
client/src/app/shared/shared.module.ts
client/src/app/side-nav/side-nav.component.ts
client/src/app/site/function-runtime/function-runtime.component.ts
client/src/app/site/quickstart/step-create-portal-function/step-create-portal-function.component.ts
client/src/app/site/site-summary/site-summary.component.ts
client/src/app/tree-view/base-functions-proxies-node.ts
client/src/app/tree-view/functions-node.ts

Completes [AB#4396075](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/4396075)

[Function APIs] getFunctions

---

client/src/app/shared/models/error-ids.ts
client/src/app/shared/models/portal-resources.ts
client/src/app/site/slots/swap-slots/swap-slots.component.ts
server/Resources/Resources.resx

AB#4471776 Fixing issue where swap opeartion still appeared as in progress after max polling attempts were exceeded.

---

client/src/app/function-dev/function-dev.component.ts
client/src/app/function-keys/function-keys.component.ts
client/src/app/shared/services/function-app.service.ts
client/src/app/shared/services/function.service.ts

fixes [AB#4396094](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/4396094)
fixes [AB#4396108](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/4396108)
fixes [AB#4396114](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/4396114)

getFunctionKeys, createFunctionKey, deleteFunctionKey

---

client/src/app/edit-mode-warning/edit-mode-warning.component.html
client/src/app/edit-mode-warning/edit-mode-warning.component.ts
client/src/app/shared/Utilities/edit-mode.helper.ts
client/src/app/shared/models/function-app-edit-mode.ts
client/src/app/shared/models/portal-resources.ts
client/src/app/shared/services/function-app.service.ts
server/Resources/Resources.resx

Fixes [AB#4484072](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/4484072)
OG PR #3870

Make Java Function Apps Read Only

---

client/src/app/site/site-dashboard/site-dashboard.component.ts

AB#4501784 - Add query string to open Diagnose/Solve directly for a function app

---

client/src/app/function-dev/function-dev.component.ts
client/src/app/function-keys/function-keys.component.ts
client/src/app/shared/models/constants.ts
client/src/app/shared/models/function-key.ts
client/src/app/shared/models/host-secrets.ts
client/src/app/shared/services/function-app.service.ts
client/src/app/shared/services/function.service.ts

Fixes [AB#4396126](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/4396126)
Fixes [AB#4396105](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/4396105)
Fixes [AB#4396166](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/4396166)

getHostKeys, createHostKey, deleteHostKey

---

client-react/src/ApiHelpers/SiteService.ts

Fixes [AB#4440570](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/4440570)

Update logsConfig call

---

client/src/app/function-dev/function-dev.component.ts
client/src/app/function-manage/function-manage.component.ts
client/src/app/function/binding-v2/binding-v2.component.ts
client/src/app/function/function-new-detail/function-new-detail.component.ts
client/src/app/functions-list/functions-list.component.ts
client/src/app/shared/models/binding-manager.ts
client/src/app/shared/models/function-info.ts
client/src/app/shared/services/function-app.service.ts
client/src/app/shared/services/function.service.ts

Fixes [AB#4559617](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/4559617)

createFunction, deleteFunction, other api updates

---

client-react/src/pages/app/app-settings/GeneralSettings/LinuxStacks/LinuxStacks.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

Fixes AB#4622800 [Configuration] Should separate stack from versions dropdown so that we can include minor versions

---

client/src/app/site/site-summary/site-summary.component.ts
server/Resources/Resources.resx

Fixes [AB#4437436](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/4437436)

Add Access Restrictions Banner for scm site

---

client-react/src/pages/app/log-stream/LogStreamLogContainer.tsx
server/Resources/Resources.resx

Fixes [AB#4497019](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/4497019)

Logstream autoscroll to bottom, update strings

---

client-react/src/ApiHelpers/HostingEnvironmentService.ts
client-react/src/pages/app/change-app-plan/ChangeAppPlan.tsx
client-react/src/pages/app/change-app-plan/ChangeAppPlanDataLoader.tsx
client-react/src/pages/app/change-app-plan/CreateOrSelectPlan.tsx
client-react/src/pages/app/change-app-plan/CreateOrSelectResourceGroup.tsx
client-react/src/pages/app/change-app-plan/CreatePlan.tsx
client-react/src/theme/dark.ts
client-react/src/utils/CommonConstants.ts
client-react/src/utils/rbac-helper.ts
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

If you don't have RBAC access on either the subscription or the existing resource group, then we'll show this:
If you have a readonly lock on the app, then you'll see this:

AB#4490349 - [ChangeAppPlan] Adding RBAC support and removing create new plan for ASE v1 apps

---

client-react/src/pages/app/log-stream/LogStreamData.ts

LogStream: Handle container format

---

client/src/app/function-edit/function-edit.component.ts
client/src/app/shared/models/constants.ts
client/src/app/shared/models/portal-resources.ts
client/src/app/shared/services/function-app.service.ts
client/src/app/site/function-runtime/function-runtime.component.html
client/src/app/site/function-runtime/function-runtime.component.ts
client/src/app/slot-new/slot-new.component.html
client/src/app/slot-new/slot-new.component.scss
client/src/app/slot-new/slot-new.component.ts
server/Resources/Resources.resx

**Add Slot - BEFORE**
**Add Slot - AFTER**
**Function App Settings - BEFORE**
**Function App Settings - AFTER**

AB#3989184 Moving Function App slots warning/control into the slot add experience

---

client-react/src/pages/app/app-settings/GeneralSettings/SlotAutoSwap.tsx

AB#4786899 Reversing the order of the AutoSwap on/off radio buttons

---

client/src/app/site/slots/swap-slots/swap-slots.component.html
client/src/app/site/slots/swap-slots/swap-slots.component.scss

AB#3963698 Rearranging controls in SwapSlotsComponent so that long slot names don't get cut off

---

client/src/app/site/deployment-center/deployment-center-setup/step-configure/configure-vsts-source/configure-vsts-source.component.ts
client/src/app/site/deployment-center/deployment-center-setup/step-configure/step-configure.component.html
client/src/app/site/deployment-center/deployment-center-setup/wizard-logic/deployment-center-state-manager.ts

AB#4702565 Hide the continue button if no accounts or repos exist

---

client/src/app/site/deployment-center/deployment-center-setup/step-configure/configure-vsts-source/configure-vsts-source.component.ts

AB#4702574 Hide the build section if no organizations are available.

---

client/src/app/copy-pre/copy-pre.component.html
client/src/app/copy-pre/copy-pre.component.scss
client/src/app/copy-pre/copy-pre.component.ts
client/src/app/site/deployment-center/deployment-center-setup/step-configure/configure-vsts-source/configure-vsts-source.component.ts
client/src/app/site/deployment-center/provider-dashboards/kudu-dashboard/kudu-dashboard.component.html
client/src/app/site/deployment-center/provider-dashboards/kudu-dashboard/kudu-dashboard.component.ts
client/src/app/site/deployment-center/provider-dashboards/vso-Dashboard/vso-dashboard.component.html
client/src/app/site/deployment-center/provider-dashboards/vso-Dashboard/vso-dashboard.component.ts
client/src/image/external.svg
server/Resources/Resources.resx

fixes AB#4844015, AB#4844026. Add a browse button and ability to copy the repository url.
**Before**
**After**

Visual improvements to the deployment dashboard

---

client/src/app/shared/models/portal-resources.ts
client/src/app/site/deployment-center/provider-dashboards/deploymentDashboard.ts
client/src/app/site/deployment-center/provider-dashboards/kudu-dashboard/kudu-dashboard.component.html
client/src/app/site/deployment-center/provider-dashboards/kudu-dashboard/kudu-dashboard.component.ts
client/src/app/site/deployment-center/provider-dashboards/vso-Dashboard/vso-dashboard.component.html
client/src/app/site/deployment-center/provider-dashboards/vso-Dashboard/vso-dashboard.component.ts
server/Resources/Resources.resx

Also localize the messages. fixes AB#4261498

Introduce a base class for common functions and show fetching message.

---

client/src/app/shared/models/constants.ts
client/src/app/shared/models/portal-resources.ts
client/src/app/shared/services/plan.service.ts
client/src/app/shared/services/scenario/onprem.environment.ts
client/src/app/site/spec-picker/price-spec-manager/plan-price-spec-manager.ts
server/Resources/Resources.resx

WORK: 4871780 [AppDensity] Show warning on spec picker when scaling up/down into a small instance

---

client/src/app/site/spec-picker/spec-picker.component.html
client/src/app/site/spec-picker/spec-picker.component.scss

Fix css for status message shown on spec picker

---

client/src/app/site/deployment-center/deployment-center-setup/step-source-control/step-source-control.component.ts

Set the provider auth property to true once the auth token is set in the token store successfully. Also add some extra logging.

AB#4802728 Set provider auth state and extra logging.

---

client-react/src/pages/app/app-settings/AppSettingsForm.tsx
client-react/src/utils/CommonConstants.ts
client-react/src/utils/scenario-checker/dynamic-linux.environment.ts
client-react/src/utils/scenario-checker/scenario-ids.ts
client/src/app/shared/models/constants.ts
client/src/app/shared/services/scenario/dynamic-linux.environment.ts
client/src/app/site/function-runtime/function-runtime.component.html
client/src/app/site/function-runtime/function-runtime.component.ts
client/src/app/site/site-manage/site-manage.component.ts

Fixes AB#4740950
Fixes AB#4761873

Linux consumption GA

---

client-react/src/models/portal-models.ts
client-react/src/portal-communicator.ts
client/src/app/shared/models/portal.ts
client/src/app/shared/services/portal.service.ts
client/src/app/test/mocks/portal.service.mock.ts

Cleaning up the code a  little by having the token type in central location for both angular and react fusion code.

Introduce 'TokenType' type.

---

client-react/src/ApiHelpers/ServerFarmService.ts
client-react/src/pages/app/change-app-plan/ChangeAppPlan.tsx
client-react/src/utils/CommonConstants.ts
client-react/src/utils/scenario-checker/azure.environment.ts
client-react/src/utils/scenario-checker/onprem.environment.ts
client-react/src/utils/scenario-checker/scenario-ids.ts
client-react/src/utils/scenario-checker/scenario.models.ts

With warning:
Without warning:

 AB#4871799 [AppDensity] Add warning on change ASP blade

---

client/src/app/shared/models/arm/hosting-environment.ts
client/src/app/shared/models/constants.ts
client/src/app/shared/preconditions.ts
client/src/app/shared/services/site.service.ts

Master -> Dev

---

server/Resources/Resources.resx

Python Functions GA

---

client/src/app/shared/models/constants.ts
client/src/app/slots-list/slots-list.component.html
client/src/app/slots-list/slots-list.component.ts
client/src/app/tree-view/slots-node.ts

Remove Slots Preview Feature Flag

---

client/src/app/shared/models/constants.ts
client/src/app/shared/models/portal-resources.ts
client/src/app/site/site-summary/site-summary.component.html
client/src/app/site/site-summary/site-summary.component.ts
server/Resources/Resources.resx

Linux Consumption GA updates

---

client/src/app/shared/models/portal-resources.ts
client/src/app/site/deployment-center/provider-dashboards/deployment-credentials/deployment-credentials.component.ts
server/Resources/Resources.resx

The latest message with the change

AB#4928643 Show the actual message rather than the resx name.

---

client-react/src/components/ActionBar.tsx
client-react/src/theme/SemanticColorsExtended.ts
client-react/src/theme/dark.ts
client-react/src/theme/light.ts

**Not Focused**
**Focused - BEFORE**
**Focused - AFTER**
**Not Focused**
**Focused - BEFORE**
**Focused - AFTER**

AB#4771969 Fixing focused styling for "OK" and "Cancel" buttons in Config blade

---

client/src/app/site/deployment-center/provider-dashboards/vso-Dashboard/vso-dashboard.component.ts

Bugs:
Refresh stuck in loading state when VSO Build definition flow is not there
Commit url not present for type 'Git'
Account url has additional https: in a specific scenario

Vso dashboard bug fixes

---

client-react/src/utils/scenario-checker/dynamic-linux.environment.ts
client/src/app/shared/services/scenario/dynamic-linux.environment.ts
client/src/app/site/deployment-center/deployment-center-setup/step-configure/configure-vsts-build/linux-frameworks/linux-frameworks.component.ts

AB#4983138 Disable auth for consumption linux apps.

---

client/src/app/function-dev/function-dev.component.ts

This should not have been removed with the ARM API updates. Re-adding the logic
Fixes AB#4988256

Re-add key logic

---

client/src/app/shared/services/function-app.service.ts

This would bring the app back online again after the extension is installed (irrespective of whether it passes or not).

Add BringAppOnline property

---

client/src/app/function-dev/function-dev.component.ts

Add firstonly check for tab focus

---

client/src/app/shared/services/function-app.service.ts
client/src/app/site/site-summary/site-summary.component.ts

Check for functionsInfo.result.value

---

client/src/app/shared/models/function-config.ts
client/src/app/shared/services/function-app.service.ts

Bug caught in staging with new ARM APIs

Config addition of properties

---

client/src/app/function-quickstart/function-quickstart.component.ts
client/src/app/function/function-new-detail/function-new-detail.component.ts
client/src/app/shared/services/function.service.ts
client/src/app/site/quickstart/step-create-portal-function/step-create-portal-function.component.ts

Linux Restart Addition

---

client/src/app/site/quickstart/step-choose-deployment-method/step-choose-deployment-method.component.html
client/src/app/site/quickstart/step-choose-deployment-method/step-choose-deployment-method.component.ts
client/src/app/site/quickstart/step-choose-dev-environment/step-choose-dev-environment.component.html
client/src/app/site/quickstart/step-choose-dev-environment/step-choose-dev-environment.component.ts
client/src/app/site/quickstart/step-create-portal-function/step-create-portal-function.component.html
client/src/app/site/quickstart/step-create-portal-function/step-create-portal-function.component.ts

Quickstart Accessibility updates

---

client/src/app/shared/models/constants.ts
client/src/app/slots-list/slots-list.component.html
client/src/app/slots-list/slots-list.component.ts
client/src/app/tree-view/slots-node.ts

Reverts Azure/azure-functions-ux#4064

Revert "AB#5000117 Adding back feature flag "RemoveSlotsPreviewTag""

---

client/src/app/shared/services/function-app.service.ts

Fixing issue where disabled v1 function apps are showing up as enabled

---

client/src/app/shared/services/scenario/container.environment.ts
client/src/app/shared/services/scenario/scenario.service.ts
client/src/app/site/site-manage/site-manage.component.ts

With these changes, following is the matrix of experience:
Windows Code Function App - Fusion Deployment Center
Windows Container Function App - Not supported
Linux Code Function App - AzureTFS Deployment Center
Linux Container Function App - AzureTFS Deployment Center
Windows code Consumption Function App - Fusion deployment center
Linux code consumption function app - Not supported

AB#4987476 Match deployment center experience with Ibiza menu item.

---

client/src/app/function-dev/function-dev.component.ts
client/src/app/function-integrate-v2/function-integrate-v2.component.ts
client/src/app/function-integrate/function-integrate.component.ts
client/src/app/function-manage/function-manage.component.ts
client/src/app/functions-list/functions-list.component.ts
client/src/app/shared/services/function-app.service.ts
client/src/app/shared/services/function.service.ts

Update function: Use ARM Apis

---

client/src/app/shared/components/function-app-context-component.ts
client/src/app/shared/function-app-context.ts

Remove extra runtime property

---

client/src/app/function-manage/function-manage.component.ts

Manage Tab: Function V2 info

---

client/src/app/site/site-manage/site-manage.component.ts

Fusion side fix for AB#5184590

userAssignedStatus is supported

---

client-react/src/ApiHelpers/FunctionsService.ts
client-react/src/models/functions/function-info.ts
client-react/src/models/functions/function-template.ts
client-react/src/pages/app/functions/common/BindingFormBuilder.tsx
client-react/src/pages/app/functions/common/CreateFunctionFormBuilder.tsx
client-react/src/pages/app/functions/create/CreateCard.helper.ts
client-react/src/pages/app/functions/create/CreateCard.tsx
client-react/src/pages/app/functions/create/DetailsPivot.helper.ts
client-react/src/pages/app/functions/create/DetailsPivot.tsx
client-react/src/pages/app/functions/create/FunctionCreate.data.ts
client-react/src/pages/app/functions/create/FunctionCreate.styles.ts
client-react/src/pages/app/functions/create/FunctionCreate.tsx
client-react/src/pages/app/functions/create/FunctionCreateDataLoader.tsx
client-react/src/pages/app/functions/create/TemplatesPivot.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

Create Function: More Details Pivot

---

client/src/app/shared/services/function-app.service.ts

Add catch on reachable ILB for Functions List

---

client/src/app/file-explorer/file-explorer.component.ts
client/src/app/function-dev/function-dev.component.html
client/src/app/function-dev/function-dev.component.ts

Update headers for function helper file upload

---

client-react/src/pages/app/app-settings/ApplicationSettings/ApplicationSettings.tsx

AB#4766381 focus changed on Add/Edit AppSettings Panel exit

---

client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/WindowsStacks.tsx

AB#4798405 Null stack fixed for .NET Core apps

---

server/Resources/cs-CZ/Server/Resources/Resources.resx
server/Resources/de-DE/Server/Resources/Resources.resx
server/Resources/es-ES/Server/Resources/Resources.resx
server/Resources/fr-FR/Server/Resources/Resources.resx
server/Resources/hu-HU/Server/Resources/Resources.resx
server/Resources/it-IT/Server/Resources/Resources.resx
server/Resources/ja-JP/Server/Resources/Resources.resx
server/Resources/ko-KR/Server/Resources/Resources.resx
server/Resources/nl-NL/Server/Resources/Resources.resx
server/Resources/pl-PL/Server/Resources/Resources.resx
server/Resources/pt-BR/Server/Resources/Resources.resx
server/Resources/pt-PT/Server/Resources/Resources.resx
server/Resources/qps-ploc/Server/Resources/Resources.resx
server/Resources/ru-RU/Server/Resources/Resources.resx
server/Resources/sv-SE/Server/Resources/Resources.resx
server/Resources/tr-TR/Server/Resources/Resources.resx
server/Resources/zh-CN/Server/Resources/Resources.resx
server/Resources/zh-TW/Server/Resources/Resources.resx

Dev is upto date with master so just updating loc strings before merging dev to master.

Update loc strings for S122

---

client-react/src/pages/app/app-settings/AppSettings.tsx
client-react/src/pages/app/app-settings/AppSettingsCommandBar.tsx
client-react/src/pages/app/app-settings/AppSettingsDataLoader.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

refresh button added for App-Settings

---

client-react/src/components/form-controls/TextFieldNoFormik.tsx
client-react/src/components/form-controls/formControl.override.styles.tsx
client-react/src/pages/app/app-settings/ApplicationSettings/AppSettingAddEdit.tsx
client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStringsAddEdit.tsx

copy button added for app-settings

---

client-react/src/components/ActionBar.tsx
client-react/src/components/form-controls/formControl.override.styles.tsx
client-react/src/pages/app/app-settings/ApplicationSettings/AppSettingAddEdit.tsx
client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEdit.tsx
client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStringsAddEdit.tsx
client-react/src/pages/app/app-settings/HandlerMappings/HandlerMappingsAddEdit.tsx
client-react/src/pages/app/app-settings/VirtualApplications/VirtualApplicationsAddEdit.tsx

Action Bar overlap issue on Add/Edit Panel

---

server/Resources/Resources.resx

closing tag added in Resources.resx

---

client-react/src/pages/app/app-settings/AppSettingsDataLoader.tsx

check prod permissions for slots

---

client/src/app/shared/models/portal-resources.ts
client/src/app/site/deployment-center/Models/provider-card.ts
client/src/app/site/deployment-center/deployment-center-setup/step-source-control/step-source-control.component.html
client/src/app/site/deployment-center/deployment-center-setup/step-source-control/step-source-control.component.scss
client/src/app/site/deployment-center/deployment-center-setup/step-source-control/step-source-control.component.ts
server/Resources/Resources.resx

Fixes AB#5277385
Before:
After:

Split the provider source in to continuous deployment and manual deployment to reduce confusion.

---

client-react/src/pages/app/app-settings/AppSettings.tsx
client-react/src/pages/app/app-settings/AppSettingsDataLoader.tsx
client-react/src/pages/app/app-settings/AppSettingsFormData.ts

AB#5271389 Block the config blade if any GET/POST calls fail while loading

---

client-react/src/components/Panel/Panel.styles.ts
client-react/src/components/Panel/Panel.tsx
client-react/src/pages/app/app-settings/ApplicationSettings/ApplicationSettings.tsx
client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMounts.tsx
client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStrings.tsx
client-react/src/pages/app/app-settings/GeneralSettings/ClientCert/ClientCert.tsx
client-react/src/pages/app/app-settings/HandlerMappings/HandlerMappings.tsx
client-react/src/pages/app/app-settings/VirtualApplications/VirtualApplications.tsx
client-react/src/pages/app/functions/integrate/binding-editor/BindingEditor.tsx
client-react/src/pages/app/functions/integrate/binding-editor/BindingEditorDataLoader.tsx

Custom panel designed similar to Ibiza

---

client/src/image/functions.svg

(Bug found on canary) Fix functions icon svg to support all scenarios

---

client/src/app/proxies-list/proxies-list.component.html
client/src/app/proxies-list/proxies-list.component.ts
client/src/app/shared/models/constants.ts
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

Add APIM Upsell in Proxies list

---

client-react/src/pages/app/app-settings/ApplicationSettings/AppSettingsBulkEdit.tsx
client-react/src/pages/app/app-settings/ApplicationSettings/ApplicationSettings.tsx
client-react/src/pages/app/app-settings/ApplicationSettings/ApplicationSettings.utils.ts
client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStrings.tsx
client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStrings.utils.ts
client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStringsBulkEdit.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

Update Bulk/Edit Panel on AppSetting to hide sticky option according to the permission

---

client-react/src/components/Panel/Panel.styles.ts
client-react/src/components/Panel/Panel.tsx

Fix the close-button color for panel

---

client-react/src/components/loading/loading-component.tsx
client-react/src/pages/app/functions/app-keys/AppKeys.styles.ts
client-react/src/pages/app/functions/app-keys/AppKeysDataLoader.tsx
client-react/src/pages/app/functions/app-keys/HostKeys.tsx
client-react/src/pages/app/functions/app-keys/SystemKeys.tsx

Show already loaded data, loader-component, and disable screen on refresh

---

client-react/src/pages/app/app-settings/AppSettingsDataLoader.tsx

state added to block command bar on configuration blade

---

client-react/src/models/functions/bindings-config.ts
client-react/src/pages/app/functions/common/BindingFormBuilder.tsx
client-react/src/pages/app/functions/common/CreateFunctionFormBuilder.tsx
client-react/src/pages/app/functions/common/NewResourceConnection.tsx
client-react/src/pages/app/functions/common/ResourceDropdown.tsx
client-react/src/pages/app/functions/create/DetailsPivot.helper.ts
client-react/src/pages/app/functions/create/DetailsPivot.tsx
client-react/src/pages/app/functions/create/FunctionCreate.tsx
client-react/src/pages/app/functions/create/FunctionCreateDataLoader.tsx
client-react/src/pages/app/functions/integrate/FunctionIntegrate.tsx
client-react/src/pages/app/functions/integrate/FunctionIntegrateDataLoader.tsx
client-react/src/pages/app/functions/integrate/binding-editor/BindingEditor.tsx
client-react/src/pages/app/functions/integrate/binding-editor/BindingEditorDataLoader.tsx
client-react/src/utils/LogCategories.ts

Getting in initial blob storage binding updates. More iterations will be done with ARM updates and storage account creation, but this will allow others to build off of this baseline in create and integrate scenarios.
Fixes AB#5084915

New Storage Binding for Azure Blob

---

client/src/app/shared/services/plan.service.ts

Update georegions filter to be case and space insensitive.

---

client/src/app/pickers/event-hub/event-hub.component.ts
client/src/app/pickers/service-bus/service-bus.component.ts
client/src/app/shared/models/constants.ts
client/src/app/shared/services/arm.service.ts

Add specific API constant for ServiceBus/EventHub

---

client-react/src/ApiHelpers/StorageService.ts
client-react/src/utils/CommonConstants.ts
client/src/app/logic-apps/logic-apps.component.ts
client/src/app/pickers/event-hub/event-hub.component.ts
client/src/app/pickers/service-bus/service-bus.component.ts

Fixes: https://msazure.visualstudio.com/Antares/_workitems/edit/5533607
Related: https://msazure.visualstudio.com/Antares/_workitems/edit/4990671

AB#5533607 Using provider-specific API versions when making ARM calls

---

client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEdit.tsx

Dirty state removed for TextField in Add/Edit Panel

---

client-react/src/pages/app/SiteRouter.tsx
client-react/src/pages/app/functions/function-editor/FunctionEditor.tsx
client-react/src/pages/app/functions/function-editor/FunctionEditorDataLoader.tsx
client-react/src/pages/app/functions/function-editor/FunctionEditorFileSelectorBar.tsx

**Will send the corresponding Ibiza one as well**

AB#5562156 [Ibizafication][FunctionsEditor][Fusion] Basic wiring up for the Editor IFrame

---

client/src/app/site/function-runtime/function-runtime.component.html
client/src/app/site/function-runtime/function-runtime.component.ts

Always show ~3 (Preview) option

---

client/src/app/site/site-summary/site-summary.component.ts

This reverts commit 5f69cf8d339c298d90304211b319182d21dd5b9a.
**Needed to be in Ignite payload hence had reverted it earlier. Reverting the revert now.**

AB#5488629 Revert "Revert "AB#5488629 Remove Poweshell Preview status bar from function app overview (#4200)" (#4206)

---

client/src/app/shared/models/arm/site-config.ts
client/src/app/shared/models/constants.ts
client/src/app/shared/models/portal-resources.ts
client/src/app/site/function-runtime/function-runtime.component.html
client/src/app/site/function-runtime/function-runtime.component.ts
server/Resources/Resources.resx

Runtime Drive Scaling

---

client-react/src/pages/app/app-settings/AppSettings.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

confirm dialog added on refreshing app-settings

---

client-react/src/ApiHelpers/IoTHubService.ts
client-react/src/models/iothub.ts
client-react/src/pages/app/functions/common/callout/NewEventHubConnectionCallout.tsx
client-react/src/pages/app/functions/common/callout/customPivot/CustomPivot.tsx
client-react/src/pages/app/functions/common/callout/eventHubPivot/EventHubPivot.tsx
client-react/src/pages/app/functions/common/callout/iotHubPivot/IoTHubPivot.data.ts
client-react/src/pages/app/functions/common/callout/iotHubPivot/IoTHubPivot.tsx
client-react/src/pages/app/functions/common/callout/iotHubPivot/IoTHubPivotDataLoader.tsx
client-react/src/utils/CommonConstants.ts
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

[Ibizafication] Add IoT Hub and Custom connection

---

client-react/src/components/form-controls/RadioButtonNoFormik.tsx
client-react/src/components/form-controls/ReactiveFormControl.tsx
client-react/src/pages/app/functions/common/callout/Callout.styles.ts
client-react/src/pages/app/functions/common/callout/NewEventHubConnectionCallout.tsx

As per design sync discussion:

[Ibizafication] Change Connection Pivots to Radio Buttons

---

client-react/src/ApiHelpers/ServiceBusService.ts
client-react/src/models/servicebus.ts
client-react/src/pages/app/functions/common/ResourceDropdown.tsx
client-react/src/pages/app/functions/common/callout/NewEventHubConnectionCallout.tsx
client-react/src/pages/app/functions/common/callout/NewServiceBusConnectionCallout.tsx
client-react/src/pages/app/functions/common/callout/serviceBusPivot/ServiceBusPivot.data.ts
client-react/src/pages/app/functions/common/callout/serviceBusPivot/ServiceBusPivot.tsx
client-react/src/pages/app/functions/common/callout/serviceBusPivot/ServiceBusPivotDataLoader.tsx
client-react/src/utils/CommonConstants.ts
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

Fixes AB#4916378
Fixes AB#4916375

[Ibizafication] Service bus binding

---

client-react/src/pages/app/spec-picker/specs/FreePlanPriceSpec.ts
client-react/src/pages/app/spec-picker/specs/SharedPlanPriceSpec.ts
client/src/app/site/spec-picker/price-spec-manager/free-plan-price-spec.ts
client/src/app/site/spec-picker/price-spec-manager/shared-plan-price-spec.ts

Discussed with Byron offline and we should not show that cpu/acu box at all.
**Before:**
**After:**

AB#5633015 FRee and Shared should not include mention of dedicated resources

---

client-react/src/pages/app/functions/common/BindingFormBuilder.tsx
client-react/src/pages/app/functions/common/CreateFunctionFormBuilder.tsx
client-react/src/pages/app/functions/common/ResourceDropdown.tsx
client-react/src/pages/app/functions/common/callout/NewAppSettingCallout.tsx
client-react/src/pages/app/functions/create/DetailsPivot.helper.ts
client-react/src/pages/app/functions/create/DetailsPivot.tsx
client-react/src/pages/app/functions/create/FunctionCreate.data.ts
client-react/src/pages/app/functions/integrate/binding-editor/BindingEditor.tsx

[Ibizafication] Custom App Setting (Send Grid)

---

client-react/src/pages/app/functions/common/callout/NewServiceBusConnectionCallout.tsx
client-react/src/pages/app/functions/common/callout/NewStorageAccountConnectionCallout.tsx
client-react/src/pages/app/functions/common/callout/newPivot/NewPivot.tsx
client-react/src/pages/app/functions/common/callout/storageAccountPivot/StorageAccountPivot.data.ts
client-react/src/pages/app/functions/common/callout/storageAccountPivot/StorageAccountPivot.tsx
client-react/src/pages/app/functions/common/callout/storageAccountPivot/StorageAccountPivotDataLoader.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

[Ibizafication] Storage Connection (BLOB, Queue Storage)

---

client-react/src/pages/app/functions/common/ResourceDropdown.tsx
client-react/src/pages/app/functions/common/callout/Callout.styles.ts
client-react/src/pages/app/functions/create/FunctionCreate.styles.ts

Callouts have correct size depending on # of fields
before:
after:

[Ibizafication] Update create styling

---

client-react/src/pages/app/functions/integrate/BindingsDiagram/BindingCard.tsx
client-react/src/pages/app/functions/integrate/BindingsDiagram/InputBindingCard.tsx

[Ibizafication][Integrate] Fix key names to not be duplicates of each other

---

client-react/src/pages/app/functions/integrate/FunctionIntegrate.tsx
client-react/src/pages/app/functions/integrate/binding-editor/BindingEditor.tsx
client-react/src/pages/app/functions/integrate/binding-editor/BindingEditorDataLoader.tsx

[Ibizafication][Integrate] Editing triggers

---

client-react/src/pages/app/functions/integrate/BindingsDiagram/BindingCard.tsx
client-react/src/pages/app/functions/integrate/FunctionIntegrate.tsx
client-react/src/pages/app/functions/integrate/binding-editor/BindingEditor.tsx
client-react/src/pages/app/functions/integrate/binding-editor/BindingEditorDataLoader.tsx
client-react/src/pages/app/functions/integrate/binding-editor/EditBindingCommandBar.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

[Ibizafication][Integrate] Add in deleting bindings

---

client-react/src/pages/app/app-settings/GeneralSettings/DebuggingLinux.tsx

Enable remote debugging for python (Linux Apps Only)

---

client-react/src/ApiHelpers/SiteService.ts
client-react/src/pages/app/functions/common/BindingFormBuilder.tsx
client-react/src/pages/app/functions/common/CreateFunctionFormBuilder.tsx
client-react/src/pages/app/functions/common/ResourceDropdown.tsx
client-react/src/pages/app/functions/common/callout/Callout.properties.ts
client-react/src/pages/app/functions/common/callout/NewAppSettingCallout.tsx
client-react/src/pages/app/functions/common/callout/NewDocumentDBConnectionCallout.tsx
client-react/src/pages/app/functions/common/callout/NewEventHubConnectionCallout.tsx
client-react/src/pages/app/functions/common/callout/NewServiceBusConnectionCallout.tsx
client-react/src/pages/app/functions/common/callout/NewStorageAccountConnectionCallout.tsx
client-react/src/pages/app/functions/common/callout/customPivot/CustomPivot.tsx
client-react/src/pages/app/functions/common/callout/documentDBPivot/DocumentDBDataLoader.tsx
client-react/src/pages/app/functions/common/callout/documentDBPivot/DocumentDBPivot.tsx
client-react/src/pages/app/functions/common/callout/eventHubPivot/EventHubPivot.tsx
client-react/src/pages/app/functions/common/callout/eventHubPivot/EventHubPivotDataLoader.tsx
client-react/src/pages/app/functions/common/callout/iotHubPivot/IoTHubPivot.tsx
client-react/src/pages/app/functions/common/callout/iotHubPivot/IoTHubPivotDataLoader.tsx
client-react/src/pages/app/functions/common/callout/newPivot/NewPivot.tsx
client-react/src/pages/app/functions/common/callout/serviceBusPivot/ServiceBusPivot.tsx
client-react/src/pages/app/functions/common/callout/serviceBusPivot/ServiceBusPivotDataLoader.tsx
client-react/src/pages/app/functions/common/callout/storageAccountPivot/StorageAccountPivot.tsx
client-react/src/pages/app/functions/common/callout/storageAccountPivot/StorageAccountPivotDataLoader.tsx
client-react/src/pages/app/functions/create/DetailsPivot.tsx
client-react/src/pages/app/functions/create/FunctionCreate.data.ts
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

[Ibizafication] Create function can update app settings

---

client/src/app/extension-install/base-extension-install-component.ts

Fixes AB#5661264
Fixes AB#5459564

[Extension Installation] Remove unnecessary final call to bring host online

---

client/src/app/shared/models/constants.ts
client/src/app/shared/services/scenario/dynamic-linux.environment.ts

Turn on CORS for Linux all the time

---

client-react/src/components/DisplayTableWithCommandBar/DisplayTableCommandBarButton.tsx
client-react/src/components/DisplayTableWithCommandBar/DisplayTableWithCommandBar.style.ts

Onclick color fixed for command bar item

---

client-react/src/pages/app/app-settings/Sections/ApplicationSettingsPivot.tsx
client-react/src/pages/app/app-settings/Sections/PathMappingsPivot.tsx

Fixes [AB#5521604](https://msazure.visualstudio.com/Antares/_workitems/edit/5521604)

AB#5521604 Changing info bubbles to subheadings in Config blade

---

client-react/src/components/Panel/Panel.tsx
client-react/src/pages/app/app-settings/ApplicationSettings/ApplicationSettings.tsx
client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMounts.tsx
client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStrings.tsx
client-react/src/pages/app/app-settings/GeneralSettings/ClientCert/ClientCert.tsx
client-react/src/pages/app/app-settings/HandlerMappings/HandlerMappings.tsx
client-react/src/pages/app/app-settings/VirtualApplications/VirtualApplications.tsx
client-react/src/pages/app/functions/app-keys/HostKeys.tsx
client-react/src/pages/app/functions/app-keys/SystemKeys.tsx
client-react/src/pages/app/functions/function-keys/FunctionKeys.tsx

Fixes [AB#5683235](https://msazure.visualstudio.com/Antares/_workitems/edit/5683235)

AB#5683235 Fixing Panel component so that onDismiss gets called when ESC is pressed

---

client/src/app/site/function-runtime/function-runtime.component.html
client/src/app/site/function-runtime/function-runtime.component.ts
server/Resources/Resources.resx

Fixes [AB#5683426](https://msazure.visualstudio.com/Antares/_workitems/edit/5683426)

AB#5683426 Show "Virtual network trigger support" toggle in a disabled state if the runtime version the app is on doesn't support the feature

---

client-react/src/pages/app/app-settings/ApplicationSettings/ApplicationSettings.utils.ts

Duplicate check added for case in app setting bulk add/edit

---

client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMounts.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

Implements AB#5536044
Create:
Edit:

[AzureStorageMounts] Change title when editing vs create

---

client-react/src/pages/app/functions/create/DetailsPivot.tsx
client-react/src/pages/app/functions/create/FunctionCreate.data.ts

[Ibizafication] Close portal blade after function create

---

client-react/src/components/form-controls/ReactiveFormControl.tsx
client-react/src/components/form-controls/formControl.override.styles.tsx
client-react/src/pages/app/app-settings/AppSettings.tsx
client-react/src/pages/app/app-settings/AppSettingsForm.tsx
client-react/src/pages/app/app-settings/Sections/FunctionRuntimeSettingsPivot.tsx
client-react/src/utils/CommonConstants.ts
client-react/src/utils/scenario-checker/function-app.environment.ts
client-react/src/utils/scenario-checker/scenario-ids.ts
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

**Width >= 1000px (No Change)**
**Width < 1000px**
Before
After (controls and info bubbles are aligned with labels)

AB#5525777 Adding empty Function App Setting tab to config blade

---

client-react/src/pages/app/functions/common/CreateFunctionFormBuilder.tsx

[Ibizafication] Add validateFunctionName function

---

client/src/app/controls/tbl/tbl.component.ts
client/src/app/shared/models/portal-resources.ts
client/src/app/site/deployment-center/provider-dashboards/github-action-dashboard/github-action-dashboard.component.html
client/src/app/site/deployment-center/provider-dashboards/github-action-dashboard/github-action-dashboard.component.ts
client/src/app/site/deployment-center/provider-dashboards/kudu-dashboard/kudu-dashboard.component.ts
server/Resources/Resources.resx

Introduce the deployments table.  fixes AB#5757819

Github action introduce deployments table. 

---

client-react/src/ApiHelpers/FunctionsService.ts
client-react/src/ApiHelpers/SiteService.ts
client-react/src/components/form-controls/RadioButtonNoFormik.tsx
client-react/src/models/functions/host-status.ts
client-react/src/models/functions/runtime-extension.ts
client-react/src/pages/app/app-settings/AppSettings.service.ts
client-react/src/pages/app/app-settings/AppSettings.tsx
client-react/src/pages/app/app-settings/AppSettings.types.ts
client-react/src/pages/app/app-settings/AppSettingsDataLoader.tsx
client-react/src/pages/app/app-settings/AppSettingsForm.tsx
client-react/src/pages/app/app-settings/AppSettingsFormData.ts
client-react/src/pages/app/app-settings/FunctionRuntimeSettings/RuntimeVersion.tsx
client-react/src/pages/app/app-settings/FunctionRuntimeSettings/RuntimeVersionControl.tsx
client-react/src/pages/app/app-settings/Sections/FunctionRuntimeSettingsPivot.tsx
client-react/src/theme/CustomOfficeFabric/AzurePortal/Dropdown.styles.ts
client-react/src/utils/CommonConstants.ts
client-react/src/utils/FunctionsRuntimeVersionHelper.ts
client-react/src/utils/scenario-checker/linux-site.environment.ts
client-react/src/utils/scenario-checker/scenario-ids.ts
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

**width > 1000px**
**width <= 1000px**
**width > 1000px**
**width <= 1000px**
**width > 1000px**
**width <= 1000px**
**width > 1000px**
**width <= 1000px**
**width > 1000px**
**width <= 1000px**
**width > 1000px**
**width <= 1000px**
**width > 1000px**
**width <= 1000px**
**width > 1000px**
**width <= 1000px**
**width > 1000px**
**width <= 1000px**

AB#5525777 Adding RuntimeVersion

---

client/src/app/function-manage/function-manage.component.ts
client/src/app/shared/models/function-info.ts
client/src/app/shared/services/function.service.ts

Force get function call in managed tab

---

client-react/src/pages/app/functions/quickstart/FunctionQuickstart.tsx

Iconadded in dropdown title

---

client-react/src/pages/app/log-stream/LogStreamData.ts

[Logstream] Auto-Enable App Logs for Linux and Xenon Apps

---

client-react/src/pages/app/app-settings/FunctionRuntimeSettings/RuntimeVersionControl.tsx
client/src/app/shared/models/portal-resources.ts
client/src/app/site/function-runtime/function-runtime.component.ts
server/Resources/Resources.resx

[Functions Runtime] Remove preview from ~3

---

client-react/src/components/form-controls/formControl.override.styles.tsx
client-react/src/models/site/config.ts
client-react/src/pages/app/app-settings/AppSettings.tsx
client-react/src/pages/app/app-settings/AppSettingsDataLoader.tsx
client-react/src/pages/app/app-settings/FunctionRuntimeSettings/RuntimeScaleMonitoring.tsx
client-react/src/pages/app/app-settings/Sections/FunctionRuntimeSettingsPivot.tsx
client-react/src/utils/FwLinks.ts
client-react/src/utils/scenario-checker/elastic-premium.environment.ts
client-react/src/utils/scenario-checker/scenario-ids.ts
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

**width > 1000px**
**width <= 1000px**
**width > 1000px**
**width <= 1000px**

AB#5457203 Adding RuntimeScaleMonitoring

---

client/src/app/shared/models/portal-resources.ts
client/src/app/site/deployment-center/deployment-center-setup/step-configure/configure-github/configure-github.component.html
client/src/app/site/deployment-center/deployment-center-setup/step-configure/configure-github/configure-github.component.ts
client/src/app/site/deployment-center/deployment-center-setup/wizard-logic/github.service.ts
server/Resources/Resources.resx

Show a warning message if the workflow file already exists

---

client-react/src/components/form-controls/ReactiveFormControl.tsx
client-react/src/components/form-controls/formControl.override.styles.tsx
client-react/src/pages/app/app-settings/AppSettings.styles.ts
client-react/src/pages/app/app-settings/AppSettingsForm.tsx
client-react/src/pages/app/functions/common/callout/storageAccountPivot/StorageAccountPivot.tsx
client-react/src/pages/app/functions/create/DetailsPivot.tsx
client-react/src/pages/app/functions/create/FunctionCreate.styles.ts

**General Settings - Wide**
Before
After
**General Settings - Narrow**
Before
After
**Application Settings - Wide**
Before
After
**Application Settings - Narrow**
Before
After
Before
After

AB#5845704 Fixing alignment for headings, labels and controls in Config blade

---

client/src/app/site/deployment-center/deployment-center-setup/wizard-logic/github.service.ts

sample can be found at https://github.com/azure/webapps-deploy

Match the sample yml file exactly

---

client-react/src/pages/app/app-settings/AppSettings.service.ts

Fixes https://msazure.visualstudio.com/Antares/_workitems/edit/5854429

AB#5854429 Inserting .NET Core 3.1 into availableStacks API response for Linux

---

client-react/src/pages/app/functions/create/DetailsPivot.tsx

[Ibizafication][Function Create]Change text to spinner after button click

---

client/src/app/site/deployment-center/provider-dashboards/credentials-dashboard/credentials-dashboard.component.ts

* handle error case for credentials dashboard
* PR Comments

handle error case for credentials dashboard (#4346)

---

client/src/app/site/site-manage/site-manage.component.ts

Set the actual  OS rather than just the boolean value.

---

client/src/app/shared/models/constants.ts

[Functions][Runtime Settings] Update nodeVersionV2

---

client/src/app/site/function-runtime/function-runtime.component.html
client/src/app/site/function-runtime/function-runtime.component.ts

[Functions][Runtime Settings] Expose Runtime toggle for Linux

---

client/src/app/shared/services/function-app.service.ts

[Functions] Add master key identifier

---

client-react/src/pages/app/functions/function-editor/FunctionEditor.tsx
client-react/src/pages/app/functions/function-editor/FunctionEditorFileSelectorBar.tsx
client-react/src/utils/string.ts

File separator added and dropdown replaced with label

---

client/src/app/shared/services/site.service.ts
client/src/app/shared/services/subscription.service.ts
client/src/app/shared/shared.module.ts
client/src/app/site/deployment-center/deployment-center-setup/wizard-logic/deployment-center-state-manager.ts
client/src/app/site/deployment-center/deployment-center.component.ts
client/src/app/site/deployment-center/provider-dashboards/deployment-credentials/deployment-credentials.component.ts
client/src/app/site/deployment-center/provider-dashboards/kudu-dashboard/kudu-dashboard.component.ts
client/src/app/site/deployment-center/provider-dashboards/vso-Dashboard/vso-dashboard.component.ts

Clean up deployment center code a bit before making futher github action updates

---

server/src/constants.ts
server/src/functions/functions.controller.ts
server/src/functions/functions.service.ts

Language support added in Quickstart Panel

---

client/src/app/shared/services/function-app.service.ts

Will merge as separate commits (not squash)

Cherry-pick Host key updates into master

---

client/src/app/function-monitor/function-monitor.module.ts
client/src/app/functions.module.ts
client/src/app/ibiza-feature/function-monitor-shell/function-monitor-shell.component.html
client/src/app/ibiza-feature/function-monitor-shell/function-monitor-shell.component.ts
client/src/app/ibiza-feature/function-monitor-shell/function-monitor-shell.module.ts
client/src/app/ibiza-feature/ibiza-feature.module.ts
client/src/app/shared/resourceDescriptors.ts
client/src/app/shared/services/application-insights.service.ts
client/src/app/shared/shared-functions.module.ts

FW: Adding support to iframe the Angular Functions monitor experience

---

client/src/app/function-manage/function-manage.component.html
client/src/app/function-manage/function-manage.component.ts
client/src/app/functions-list/functions-list.component.html
client/src/app/functions-list/functions-list.component.ts

[Functions][V3] Update version checks for enable/disable

---

client-react/src/components/monaco-editor/monaco-editor.tsx
client-react/src/pages/app/functions/function-editor/FunctionEditor.tsx

Auto-format json in JSON.stringify

---

client-react/src/ArmTokenContext.ts
client-react/src/models/portal-models.ts
client-react/src/pages/App.tsx
client-react/src/pages/app/log-stream/LogStreamDataLoader.tsx
client-react/src/portal-communicator.ts
client/src/app/shared/models/portal.ts
client/src/app/shared/services/portal.service.ts

Fixes https://msazure.visualstudio.com/Antares/_workitems/edit/5984468

AB#5984468 Switch to using SendToken2 instead of SendToken

---

client-react/src/pages/app/functions/function-editor/function-test/FunctionTest.styles.ts
client-react/src/pages/app/functions/function-editor/function-test/FunctionTestOutput.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

[Function Editor] Text and styling changed for editor output

---

client/package-lock.json
client/src/app/shared/services/application-insights.service.ts

The AI team has requested that we send in a static string as the source parameter.

AB#5993323 - Update source parameter for AI telemetry

---

server/Resources/Resources.resx
server/Resources/cs-CZ/Server/Resources/Resources.resx
server/Resources/de-DE/Server/Resources/Resources.resx
server/Resources/es-ES/Server/Resources/Resources.resx
server/Resources/fr-FR/Server/Resources/Resources.resx
server/Resources/hu-HU/Server/Resources/Resources.resx
server/Resources/it-IT/Server/Resources/Resources.resx
server/Resources/ja-JP/Server/Resources/Resources.resx
server/Resources/ko-KR/Server/Resources/Resources.resx
server/Resources/nl-NL/Server/Resources/Resources.resx
server/Resources/pl-PL/Server/Resources/Resources.resx
server/Resources/pt-BR/Server/Resources/Resources.resx
server/Resources/pt-PT/Server/Resources/Resources.resx
server/Resources/qps-ploc/Server/Resources/Resources.resx
server/Resources/ru-RU/Server/Resources/Resources.resx
server/Resources/sv-SE/Server/Resources/Resources.resx
server/Resources/tr-TR/Server/Resources/Resources.resx
server/Resources/zh-CN/Server/Resources/Resources.resx
server/Resources/zh-TW/Server/Resources/Resources.resx

Reverts Azure/azure-functions-ux#4429

Revert "S130: Update localized strings"

---

client-react/src/models/site/config.ts
client-react/src/pages/app/app-settings/AppSettingsDataLoader.tsx

Fixes https://msazure.visualstudio.com/Antares/_workitems/edit/6039655

AB#6039655 Don't include the 'ipSecurityRestrictions' or 'scmIpSecurityRestrictions' properties in the config/web payload

---

client-react/src/pages/app/functions/function-editor/FunctionEditor.tsx

Old
New (Same screen size as above)
(Smaller screen size)

[Function Editor] Update Styling of Editor

---

client-react/src/models/functions/host-status.ts
client-react/src/pages/app/app-settings/FunctionRuntimeSettings/RuntimeVersion.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

Fixes https://msazure.visualstudio.com/Antares/_workitems/edit/4222382

AB#4222382 Show Extension bundle version in Function Runtime Settings tab

---

client-react/src/pages/app/functions/create/DetailsPivot.tsx

Initial pristine state is valid

---

client-react/src/ApiHelpers/FunctionsService.ts
client-react/src/pages/app/app-files/AppFiles.tsx
client-react/src/pages/app/app-files/AppFilesDataLoader.tsx

[Function App Editor] Fill dropdown with the files

---

client-react/src/ApiHelpers/FunctionsService.ts
client-react/src/pages/app/app-files/AppFiles.styles.ts
client-react/src/pages/app/app-files/AppFiles.tsx
client-react/src/pages/app/app-files/AppFilesDataLoader.tsx

[Function App Files] App files monaco-editor added

---

client-react/src/ApiHelpers/FunctionsService.ts
client-react/src/pages/app/app-files/AppFiles.styles.ts
client-react/src/pages/app/app-files/AppFiles.tsx
client-react/src/pages/app/app-files/AppFilesDataLoader.tsx
client-react/src/pages/app/functions/function-editor/FunctionEditorFileSelectorBar.tsx

[Function App Editor] App-files file selector added

---

client-react/src/ApiHelpers/FunctionsService.ts
client-react/src/pages/app/app-files/AppFiles.styles.ts
client-react/src/pages/app/app-files/AppFiles.tsx
client-react/src/pages/app/app-files/AppFilesCommandBar.tsx
client-react/src/pages/app/app-files/AppFilesDataLoader.tsx
client-react/src/pages/app/functions/function-editor/FunctionEditorFileSelectorBar.tsx

[Function App Editor] App files command bar

---

client-react/src/components/monaco-editor/monaco-editor.styles.ts
client-react/src/components/monaco-editor/monaco-editor.tsx
client-react/src/pages/app/functions/function-editor/function-test/FunctionTestInput.tsx

Allow for customized height of Monaco editor

---

client-react/src/ApiHelpers/FunctionsService.ts
client-react/src/pages/app/app-files/AppFiles.tsx
client-react/src/pages/app/functions/function-editor/FunctionEditor.tsx
client-react/src/pages/app/functions/function-editor/FunctionEditor.types.ts

[Function App Editor] Save file function added

---

client-react/src/ApiHelpers/FunctionsService.ts
client-react/src/pages/app/SiteRouter.tsx
client-react/src/pages/app/app-files/AppFiles.tsx
client-react/src/pages/app/app-files/AppFilesDataLoader.tsx
client-react/src/pages/app/functions/function-editor/FunctionEditor.tsx
client-react/src/pages/app/functions/function-editor/FunctionEditor.types.ts
client-react/src/utils/EditorManager.ts

[Function App Editor] File content fetched on initial rendering and dropdown change

---

client-react/src/components/ActionBar.tsx
client-react/src/pages/app/functions/function-editor/FunctionEditor.tsx
client-react/src/pages/app/functions/function-editor/function-test/FunctionTest.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

After the mocks are updated, column labels will be added for Query and Headers denoting the required fields.
Updated

[Function Editor] Required field validation added

---

client-react/src/pages/app/functions/integrate/BindingPanel/BindingCreator.tsx
client-react/src/pages/app/functions/integrate/BindingPanel/BindingPanel.tsx
client-react/src/pages/app/functions/integrate/BindingsDiagram/TriggerBindingCard.tsx
client-react/src/pages/app/functions/integrate/FunctionIntegrateDataLoader.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

[Ibizafication][Integrate] Can create new trigger on function that doesn't have one

---

client-react/src/pages/app/functions/function-editor/FunctionEditor.styles.ts
client-react/src/pages/app/functions/function-editor/FunctionEditorFileSelectorBar.tsx

[Function Editor] Dropdown style updated for editor

---

client-react/src/pages/app/functions/function-editor/function-log/FunctionLog.styles.ts
client-react/src/pages/app/functions/function-editor/function-log/FunctionLog.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

[Function Editor] Logstream Command bar buttons added

---

client-react/src/pages/app/functions/function-editor/FunctionEditor.styles.ts
client-react/src/pages/app/functions/function-editor/FunctionEditor.tsx
client-react/src/pages/app/functions/function-editor/function-log/FunctionLog.styles.ts
client-react/src/pages/app/functions/function-editor/function-log/FunctionLog.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

[Function Editor] Log panel expansion added

---

client-react/src/images/Common/down-chevron.svg
client-react/src/pages/app/functions/function-editor/FunctionEditor.styles.ts
client-react/src/pages/app/functions/function-editor/FunctionEditor.tsx
client-react/src/pages/app/functions/function-editor/function-log/FunctionLog.styles.ts
client-react/src/pages/app/functions/function-editor/function-log/FunctionLog.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

Fixes AB#6049318
Smaller Screen-1
Smaller Screen-2

[Function Editor] Function-Log component added

---

client-react/src/pages/app/functions/function-editor/FunctionEditor.styles.ts
client-react/src/pages/app/functions/function-editor/FunctionEditor.tsx
client-react/src/pages/app/functions/function-editor/function-log/FunctionLog.styles.ts
client-react/src/pages/app/functions/function-editor/function-log/FunctionLog.tsx

[Function Editor] Function Log fullscreen support added

---

client-react/src/pages/app/functions/create/FunctionCreate.styles.ts

[Ibizafication][Create Function] Create Card width to percentile

---

client/src/app/function-dev/function-dev.component.ts

[Functions] [Event Grid] Update blade call

---

client/src/app/function-monitor/function-monitor.component.ts
client/src/app/shared/models/constants.ts
client/src/app/shared/services/application-insights.service.ts
client/src/app/shared/services/scenario/azure.environment.ts
client/src/app/shared/services/scenario/national-cloud.environment.ts
client/src/app/site/site-summary/site-summary.component.ts

Changes in this PR:
1. introduce ApplicationInsights connection stirng
2. fix the resource graph request
3. enable for national clouds with a feature flag

Introduce ApplicationInsights connection string

---

client-react/src/pages/app/functions/function-editor/function-test/FunctionTest.styles.ts
client-react/src/pages/app/functions/function-editor/function-test/FunctionTestInput.tsx
client-react/src/pages/app/functions/function-editor/function-test/FunctionTestOutput.tsx

[Function Editor] Labels added and style modified for Function Test

---

client-react/src/models/available-stacks.ts
client-react/src/pages/app/app-settings/AppSettings.service.ts
client-react/src/pages/app/app-settings/GeneralSettings/LinuxStacks/LinuxStacks.tsx
client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/PhpStack.tsx
client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/PythonStack.tsx
client-react/src/utils/stacks-utils.ts
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

Fixes https://msazure.visualstudio.com/Antares/_workitems/edit/5956403
Fixes https://msazure.visualstudio.com/Antares/_workitems/edit/5892816
Fixes https://msazure.visualstudio.com/Antares/_workitems/edit/5956398

AB#5956403 AB#5892816 AB#5956398  Adding '(EOL)' tag to stacks that are end-of-life.

---

client-react/src/QuickPulseQuery/QuickPulseSchema.ts
client-react/src/pages/app/functions/function-editor/function-log/FunctionLog.constants.ts
client-react/src/pages/app/functions/function-editor/function-log/FunctionLog.styles.ts
client-react/src/pages/app/functions/function-editor/function-log/FunctionLog.tsx
client-react/src/utils/CommonConstants.ts

[Ibizafication] [Logstream] Logstream updates

---

client/src/app/site/site-summary/site-summary.component.ts

The initial check has the correct condition. I messed up I updated the code.

fix for AB#6120022 - Update condition for validating if AI is enabled on the app.

---

client-react/src/pages/app/functions/function-editor/FunctionEditor.tsx
client-react/src/pages/app/functions/function-editor/function-log/FunctionLog.styles.ts
client-react/src/pages/app/functions/function-editor/function-log/FunctionLog.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

[Ibizafication][Function Logs] Configure App Insights Message and Open Logs on Save

---

client-react/src/pages/app/functions/function-editor/FunctionEditor.tsx
client-react/src/pages/app/functions/function-editor/function-log/FunctionLog.tsx
client-react/src/pages/app/functions/function-editor/function-test/FunctionTest.styles.ts
client-react/src/pages/app/functions/function-editor/function-test/FunctionTestInput.tsx
client-react/src/theme/CustomOfficeFabric/AzurePortal/Dropdown.styles.ts

Font-size
Header left-padding
Logs Chevron

Function Editor styles updated

---

client-react/src/pages/app/functions/function-editor/FunctionEditor.tsx
client-react/src/pages/app/functions/function-editor/function-log/FunctionLog.styles.ts

Log stream height updated to handle page scrolling

---

client-react/src/pages/app/functions/function-editor/FunctionEditor.tsx
client-react/src/pages/app/functions/integrate/FunctionIntegrate.tsx

Read only banner added Code/Integrate blades

---

client-react/src/pages/app/functions/function-editor/function-log/FunctionLog.styles.ts
client-react/src/pages/app/functions/function-editor/function-log/FunctionLog.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

[Ibizafication][Function Logs] Connecting message and auto connect on opening

---

client-react/src/components/EditModeBanner/EditModeBanner.styles.ts
client-react/src/components/EditModeBanner/EditModeBanner.tsx
client-react/src/models/portal-models.ts
client-react/src/pages/app/SiteRouter.tsx
client-react/src/pages/app/functions/function-editor/FunctionEditor.tsx
client-react/src/pages/app/functions/integrate/FunctionIntegrate.tsx

read only banner created

---

client-react/src/pages/app/functions/function-editor/FunctionEditor.tsx
client-react/src/pages/app/functions/function-editor/function-test/FunctionTest.tsx

Handle the initial sample data in Function Editor

---

client-react/src/pages/app/functions/function-editor/FunctionEditor.tsx
client/src/app/shared/services/utilities.service.ts

Fix the copy button in angular

---

client-react/src/models/site/site.ts
client-react/src/pages/app/app-settings/GeneralSettings/DebuggingLinux.tsx
client-react/src/pages/app/app-settings/GeneralSettings/DebuggingWindows.tsx
client-react/src/pages/app/functions/function-editor/FunctionEditor.tsx
client-react/src/utils/FwLinks.ts
client-react/src/utils/SiteHelper.ts
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

Remote debugging option disabled on flex stamp

---

client/src/app/shared/models/portal-resources.ts
client/src/app/site/function-runtime/function-runtime.component.html
server/Resources/Resources.resx

[Functions] [Function Runtime] Add specific Linux message for disabled runtime

---

client-react/src/components/EditModeBanner/EditModeBanner.tsx
client-react/src/pages/app/functions/function-editor/FunctionEditor.styles.ts
client-react/src/pages/app/functions/function-editor/FunctionEditor.tsx
client-react/src/pages/app/functions/function-editor/function-log/FunctionLog.styles.ts
client-react/src/pages/app/functions/function-editor/function-log/FunctionLog.tsx

Update editor component height if the banner is visible

---

client-react/src/pages/app/functions/create/FunctionCreate.styles.ts
client-react/src/pages/app/functions/create/FunctionCreate.tsx
client-react/src/pages/app/functions/create/TemplatesPivot.tsx
client-react/src/utils/CommonConstants.ts
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

[Ibizafication] [Function Create] Extension Bundles and Message Update

---

server/Resources/Resources.resx

Change file message updated

---

client-react/src/pages/app/app-settings/GeneralSettings/LinuxStacks/LinuxStacks.tsx
client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/PhpStack.tsx
client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/PythonStack.tsx
client-react/src/utils/stacks-utils.ts

* mark Wildfly 14 - Preview as EOL
* only show EOL stacks if configured

Handling EOL stacks in Config UI

---

client-react/src/pages/app/app-files/AppFiles.tsx
client-react/src/pages/app/functions/function-editor/FunctionEditor.tsx

Disable editor on read only and while running the function

---

client/src/app/shared/models/arm/site.ts
client/src/app/shared/models/constants.ts
client/src/app/shared/models/portal-resources.ts
client/src/app/site/spec-picker/price-spec-manager/plan-price-spec-manager.ts
client/src/app/site/spec-picker/spec-picker.component.html
client/src/app/site/spec-picker/spec-picker.component.ts
server/Resources/Resources.resx

Fixes AB#6049360
**App in Flex stamp:**
**App not in flex stamp:**

AB#6049360 Add IP Address change notification on spec picker

---

client/src/app/shared/models/constants.ts
client/src/app/shared/services/scenario/national-cloud.environment.ts

remove feature flags for enabling AI on mooncake and fairfax

---

client-react/src/pages/app/functions/function-keys/FunctionKeyAddEdit.tsx
client-react/src/pages/app/functions/function-keys/FunctionKeys.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

Disable button and rename empty message

---

client/src/app/shared/models/portal-resources.ts
client/src/app/site/deployment-center/Models/deployment-enums.ts
client/src/app/site/deployment-center/Models/github.ts
client/src/app/site/deployment-center/deployment-center-setup/deployment-center-setup.component.ts
client/src/app/site/deployment-center/deployment-center-setup/step-complete/step-complete.component.html
client/src/app/site/deployment-center/deployment-center-setup/step-complete/step-complete.component.ts
client/src/app/site/deployment-center/deployment-center-setup/step-configure/configure-github/configure-github.component.html
client/src/app/site/deployment-center/deployment-center-setup/step-configure/configure-github/configure-github.component.ts
client/src/app/site/deployment-center/deployment-center-setup/wizard-logic/deployment-center-setup-models.ts
client/src/app/site/deployment-center/deployment-center-setup/wizard-logic/deployment-center-state-manager.ts
server/Resources/Resources.resx

If the user decides to overwrite
We show an info message
If the user decides to use existing
If the user decides to switch branch

Add a required option for the user to select to either overwrite configuration or use existing.

---

server/src/quickstart/coretoolsDirectPublish-react.md
server/src/quickstart/mavenDirectPublish-react.md
server/src/quickstart/vsDirectPublish-react.md
server/src/quickstart/vscodeDirectPublish-react.md

Links updated to use anchor tags in markdown files

---

client-react/src/pages/app/functions/app-keys/AppKeyAddEdit.tsx
client-react/src/pages/app/functions/app-keys/AppKeysPivot.tsx
client-react/src/pages/app/functions/app-keys/HostKeys.tsx
client-react/src/pages/app/functions/app-keys/SystemKeys.tsx
client-react/src/pages/app/functions/function-keys/FunctionKeyAddEdit.tsx
client-react/src/pages/app/functions/function-keys/FunctionKeys.tsx

disable editing for keys in read-only mode

---

client-react/src/pages/app/functions/function-editor/function-test/FunctionTest.tsx
client-react/src/utils/constants/ValidationRegex.ts

Name Regex Validation added 

---

client-react/src/pages/app/app-settings/ApplicationSettings/AppSettingsBulkEdit.tsx
client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStringsBulkEdit.tsx

Fix Monaco editor height for config bulk add/edit

---

client-react/src/pages/app/functions/quickstart/FunctionQuickstart.tsx
client-react/src/utils/string.ts

Fixes AB#6217485
New
Old
(Last line specifically)

format string with variables in quickstart panel

---

server/src/stacks/stacks.webapp.create.service.ts

Update .net core 3.0 title

---

client-react/src/pages/app/functions/function-editor/function-log/FunctionLog.tsx

Fixes AB#6216758
Fixes AB#6215993

[Ibizafication] [Function Logs] Don't show undefined logs and remove loading message on clear

---

server/src/stacks/stacks.functionapp.config.service.ts
server/src/stacks/stacks.functionapp.create.service.ts
server/src/stacks/stacks.ts

AB#6222548 Update Fusion server with new functionAppStacks json to match API output

---

client-react/src/pages/app/functions/create/FunctionCreate.styles.ts
client-react/src/pages/app/functions/create/TemplatesPivot.tsx

[Ibizafication][Function Create] Use warning box for bundles message

---

client-react/src/components/form-controls/DropDown.tsx
client-react/src/models/functions/host-status.ts
client-react/src/pages/app/functions/integrate/BindingPanel/BindingCreator.tsx
client-react/src/pages/app/functions/integrate/BindingPanel/BindingEditor.tsx
client-react/src/pages/app/functions/integrate/BindingPanel/BindingPanel.tsx
client-react/src/pages/app/functions/integrate/FunctionIntegrate.data.ts
client-react/src/pages/app/functions/integrate/FunctionIntegrate.tsx
client-react/src/pages/app/functions/integrate/FunctionIntegrateConstants.ts
client-react/src/pages/app/functions/integrate/FunctionIntegrateDataLoader.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

Also makes all the dropdowns consistent
Implements AB#6216349, AB#6185330

[Ibizafication][Integrate] Show only built in bindings if extensions aren't set up

---

client-react/src/pages/app/functions/quickstart/FunctionQuickstart.styles.ts
client-react/src/pages/app/functions/quickstart/FunctionQuickstart.tsx
server/src/quickstart/vscodeDirectPublish-v2.md

chevron icon in md file

---

client-react/src/pages/app/SiteRouter.tsx
client-react/src/utils/SiteHelper.ts

read only mode for deployment slots in consumption apps

---

client-react/src/pages/app/SiteRouter.tsx

Refactor Site Router and add logs

---

client-react/src/components/monaco-editor/monaco-editor.tsx
client-react/src/models/portal-models.ts
client-react/src/pages/app/functions/function-editor/FunctionEditor.tsx
client-react/src/pages/app/functions/function-editor/function-test/FunctionTestInput.tsx
client-react/src/portal-communicator.ts
client-react/src/utils/CommonConstants.ts

Editor theme changed according to the portal theme

---

client/src/app/site/deployment-center/provider-dashboards/credentials-dashboard/credentials-dashboard.component.ts

Add the learnmore link in the typescript file to be consumed by the html page

---

server/src/stacks/stacks.webapp.create.service.ts

add gh action recommended version for python for windows.

---

server/src/stacks/stacks.webapp.create.service.ts

Add recommended dotnet core versions for GitHub Action workflow file

---

client-react/src/pages/app/functions/quickstart/FunctionQuickstart.tsx
client-react/src/pages/app/functions/quickstart/FunctionQuickstart.types.ts

set default selected file on quickstart

---

client-react/src/pages/app/functions/integrate/BindingsDiagram/BindingCard.tsx
server/Resources/Resources.resx

Show updating app settings bindings notification

---

client-react/src/pages/app/functions/function-editor/FunctionEditor.styles.ts
client-react/src/pages/app/functions/function-editor/FunctionEditorCommandBar.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

add tooltip on test button disabled state

---

client-react/src/pages/app/functions/common/ResourceDropdown.tsx

[Ibizafication][Integrate] Fix for "new" not showing up

---

client-react/src/pages/app/log-stream/LogStreamDataLoader.tsx
client-react/src/utils/url.ts

Update Function App Log Stream URL
Fixes AB#6325076

[Function Apps][Log Stream] Remove Duplicate Logs

---

client-react/src/pages/app/functions/function-editor/FunctionEditor.tsx
client-react/src/pages/app/functions/function-editor/FunctionEditorDataLoader.tsx

rbac permission check for function editor

---

client-react/src/ApiHelpers/FunctionsService.ts
client-react/src/models/functions/function-info.ts
client-react/src/pages/app/functions/function-editor/FunctionEditor.tsx
client-react/src/pages/app/functions/function-editor/FunctionEditorDataLoader.tsx
client-react/src/pages/app/functions/function-editor/function-test/FunctionTest.tsx

Get test data from href instead of using it directly from functionInfo

---

client-react/src/pages/app/functions/create/FunctionCreate.tsx
client-react/src/pages/app/functions/create/TemplatesPivot.tsx
server/Resources/Resources.resx

[Ibizafication][Function Create] Fix Pivot Navigation

---

client-react/src/pages/app/functions/integrate/FunctionIntegrate.tsx
client-react/src/pages/app/functions/integrate/FunctionIntegrateCommandBar.tsx
client-react/src/pages/app/functions/integrate/FunctionIntegrateDataLoader.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

Command bar added for Integrate Blade

---

client-react/src/components/form-controls/DropDown.tsx
client-react/src/components/form-controls/DropDownnoFormik.tsx
client-react/src/pages/app/functions/common/BindingFormBuilder.tsx

fix dropdown erorr message

---

client-react/src/ApiHelpers/RuntimeStackService.ts
client-react/src/ApiHelpers/SiteService.ts
client-react/src/pages/app/app-settings/AppSettings.service.ts
client-react/src/utils/CommonConstants.ts
client-react/src/utils/stacks-utils.ts

Fixes https://msazure.visualstudio.com/Antares/_workitems/edit/6167520

AB#6167520 Use new stacks API (behind a feature flag)

---

client-react/src/pages/app/SiteRouter.tsx
client-react/src/pages/app/app-settings/Sections/FunctionRuntimeSettingsPivot.tsx
client-react/src/utils/CommonConstants.ts
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

Site not stopped:
Site stopped:

AB#6259303 Updating Function Runtime Settings UI to handle scenario where app is stopped

---

client/src/app/shared/models/constants.ts
client/src/app/shared/models/portal-resources.ts
client/src/app/site/deployment-center/Models/github.ts
client/src/app/site/deployment-center/deployment-center-setup/step-configure/configure-github/configure-github.component.html
client/src/app/site/deployment-center/deployment-center-setup/step-configure/configure-github/configure-github.component.ts
client/src/app/site/deployment-center/deployment-center-setup/wizard-logic/github.service.ts
server/Resources/Resources.resx

fixes AB#6287713
I would recommend going through the discussions on https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s134?workitem=6287713 to understand why we landed on this issue.

Show an info bubble for protected branches.

---

client-react/src/components/form-controls/DropDown.tsx
client-react/src/components/form-controls/DropDownnoFormik.tsx
client-react/src/pages/app/functions/common/BindingFormBuilder.tsx
client-react/src/pages/app/functions/common/HttpMethodMultiDropdown.tsx

Fixes: AB#6216626, it also fixes a previous unknown bug where deselecting some values would select only the value you tried to remove

[Ibizafication][Inegrate] Move and update multiselect change handling

---

client-react/src/pages/app/functions/common/callout/documentDBPivot/DocumentDBPivot.tsx
client-react/src/pages/app/functions/common/callout/eventHubPivot/EventHubPivot.tsx
client-react/src/pages/app/functions/common/callout/iotHubPivot/IoTHubPivot.tsx
client-react/src/pages/app/functions/common/callout/serviceBusPivot/ServiceBusPivot.tsx

Fixes AB#6388741
They all now basically follow this:

[Ibizafication][Integrate] Set all dropdowns to vertical orientation

---

client-react/src/components/ConfirmDialog/ConfirmDialog.styles.ts
client-react/src/components/ConfirmDialog/ConfirmDialog.tsx
client-react/src/pages/app/functions/integrate/BindingPanel/BindingEditor.tsx
client-react/src/pages/app/functions/integrate/BindingPanel/BindingPanel.tsx
client-react/src/pages/app/functions/integrate/FunctionIntegrate.style.ts
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

delete confirmation asked on integrate blade

---

client-react/src/pages/app/functions/common/ResourceDropdown.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

[Ibizafication][Integrate] Show a placeholder message when no connections found

---

client-react/src/pages/app/functions/integrate/BindingPanel/BindingCreator.tsx

[Ibizafication][Integrate] Sort the bindings by their text

---

client-react/src/pages/app/functions/integrate/BindingsDiagram/BindingCard.tsx

[Ibizafication][Integrate] Fix error messages

---

client-react/src/pages/app/functions/function-editor/FunctionEditor.styles.ts

Background added for File Selector

---

client-react/src/pages/app/functions/function-editor/FunctionEditor.tsx

Set selected file on code editor

---

client-react/src/pages/app/functions/integrate/BindingPanel/BindingEditor.tsx
client-react/src/pages/app/functions/integrate/BindingsDiagram/BindingCard.tsx
client-react/src/pages/app/functions/integrate/FunctionIntegrateDataLoader.tsx
client-react/src/pages/app/functions/monitor/FunctionMonitor.tsx
client-react/src/utils/resourceDescriptors.ts

Move some Ibizafication logic to use ArmFunctionDescriptor. Also, remove CDSFunctionDescriptor!

[Ibizafication][General] Move to ArmFunctionDescriptor

---

client-react/src/components/CustomBanner/CustomBanner.tsx
client-react/src/pages/app/functions/integrate/FunctionIntegrate.tsx
client-react/src/utils/CommonConstants.ts
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

Fixes AB#6379373
With direction
Missing direction

[Ibizafication][Integrate] Add a banner to show if bindings are missing direction

---

client-react/src/components/FormControlWrapper/FormControlWrapper.tsx
client-react/src/components/InfoTooltip/InfoTooltip.tsx

Fixes AB#6217123
Before
After
After (Focused)

[Ibizafication][Integrate] Update the info tooltip to be read by screen reader

---

client-react/src/components/FormControlWrapper/FormControlWrapper.tsx
client-react/src/pages/app/functions/function-editor/function-test/FunctionTestInput.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

Tooltip added to HttpMethod in Test Panel

---

client-react/src/pages/app/functions/function-editor/FunctionEditor.styles.ts
client-react/src/pages/app/functions/function-editor/FunctionEditor.tsx

New
Old
Look closely at a small space just below the file-selector bar 😛

Editor style updated

---

client-react/src/pages/app/functions/integrate/BindingPanel/BindingEditor.tsx

Part of the work for AB#6445294

[Ibizafication][Integrate] Pass data to LogService as it is required

---

client/src/app/controls/form-wizard/components/wizard-navigation-bar.component.scss

WCAG: Hide navigation bar if the width is below 600px

---

client/src/app/api/api-details/api-details.component.ts
client/src/app/api/api-new/api-new.component.ts
client/src/app/ibiza-feature/ibiza-feature.module.ts
client/src/app/ibiza-feature/proxy-detail-shell/proxy-detail-shell.component.html
client/src/app/ibiza-feature/proxy-detail-shell/proxy-detail-shell.component.ts
client/src/app/ibiza-feature/proxy-detail-shell/proxy-detail-shell.module.ts
client/src/app/proxies.module.ts
client/src/app/shared/services/portal.service.ts
client/src/app/shared/shared-functions.module.ts

Support added to iframe Angular Proxy Detail component

---

client-react/src/components/DisplayTableWithEmptyMessage/DisplayTableWithEmptyMessage.tsx

Remove shimmer overlay

---

client-react/package-lock.json
client-react/package.json
client-react/src/ApiHelpers/AppInsightsService.ts
client-react/src/pages/app/functions/invocations/FunctionInvocationDetails.tsx
client-react/src/pages/app/functions/invocations/FunctionInvocations.style.ts
client-react/src/pages/app/functions/invocations/FunctionInvocations.tsx

[Ibizafication][Functions Monitor] Add Message Bar, Update Node Module

---

client-react/src/components/CustomBanner/CustomBanner.styles.ts
client-react/src/components/CustomBanner/CustomBanner.tsx

Dismiss button added on Custom Banner

---

client/src/app/site/site-config/site-config.component.scss

add media to stack up fields on lower resolution

---

client-react/src/pages/app/functions/invocations/FunctionInvocations.style.ts
client-react/src/pages/app/functions/invocations/FunctionInvocations.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

[Ibizafication][Function Monitor] Summary items formatted, dimissible banner

---

client-react/src/components/CustomBanner/CustomBanner.styles.ts

Position updated for dismiss button

---

client-react/src/pages/app/functions/invocations/FunctionInvocations.style.ts
client-react/src/pages/app/functions/invocations/FunctionInvocations.tsx

[Ibizafication][Function Monitor] Cleanup SVG spacing

---

client-react/src/pages/app/app-files/AppFilesCommandBar.tsx
client-react/src/pages/app/functions/function-editor/FunctionEditorCommandBar.tsx

position updated for refresh button

---

client-react/src/pages/app/functions/function-editor/FunctionEditor.styles.ts

padding updated for file selector

---

client-react/src/pages/app/functions/function-editor/FunctionEditor.styles.ts
client-react/src/pages/app/functions/function-keys/FunctionKeys.styles.ts
client-react/src/pages/app/functions/function-keys/FunctionKeys.tsx
server/Resources/Resources.resx

function keys blade updated

---

client-react/src/pages/app/functions/integrate/FunctionIntegrate.style.ts
client-react/src/pages/app/functions/integrate/FunctionIntegrate.tsx
client-react/src/pages/app/functions/integrate/binding-card/BindingCard.styles.ts
client-react/src/pages/app/functions/integrate/binding-card/BindingCard.tsx
client-react/src/pages/app/functions/integrate/binding-card/FunctionNameBindingCard.tsx
client-react/src/pages/app/functions/integrate/binding-card/InputBindingCard.tsx
client-react/src/pages/app/functions/integrate/binding-card/OutputBindingCard.tsx
client-react/src/pages/app/functions/integrate/binding-card/TriggerBindingCard.tsx
client-react/src/theme/SemanticColorsExtended.ts
client-react/src/theme/dark.ts
client-react/src/theme/light.ts

Fixes AB#6185304
Fixes AB#6455670
Fixes AB#6185299
* Set width to exactly 1000
* Change light theme card background to white
* Move icons to the left
All the pictures show icons on the left
Max size
Min size
White background:

[Ibizafication][Integrate] Fit and finish fixes

---

client-react/src/pages/app/functions/function-editor/FunctionEditor.tsx
client-react/src/pages/app/functions/function-editor/FunctionEditor.types.ts
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

confirm dialog added for discard

---

client-react/src/pages/app/functions/common/callout/customPivot/CustomPivot.tsx
client-react/src/pages/app/functions/common/callout/documentDBPivot/DocumentDBPivot.tsx
client-react/src/pages/app/functions/common/callout/eventHubPivot/EventHubPivot.tsx
client-react/src/pages/app/functions/common/callout/iotHubPivot/IoTHubPivot.tsx
client-react/src/pages/app/functions/common/callout/serviceBusPivot/ServiceBusPivot.tsx
client-react/src/pages/app/functions/common/callout/storageAccountPivot/StorageAccountPivot.tsx
client-react/src/pages/app/functions/create/DetailsPivot.tsx

Fixes AB#6306296
Create:
Callout:

[Ibizafication] Use Primary buttons on callouts (and Create)

---

client-react/src/ApiHelpers/SiteService.ts
client-react/src/components/feature-description-card/FeatureDescriptionCard.tsx
client-react/src/images/Common/AppInsights.svg
client-react/src/pages/app/functions/monitor/AppInsightsSetup.tsx
client-react/src/pages/app/functions/monitor/FunctionMonitor.styles.ts
client-react/src/pages/app/functions/monitor/FunctionMonitor.tsx
client-react/src/pages/app/functions/monitor/FunctionMonitorDataLoader.tsx

[Ibizafication][Functions Monitor] Link to configure app insights

---

client-react/src/ApiHelpers/FunctionsService.ts

Update vfs api to pass `/` at the end

---

client-react/src/pages/app/functions/function-log/FunctionLog.constants.ts
client-react/src/pages/app/functions/function-log/FunctionLog.tsx
client-react/src/utils/LogCategories.ts

[Ibizafication][Function Log] Correct Endpoints for FF, MC

---

client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMounts.tsx
client-react/src/pages/app/app-settings/HandlerMappings/HandlerMappings.tsx
client-react/src/pages/app/app-settings/VirtualApplications/VirtualApplications.tsx

Fixes AB#5702833
Reduced panel from full page which looked awkawrd to medium:

[BYOS] Reduce panel size

---

client/src/app/site/spec-picker/spec-picker.component.scss
client/src/sass/common/_variables.scss

Fixes AB#6428385
Fixes AB#6428442
Fixes AB#6428322
I took the colors from Ibiza.

AB#6428385, AB#6428442, AB#6428322 Contrast ratio bugs

---

client-react/src/pages/app/app-settings/FunctionRuntimeSettings/RuntimeVersion.tsx
client-react/src/utils/SiteHelper.ts
client-react/src/utils/arm-utils.ts

Premiumv2 check added for flex stamp

---

client/src/app/controls/group-tabs/group-tabs.component.scss
client/src/app/site/spec-picker/spec-picker.component.scss

Fixes AB#6428411 
Got the colors from Wei-Hung (our designer)

AB#6428411 [Visual Requirements - App Service - Dev/Test] Color contrast ratio of grey foreground over white background is less than 3:1

---

client-react/src/ApiHelpers/AppInsightsService.ts
client-react/src/utils/CommonConstants.ts

[Ibizafication][Function Monitor] Invocations in FF, MC

---

client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx

Show only one banner on the Function-Editor

---

client-react/src/pages/app/functions/function/function-log/FunctionLog.tsx
client-react/src/pages/app/functions/function/function-log/FunctionLog.types.ts
client-react/src/pages/app/functions/function/function-log/FunctionLogCommandBar.tsx
client-react/src/utils/CommonConstants.ts
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx
server/src/stacks/stacks.webapp.create.service.ts

[Ibizafication][Function Logs] Add ability to filter logs

---

client/src/app/shared/models/portal-resources.ts
client/src/app/site/deployment-center/deployment-center-setup/wizard-logic/deployment-center-state-manager.ts
client/src/app/site/deployment-center/deployment-center-setup/wizard-logic/github.service.ts
client/src/app/site/deployment-center/provider-dashboards/github-action-dashboard/github-action-dashboard.component.html
client/src/app/site/deployment-center/provider-dashboards/github-action-dashboard/github-action-dashboard.component.ts
server/Resources/Resources.resx

Missing Repository
Missing Branch
All available

Show errors for missing repository or branch.

---

client/src/app/shared/models/portal-resources.ts
client/src/app/shared/services/site.service.ts
client/src/app/site/deployment-center/provider-dashboards/github-action-dashboard/github-action-dashboard.component.html
client/src/app/site/deployment-center/provider-dashboards/github-action-dashboard/github-action-dashboard.component.ts
server/Resources/Resources.resx

I am still testing through all the various possibilities. But basically in this PR, if the user has elected to delete the workflow file, than we should make the whole process dependent on it. Initially, I had designed that feature as fire and forget. But after some discussions we have landed on following scnearions:
1. If the user elects to delete the workflow file, then block the entire disconnect scenario on ANY error during deletion of the file.
2. if the user does not elect to delete the workflow file, then skip that part, and continue to clear the SCM settings.
3. The file deletion would fail if the file is either already deleted, renamed, or there are permission issues on github. There is no way to identify that from the github API response. So we show a generic message.
4. If the …

Update GitHub Action disconnect scenario 

---

client-react/src/ApiHelpers/FunctionsService.ts

refactor function service

---

client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx
client-react/src/pages/app/functions/function/function-log/FunctionLogFileStreamData.ts
client-react/src/pages/app/functions/function/function-log/FunctionLogFileStreamDataLoader.tsx
client-react/src/utils/scenario-checker/national-cloud.environment.ts
client-react/src/utils/scenario-checker/onprem.environment.ts
client-react/src/utils/scenario-checker/scenario-ids.ts

[Ibizafication][Function Log] Use File-based stream for Blackforest and Onprem

---

client-react/src/pages/app/functions/function/integrate/FunctionIntegrate.tsx

Update banner location on Integrate

---

client-react/src/pages/app/deployment-center/DeploymentCenter.styles.ts
client-react/src/pages/app/deployment-center/DeploymentCenter.tsx
client-react/src/pages/app/deployment-center/DeploymentCenterCommandBar.tsx
client-react/src/pages/app/deployment-center/DeploymentCenterDataLoader.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

Adding empty command bar buttons

---

client-react/src/pages/app/functions/function/function-editor/FunctionEditorDataLoader.tsx

Stringify the response if it is json

---

client-react/src/components/monaco-editor/monaco-editor.tsx

update Monaco Editor read-only state

---

client/src/app/site/deployment-center/deployment-center-setup/step-complete/step-complete.component.ts
client/src/app/site/deployment-center/deployment-center-setup/step-configure/configure-github/configure-github.component.ts
client/src/app/site/deployment-center/provider-dashboards/github-action-dashboard/github-action-dashboard.component.ts

Add more traces for detecting GitHub Action usage.

---

client-react/src/pages/app/functions/function/function-log/FunctionLog.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

[Ibizafication][Functions Logs] Add connected message

---

client-react/src/pages/app/functions/function/function-log/FunctionLog.styles.ts
client-react/src/pages/app/functions/function/function-log/FunctionLogCommandBar.tsx

[Ibizafication][Function Logs] Remove Bottom Command Bar

---

client-react/src/components/EditModeBanner/EditModeBanner.tsx
client-react/src/utils/FwLinks.ts
client-react/src/utils/SiteHelper.ts
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

Learn more link added and string updated for read only state

---

client-react/src/pages/app/functions/function/function-editor/FunctionEditorDataLoader.tsx

Test function irrespective of update query result

---

client-react/src/pages/app/functions/function/invocations/FunctionInvocations.style.ts
client-react/src/pages/app/functions/function/invocations/FunctionInvocations.tsx

Fixes AB#6978810
Fixes AB#6978805
Fixes AB#6978819

[Ibizafication][Functions Monitor] Update Invocations Table Alignment

---

client-react/src/pages/app/functions/function/function-editor/FunctionEditor.data.ts
client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

Handle blacklisted files, change default and show error message

---

client-react/src/pages/app/functions/function/invocations/FunctionInvocations.tsx

[Ibizafication][Function Monitor] Always show Invocation Filter

---

client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx
client-react/src/pages/app/functions/function/function-editor/FunctionEditorDataLoader.tsx

non-http run function logic added

---

client-react/src/pages/app/functions/function/function-editor/FunctionEditor.data.ts
client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx
client-react/src/pages/app/functions/function/function-editor/FunctionEditorDataLoader.tsx
client-react/src/pages/app/functions/function/function-editor/function-test/FunctionTestInput.tsx

Initial steps to run non-http functions

---

client-react/src/pages/app/functions/function/invocations/FunctionInvocations.style.ts

[Ibizafication][Function Monitor] Remove Invocations Summary indent padding

---

client-react/src/pages/App.tsx
client-react/src/pages/static-app/StaticSiteRouter.tsx

StaticSite router init

---

client-react/src/pages/app/functions/function/function-log/FunctionLog.styles.ts
client-react/src/pages/app/functions/function/function-log/FunctionLog.tsx
client-react/src/pages/app/functions/function/function-log/FunctionLogAppInsightsDataLoader.tsx
client-react/src/pages/app/functions/function/function-log/FunctionLogCommandBar.tsx
client-react/src/pages/app/functions/function/invocations/FunctionInvocations.style.ts
client-react/src/pages/app/functions/function/monitor/FunctionMonitor.styles.ts
client-react/src/pages/app/functions/function/monitor/FunctionMonitor.tsx
client-react/src/pages/app/functions/log-stream/LogStreamDataLoader.tsx

[Ibizafication][Function Monitor] Update Log Command Bar Placement

---

client-react/src/pages/static-app/configuration/Configuration.styles.ts
client-react/src/pages/static-app/configuration/Configuration.tsx
client-react/src/pages/static-app/configuration/ConfigurationEnvironmentSelector.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

Jamstack environment selector added

---

client-react/src/pages/static-app/configuration/Configuration.styles.ts
client-react/src/pages/static-app/configuration/Configuration.tsx
client-react/src/pages/static-app/configuration/Configuration.types.ts
client-react/src/pages/static-app/configuration/ConfigurationEnvironmentSelector.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

Configuration table and command bar added

---

client-react/src/pages/static-app/StaticSiteRouter.tsx
client-react/src/pages/static-app/configuration/Configuration.data.ts
client-react/src/pages/static-app/configuration/Configuration.styles.ts
client-react/src/pages/static-app/configuration/Configuration.tsx
client-react/src/pages/static-app/configuration/Configuration.types.ts
client-react/src/pages/static-app/configuration/ConfigurationCommandBar.tsx
client-react/src/pages/static-app/configuration/ConfigurationDataLoader.tsx
client-react/src/pages/static-app/configuration/ConfigurationEnvironmentSelector.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

Static Site Configuration files added

---

client-react/src/ApiHelpers/static-site/ConfigurationService.ts
client-react/src/ApiHelpers/static-site/EnvironmentService.ts
client-react/src/ApiHelpers/static-site/StaticSiteService.ts
client-react/src/models/static-site/environment.ts
client-react/src/models/static-site/static-site.ts
client-react/src/pages/static-app/configuration/Configuration.tsx
client-react/src/pages/static-app/configuration/ConfigurationDataLoader.tsx
client-react/src/pages/static-app/configuration/ConfigurationEnvironmentSelector.tsx
client-react/src/utils/CommonConstants.ts
client-react/src/utils/LogCategories.ts

Get environments and fill up the dropdown

---

server/src/shared/logging/logging.service.ts

add common identifiers to the logging client.

---

server/src/shared/logging/logging.service.ts

This reverts commit 614c0c68450e8ceb4ed6ddc6b3db81d11d654341.

Revert "add common identifiers to the loggin client. (#4810)"

---

client-react/src/pages/static-app/configuration/Configuration.tsx
client-react/src/pages/static-app/configuration/ConfigurationAdvancedAddEdit.tsx

bulk add/edit panel added

---

client-react/src/pages/static-app/configuration/Configuration.tsx
client-react/src/pages/static-app/configuration/ConfigurationAdvancedAddEdit.tsx
client-react/src/pages/static-app/configuration/ConfigurationCommandBar.tsx
client-react/src/pages/static-app/configuration/ConfigurationEnvironmentSelector.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

discard confirm panel added

---

client-react/src/ApiHelpers/static-site/EnvironmentService.ts
client-react/src/pages/static-app/configuration/Configuration.tsx
client-react/src/pages/static-app/configuration/Configuration.types.ts
client-react/src/pages/static-app/configuration/ConfigurationAddEdit.tsx
client-react/src/pages/static-app/configuration/ConfigurationAdvancedAddEdit.tsx
client-react/src/pages/static-app/configuration/ConfigurationCommandBar.tsx
client-react/src/pages/static-app/configuration/ConfigurationDataLoader.tsx
client-react/src/pages/static-app/configuration/ConfigurationEnvironmentSelector.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

Static Site configuration - filter added

---

client-react/src/ApiHelpers/static-site/EnvironmentService.ts
client-react/src/pages/static-app/configuration/Configuration.data.ts
client-react/src/pages/static-app/configuration/Configuration.tsx
client-react/src/pages/static-app/configuration/Configuration.types.ts
client-react/src/pages/static-app/configuration/ConfigurationAddEdit.tsx
client-react/src/pages/static-app/configuration/ConfigurationAdvancedAddEdit.tsx
client-react/src/pages/static-app/configuration/ConfigurationCommandBar.tsx
client-react/src/pages/static-app/configuration/ConfigurationDataLoader.tsx
client-react/src/pages/static-app/configuration/ConfigurationEnvironmentSelector.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

environment variables table filled

---

client-react/src/ApiHelpers/static-site/EnvironmentService.ts
client-react/src/pages/static-app/configuration/Configuration.data.ts
client-react/src/pages/static-app/configuration/Configuration.tsx
client-react/src/pages/static-app/configuration/ConfigurationDataLoader.tsx

Just cherry-picked a commit - 9bdb255 from https://github.com/Azure/azure-functions-ux/pull/4807

[Static Site] Environment Table populated

---

client-react/src/pages/static-app/configuration/Configuration.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

Cherry-picked the commits - 97173bd, bad1536 from https://github.com/Azure/azure-functions-ux/pull/4808

[Static Site] Filter added on the table

---

client-react/src/ApiHelpers/static-site/EnvironmentService.ts
client-react/src/pages/static-app/configuration/Configuration.tsx
client-react/src/pages/static-app/configuration/Configuration.types.ts
client-react/src/pages/static-app/configuration/ConfigurationAddEdit.tsx
client-react/src/pages/static-app/configuration/ConfigurationCommandBar.tsx
client-react/src/pages/static-app/configuration/ConfigurationDataLoader.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

Cherry-picked the commits - f5bdcbe, 32da007 from https://github.com/Azure/azure-functions-ux/pull/4809

[Static Site] Add/Edit panel added

---

client-react/src/pages/static-app/configuration/Configuration.tsx
client-react/src/pages/static-app/configuration/ConfigurationCommandBar.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

Cherry-picked the commits - cf90c0d from https://github.com/Azure/azure-functions-ux/pull/4811

[Static Site] Discard Confirm Dialog added

---

client-react/src/pages/static-app/configuration/Configuration.tsx
client-react/src/pages/static-app/configuration/ConfigurationEnvironmentSelector.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

Cherry-picked the commits - 18b41e9, 96ca2ab, e47a37e from https://github.com/Azure/azure-functions-ux/pull/4812

[Static Site] OnChange Confirm Dialog added

---

client-react/src/pages/static-app/configuration/Configuration.tsx

Cherry-picked the commit - 52100fa from #4813

[Static Site] Delete variable functionality added

---

client/src/app/site/deployment-center/deployment-center.module.ts
client/src/app/site/deployment-center/provider-dashboards/github-action-dashboard/github-action-dashboard.component.html
client/src/app/site/deployment-center/provider-dashboards/github-action-dashboard/github-action-dashboard.component.scss
client/src/app/site/deployment-center/provider-dashboards/github-action-dashboard/github-action-dashboard.component.ts
client/src/app/site/deployment-center/provider-dashboards/github-action-dashboard/github-deployment-detail/github-deployment-detail.component.html
client/src/app/site/deployment-center/provider-dashboards/github-action-dashboard/github-deployment-detail/github-deployment-detail.component.scss
client/src/app/site/deployment-center/provider-dashboards/github-action-dashboard/github-deployment-detail/github-deployment-detail.component.ts

Introduce log details for github action

---

client-react/src/pages/static-app/configuration/Configuration.tsx
client-react/src/pages/static-app/configuration/ConfigurationAdvancedAddEdit.tsx

Cherry-picked the commit - 585327d from #4814

[Static Site] Bulk Add/Edit Panel added

---

client-react/src/pages/static-app/configuration/Configuration.tsx
client-react/src/pages/static-app/configuration/ConfigurationDataLoader.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

[Static Site] Rbac permission added

---

client-react/src/pages/app/deployment-center/DeploymentCenter.tsx
client-react/src/pages/app/deployment-center/DeploymentCenterCommandBar.tsx

Implement browse command in deployment center

---

client-react/src/pages/static-app/configuration/Configuration.tsx

[Static Site] Hide bulk add/edit

---

client/src/app/shared/models/constants.ts
client/src/app/shared/models/portal-resources.ts
client/src/app/shared/services/scenario/national-cloud.environment.ts
client/src/app/shared/services/scenario/onprem.environment.ts
client/src/app/site/site-summary/site-summary.component.ts
package-lock.json
server/Resources/Resources.resx

[Ibizafication][GA] Always show new experience banner, update text

---

client-react/src/pages/static-app/configuration/Configuration.styles.ts
client-react/src/pages/static-app/configuration/Configuration.tsx
client-react/src/pages/static-app/configuration/ConfigurationCommandBar.tsx

[Static Site] Copy button added

---

client-react/src/pages/app/functions/function/invocations/FunctionInvocationDetails.tsx
client-react/src/pages/app/functions/function/invocations/FunctionInvocations.tsx
client-react/src/pages/app/functions/function/invocations/FunctionInvocationsDataLoader.tsx

Fixes AB#6978800
Fixes AB#6978798

[Ibizafication][Function Invocations] Add shimmer to invocations and detail table

---

client-react/src/ApiHelpers/ContainerLogsService.ts
client-react/src/pages/app/deployment-center/DeploymentCenter.data.ts
client-react/src/pages/app/deployment-center/DeploymentCenter.styles.ts
client-react/src/pages/app/deployment-center/DeploymentCenterContainerLogs.tsx
client-react/src/pages/app/deployment-center/DeploymentCenterContainerLogsDataLoader.tsx
client-react/src/pages/app/deployment-center/DeploymentCenterPivot.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

fixes AB#6972505
Loading state
Logs loaded
Failure case

Implement container logs

---

client-react/src/pages/app/functions/app-keys/SystemKeys.tsx

[Ibizafication] Remove new system keys option

---

client-react/src/pages/app/functions/function/function-log/FunctionLog.styles.ts
client-react/src/pages/app/functions/function/function-log/FunctionLog.tsx
client-react/src/pages/app/functions/function/function-log/FunctionLogAppInsightsDataLoader.tsx
client-react/src/pages/app/functions/log-stream/LogStreamDataLoader.tsx
client-react/src/pages/app/log-stream/LogStreamRouter.tsx
client-react/src/utils/scenario-checker/function-app.environment.ts
client-react/src/utils/scenario-checker/scenario-ids.ts

[Ibizafication][Log Stream] Style and Loading Updates

---

client-react/package.json
client-react/src/pages/static-app/configuration/Configuration.tsx
client-react/src/pages/static-app/configuration/ConfigurationAdvancedAddEdit.tsx
tools/pipelines/react-pr-test.yml

[Static Site] Remove react tests and add monaco editor

---

client-react/src/ApiHelpers/ArmHelper.ts
client-react/src/ApiHelpers/ContainerLogsService.ts
client-react/src/ApiHelpers/FunctionsService.ts
client-react/src/ApiHelpers/SiteService.ts
client-react/src/ArmHelper.spec.ts
client-react/src/ArmHelper.types.ts

Change skipBuffer to skipBatching for readability and consistency.

---

client-react/src/pages/static-app/configuration/Configuration.styles.ts
client-react/src/pages/static-app/configuration/Configuration.tsx

Removing this as per the fit and finish meeting, will be re-added with a different style

[Static Site] Copy column removed

---

client-react/src/pages/static-app/configuration/Configuration.tsx
client-react/src/pages/static-app/configuration/ConfigurationDataLoader.tsx

[Static Site] Fix refreshing and show confirm dialog only on dirty

---

client-react/src/pages/app/app-settings/ApplicationSettings/ApplicationSettings.tsx
client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStrings.tsx

Fixes [AB#6101551](https://msazure.visualstudio.com/Antares/_workitems/edit/6101551)

AB#6101551 Adding aria-label to name column in Application Settings table and Connection Strings table

---

client-react/src/pages/app/functions/function/invocations/FunctionInvocations.style.ts
client-react/src/pages/app/functions/function/invocations/FunctionInvocations.tsx

[Invocation][Function Monitor] Scroll on table, not entire page

---

client-react/src/pages/app/functions/function/invocations/FunctionInvocationDetails.tsx

[Ibizafication][Function Monitor] Multi-line message

---

client-react/src/pages/static-app/configuration/Configuration.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

[Static Site] Update Add button text

---

client-react/src/pages/static-app/configuration/Configuration.styles.ts
client-react/src/pages/static-app/configuration/Configuration.tsx
client-react/src/pages/static-app/configuration/ConfigurationEnvironmentSelector.tsx

[Static Site] Update dropdown position

---

client-react/src/pages/static-app/configuration/Configuration.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

[Static Site] Update Add/Edit header on the panel

---

client-react/src/components/form-controls/TextFieldNoFormik.tsx
client-react/src/components/form-controls/formControl.override.styles.tsx

[Static Site] Copy button style updated

---

client-react/src/pages/static-app/configuration/Configuration.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

[Static Site] Add refresh confirm dialog

---

client-react/src/pages/static-app/configuration/Configuration.tsx
client-react/src/utils/FwLinks.ts

[Static Site] Update link on Configuration blade

---

client-react/src/pages/app/functions/app-keys/AppKeysPivot.tsx
client-react/src/pages/app/functions/function/function-keys/FunctionKeys.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

Update description texts for Keys

---

client-react/src/components/MarkdownComponents/MarkdownComponents.styles.ts
client-react/src/components/MarkdownComponents/MarkdownComponents.tsx
client-react/src/components/form-controls/TextFieldNoFormik.tsx
client-react/src/components/form-controls/formControl.override.styles.tsx

Update copy button position and style for the TextField

---

client-react/src/components/form-controls/TextField.tsx
client-react/src/components/form-controls/TextFieldNoFormik.tsx
client-react/src/pages/app/deployment-center/DeploymentCenter.styles.ts
client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts
client-react/src/pages/app/deployment-center/DeploymentCenterContainerPivot.tsx
client-react/src/pages/app/deployment-center/DeploymentCenterDataLoader.tsx
client-react/src/pages/app/deployment-center/DeploymentCenterFtps.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

Introduce the show/hide controls for the password and reset control for the publishing profile password.

Add show, hide, and reset controls to the password fields.

---

client/src/app/shared/models/portal-resources.ts
client/src/app/site/container-settings/container-image-source/container-image-source-dockerhub/container-image-source-dockerhub.component.html
client/src/app/site/container-settings/container-image-source/container-image-source-privateregistry/container-image-source-privateregistry.component.html
server/Resources/Resources.resx

Add placeholder text with examples for container selections

---

client-react/src/pages/app/app-settings/FunctionRuntimeSettings/RuntimeScaleMonitoring.tsx
server/Resources/Resources.resx

Fixes [AB#7086419](https://msazure.visualstudio.com/Antares/_workitems/edit/7086419)
- Enabling Runtime Scale Monitoring toggle even if no vnet is configured
- Updating label and description for Runtime Scale Monitoring toggle.

Runtime Scale Monitoring toggle updates

---

client-react/src/components/CustomBanner/CustomBanner.styles.ts
client-react/src/components/CustomBanner/CustomBanner.tsx
client-react/src/pages/app/app-settings/AppSettings.tsx
client-react/src/pages/app/app-settings/ApplicationSettings/AppSettingAddEdit.tsx
client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMounts.tsx
client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEditAdvanced.tsx
client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEditBasic.tsx
client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStringsAddEdit.tsx
client-react/src/pages/app/app-settings/FunctionRuntimeSettings/DailyUsageQuota.tsx
client-react/src/pages/app/app-settings/FunctionRuntimeSettings/RuntimeVersion.tsx
client-react/src/pages/app/app-settings/FunctionRuntimeSettings/RuntimeVersionBanner.tsx
client-react/src/pages/app/app-settings/GeneralSettings/DebuggingWindows.tsx
client-react/src/pages/app/app-settings/GeneralSettings/SlotAutoSwap.tsx
client-react/src/pages/app/app-settings/Sections/ApplicationSettingsPivot.tsx
client-react/src/pages/app/app-settings/Sections/FunctionRuntimeSettingsPivot.tsx
client-react/src/pages/app/app-settings/Sections/PathMappingsPivot.tsx

Fixes [AB#7110527](https://msazure.visualstudio.com/Antares/_workitems/edit/7110527)

Updating config UI to use CustomBanner

---

client-react/src/pages/app/deployment-center/DeploymentCenter.styles.ts
client-react/src/pages/app/deployment-center/DeploymentCenterFtps.tsx
client/src/app/shared/models/portal-resources.ts
server/Resources/Resources.resx

Add a reset callout for application password reset

---

client-react/src/components/CustomCallout/CustomCallout.styles.ts
client-react/src/components/CustomCallout/CustomFocusTrapCallout.tsx
client-react/src/pages/app/deployment-center/DeploymentCenter.styles.ts
client-react/src/pages/app/deployment-center/DeploymentCenterFtps.tsx

Making this a common component as I will be using it in other areas.

Make a common component for FocusTrapCallout

---

client-react/src/pages/static-app/configuration/Configuration.tsx
client-react/src/pages/static-app/configuration/ConfigurationCommandBar.tsx
client-react/src/pages/static-app/configuration/ConfigurationDataLoader.tsx

[Static Site] Update dirty and API failure state
