client-react/src/pages/app/functions/app-files/AppFiles.tsx
=> [Ibizafication] Read-only banner added on App Files

client-react/src/pages/static-app/configuration/ConfigurationDataLoader.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes AB#7140303
Fixes AB#7140309
=> [Static Site] Notification added on save

server/Resources/Resources.resx
=> system keys typo fixed

client/src/app/site/spec-picker/spec-list/spec-list.component.html, server/Resources/Resources.resx
Fixes AB#7116896 [Programmatic Access - App Service - Dev/Test] Incorrect role as 'radio' is defined for the button controls available under 'Recommended pricing tiers'
Fixes AB#7118117 [Screen Reader - App Service - Dev/Test] Incorrect information is announced when the focus reaches on the 'Apply' button
=> AB#7118117, AB#7116896 Minor accessibility bugs

client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/DeploymentCenterCommandBar.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterContainerForm.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterDataLoader.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterFtps.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
NOTE - I will introduce a concept of FormBuilder once more form components are added. No need to over optimize right now.
Initial load with an empty form:
Username min requirements:
Password validation:
=> Introduce form validation

client-react/src/ApiHelpers/RuntimeStackService.ts, client-react/src/utils/CommonConstants.ts, client/src/app/shared/models/constants.ts, client/src/app/shared/services/runtimestack.service.ts
=> [Stacks] Update api version in fusion calls

server/Resources/Resources.resx
=> [Static Site] Update banner string

client-react/src/components/form-controls/RadioButton.tsx, client-react/src/models/site/config.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.data.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/DeploymentCenterContainerSettings.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterContainerSource.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterDataLoader.tsx, client-react/src/theme/CustomOfficeFabric/AzurePortal/ChoiceGroup.styles.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> Start adding content to container settings tab

client-react/src/ApiHelpers/FunctionsService.ts
* [Functions][Editor] Fixing browser file caching issues
* Updating helper function name
* Updated function names
=> [Functions][Editor] Fixing browser file caching issues (#4905)

client-react/src/pages/static-app/configuration/Configuration.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> [Static Site] Toggle the filter field to be visible at all times

client-react/src/pages/app/app-settings/AppSettings.tsx
Fixes [AB#7105340](https://msazure.visualstudio.com/Antares/_workitems/edit/7105340)
=> AB#7105340 Stop calling preventDefault() on all enter keypress events on AppSettings form

client-react/src/pages/app/deployment-center/DeploymentCenter.data.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/DeploymentCenterContainerAcrSettings.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterContainerDockeHubSettings.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterContainerFormBuilder.ts, client-react/src/pages/app/deployment-center/DeploymentCenterContainerPivot.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterContainerPrivateRegistrySettings.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterContainerRegistrySettings.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterContainerSettings.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterDataLoader.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterGitHubProvider.tsx, client-react/src/utils/CommonConstants.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Add individual files to start working on the individual container source forms. Also refactoring the formData generation and validation schema generation.
=> Introduce the separate files for docker options

client-react/src/pages/app/functions/function/function-editor/FunctionEditor.types.ts, client-react/src/pages/app/functions/function/function-editor/FunctionEditorDataLoader.tsx, client-react/src/pages/app/functions/function/function-editor/FunctionEditorGetFunctionUrlCallout.tsx
=> [Ibizafication] Update function url to include segregate system urls from host urls

client/src/app/shared/models/portal-resources.ts, client/src/app/shared/validators/slotNameValidator.ts, server/Resources/Resources.resx
Fixes [AB#5764672](https://msazure.visualstudio.com/Antares/_workitems/edit/5764672)
=> AB#5764672 Updating SlotNameValidator to enforce 60 character limit on combined site and slot name

client-react/src/pages/app/functions/function/function-editor/function-test/FunctionTest.tsx, client-react/src/utils/FwLinks.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> [Ibizafication] Add private link banner message

client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/DeploymentCenterCommandBar.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterDataLoader.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx, client-react/src/pages/app/deployment-center/publish-profile/DeploymentCenterPublishProfileCommandBar.tsx, client-react/src/pages/app/deployment-center/publish-profile/DeploymentCenterPublishProfilePanel.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
fixes AB#6972406
fixes AB#6972435
I am not sure why portal decided to go with the crazy amounts of white space, but that is not in my control. Please let me know I am incorrect about it.
I could not use the confirm dialog as that spans across the entire blade. Also I believe the focus callout looks a lot cleaner.
=> [DeploymentCenterPreview] Implement manage publish profile command

server/Resources/Resources.resx
=> Update host keys description string

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerFormBuilder.ts, client/src/app/site/deployment-center/provider-dashboards/credentials-dashboard/credentials-dashboard.component.ts, client/src/app/site/deployment-center/provider-dashboards/deployment-credentials/deployment-credentials.component.ts, server/Resources/Resources.resx
=> Update the user credential password requirements to match API requirements.

client-react/src/pages/app/functions/function/function-editor/FunctionEditorCommandBar.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> [Ibizafication] Test button updated

client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/DeploymentCenterDataLoader.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeLogs.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodePivot.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerPivot.tsx, client-react/src/pages/app/functions/function/function-editor/FunctionEditorCommandBar.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> Created deployment center split for code and container and created placeholder pages for code

client-react/src/pages/app/functions/function/function-log/FunctionLog.styles.ts
=> [Ibizafication] Update font for logs panel, to be similar to angular

client-react/src/ApiHelpers/AppInsightsService.ts, client-react/src/components/CustomBanner/CustomBanner.styles.ts, client-react/src/components/CustomBanner/CustomBanner.tsx, client-react/src/models/app-insights.ts, client-react/src/pages/app/functions/function/monitor/FunctionMonitor.tsx, client-react/src/pages/app/functions/function/monitor/FunctionMonitorDataLoader.tsx, client-react/src/utils/CommonConstants.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes AB#7264610
Functions where App-Insights key is valid
=> [Ibizafication] App insights warning banner added for KeyVault reference

client-react/src/pages/app/functions/app-keys/AppKeysDataLoader.tsx
=> [Ibizafication] Enable AppKeys management in rbac mode

client-react/src/pages/app/functions/app-keys/AppKeys.styles.ts
=> [Ibizafication] Change filter box width

client-react/src/pages/app/app-settings/AppSettingsDataLoader.tsx
=> Remove slot check  for keyVault

client-react/src/pages/app/functions/function/function-log/FunctionLogAppInsightsDataLoader.tsx
=> [Function][Logs] Enforce sort order by sequencenumber

client-react/src/components/DisplayTableWithEmptyMessage/DisplayTableWithEmptyMessage.tsx, client-react/src/components/form-controls/formControl.override.styles.tsx
=> update detail list header

client-react/src/components/CustomPanel/CustomPanel.styles.ts
=> Remove panel padding-top

client-react/src/components/form-controls/formControl.override.styles.tsx, client-react/src/pages/app/app-settings/AppSettings.styles.ts, client-react/src/pages/app/app-settings/ApplicationSettings/ApplicationSettings.tsx, client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStrings.tsx, client-react/src/pages/app/functions/app-keys/AppKeys.styles.ts, client-react/src/pages/app/functions/app-keys/HostKeys.tsx, client-react/src/pages/app/functions/app-keys/SystemKeys.tsx, client-react/src/pages/app/functions/function/function-keys/FunctionKeys.styles.ts, client-react/src/pages/app/functions/function/function-keys/FunctionKeys.tsx, client-react/src/pages/app/functions/function/invocations/FunctionInvocations.style.ts, client-react/src/pages/app/functions/function/invocations/FunctionInvocations.tsx, client-react/src/pages/static-app/configuration/Configuration.tsx
Fixes AB#7281286
AppSettings
AppKeys
Monitor
FunctionKeys
=> [Ibizafication] Update filter box on all blades

client-react/src/pages/app/functions/function/function-editor/function-test/FunctionTest.tsx
=> [Function Editor] Update useEffect in Input tab

client-react/src/pages/app/deployment-center/DeploymentCenter.styles.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeLogs.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerLogs.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes ab#7278528
Fixes ab#7278522
=> Displaying list of deployments for deployment center code logs, displaying empty side panel

client-react/src/pages/app/functions/app-keys/AppKeys.styles.ts, client-react/src/pages/app/functions/app-keys/AppKeys.tsx, client-react/src/pages/app/functions/app-keys/AppKeysCommandBar.tsx, client-react/src/pages/app/functions/app-keys/AppKeysDataLoader.tsx, client-react/src/pages/app/functions/app-keys/AppKeysPivot.tsx, client-react/src/pages/app/functions/app-keys/HostKeys.tsx, client-react/src/pages/app/functions/app-keys/SystemKeys.tsx
Fixes AB#7294796
Fixes AB#7235787
=> [Ibizafication] AppKeys enabled for all scenarios (except when site is stopped) and Spinner removed

client-react/src/pages/app/SiteRouter.tsx, client-react/src/utils/LogCategories.ts
=> [Ibizafication] Read-only added for deployment slot

client-react/src/pages/app/functions/function/function-keys/FunctionKeys.tsx, client-react/src/pages/app/functions/function/function-keys/FunctionKeysCommandBar.tsx, client-react/src/pages/app/functions/function/function-keys/FunctionKeysDataLoader.tsx
Fixes AB#7294796
Fixes AB#7235787
=> [Ibizafication] FunctionKeys enabled for all read-only scenarios and Spinner removed

client-react/src/ApiHelpers/SiteService.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.data.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeLogs.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCommitLogs.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> Deployment center code logs panel displaying data, log details viewable on panel

client-react/src/components/DisplayTableWithCommandBar/DisplayTableWithCommandBar.style.ts, client-react/src/components/DisplayTableWithCommandBar/DisplayTableWithCommandBar.tsx, client-react/src/components/DisplayTableWithEmptyMessage/DisplayTableWithEmptyMessage.tsx
=> [Ibizafication] Set detail list height similar to Ibiza

client-react/src/components/form-controls/ReactiveFormControl.tsx, client-react/src/components/form-controls/formControl.override.styles.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubAccount.tsx
FTPS before
FTP after
The Github UX is still good
=> Fix the styling on the reactive form control.

client-react/src/components/DisplayTableWithCommandBar/DisplayTableWithCommandBar.style.ts
All the other blades are same 
The only difference in on Monitoring experience
New
Old
=> [Ibizafication] Fix detail list height in overflow cases

client-react/src/utils/scenario-checker/national-cloud.environment.ts, client/src/app/shared/services/scenario/national-cloud.environment.ts
Work for AB#7305949
Work for AB#7305952
=> [Functions][Monitor] Enable App Insights Function Monitor in Fairfax & Mooncake

client/src/app/site/deployment-center/deployment-center-setup/wizard-logic/github.service.ts
=> [GitHub Action] add python version to the oryx build

client-react/src/utils/textUtilities.ts
=> Fix scroll to bottom issue on click of copy button in Deployment Center code FTP/FTPs credentials tab

client-react/src/ApiHelpers/AppInsightsService.ts, client-react/src/pages/app/functions/function/invocations/FunctionInvocations.data.ts, client-react/src/pages/app/functions/function/invocations/FunctionInvocations.tsx, client-react/src/pages/app/functions/function/invocations/FunctionInvocationsDataLoader.tsx
=> [Functions][Monitor] Modify App Insights Query for Slots

server/src/stacks/webapp/2020-06-01/stack.model.ts, server/src/stacks/webapp/2020-06-01/stacks/aspDotnet.ts, server/src/stacks/webapp/2020-06-01/stacks/node.ts, server/src/stacks/webapp/2020-06-01/stacks/ruby.ts
Fixes AB#7339494
Fixes AB#7339519
Fixes AB#7339534
=> [Stacks][WebApp][V2] Create New Model & Combine Some Create/Config Stacks

client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx, client-react/src/pages/app/functions/function/function-editor/function-test/FunctionTest.tsx, client-react/src/pages/app/functions/function/function-editor/function-test/FunctionTestInput.tsx, client-react/src/pages/app/functions/function/function-editor/function-test/FunctionTestOutput.tsx, client-react/src/utils/string.ts
Fixes AB#7332813
The only real change is on lines 176, 113, 141. Rest are just a part of refactoring
=> [ibizafication] Handle non-http function's body differently than for http

server/src/stacks/webapp/2020-06-01/stacks/php.ts, server/src/stacks/webapp/2020-06-01/stacks/python.ts
Fixes AB#7339546
Fixes AB#7339612
=> [Stacks][WebApp][V2] Add Python & PHP Stacks

client-react/src/components/DisplayTableWithCommandBar/DisplayTableWithCommandBar.style.ts, client-react/src/pages/app/app-settings/ApplicationSettings/ApplicationSettings.tsx, client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStrings.tsx, client-react/src/pages/app/functions/app-keys/HostKeys.tsx, client-react/src/pages/app/functions/app-keys/SystemKeys.tsx, client-react/src/pages/app/functions/function/function-keys/FunctionKeys.tsx
=> [Ibizafication] Update hidden value in DetailList

client-react/src/components/form-controls/ToggleNoFormik.tsx
Fixes AB#7352473
Accidentally added in a extra label in a previous commit
Prod
Canary
New
=> [Ibizafication][Integrate] Fix double label on Toggle

client-react/src/components/form-controls/DropDown.tsx, client-react/src/components/form-controls/DropDownnoFormik.tsx, client-react/src/pages/app/functions/common/BindingFormBuilder.tsx, client-react/src/pages/app/functions/common/ResourceDropdown.tsx, client-react/src/pages/app/functions/common/callout/Callout.styles.ts, client-react/src/pages/app/functions/common/callout/documentDBPivot/DocumentDBPivot.tsx, client-react/src/pages/app/functions/common/callout/eventHubPivot/EventHubPivot.tsx, client-react/src/pages/app/functions/common/callout/iotHubPivot/IoTHubPivot.tsx, client-react/src/pages/app/functions/common/callout/serviceBusPivot/ServiceBusPivot.tsx, client-react/src/pages/app/functions/common/callout/storageAccountPivot/StorageAccountPivot.tsx
Part of AB#7351973
Before:
After:
Before:
After:
=> [Ibizafication][WCAG][Integrate] Remove FormControlWrapper from connection pivots

server/src/stacks/webapp/2020-06-01/stacks/dotnetCore.ts
=> [Stacks][WebApp][V2] Add Dotnet Stack

client-react/src/components/form-controls/DropDown.tsx, client-react/src/components/form-controls/DropDownnoFormik.tsx, client-react/src/components/form-controls/ReactiveFormControl.tsx, client-react/src/pages/app/functions/common/BindingFormBuilder.tsx, client-react/src/pages/app/functions/common/CreateFunctionFormBuilder.tsx, client-react/src/pages/app/functions/common/callout/documentDBPivot/DocumentDBPivot.tsx, client-react/src/pages/app/functions/common/callout/eventHubPivot/EventHubPivot.tsx, client-react/src/pages/app/functions/common/callout/iotHubPivot/IoTHubPivot.tsx, client-react/src/pages/app/functions/common/callout/serviceBusPivot/ServiceBusPivot.tsx, client-react/src/pages/app/functions/common/callout/storageAccountPivot/StorageAccountPivot.tsx, client-react/src/pages/app/functions/function/integrate/BindingPanel/BindingCreator.tsx, client-react/src/pages/app/functions/function/integrate/BindingPanel/BindingEditor.tsx
Fix from previous PR #5010
Horizontal (Contrived, not very good, example)
Vertical
=> [Ibizafication][Integrate] Change horizontal prop to be layout instead

server/src/stacks/webapp/2020-06-01/stack.model.ts, server/src/stacks/webapp/2020-06-01/stacks/aspDotnet.ts, server/src/stacks/webapp/2020-06-01/stacks/dotnetCore.ts, server/src/stacks/webapp/2020-06-01/stacks/node.ts, server/src/stacks/webapp/2020-06-01/stacks/php.ts, server/src/stacks/webapp/2020-06-01/stacks/python.ts, server/src/stacks/webapp/2020-06-01/stacks/ruby.ts
=> [Stacks][WebApp][V2] Updated variable names (enabled to supported) & Add known EOL Dates

client-react/src/pages/app/functions/app-keys/AppKeys.styles.ts, client-react/src/pages/app/functions/function/function-keys/FunctionKeys.styles.ts
Fixes AB# 7080212
New
Old
Note: Will be updating the column width in next one
=> [Ibizaifcation] Keys width updated

client-react/src/components/form-controls/TextFieldNoFormik.tsx, client-react/src/pages/app/change-app-plan/ChangeAppPlan.tsx, client-react/src/pages/app/change-app-plan/CreateOrSelectResourceGroup.tsx, client-react/src/pages/app/change-app-plan/CreatePlan.tsx
Part of fix: AB#7351973
Before
After
=> Remove FormControlWrapper pt.2 - Change over ASP flow

client-react/src/components/form-controls/TextFieldNoFormik.tsx, client-react/src/utils/textUtilities.ts
=> Fix the copy button

client-react/src/ApiHelpers/FunctionsService.ts, client-react/src/pages/app/functions/function/function-editor/FunctionEditorDataLoader.tsx
=> [Ibizafication] Update and refactor the getHostJson()

client/src/app/site/spec-picker/spec-list/spec-list.component.html, client/src/app/site/spec-picker/spec-list/spec-list.component.ts, client/src/app/site/spec-picker/spec-picker.component.html
=> AB#7117240 [Screen reader - App Service web - App Service Plan - Production] Label is not associated with the radio buttons.

client-react/src/pages/app/functions/function/function-log/FunctionLogCommandBar.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Hotfix after s139/s140 rollout completes
AB#7363232
=> [Function][Log] Add Feedback Button

client-react/src/pages/app/functions/function/function-editor/function-test/FunctionTest.tsx
=> [Ibizafication] Update function test body to the entire object

client/src/app/controls/group-tabs/group-tabs.component.scss, client/src/app/site/spec-picker/spec-picker.component.scss
Fixes AB#7118143
Fixes AB#7117356
Also fixed outline offset for tab focus as discussed with Byron offline. Changed the grey back to the lighter one as Byron is going to fight with them if they complain about the contrast ratio with white background :P 
**After changes:**
Focus on non-selected sku
Focus on selected sku
=> AB#7118143, AB#7117356 Few accessibility bug fixes

server/Resources/Resources.resx
=> [Ibizaifcation] Update function keys text

client-react/src/pages/app/functions/function/function-log/FunctionLogAppInsightsDataLoader.tsx
=> [Functions][Logs] Update error log for token timeout and add preemptive check

client/src/app/shared/services/utilities.service.ts
=> Add an event listener to write data directly in to the clipboard.

client-react/src/pages/app/functions/function/function-editor/FunctionEditorDataLoader.tsx
=> [Ibizafication] Use Auth header instead of keyHeader in test_data

client/src/app/function-dev/function-dev.component.ts, client/src/app/shared/models/function-info.ts, client/src/app/shared/services/function-app.service.ts
=> Remove dependency from test_data property in angular

client-react/src/pages/app/app-settings/GeneralSettings/Stacks.tsx, client-react/src/utils/scenario-checker/function-app.environment.ts
Fixes [AB#7422824](https://msazure.visualstudio.com/Antares/_workitems/edit/7422824)
=> AB#7422824 Don't show stacks selection in config for function apps

server/src/stacks/webapp/2020-05-01/stacks.service.ts
=> [Stacks][Web App Create][2020-05-01] Fix filtering bug

client-react/src/pages/app/functions/function/function-editor/function-test/FunctionTest.tsx
=> [Ibizafication] Update function test body to the entire object 

client-react/src/utils/scenario-checker/national-cloud.environment.ts, client/src/app/shared/services/scenario/national-cloud.environment.ts
This reverts commit ce72d975381f714f689726a02948140701e4cc9a.
=> [Functions][Logs] Disable App Insights in Fairfax, Mooncake

client-react/src/pages/app/functions/app-keys/AppKeys.styles.ts, client-react/src/pages/app/functions/app-keys/AppKeysPivot.tsx, client-react/src/pages/app/functions/function/function-keys/FunctionKeys.styles.ts, client-react/src/pages/app/functions/function/function-keys/FunctionKeys.tsx, client-react/src/pages/static-app/configuration/Configuration.styles.ts, client-react/src/pages/static-app/configuration/Configuration.tsx
=> [Ibizafication] Update table to use full screen width

client-react/src/pages/app/functions/app-keys/AppKeys.styles.ts, client-react/src/pages/app/functions/app-keys/HostKeys.tsx, client-react/src/pages/app/functions/app-keys/SystemKeys.tsx, client-react/src/pages/app/functions/function/function-keys/FunctionKeys.styles.ts, client-react/src/pages/app/functions/function/function-keys/FunctionKeys.tsx, client-react/src/pages/static-app/configuration/Configuration.styles.ts, client-react/src/pages/static-app/configuration/Configuration.tsx
=> [Ibizafication] Copy functionality added on table for keys

client-react/src/models/functions/function-binding.ts, client-react/src/pages/app/functions/function/monitor/FunctionMonitor.tsx, client-react/src/pages/app/functions/function/monitor/FunctionMonitor.types.ts, client-react/src/pages/app/functions/function/monitor/FunctionMonitorDataLoader.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes AB# 6238602
Durable Function
Non-durable Function
=> [Ibizafication][Function Monitor] Add tabs for durable functions

client-react/src/pages/app/functions/function/monitor/FunctionMonitor.tsx, client-react/src/pages/app/functions/function/monitor/tabs/entities/FunctionEntities.data.ts, client-react/src/pages/app/functions/function/monitor/tabs/entities/FunctionEntities.tsx, client-react/src/pages/app/functions/function/monitor/tabs/entities/FunctionEntitiesDataLoader.tsx, client-react/src/pages/app/functions/function/monitor/tabs/orchestrations/FunctionOrchestrations.data.ts, client-react/src/pages/app/functions/function/monitor/tabs/orchestrations/FunctionOrchestrations.tsx, client-react/src/pages/app/functions/function/monitor/tabs/orchestrations/FunctionOrchestrationsDataLoader.tsx
=> [Ibizafication] Initial files added for Monitor - Durable Functions

server/src/stacks/webapp/2020-06-01/stacks/dotnetCore.ts, server/src/stacks/webapp/2020-06-01/stacks/node.ts, server/src/stacks/webapp/2020-06-01/stacks/python.ts
=> [Stacks][2020-06-01] Explicitly set GitHub Action version values

client-react/src/ApiHelpers/AppInsightsService.ts, client-react/src/models/app-insights.ts, client-react/src/pages/app/functions/function/monitor/tabs/entities/FunctionEntities.data.ts, client-react/src/pages/app/functions/function/monitor/tabs/entities/FunctionEntities.tsx, client-react/src/pages/app/functions/function/monitor/tabs/entities/FunctionEntitiesDataLoader.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> [Ibizafication] Add Entities table

client-react/src/ApiHelpers/AppInsightsService.ts, client-react/src/models/app-insights.ts, client-react/src/pages/app/functions/function/monitor/tabs/FunctionMonitorTab.data.ts, client-react/src/pages/app/functions/function/monitor/tabs/FunctionMonitorTab.styles.ts, client-react/src/pages/app/functions/function/monitor/tabs/entities/FunctionEntities.data.ts, client-react/src/pages/app/functions/function/monitor/tabs/entities/FunctionEntities.tsx, client-react/src/pages/app/functions/function/monitor/tabs/entities/FunctionEntitiesDataLoader.tsx, client-react/src/pages/app/functions/function/monitor/tabs/orchestrations/FunctionOrchestrations.data.ts, client-react/src/pages/app/functions/function/monitor/tabs/orchestrations/FunctionOrchestrations.tsx, client-react/src/pages/app/functions/function/monitor/tabs/orchestrations/FunctionOrchestrationsDataLoader.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> [Ibizafication] Add Orchestration table

client-react/src/components/ActionBar.tsx, client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx, client-react/src/pages/app/functions/function/function-editor/FunctionEditor.types.ts, client-react/src/pages/app/functions/function/function-log/FunctionLog.styles.ts, client-react/src/pages/app/functions/function/function-log/FunctionLog.tsx, client-react/src/pages/app/functions/function/function-log/FunctionLogAppInsightsDataLoader.tsx, client-react/src/pages/app/functions/function/function-log/FunctionLogCommandBar.tsx, client-react/src/pages/app/functions/function/function-log/FunctionLogFileStreamDataLoader.tsx, client-react/src/pages/app/functions/function/function-log/FunctionLogOptionsCallout.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> Add logging options dropdown to switch from ai to filesystem logs

client-react/src/ApiHelpers/AppInsightsService.ts, client-react/src/models/app-insights.ts, client-react/src/pages/app/functions/function/monitor/tabs/orchestrations/FunctionOrchestrationDetails.tsx, client-react/src/pages/app/functions/function/monitor/tabs/orchestrations/FunctionOrchestrations.data.ts, client-react/src/pages/app/functions/function/monitor/tabs/orchestrations/FunctionOrchestrations.tsx, client-react/src/pages/app/functions/function/monitor/tabs/orchestrations/FunctionOrchestrationsDataLoader.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> [Function Monitor] Orchestration Details Panel added

client/src/app/site/deployment-center/deployment-center-setup/step-configure/configure-vsts-source/configure-vsts-source.component.scss
DTS and more details: https://dev.azure.com/mseng/AzureDevOps/_workitems/edit/1732697
=> Button overlap bug fix ADO Pipelines

client-react/src/pages/app/functions/function/function-editor/FunctionEditorDataLoader.tsx
=> show body in error response

client-react/src/pages/static-app/configuration/Configuration.tsx
=> [JAMStack] update dirty state

server/src/stacks/functionapp/2020-06-01/stack.model.ts, server/src/stacks/functionapp/2020-06-01/stacks/dotnetCore.ts, server/src/stacks/functionapp/2020-06-01/stacks/node.ts, server/src/stacks/functionapp/2020-06-01/stacks/python.ts
Fixes AB#7386538
Fixes AB#7386539
Fixes AB#7386540
=> [Stacks][Function App][2020-06-01] Add Model, .NET Core Stack, Node Sack, Python Stack

server/src/stacks/functionapp/2020-06-01/stacks/java.ts
=> [Stacks][Function App][2020-06-01] Add Java Stack

server/src/stacks/functionapp/2020-06-01/stacks/powershell.ts
=> [Stacks][Function App][2020-06-01] Add PowerShell Stack

client/src/app/shared/models/portal-resources.ts, client/src/app/site/spec-picker/price-spec-manager/plan-price-spec-manager.ts, client/src/app/site/spec-picker/spec-picker.component.html, client/src/app/site/spec-picker/spec-picker.component.ts, server/Resources/Resources.resx
=> AB#7117765 [Screen reader - App Service web - App Service Plan - Production] The "Learn More" link at the bottom of the page is not descriptive.

client-react/src/pages/static-app/configuration/Configuration.tsx
Fixes AB#6978828
Note: Dependency on array index removed and sorting added thereafter.
=> [JAMStack] Sorting by name and value added

server/src/stacks/functionapp/2020-05-01/stacks/dotnetCore.ts, server/src/stacks/functionapp/2020-05-01/stacks/java11.ts, server/src/stacks/functionapp/2020-05-01/stacks/java8.ts, server/src/stacks/functionapp/2020-05-01/stacks/node.ts, server/src/stacks/functionapp/2020-05-01/stacks/powershell.ts, server/src/stacks/functionapp/2020-05-01/stacks/python.ts, server/src/stacks/functionapp/2020-06-01/stack.model.ts, server/src/stacks/functionapp/2020-06-01/stacks/dotnetCore.ts, server/src/stacks/functionapp/2020-06-01/stacks/dotnetFramework.ts, server/src/stacks/functionapp/2020-06-01/stacks/java.ts, server/src/stacks/functionapp/2020-06-01/stacks/node.ts, server/src/stacks/functionapp/2020-06-01/stacks/powershell.ts, server/src/stacks/functionapp/2020-06-01/stacks/python.ts
@shimedh @pragnagopa @gzuber FYI
=> [Stacks][Function App] Update config casing

client-react/.vscode/settings.json, client-react/src/ApiHelpers/FunctionsService.ts, client-react/src/models/arm-obj.ts
Fixes AB#7529540
Create an untracked arm resource to create a function without a location
=> [Function Create][CRI] Remove location as a required field for function create

client-react/src/components/DisplayTableWithCommandBar/DisplayTableWithCommandBar.style.ts, client-react/src/pages/static-app/configuration/Configuration.tsx, client-react/src/pages/static-app/configuration/Configuration.types.ts, client-react/src/pages/static-app/configuration/ConfigurationCommandBar.tsx
Fixes AB#7080097
New
Dirty State
Existing Grid
Old
=> Bulk delete option added

server/src/stacks/functionapp/2020-06-01/stack.model.ts, server/src/stacks/functionapp/2020-06-01/stacks.service.ts, server/src/stacks/stacks.controller.ts, server/src/tests/Stacks/FunctionApp/2020-06-01/tests.ts, server/src/tests/Stacks/FunctionApp/2020-06-01/validations.ts
=> [Stacks][Function App][2020-06-01] Add Filters for Os, Stack

client-react/src/pages/app/app-settings/GeneralSettings/SlotAutoSwap.tsx
=> [Configuration] Add check for Linux to autoswap

client-react/src/SiteState.ts, client-react/src/pages/app/SiteRouter.tsx, client-react/src/pages/app/functions/function/function-log/FunctionLog.tsx, client-react/src/pages/app/functions/function/function-log/FunctionLogCommandBar.tsx, client-react/src/pages/app/functions/function/function-log/FunctionLogOptionsCallout.tsx
=> Telemetry added for file-based logging

client-react/src/components/monaco-editor/monaco-editor.tsx, client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx
=> Add save on Ctrl + S press

client-react/src/models/functions/binding.ts, client-react/src/pages/app/functions/function/integrate/FunctionIntegrate.tsx, client-react/src/pages/app/functions/function/integrate/FunctionIntegrate.utils.ts, client-react/src/pages/app/functions/function/integrate/binding-card/BindingCard.styles.ts, client-react/src/pages/app/functions/function/integrate/binding-card/InputBindingCard.tsx, client-react/src/pages/app/functions/function/integrate/binding-card/OutputBindingCard.tsx, client-react/src/pages/app/functions/function/integrate/binding-card/TriggerBindingCard.tsx, client-react/src/pages/app/functions/function/integrate/binding-card/UnknownDirectionBindingCard.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes AB#7052303
No missing directions:
Missing directions:
Missing directions reflow:
=> [Integrate] Add in an unknown direction binding card

client-react/src/pages/app/functions/common/callout/iotHubPivot/IoTHubPivot.tsx
=> [Function Create][CRI] Remove IoT Hub key on change of selection

client/src/app/site/deployment-center/deployment-center-setup/wizard-logic/github.service.ts
Update the app-name to contain only the production site name
=> [GitHubAction]Update the app-name to contain only the production site name

client/src/app/site/deployment-center/deployment-center-setup/wizard-logic/github.service.ts
Update the app-name to contain only the production site name
=> Update github.service.ts (#5152)

client-react/src/pages/app/functions/function/function-log/FunctionLog.styles.ts, client-react/src/pages/app/functions/function/function-log/FunctionLog.tsx, client-react/src/pages/app/functions/function/function-log/FunctionLogCommandBar.tsx
=> Set checked log level

client-react/src/pages/app/spec-picker/specs/isolated/IsolatedPlanPriceSpec.ts, client-react/src/utils/CommonConstants.ts, client/src/app/shared/models/constants.ts, client/src/app/site/spec-picker/price-spec-manager/isolated-plan-price-spec.ts
Fixes AB#7567783
Before:
After:
=> [ASE][V3] Update speck picker checks for ASPs on ASEv3

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSource.tsx, client-react/src/utils/FwLinks.ts
Fixes ab#7173969
Added learn more link to deployment center v2 container setting
=> Added learn more link to deployment center v2 container setting

client-react/src/components/form-controls/TextField.tsx, client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEditAdvanced.tsx, client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEditBasic.tsx, client-react/src/pages/app/app-settings/GeneralSettings/LinuxStacks/LinuxStacks.tsx, client-react/src/pages/app/change-app-plan/ChangeAppPlan.tsx, client-react/src/pages/app/functions/create/TemplatesPivot.tsx, client-react/src/pages/app/functions/function/integrate/BindingPanel/BindingCreator.tsx, client-react/src/pages/app/functions/function/integrate/FunctionIntegrate.tsx, client-react/src/pages/app/functions/quickstart/FunctionQuickstart.tsx, client-react/src/pages/app/spec-picker/specs/basic/BasicPlanPriceSpec.ts, client-react/src/pages/app/spec-picker/specs/elastic-premium/ElasticPremiumPlanPriceSpec.ts, client-react/src/pages/app/spec-picker/specs/isolated/IsolatedPlanPriceSpec.ts, client-react/src/pages/app/spec-picker/specs/premium-container/PremiumContainerPlanPriceSpec.ts, client-react/src/pages/app/spec-picker/specs/premium/PremiumPlanPriceSpec.ts, client-react/src/pages/app/spec-picker/specs/premiumv2/PremiumV2PlanPriceSpec.ts, client-react/src/pages/app/spec-picker/specs/standard/StandardPlanPriceSpec.ts, client-react/src/utils/CommonConstants.ts, client-react/src/utils/FwLinks.ts
Fixes ab#7361480
Moved existing fwlinks from CommonConstants.ts to FwLinks.ts
=> Moved existing fwlinks from CommonConstants.ts to FwLinks.ts

client-react/src/pages/app/deployment-center/DeploymentCenter.styles.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx
'i' icon position was absolute with panel and would not scroll when panel was scrolled.
=> Fixed issue with info icon moving with panel scroll

client-react/src/pages/app/deployment-center/DeploymentCenter.styles.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/DeploymentCenterFtps.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeBuildRuntimeAndVersion.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceAndBuild.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubWorkflowConfigPreview.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubWorkflowConfigSelector.tsx
=> Close 'x' button on CustomBanner components in Deployment Center v2

client-react/src/pages/app/deployment-center/DeploymentCenter.styles.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerLogs.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubDataLoader.tsx
=> Removed background and border from container logs view in Deployment Center v2

client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeBuildConfiguredView.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceKuduConfiguredView.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubConfiguredView.tsx
Fixes ab#7752336
*ConfiguredView is more descriptive of what these components are
=> Rename *ReadOnly components to *ConfiguredView

client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx, client-react/src/pages/app/functions/function/function-log/FunctionLog.tsx, client-react/src/pages/app/functions/function/function-log/FunctionLogFileStreamDataLoader.tsx, client-react/src/utils/scenario-checker/national-cloud.environment.ts
=> [Functions][Function Editor Logs] Default to filebased logs

client-react/src/ApiHelpers/RuntimeStackService.ts, client-react/src/models/stacks/app-stacks.ts, client-react/src/models/stacks/function-app-stacks.ts, client-react/src/models/stacks/web-app-stacks.ts, client-react/src/pages/app/app-settings/AppSettings.service.ts, client-react/src/pages/app/app-settings/AppSettingsDataLoader.tsx, client-react/src/pages/app/app-settings/Contexts.ts, client-react/src/pages/app/app-settings/GeneralSettings/DebuggingLinux.tsx, client-react/src/pages/app/app-settings/GeneralSettings/LinuxStacks/LinuxStacks.data.ts, client-react/src/pages/app/app-settings/GeneralSettings/LinuxStacks/LinuxStacks.tsx, client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/DotNetStack.tsx, client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/JavaData.ts, client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/JavaStack.tsx, client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/PhpStack.tsx, client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/PythonStack.tsx, client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/WindowsStacks.tsx, client-react/src/pages/app/functions/quickstart/FunctionQuickstart.tsx, client-react/src/utils/CommonConstants.ts, client-react/src/utils/FunctionAppService.ts, client-react/src/utils/stacks-utils.ts
=> Setup for Function App stack settings

client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/JavaStack.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> Java container label updated

client-react/src/pages/app/app-settings/GeneralSettings/LinuxStacks/JavaStack.tsx, client-react/src/pages/app/app-settings/GeneralSettings/LinuxStacks/LinuxStacks.data.ts, client-react/src/pages/app/app-settings/GeneralSettings/LinuxStacks/LinuxStacks.tsx, client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/JavaData.ts, client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/JavaStack.tsx, client/src/app/function-dev/function-dev.component.ts
Cherry-picked https://github.com/Azure/azure-functions-ux/pull/5191
=> Fix Java Stacks for Windows and Linux Apps (#5191)

client-react/src/pages/app/functions/function/invocations/FunctionInvocationDetails.tsx, client-react/src/pages/app/functions/function/invocations/FunctionInvocations.tsx
=> [Function][Monitor] Large panel for invocation details

client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEdit.tsx, client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEditAdvanced.tsx, client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEditBasic.tsx
=> [BYOS] Required configuration fields don't have '*' 

server/src/stacks/functionapp/2020-05-01/stacks.service.ts, server/src/stacks/functionapp/2020-06-01/stacks.service.ts, server/src/stacks/stacks.controller.ts, server/src/tests/Stacks/FunctionApp/2020-05-01/tests.ts, server/src/tests/Stacks/FunctionApp/2020-05-01/validations.ts, server/src/tests/Stacks/FunctionApp/2020-06-01/tests.ts, server/src/tests/Stacks/FunctionApp/2020-06-01/validations.ts
=> [Stacks][FunctionApp]Add isHidden filter

client-react/src/models/portal-models.ts, client-react/src/pages/app/SiteRouter.tsx, client-react/src/pages/app/app-settings/GeneralSettings/stacks/function-app/FunctionAppStackSettings.tsx, client-react/src/utils/CommonConstants.ts, client-react/src/utils/FunctionAppService.ts, client-react/src/utils/SiteHelper.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes AB#7835664
Fixes AB# 7835655
=> Support added for custom Handler in Configurations

client-react/src/pages/app/app-settings/FunctionRuntimeSettings/RuntimeVersion.tsx
=> Remove v2 for Usnat and Ussec

client-react/src/pages/app/functions/function/invocations/FunctionInvocations.tsx
=> Fix Esc press on Invocation Detail panel

client-react/src/ApiHelpers/ArmHelper.ts, client-react/src/ArmHelper.types.ts, client/src/app/function-dev/function-dev.component.ts
=> Handle batch error

client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMounts.tsx, client-react/src/utils/arm-utils.ts
Fixes AB #7889022
Fixes AB #7897408
Current:
Fix:
=> Update AzureStorageMounts to functional component #7897408

server/src/stacks/webapp/2020-05-01/stacks/config/linux/java11.ts, server/src/stacks/webapp/2020-06-01/stacks/javaContainers.ts
=> [Stacks] Add missing JAVA|11.0.6

client-react/src/components/DisplayTableWithCommandBar/DisplayTableWithCommandBar.tsx, client-react/src/pages/app/SiteRouter.tsx, client-react/src/pages/app/functions/new-create-preview/FunctionCreate.data.ts, client-react/src/pages/app/functions/new-create-preview/FunctionCreate.styles.ts, client-react/src/pages/app/functions/new-create-preview/FunctionCreateDataLoader.tsx, client-react/src/pages/app/functions/new-create-preview/portal-create/TemplateDetail.tsx, client-react/src/pages/app/functions/new-create-preview/portal-create/TemplateList.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> [Local Dev Experience] Template List Added

client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubAccount.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubDataLoader.tsx
Fixes AB#7960784
Generalize GitHub provider properties to be account provider properties
=> Generalize github provider properties

client-react/src/portal-communicator.ts, client-react/src/react-app-env.d.ts, client-react/src/utils/LogService.ts, client/src/app/shared/services/ai.service.ts, client/src/app/shared/services/portal.service.ts, client/src/polyfills/window.ts
=> Add frameId in the logs to uniquely identify each experience entry

client-react/src/components/shimmer/CustomElementsShimmer.tsx, client-react/src/components/shimmer/Shimmer.styles.ts, client-react/src/components/shimmer/Shimmer.types.tsx, client-react/src/pages/app/functions/new-create-preview/FunctionCreate.data.ts, client-react/src/pages/app/functions/new-create-preview/FunctionCreateDataLoader.tsx, client-react/src/pages/app/functions/new-create-preview/local-create/CustomMarkdownComponents.tsx, client-react/src/pages/app/functions/new-create-preview/local-create/LocalCreateInstructions.style.ts, client-react/src/pages/app/functions/new-create-preview/local-create/LocalCreateInstructions.tsx
=> [Local Dev Experience] Load local instructions

client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/bitbucket-provider/DeploymentCenterBitbucketAccount.tsx, client-react/src/pages/app/deployment-center/bitbucket-provider/DeploymentCenterBitbucketDataLoader.tsx, client-react/src/pages/app/deployment-center/bitbucket-provider/DeploymentCenterBitbucketProvider.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx
Fixes AB#7972742
Scaffolding for BitbucketDataLoader, BitbucketAcount, and BitbucketProvider
=> Scaffolding for Bitbucket Data Loader

client-react/src/pages/app/functions/new-create-preview/FunctionCreateDataLoader.tsx, client-react/src/pages/app/functions/new-create-preview/local-create/LocalCreateInstructions.tsx
=> [Local Dev Experience] Add Close Button  + Refactoring some bits

client-react/src/pages/app/functions/new-create-preview/FunctionCreate.data.ts, client-react/src/pages/app/functions/new-create-preview/FunctionCreateDataLoader.tsx, client-react/src/pages/app/functions/new-create-preview/portal-create/TemplateList.tsx
=> [Local Dev Experience] Add onSubmit for new function

client-react/src/pages/app/functions/function/function-editor/FunctionEditorDataLoader.tsx, client-react/src/pages/app/functions/new-create-preview/FunctionCreate.data.ts, client-react/src/pages/app/functions/new-create-preview/FunctionCreate.types.ts, client-react/src/pages/app/functions/new-create-preview/portal-create/TemplateList.tsx, client-react/src/utils/string.ts
=> [Local Dev Experience] Sorting added for template list + Name updated according to runtimeVersion

server/src/stacks/functionapp/2020-06-01/stacks/powershell.ts, server/src/tests/Stacks/FunctionApp/2020-06-01/validations.ts
=> [Stacks][Function App] PowerShell Name Update 2020-06-01

client-react/src/ApiHelpers/BitbucketService.ts, client-react/src/pages/app/deployment-center/bitbucket-provider/DeploymentCenterBitbucketDataLoader.tsx, client-react/src/pages/app/deployment-center/bitbucket-provider/DeploymentCenterBitbucketProvider.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubDataLoader.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> Implement getUser in Bitbucket Service Class 

client-react/src/components/shimmer/BasicShimmerLines.tsx, client-react/src/pages/app/functions/new-create-preview/local-create/LocalCreateInstructions.tsx, client-react/src/pages/app/functions/new-create-preview/portal-create/TemplateDetail.tsx
=> [Local Dev Experience] Shimmer added for Template Details Components

client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubAccount.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubProvider.tsx
=> Move GitHub source controls dropdowns from GitHubAccount component to GitHubProvider component.

client-react/src/ApiHelpers/BitbucketService.ts, client-react/src/models/bitbucket.ts, client-react/src/pages/app/deployment-center/bitbucket-provider/DeploymentCenterBitbucketDataLoader.tsx
=> [Bitbucket] Implement repositories and branches in Bitbucket service class

client-react/src/utils/CommonConstants.ts
=> [Function][Monitoring] Update Mooncake AI endpoint

client/src/app/shared/services/function-app.service.ts
Fixes AB#8036819
Fixes AB#8036991
=> Update headers for PUT request on Proxies blade

client-react/src/ApiHelpers/OneDriveService.ts, client-react/src/models/onedrive.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.data.ts
=> Implement Scaffolding for OneDrive Service Class 

client-react/src/ApiHelpers/BitbucketService.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.data.ts, client-react/src/pages/app/deployment-center/bitbucket-provider/DeploymentCenterBitbucketConfiguredView.tsx, client-react/src/pages/app/deployment-center/bitbucket-provider/DeploymentCenterBitbucketDataLoader.tsx
=> [Bitbucket] OAuth for Bitbucket

client/src/app/shared/models/constants.ts, client/src/app/shared/models/portal-resources.ts, client/src/app/site/site-summary/site-summary.component.ts, client/src/app/top-bar/top-bar-models.ts, client/src/app/top-warning/top-warning.component.html, server/Resources/Resources.resx
Here's what it looks like below.  Clicking on the banner will take you to this repo: https://github.com/Azure/azure-functions/issues
=> Adding classic Functions deprecation banner

client-react/src/pages/app/deployment-center/bitbucket-provider/DeploymentCenterBitbucketConfiguredView.tsx, client-react/src/pages/app/deployment-center/bitbucket-provider/DeploymentCenterBitbucketDataLoader.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubConfiguredView.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubDataLoader.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.ts
=> Refactor OAuth in Bitbucket and Github

server/src/stacks/webapp/2020-05-01/stacks/create/dotnetCore.ts, server/src/stacks/webapp/2020-06-01/stacks/dotnetCore.ts
* Update 2020-05-01
* Update dotnetCore.ts
=> [Stacks][WebApp] Enable AI for Windows Dotnet Core (#5272)

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeCommandBar.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceKuduConfiguredView.tsx, client-react/src/pages/app/deployment-center/local-git-provider/DeploymentCenterLocalGitConfiguredView.tsx, client-react/src/pages/app/deployment-center/local-git-provider/DeploymentCenterLocalGitProvider.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes AB#8060904
Fixe AB#8060968
Fixe AB#8060918
=> Implement Local Git functionality

client/src/app/site/slots/swap-slots/swap-diff-table/swap-diff-table.component.html, client/src/app/site/slots/swap-slots/swap-slots.component.scss
Fixes AB#8039215
Before:
After:
=> [Slots] Mouse over tool tip on swapping settings

client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx, client-react/src/pages/app/functions/function/function-log/FunctionLogFileStreamDataLoader.tsx, client-react/src/pages/app/functions/function/monitor/FunctionMonitor.tsx, client-react/src/pages/app/functions/function/monitor/tabs/logs/FunctionLogsDataLoader.tsx
=> [Function][Monitor] Default to file-based stream

client-react/src/pages/app/functions/function/function-log/FunctionLogFileStreamDataLoader.tsx, client-react/src/pages/app/functions/log-stream/LogStreamDataLoader.tsx
=> [Function App][Log Stream] Default to filebased logs

client-react/src/pages/app/deployment-center/DeploymentCenterFtps.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodePivot.tsx, client-react/src/pages/app/deployment-center/local-git-provider/DeploymentCenterLocalGitConfiguredView.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes AB#8060837
Fixes AB#7431966
=> Display Clone Uri in Tabs and Change FTP tab name 

client-react/src/ApiHelpers/ACRService.ts, client-react/src/models/acr.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.data.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrDataLoader.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrSettings.tsx, client-react/src/utils/CommonConstants.ts
registries dropdown
images dropdown
tags dropdown
=> Wireup the ACR calls to the ACR dropdowns

client-react/src/models/external.ts, client-react/src/models/site/config.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeCommandBar.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx, client-react/src/pages/app/deployment-center/external-provider/DeploymentCenterExternalProvider.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes AB#8101140
Fixes AB#7320738
=> External git scaffolding

server/src/stacks/webapp/2020-06-01/stacks/ruby.ts, server/src/tests/Stacks/WebApp/2020-06-01/validations.ts
Align Ruby with other stack structure (major version = 2)
@nertim @takyyon FYI
=> [Stacks][WebApp] 2020-06-01 Ruby updates

client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerCommandBar.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx
Bring command bar for container scenario in parity with code command bar
=> Bring command bar for container scenario in parity with code command bar

client-react/src/utils/arm-utils.ts, client-react/src/utils/scenario-checker/function-app.environment.ts, client-react/src/utils/scenario-checker/scenario.service.ts, client-react/src/utils/scenario-checker/workflow-app.environment.ts
Fixes AB#8089451
Fixes AB#7822875 
**WorkflowApp Configuration**
**FunctionApp Configuration**
**WebApp Configuration**
=> AB#8089451, AB#7822875 Add scenario checker to hide function runtime settings tab

client-react/src/ApiHelpers/SiteService.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/DeploymentCenterCommandBar.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeCommandBar.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> Sync Button for Manual Deployment

client-react/src/pages/app/app-settings/FunctionRuntimeSettings/RuntimeVersionBanner.tsx, client-react/src/utils/FwLinks.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> Upgrade Function Runtime Settings banner for custom (2.0) only

client-react/src/components/ActionBar.tsx
=> Make action bar button size consistent with Ibiza

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerFormBuilder.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Clicking the save button will yield validation checks before the form is submitted.
=> [DeploymentCenterV2] Add validation for container form.

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceAndBuild.tsx
=> Removing Onedrive/Dropbox from Dropdown

client-react/src/pages/app/deployment-center/DeploymentCenterDataLoader.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterFtps.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterPublishingContext.ts, client-react/src/pages/app/deployment-center/DeploymentCenterPublishingUser.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes AB#8101030
Error (There is no error message because there was no actual error here)
Loading
Normal
=> Deployment Center Publishing User Component

server/Resources/Resources.resx
=> [DeploymentCenterV2] fix 'seize' to 'cease'

client-react/src/pages/app/deployment-center/DeploymentCenterCommandBar.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, server/Resources/Resources.resx
Fixes AB#8180357
Fixes AB#8180364
Fixes AB#8180366
Fixes AB#8180368
=> [Deployment Center V2] Sync button updates

client-react/src/components/form-controls/DropDown.tsx, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubDataLoader.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubProvider.tsx
Show a loading indicator and disable the dropdown during a network call.
Super thanks to @takyyon for the better design help and parity with Ibiza look and feel.
=> Introduce loading indicator for dropdowns

client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/bitbucket-provider/DeploymentCenterBitbucketDataLoader.tsx, client-react/src/pages/app/deployment-center/bitbucket-provider/DeploymentCenterBitbucketProvider.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrDataLoader.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrSettings.tsx
=> Add loading indicator for ACR and Bitbucket dropdowns

client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/DeploymentCenterCommandBar.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceAndBuild.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes AB#8195535 Show confirm dialog for discard button
Fixes AB#8195706 Discard does not reset Source dropdown
Fixes AB#8180304 Save/Discard should be disabled when form is not dirty
Fixes AB#8195567
=> [Deployment Center V2] Discard button updates

server/src/stacks/webapp/2020-05-01/stacks/config/linux/java8.ts, server/src/stacks/webapp/2020-05-01/stacks/create/java8.ts, server/src/stacks/webapp/2020-06-01/stacks/javaContainers.ts, server/src/tests/Stacks/WebApp/2020-05-01/validations.ts, server/src/tests/Stacks/WebApp/2020-06-01/validations.ts
=> [Stacks][WebApp] Add JBoss EAP Preview

client/src/app/shared/models/constants.ts, client/src/app/shared/models/portal-resources.ts, client/src/app/shared/models/server-farm.ts, client/src/app/shared/models/serverFarmSku.ts, client/src/app/site/spec-picker/price-spec-manager/dV3series-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/premium-container-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/premiumv3-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/price-spec-group.ts, server/Resources/Resources.resx
Fixes AB#7683522
**NOTE: The changes are added behind a feature flag since the API's are not ready yet to test it completely. I have gotten the screenshots by removing some checks to show how it looks. 
Also I will have separate PR's on Ibiza side to handle the new Pv3 sku as well**
**Only when feature flag enabled**
**For new creates -  show only PV3 sku's**
**For existing apps -** 
**If sku is premiumContainer then only show PC sku's.** 
**If sku is PV3 then only show PV3 sku's**
=> AB#7683522 [PV3][SpecPicker] Add support for PV3

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSettings.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubDisconnect.tsx
=> Dismiss panel on button click and refresh form on disconnect.

client-react/src/pages/app/deployment-center/DeploymentCenterFormBuilder.ts
=> Error message for Publishing Username and Password

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerFormBuilder.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerRegistrySettings.tsx
=> Hide container options for now.

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerDockeHubSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerPrivateRegistrySettings.tsx, client-react/src/pages/app/deployment-center/utility/GitHubActionUtility.ts
=> Always get the serverurl, login, password, image, and tag for github action setup.

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSource.tsx
=> Fix the discard button for containers

client/src/app/site/deployment-center/deployment-center-setup/wizard-logic/deployment-center-state-manager.ts
After a ton of discussion with @ehamai we found a solution where we can simple update the metadata and scmtype for a site with the source control information. This allows the source controls and site config APIs to return the correct payload post-save. It also preserves the user data for future disconnect scenarios.
With this change once the source controls api is fixed, we can simply remove the change.
=> [HOTFIX] Add a workaround to prevent failures from the /sourcecontrols API for GitHub actions settings

client-react/src/pages/static-app/configuration/ConfigurationAdvancedAddEdit.tsx
=> [SWA][Configuration] Fix advanced AddEdit

client-react/src/pages/app/deployment-center/external-provider/DeploymentCenterExternalProvider.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> Placeholder for external git repo and branch

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceAndBuild.tsx
=> [Deployment Center V2] Github should always have Github Actions as default build provider

client-react/src/models/external.ts, client-react/src/pages/app/deployment-center/DeploymentCenterPublishingUser.tsx, client-react/src/pages/app/deployment-center/external-provider/DeploymentCenterExternalProvider.tsx
=> Remove show label for passwords

client-react/src/components/form-controls/ReactiveFormControl.tsx, client-react/src/components/form-controls/formControl.override.styles.tsx, client-react/src/pages/app/deployment-center/local-git-provider/DeploymentCenterLocalGitConfiguredView.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.ts
=> Copy button added to Git Clone Url

client/src/app/shared/Utilities/flighting-utility.ts, client/src/app/shared/models/constants.ts, client/src/app/site/site-summary/site-summary.component.ts
=> [Slots] Remove slots flighting

client/src/app/site/slots/swap-slots/swap-slots.component.html
=> [Slots] Fix for undefined console error

client-react/src/pages/app/app-settings/GeneralSettings/stacks/function-app/FunctionAppStackSettings.tsx
=> [Stacks][FunctionApp] Successful saving should not show dirty state

client-react/src/pages/app/app-settings/GeneralSettings/stacks/function-app/FunctionAppStackSettings.tsx
Fixes AB#8214909
Fixes AB#8214967
=> [Stacks] StartUp command shown for function container apps

client-react/src/pages/app/deployment-center/external-provider/DeploymentCenterExternalConfiguredView.tsx
=> External component rename

client/src/app/site/spec-picker/price-spec-manager/premiumv3-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/price-spec-group.ts
=> AB#8275252 [PV3] Remove Windows Containers Preview banner when PV3 is enabled and fix vCPU strings

client-react/src/pages/app/deployment-center/DeploymentCenterCommandBar.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> Feedback button for deployment center preview

server/Resources/Resources.resx
=> Change FTP to FTPS

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerDockeHubSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerPrivateRegistrySettings.tsx, client-react/src/pages/app/deployment-center/external-provider/DeploymentCenterExternalProvider.tsx
=> Add * next to required fields.

client-react/src/pages/app/deployment-center/DeploymentCenterFormBuilder.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodePivot.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerPivot.tsx
Fixes AB #8180334 
Fixes AB #8294502
=> [Deployment Center V2] Dirty state on tabs

client-react/src/pages/app/deployment-center/DeploymentCenterFormBuilder.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodePivot.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerPivot.tsx
* Dirty state on tabs
* pr updates
=> [Cherry pick] [Deployment Center V2] Dirty state on tabs 

client-react/src/pages/app/functions/function/function-log/FunctionLogCommandBar.tsx
=> [Logs][Telemetry] Update featureName

client-react/src/ApiHelpers/RuntimeStackService.ts, client-react/src/utils/CommonConstants.ts
=> [Stack Settings] Add hidden flag for stacks api

client-react/src/ApiHelpers/FunctionsService.ts, client-react/src/pages/app/functions/function/function-editor/FunctionEditorDataLoader.tsx
=> [FunctionEditor] Get test data over VFS Arm API and keep the current logic as fallback

client-react/src/pages/app/functions/function/function-log/FunctionLogFileStreamDataLoader.tsx
=> [Functions][Logs] Call host before filebased connection

client-react/src/pages/app/deployment-center/utility/GitHubActionUtility.ts
- The "jobs" section was tabbed in
- Removed .NET commands from workflow
- "-run" was indented
- missing single quote on "images: "
I  noticed the "jobs" section on the ASP.NET workflow was also tabbed in too far.
=> Fixes for custom container workflow

client-react/src/pages/app/app-settings/GeneralSettings/Platform.tsx
=> Hide bit dropdown for java windows stack

client-react/src/pages/app/deployment-center/utility/GitHubActionUtility.ts, client/src/app/site/deployment-center/deployment-center-setup/wizard-logic/github.service.ts
The templates should match https://github.com/azure/actions-workflow-templates
=> Update the code based template files to match templates repo.

client-react/src/pages/app/deployment-center/utility/GitHubActionUtility.ts, client/src/app/site/deployment-center/deployment-center-setup/wizard-logic/github.service.ts
* Update the code based template files to match templates repo.
* update python3 to python
* update the app.zip file name
* Fixes for custom container workflow (#5392)
Removed .NET commands from workflow
"-run" was indented
missing single quote on "images: "
* update container template
Co-authored-by: Jason Freeberg <jafreebe@microsoft.com>
=> Update the code based template files to match templates repo. (#5384)

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerPivot.tsx
=> Updating container settings dirty tab

client-react/src/pages/app/deployment-center/DeploymentCenterConstants.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerDockerHubSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerFormBuilder.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerPrivateRegistrySettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerRegistrySettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSettings.tsx, client-react/src/pages/app/deployment-center/utility/GitHubActionUtility.ts
These fixes the dockerhub private repo scenario and also the github action scenario for docker hub.
=> Update the container template and docker hub server info.

client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/DotNetStack.tsx, client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/PhpStack.tsx, client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/PythonStack.tsx, client-react/src/utils/stacks-utils.ts
=> Update EOL stack for Windows Apps

client-react/src/pages/app/deployment-center/DeploymentCenterConstants.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerDockerHubSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerFormBuilder.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerPrivateRegistrySettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerRegistrySettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSettings.tsx, client-react/src/pages/app/deployment-center/utility/GitHubActionUtility.ts
* Bug fixes to get the container scenrio working with github action.
* add a slash at the end
=> [CherryPick] Update the container template and docker hub server info. (#5401)

client-react/src/pages/app/functions/app-keys/AppKeys.data.ts, client-react/src/pages/app/functions/app-keys/HostKeys.tsx, client-react/src/pages/app/functions/app-keys/SystemKeys.tsx, client-react/src/pages/app/functions/function/function-keys/FunctionKeys.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> Notification added for CreateKey scenario

server/src/stacks/functionapp/2020-06-01/stacks.service.ts, server/src/stacks/stacks.controller.ts, server/src/stacks/webapp/2020-06-01/stack.model.ts, server/src/stacks/webapp/2020-06-01/stacks.service.ts, server/src/stacks/webapp/2020-06-01/stacks/dotnetCore.ts, server/src/stacks/webapp/2020-06-01/stacks/java.ts, server/src/stacks/webapp/2020-06-01/stacks/node.ts, server/src/stacks/webapp/2020-06-01/stacks/php.ts, server/src/stacks/webapp/2020-06-01/stacks/python.ts, server/src/stacks/webapp/2020-06-01/stacks/ruby.ts, server/src/tests/Stacks/FunctionApp/2020-06-01/tests.ts, server/src/tests/Stacks/FunctionApp/2020-06-01/validations.ts, server/src/tests/Stacks/WebApp/2020-06-01/tests.ts, server/src/tests/Stacks/WebApp/2020-06-01/validations.ts
=> [Stacks][2020-06-01] Add additional filtering

server/src/stacks/webapp/2020-05-01/stacks/config/windows/javaContainer.ts, server/src/stacks/webapp/2020-06-01/stacks/javaContainers.ts
=> [Stacks][Web App] Mark jetty as deprecated

server/src/stacks/webapp/2020-05-01/stacks/config/linux/node.ts, server/src/stacks/webapp/2020-06-01/stacks/node.ts, server/src/tests/Stacks/WebApp/2020-05-01/validations.ts, server/src/tests/Stacks/WebApp/2020-06-01/validations.ts
=> [Stacks][Web App] Add node 14 as preview and hidden

server/src/stacks/webapp/2020-06-01/stacks/javaContainers.ts
=> [Stacks][Web App] Combine Java SE into one stack

client-react/src/ApiHelpers/RuntimeStackService.ts, client-react/src/pages/app/app-settings/GeneralSettings/LinuxStacks/LinuxStacks.data.ts, client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/JavaData.ts, client-react/src/utils/CommonConstants.ts, client-react/src/utils/stacks-utils.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> Deprecated flag added for Stacks and refactored

client-react/src/utils/stacks-utils.ts
(there should ideally be only one class per file)
=> Update stack-utils to have consts

client-react/src/pages/app/deployment-center/DeploymentCenter.styles.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceKuduConfiguredView.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubDisconnect.tsx
=> Disconnect link below source provider

client-react/src/pages/app/functions/function/function-log/FunctionLogFileStreamDataLoader.tsx
=> [Function][Logs] Show any host status errors on filebased stream

client-react/src/pages/app/deployment-center/bitbucket-provider/DeploymentCenterBitbucketConfiguredView.tsx, client-react/src/pages/app/deployment-center/external-provider/DeploymentCenterExternalConfiguredView.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubConfiguredView.tsx
Fixes AB#8180371
Before:
After:
=> [Deployment Center V2] Remove indent on branch link

client/src/app/shared/Utilities/flighting-utility.ts, client/src/app/shared/models/constants.ts, client/src/app/site/spec-picker/price-spec-manager/price-spec-group.ts
Fixes AB#7062491
**Before**:
**After when subscription is in flighting :**
=> AB#7062491 Remove Standard from recommended SKU

client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEdit.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> Update validation for mount path

client/src/app/shared/services/plan.service.ts, client/src/app/site/spec-picker/price-spec-manager/dV2series-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/dV3series-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/free-plan-price-spec.ts, client/src/app/test/mocks/plan.service.mock.ts
=> AB#8369862 [PV3] Should pass xenonWorkersEnabled=true query along with sku for georegions API for xenon scenario

server/src/stacks/2020-06-01/stacks/web-app-stacks/Java.ts
=> [Stacks][Web App] Update Java 1.8.0_25 runtime version

client/src/app/shared/models/arm/serverfarm-recommendation.ts, client/src/app/shared/models/constants.ts, client/src/app/shared/models/portal-resources.ts, client/src/app/shared/services/plan.service.ts, client/src/app/site/spec-picker/price-spec-manager/plan-price-spec-manager.ts, client/src/app/site/spec-picker/spec-picker.component.scss, server/Resources/Resources.resx
=> AB#8378370 [Spec picker] Update app density logic to show/hide using the new API

server/src/stacks/2020-06-01/stacks/web-app-stacks/Node.ts, server/src/stacks/2020-06-01/stacks/web-app-stacks/Php.ts
Synced with @btardif and these are not yet ready for public preview
=> [Stacks][Web App] Hide Node 10.15 and PHP 7.4

server/src/stacks/2020-06-01/stacks/web-app-stacks/JavaContainers.ts
Capitalize 'Embedded Web Server' and add to the minor version
Update 8u232 value to 1.8.232 so it is properly identified as a pinned version
=> [Stacks][Web App] Java Container Stack Updates

client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx, client-react/src/pages/app/deployment-center/onedrive-provider/DeploymentCenterOneDriveAccount.tsx, client-react/src/pages/app/deployment-center/onedrive-provider/DeploymentCenterOneDriveDataLoader.tsx, client-react/src/pages/app/deployment-center/onedrive-provider/DeploymentCenterOneDriveProvider.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> [OneDrive] OneDrive Data Loader, Provider, & Account Scaffolding

client-react/src/ApiHelpers/RuntimeStackService.ts, client-react/src/pages/app/app-settings/GeneralSettings/LinuxStacks/LinuxStacks.tsx, client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/DotNetStack.tsx, client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/JavaStack.tsx, client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/PhpStack.tsx, client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/PythonStack.tsx, client-react/src/utils/stacks-utils.ts
=> [AppSettings][Stacks] Handle deprecated stacks for web-apps

server/Resources/Resources.resx, server/Resources/qps-ploc/Server/Resources/Resources.resx
=> Update message for CustomHandler editing

client-react/src/ApiHelpers/OneDriveService.ts, client-react/src/models/onedrive.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/bitbucket-provider/DeploymentCenterBitbucketConfiguredView.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx, client-react/src/pages/app/deployment-center/onedrive-provider/DeploymentCenterOneDriveAccount.tsx, client-react/src/pages/app/deployment-center/onedrive-provider/DeploymentCenterOneDriveConfiguredView.tsx, client-react/src/pages/app/deployment-center/onedrive-provider/DeploymentCenterOneDriveProvider.tsx
=> [OneDrive] OneDrive Configured view & Bitbucket getOrgValue Update

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeBuildRuntimeAndVersion.tsx
=> GitHub in Deployment Center Preview crashes for non-github action supported runtime stacks

client-react/src/pages/app/SiteRouter.tsx
=> Update SiteState to wait on the Site call

client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/DeploymentCenterCommandBar.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> [Deployment Center V2] Change sync button to redeploy button

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceAndBuild.tsx
=> Add scenario service check for external git in dropdown

client-react/src/pages/app/app-settings/GeneralSettings/stacks/function-app/FunctionAppStackSettings.data.ts, client-react/src/pages/app/app-settings/GeneralSettings/stacks/function-app/FunctionAppStackSettings.tsx
=> [Stacks] Fix the casing for the stack version dropdown

client-react/src/ApiHelpers/OneDriveService.ts, client-react/src/pages/app/deployment-center/onedrive-provider/DeploymentCenterOneDriveDataLoader.tsx, client-react/src/pages/app/deployment-center/onedrive-provider/DeploymentCenterOneDriveProvider.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes AB#8364224
Note: The OneDrive option dropdown was added for testing, the actual dropdown in canary or prod will not show OneDrive yet.
=> [OneDrive] Onedrive provider and folder information displayed 

client-react/src/pages/static-app/configuration/ConfigurationCommandBar.tsx
=> [SWA] Fix save app setting 

client-react/src/pages/app/app-settings/AppSettingsForm.tsx, client-react/src/pages/app/app-settings/Sections/FunctionRuntimeSettingsPivot.tsx, client-react/src/pages/static-app/configuration/ConfigurationCommandBar.tsx, client-react/src/utils/scenario-checker/scenario-ids.ts, client-react/src/utils/scenario-checker/workflow-app.environment.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes AB#8449595
Old
Now
Tabs
Component
Dirty State
FunctionApp
=> [Workflow App] Enable Function Runtime setting for Workflow apps with only runtime scale monitoring property

client-react/src/models/onedrive.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client-react/src/pages/app/deployment-center/onedrive-provider/DeploymentCenterOneDriveDataLoader.tsx, client-react/src/pages/app/deployment-center/onedrive-provider/DeploymentCenterOneDriveProvider.tsx
=> [OneDrive] OneDrive deployment implementation

client-react/src/ApiHelpers/OneDriveService.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.data.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceAndBuild.tsx, client-react/src/pages/app/deployment-center/onedrive-provider/DeploymentCenterOneDriveConfiguredView.tsx, client-react/src/pages/app/deployment-center/onedrive-provider/DeploymentCenterOneDriveDataLoader.tsx
Fixes AB#8122095
Note: similarly to GitHub and Bitbucket I am not able to provide a screen shot for the OAuth flow itself as we can't test it locally. Since the code is almost identical to GitHub and Bitbucket it should work in the canary environment... but if it does not than I will  remove OneDrive from the dropdown.
=> [OneDrive] OAuth for OneDrive

server/Resources/cs-CZ/Server/Resources/Resources.resx, server/Resources/de-DE/Server/Resources/Resources.resx, server/Resources/es-ES/Server/Resources/Resources.resx, server/Resources/fr-FR/Server/Resources/Resources.resx, server/Resources/hu-HU/Server/Resources/Resources.resx, server/Resources/it-IT/Server/Resources/Resources.resx, server/Resources/ja-JP/Server/Resources/Resources.resx, server/Resources/ko-KR/Server/Resources/Resources.resx, server/Resources/nl-NL/Server/Resources/Resources.resx, server/Resources/pl-PL/Server/Resources/Resources.resx, server/Resources/pt-BR/Server/Resources/Resources.resx, server/Resources/pt-PT/Server/Resources/Resources.resx, server/Resources/qps-ploc/Server/Resources/Resources.resx, server/Resources/ru-RU/Server/Resources/Resources.resx, server/Resources/sv-SE/Server/Resources/Resources.resx, server/Resources/tr-TR/Server/Resources/Resources.resx, server/Resources/zh-CN/Server/Resources/Resources.resx, server/Resources/zh-TW/Server/Resources/Resources.resx
Updated localized strings for S149 deployment.
=> [S149 Deployment] Updated localized strings for S149 Deployment.

client-react/src/pages/app/deployment-center/DeploymentCenter.styles.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCommitLogs.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubWorkflowConfigPreview.tsx
Fixes AB#8450954
Before(Workflow):
After(Workflow):
Before(Logs):
After (Logs):
=> Workflow preview not visible in dark mode

client/src/app/shared/models/portal-resources.ts, client/src/app/site/container-settings/container-settings.ts, server/Resources/Resources.resx
Fixes AB#8476574
Before:
After:
=> AB#8476574 Remove (Preview) from Single Container title string for Xenon

client/src/app/shared/models/portal-resources.ts, client/src/app/site/container-settings/container-settings.ts, server/Resources/Resources.resx
* AB#8476574 Remove (Preview) from Single Container title string for Xenon
* empty commit to re-trigger build
Co-authored-by: Shibani Medhekar <shibanimedhekar@CHHAN-CON.redmond.corp.microsoft.com>
=> AB#8476574 Remove (Preview) from Single Container title string for Xenon (#5461)

client-react/src/ApiHelpers/DropboxService.ts, client-react/src/models/dropbox.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.data.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx, client-react/src/pages/app/deployment-center/dropbox-provider/DeploymentCenterDropboxAccount.tsx, client-react/src/pages/app/deployment-center/dropbox-provider/DeploymentCenterDropboxDataLoader.tsx, client-react/src/pages/app/deployment-center/dropbox-provider/DeploymentCenterDropboxProvider.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> [Dropbox] Scaffolding for Dropbox

server/src/stacks/2020-05-01/stacks/web-app-stacks/create/Php.ts, server/src/stacks/2020-06-01/stacks/web-app-stacks/Php.ts, server/src/tests/Stacks/2020-05-01/web-app/validations.ts
=> [Stacks][Web App] PHP 7.4 GA

server/src/stacks/2020-06-01/stacks/web-app-stacks/Node.ts
=> [Stacks][Web App] Unhide Node 14 preview

server/src/stacks/2020-05-01/stacks/web-app-stacks/config/windows/AspDotnet.ts, server/src/stacks/2020-05-01/stacks/web-app-stacks/create/AspDotnet.ts, server/src/stacks/2020-06-01/stacks/web-app-stacks/AspDotnet.ts
=> [Stacks][Web App] Update ASP.net v4 display to 4.8

client/src/app/shared/models/constants.ts, client/src/app/shared/models/portal-resources.ts, client/src/app/site/spec-picker/price-spec-manager/premium-container-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/premiumv3-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/price-spec-group.ts, server/Resources/Resources.resx
=> AB#8279603 [PV3][Fusion] Remove feature flag

client/src/app/shared/models/constants.ts, client/src/app/shared/models/portal-resources.ts, client/src/app/site/spec-picker/price-spec-manager/premium-container-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/premiumv3-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/price-spec-group.ts, server/Resources/Resources.resx
* AB#8279603 [PV3][Fusion] Remove feature flag
* Removing unused imports
Co-authored-by: Shibani Medhekar <shibanimedhekar@CHHAN-CON.redmond.corp.microsoft.com>
=> AB#8279603 [PV3][Fusion] Remove feature flag (#5453)

client-react/src/pages/app/app-settings/AppSettings.service.ts, client-react/src/pages/app/app-settings/AppSettings.types.ts, client-react/src/pages/app/app-settings/AppSettingsDataLoader.tsx, client-react/src/pages/app/app-settings/AppSettingsFormData.ts, client-react/src/pages/app/app-settings/ApplicationSettings/AppSettingAddEdit.tsx, client-react/src/pages/app/app-settings/ApplicationSettings/ApplicationSettings.tsx, client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStrings.tsx, client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStringsAddEdit.tsx, client-react/src/pages/app/app-settings/KeyVaultReferenceComponent.tsx
=> [AppSettings] Keyvault reference added for connection strings 

client-react/src/ApiHelpers/DropboxService.ts, client-react/src/models/dropbox.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/DeploymentCenterContext.ts, client-react/src/pages/app/deployment-center/DeploymentCenterDataLoader.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx, client-react/src/pages/app/deployment-center/dropbox-provider/DeploymentCenterDropboxConfiguredView.tsx
=> [Dropbox] Dropbox configured view

client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeBuildConfiguredView.tsx
Fixes AB#8490512
Node/Linux
Node/Windows
ASP/Windows
Python/Windows
Java/Windows
Tomcat/Linux
Java SE/Linux
JBoss/Linux
=> [Deployment Center V2] Update Configured view runtime stack and version

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceAndBuild.tsx, client-react/src/utils/FwLinks.ts
=> [Deployment Center V2] Learn more for banner

server/src/stacks/2020-06-01/stacks/web-app-stacks/Java.ts, server/src/stacks/2020-06-01/stacks/web-app-stacks/JavaContainers.ts
=> [Stacks][Web App] Add New Java and Tomcat Versions

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client-react/src/pages/app/deployment-center/dropbox-provider/DeploymentCenterDropboxDataLoader.tsx, client-react/src/pages/app/deployment-center/dropbox-provider/DeploymentCenterDropboxProvider.tsx
=> [Dropbox] Deployment using dropbox

server/src/stacks/2020-05-01/stacks/function-app-stacks/Java.ts, server/src/stacks/2020-06-01/models/AppStackModel.ts, server/src/stacks/2020-06-01/stacks/function-app-stacks/Java.ts
Fixes AB#8437889
Work for AB#8496057
=> [Stacks][Function App] Java 11 GA, Java 8 default

client-react/src/pages/app/deployment-center/DeploymentCenter.styles.ts, client-react/src/pages/app/deployment-center/DeploymentCenterFtps.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterPublishingUser.tsx
Fixes AB#7339625
Fixes AB#8195559
Before:
After:
=> [Deployment Center V2] FTPS textbox styling/focusing

server/src/stacks/2020-06-01/stacks/web-app-stacks/Java.ts, server/src/stacks/2020-06-01/stacks/web-app-stacks/JavaContainers.ts
=> [Stacks][Web App] Java stack updates - more from ANT88 & ANT89

client-react/src/utils/arm-utils.ts
=> AB#8538777 [Fusion] Make the check for Workflow App less exact and more robust

client-react/src/pages/app/app-settings/ApplicationSettings/AppSettingAddEdit.tsx, client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStringsAddEdit.tsx, client-react/src/pages/static-app/configuration/ConfigurationAddEdit.tsx
=> [Configuration]AppSettings values should not be cached in the browser

client-react/src/utils/stacks-utils.ts
=> [Stack] Add check for null stackVersion

client-react/src/utils/stacks-utils.ts
=> [Stack] Add check for null stackVersion 2

client-react/src/utils/stacks-utils.ts
Cherry-Pick to s149
Fixes AB#8565325
=> [Stacks][Config] Update stackVersion check

client-react/src/pages/app/deployment-center/DeploymentCenter.styles.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeLogs.tsx
=> [Deployment Center V2] Log error message getting cut off on overflow

server/src/stacks/2020-06-01/models/AppStackModel.ts, server/src/stacks/2020-06-01/stacks/web-app-stacks/AspDotnet.ts, server/src/tests/Stacks/2020-06-01/web-app/validations.ts
=> [Stacks][Web App] Add Hidden .NET 5

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> [Deployment Center V2 Devops] Tfs and Vso banner

client-react/src/pages/app/app-settings/GeneralSettings/LinuxStacks/JavaStack.tsx, client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/JavaData.ts, client-react/src/utils/stacks-utils.ts
=> [Stacks][Config] Add tag for Java Containers

client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx, client-react/src/pages/app/functions/function/function-editor/FunctionEditorDataLoader.tsx
=> [FunctionEditor] Refresh only file list on upload if some files already exist

server/src/stacks/2020-06-01/stacks/web-app-stacks/AspDotnet.ts
=> [Stacks][Web App] .NET 5 - Add GHA version

client-react/src/ApiHelpers/RuntimeStackService.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeBuildConfiguredView.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeBuildRuntimeAndVersion.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.ts, client-react/src/utils/stacks-utils.ts
Fixes AB#7800650
Windows Java 11.0.7
Windows Java 
Linux Java
Linux Python
Linux Node Options
Current .NET options
=> [Deployment Center V2] Stacks update to 2020-06-01 version

client-react/src/models/stacks/app-stacks.ts, client-react/src/utils/stacks-utils.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> [Stacks][Fusion]Early access label added

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodePivot.tsx
=> [Deployment Center V2] Update to FTPS dirty tab logic

server/src/stacks/2020-05-01/stacks/function-app-stacks/Node.ts, server/src/stacks/2020-06-01/stacks/function-app-stacks/Node.ts, server/src/stacks/2020-10-01/stacks/function-app-stacks/Node.ts
=> Show Node.js 14 in Portal (stay preview)

client-react/src/pages/app/functions/function/function-log/FunctionLogFileStreamDataLoader.tsx
=> [Functions][Logs] Ping functions host every minute to keep alive and show any new errors

client-react/src/pages/app/functions/function/function-log/FunctionLogFileStreamDataLoader.tsx
=> [Functions][Logs] Attempt reconnect if error in first 15 minutes

client-react/src/pages/app/functions/function/function-log/FunctionLogFileStreamDataLoader.tsx
=> [Functions][Logs] Fix clear logs issue

client-react/src/pages/app/functions/create/FunctionCreate.tsx, client-react/src/pages/app/functions/create/FunctionCreateDataLoader.tsx
=> [Function][Create] Error message on failed host status or function templates call

server/src/stacks/2020-05-01/stacks/function-app-stacks/Custom.ts, server/src/stacks/2020-06-01/stacks/function-app-stacks/Custom.ts, server/src/stacks/2020-10-01/stacks/function-app-stacks/Custom.ts, server/src/tests/Stacks/2020-06-01/function-app/validations.ts, server/src/tests/Stacks/2020-10-01/function-app/validations.ts
=> [Function][CustomStack]Remove preview flag

client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeBuildRuntimeAndVersion.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx, client-react/src/pages/app/deployment-center/utility/GitHubActionUtility.ts
* Fix the java scenario for github action in DC preview
* addressed PR comments.
=> Fix the java scenario for github action in DC preview (#5518)

server/src/stacks/2020-05-01/stacks/function-app-stacks/Custom.ts, server/src/stacks/2020-06-01/stacks/function-app-stacks/Custom.ts, server/src/stacks/2020-10-01/stacks/function-app-stacks/Custom.ts, server/src/tests/Stacks/2020-05-01/function-app/validations.ts, server/src/tests/Stacks/2020-06-01/function-app/validations.ts, server/src/tests/Stacks/2020-10-01/function-app/validations.ts
=> Update Custom Stack's display value

client-react/src/pages/app/deployment-center/utility/GitHubActionUtility.ts, client/src/app/site/deployment-center/deployment-center-setup/wizard-logic/github.service.ts
I had updated the value in the stacks api (2020-05-01) but forgot to update here. Original PR: https://github.com/Azure/azure-functions-ux/pull/5524
=> Workflowfile generation for linux .net 5 in classic deployment center

client-react/src/pages/app/app-settings/FunctionRuntimeSettings/RuntimeVersion.tsx, client-react/src/utils/FwLinks.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes AB#8724951
New
Old
Old and New (if user is on v2 already)
New (when v2 user changes to v3)
After updating to v3
=> [RuntimeVersion] [FunctionConfig] Remove v2 from dropdown

client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/DotNetStack.tsx, client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/WindowsStacks.tsx
=> [Stacks][Configuration] Key set updated for Dotnet stack dropdown 

client-react/src/SiteState.ts, client-react/src/pages/app/SiteRouter.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSettings.tsx, client-react/src/pages/app/deployment-center/utility/GitHubActionUtility.ts
There really isn't any UX to show here yet.. I'm just putting all the helper pieces in place.
=> Introduce retrieving function app workflow file content and disable container functionapp github action source.

server/src/stacks/2020-05-01/stacks/web-app-stacks/create/AspDotnet.ts, server/src/stacks/2020-06-01/stacks/web-app-stacks/AspDotnet.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts, server/src/tests/Stacks/2020-05-01/web-app/validations.ts, server/src/tests/Stacks/2020-06-01/web-app/validations.ts
**Do not merge until s151 is forked**
Work for AB#8353326
=> [Stacks][Web App] Unhide .NET 5

client-react/src/ApiHelpers/RuntimeStackService.ts, client-react/src/models/site/site.ts, client-react/src/models/stacks/app-stacks.ts, client-react/src/models/stacks/function-app-stacks.ts, client-react/src/models/stacks/web-app-stacks.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.data.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeBuildRuntimeAndVersion.tsx
you can get the query params to access preview deployment center in function apps from here - https://aka.ms/functionslocal-deploymentcenter
Sample from Linux
Sample from Windows
=> Deployment Center preview: Enable stack selection for function apps.

server/src/deployment-center/github/github.controller.ts
=> [GitHub Actions/Create] Get token for GitHub OAuth for creates

server/src/deployment-center/github/github.controller.ts
=> [GitHub Actions/Create] Remove OAuth parameters

client-react/src/ApiHelpers/AppInsightsService.ts, client-react/src/models/app-insights.ts, client-react/src/pages/app/functions/function/function-log/FunctionLogAppInsightsDataLoader.tsx, client-react/src/utils/CommonConstants.ts
Reverts Azure/azure-functions-ux#5553
=> Revert "Update Quickpulse tokens to ARM"

client-react/src/ApiHelpers/AppInsightsService.ts, client-react/src/models/app-insights.ts, client-react/src/pages/app/functions/function/function-log/FunctionLogAppInsightsDataLoader.tsx, client-react/src/utils/CommonConstants.ts
=> [Function][Monitor] Split off quickpulse token call and update api

.vscode/settings.json, client-react/src/ApiHelpers/AppInsightsService.ts, client-react/src/models/app-insights.ts, client-react/src/pages/app/functions/function/monitor/FunctionMonitorDataLoader.tsx
=> [Functions][Monitor] Remove getToken call for AppInsights, call via portal auth communicator 

client-react/package-lock.json, client-react/package.json, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerDockerHubSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerFormBuilder.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerPrivateRegistrySettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerRegistrySettings.tsx, client-react/src/utils/CommonConstants.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Introduce the ability to add a docker compose YML. There will be future PRs which introduce more validation and also ability to upload a yml in to the textbox. 
Docker Compose YML should only work with non-github action based setup.
=> Introduce docker compose functionality on the deployment center

server/src/stacks/2020-05-01/stacks/web-app-stacks/create/Node.ts, server/src/stacks/2020-06-01/stacks/web-app-stacks/Node.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Node.ts, server/src/tests/Stacks/2020-05-01/web-app/validations.ts
=> [Stacks][Web App] Add node 14 as early access, linux and windows

client-react/src/components/ActionBar.tsx, client-react/src/pages/app/functions/new-create-preview/FunctionCreate.styles.ts, client-react/src/pages/app/functions/new-create-preview/local-create/LocalCreateInstructions.tsx
=> Function create scrolling fixed

client-react/src/pages/app/app-settings/AppSettings.service.ts, client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStringsAddEdit.tsx
=> Update the API response for ConnectionString keyvault reference

client-react/src/pages/app/deployment-center/DeploymentCenterCommandBar.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> [Deployment Center V2] Redeploy/sync

client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEditBasic.tsx
=> Log error when the getStorage mount call fails

client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/JavaStack.tsx
=> Handle deep copy issue for Java Windows stacks

client-react/src/pages/app/deployment-center/DeploymentCenterFormBuilder.ts, client/src/app/site/deployment-center/provider-dashboards/credentials-dashboard/credentials-dashboard.component.ts, client/src/app/site/deployment-center/provider-dashboards/deployment-credentials/deployment-credentials.component.ts
fixes AB#7742758
Regex test validation:
=> FTPS Password regex simplification and accuracy

client-react/src/ApiHelpers/SiteService.ts, client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/JavaStack.tsx, client-react/src/pages/app/deployment-center/DeploymentCenter.data.ts, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubDisconnect.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.ts
Fixes AB# 
Deployed with Source controls API preserving workflow file:
Deployed with Source controls API deleting workflow file:
=> [GitHub Actions/Create] Update disconnect from GitHub Actions

client-react/src/components/form-controls/DropDown.tsx, client-react/src/pages/app/app-settings/GeneralSettings/stacks/function-app/FunctionAppStackSettings.tsx
=> Handle windows node version for function apps

client-react/src/react-app-env.d.ts, client-react/src/utils/scenario-checker/scenario-ids.ts, client-react/src/utils/url.ts
=> [Function][Config] Remove standalone runtime reference

client-react/src/pages/app/deployment-center/DeploymentCenter.data.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/DeploymentCenterFormBuilder.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceAndBuild.tsx, client-react/src/pages/app/deployment-center/devops-provider/DeploymentCenterDevOpsDataLoader.tsx, client-react/src/pages/app/deployment-center/devops-provider/DeploymentCenterDevOpsProvider.tsx, client-react/src/pages/app/deployment-center/devops-provider/DeploymentCenterVstsBuildConfiguredView.tsx, client-react/src/utils/CommonConstants.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
feature flag query parameter - websitesextension_ext=appsvc.enableAzureDevOpsSetup%3Dtrue
Some of the error handling and the saving of data will be happening in the follow up PRs.
=> Introduce devops on deployment center preview behind a feature flag

client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceAndBuild.tsx, client-react/src/pages/app/deployment-center/devops-provider/DeploymentCenterDevOpsDataLoader.tsx, client-react/src/pages/app/deployment-center/devops-provider/DeploymentCenterDevOpsProvider.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> Introduce scenario checkers and error messages for DevOps

client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubWorkflowConfigSelector.tsx
=> [Deployment Center V2] Workflow option radio buttons

client-react/src/pages/app/app-settings/GeneralSettings/stacks/function-app/FunctionAppStackSettings.tsx
=> Show linux stacks in Configuration

client-react/src/pages/app/deployment-center/DeploymentCenterFormBuilder.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceAndBuild.tsx, client-react/src/pages/app/deployment-center/devops-provider/DeploymentCenterDevOpsDataLoader.tsx, client-react/src/pages/app/deployment-center/devops-provider/DeploymentCenterDevOpsKuduBuildConfiguredView.tsx, client-react/src/pages/app/deployment-center/devops-provider/DeploymentCenterDevOpsProvider.tsx, client-react/src/utils/CommonConstants.ts
Include the ability to save/disconnect Azure Devops selections for Kudu build. Also remove the feature flag.
=> Deployment Center. Add in the save functionality for AzureRepos and remove flag

client-react/src/pages/app/functions/function/monitor/FunctionMonitor.tsx, client-react/src/pages/app/functions/function/monitor/FunctionMonitorDataLoader.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> [Function Monitor] Banner added when incorrect key is configured

client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubWorkflowConfigSelector.tsx
=> [Deployment Center V2] Workflow Preview Button fix

client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubWorkflowConfigSelector.tsx, server/Resources/Resources.resx
=> [GitHub Actions/Create] Update Workflow option radio buttons + remove banner

client-react/src/pages/app/functions/new-create-preview/portal-create/TemplateList.tsx
=> [FunctionCreate] Show warning banner when extensionbundle not setup

client-react/src/pages/app/app-settings/GeneralSettings/LinuxStacks/JavaStack.tsx, client-react/src/pages/app/app-settings/GeneralSettings/LinuxStacks/LinuxStacks.data.ts, client-react/src/pages/app/app-settings/GeneralSettings/LinuxStacks/LinuxStacks.tsx, client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/DotNetStack.tsx, client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/JavaData.ts, client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/JavaStack.tsx, client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/PhpStack.tsx, client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/PythonStack.tsx, client-react/src/utils/FwLinks.ts, client-react/src/utils/stacks-utils.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes AB#8775168
Early-Access
Not Early-Access
=> [Stacks][Configuration] Early Access stack message added

client-react/src/pages/app/deployment-center/DeploymentCenter.styles.ts, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubDisconnect.tsx, server/Resources/Resources.resx
Fixes AB#
Link to Figma: https://www.figma.com/file/hUcIzai0sRSgeQ8HjtbRtF/Deployment-center?node-id=1071%3A24
Before:
After:
=> [Deployment Center V2] Disconnect content update

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerLogs.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> [Deployment Center V2] Container logs description

client-react/src/ApiHelpers/DropboxService.ts, client-react/src/ApiHelpers/HttpClient.ts, client-react/src/ApiHelpers/OneDriveService.ts
Test to see if the CORS issue is fixed by removing the well known headers.
=> Fix CORS issue due to well known headers.

client-react/src/ApiHelpers/BitbucketService.ts
=> [Deployment center v2] Bitbucket header update

server/Resources/cs-CZ/Server/Resources/Resources.resx, server/Resources/de-DE/Server/Resources/Resources.resx, server/Resources/es-ES/Server/Resources/Resources.resx, server/Resources/fr-FR/Server/Resources/Resources.resx, server/Resources/hu-HU/Server/Resources/Resources.resx, server/Resources/it-IT/Server/Resources/Resources.resx, server/Resources/ja-JP/Server/Resources/Resources.resx, server/Resources/ko-KR/Server/Resources/Resources.resx, server/Resources/nl-NL/Server/Resources/Resources.resx, server/Resources/pl-PL/Server/Resources/Resources.resx, server/Resources/pt-BR/Server/Resources/Resources.resx, server/Resources/pt-PT/Server/Resources/Resources.resx, server/Resources/qps-ploc/Server/Resources/Resources.resx, server/Resources/ru-RU/Server/Resources/Resources.resx, server/Resources/sv-SE/Server/Resources/Resources.resx, server/Resources/tr-TR/Server/Resources/Resources.resx, server/Resources/zh-CN/Server/Resources/Resources.resx, server/Resources/zh-TW/Server/Resources/Resources.resx
=> S153: Update resources

client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeLogs.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> [Deployment Center V2] Adding commit author to logs

client/src/app/shared/models/portal-resources.ts, client/src/app/site/container-settings/container-settings.ts, server/Resources/Resources.resx
=> Disable docker compose in national clouds

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceKuduConfiguredView.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubDisconnect.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
fixes AB#8839029
Before:
After:
=> Show error message on disconnect from source control

client-react/src/pages/app/deployment-center/local-git-provider/DeploymentCenterLocalGitProvider.tsx, client-react/src/utils/FwLinks.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes AB#8180355
https://docs.microsoft.com/en-us/azure/app-service/deploy-local-git
=> [Deployment Center V2] Local Git description

client-react/src/pages/app/deployment-center/DeploymentCenter.styles.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeDataLoader.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeLogs.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeLogsTimer.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodePivot.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> Add a timer to refresh the deployment center code logs

client-react/src/utils/CommonConstants.ts, client-react/src/utils/scenario-checker/windows-code.environment.ts
=> Enable BYOS behind hide-key

client-react/src/pages/app/deployment-center/utility/GitHubActionUtility.ts
=> [Deployment Center V2] workflow_dispatch update

client-react/src/pages/app/deployment-center/utility/GitHubActionUtility.ts, server/src/workflows/2020-12-01/function-app-configs/java-linux.config.yml, server/src/workflows/2020-12-01/function-app-configs/java-windows.config.yml
=> [Deployment Center V2] Java function app workflow update

client-react/src/models/telemetry.ts, client-react/src/pages/app/deployment-center/DeploymentCenterCommandBar.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterDataLoader.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterFtps.tsx, client-react/src/pages/app/deployment-center/bitbucket-provider/DeploymentCenterBitbucketDataLoader.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeBuildRuntimeAndVersion.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeDataLoader.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodePivot.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceAndBuild.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceKuduConfiguredView.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCommitLogs.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrDataLoader.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerComposeFileUploader.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerDataLoader.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerRegistrySettings.tsx, client-react/src/pages/app/deployment-center/devops-provider/DeploymentCenterDevOpsDataLoader.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubConfiguredView.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubDataLoader.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubDisconnect.tsx, client-react/src/pages/app/deployment-center/publish-profile/DeploymentCenterPublishProfileCommandBar.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.ts
There are no functional changes in this PR. This PR updates the Deployment Center experience to adopt the new telemetry pipeline introduced and add new logs where needed. There are three tasks to be be achieved from the logs in the Deployment Center experience:
1. ability to investigate individual user issues
2. ability to generate aggregation reports on feature usage (github action vs kudu, workflow options, etc)
3. ability to generate funnel metrics (user dropoff points, most time spent, etc.)
I believe this PR achieves 1 and 2 above pretty well. And more analysis from the logs will determine what should be updated for 3.
=> Update telemetry for deployment center

server/src/workflows/2020-12-01/WorkflowService.ts, server/src/workflows/2020-12-01/container-configs/container-linux.config.yml, server/src/workflows/2020-12-01/function-app-configs/dotnetcore-linux.config.yml, server/src/workflows/2020-12-01/function-app-configs/dotnetcore-windows.config.yml, server/src/workflows/2020-12-01/function-app-configs/java-linux.config.yml, server/src/workflows/2020-12-01/function-app-configs/java-windows.config.yml, server/src/workflows/2020-12-01/function-app-configs/node-linux.config.yml, server/src/workflows/2020-12-01/function-app-configs/node-windows.config.yml, server/src/workflows/2020-12-01/function-app-configs/powershell-windows.config.yml, server/src/workflows/2020-12-01/function-app-configs/python-linux.config.yml, server/src/workflows/2020-12-01/web-app-configs/aspnet-windows.config.yml, server/src/workflows/2020-12-01/web-app-configs/dotnetcore-linux.config.yml, server/src/workflows/2020-12-01/web-app-configs/dotnetcore-windows.config.yml, server/src/workflows/2020-12-01/web-app-configs/java-jar-linux.config.yml, server/src/workflows/2020-12-01/web-app-configs/java-jar-windows.config.yml, server/src/workflows/2020-12-01/web-app-configs/java-war-linux.config.yml, server/src/workflows/2020-12-01/web-app-configs/java-war-windows.config.yml, server/src/workflows/2020-12-01/web-app-configs/node-linux.config.yml, server/src/workflows/2020-12-01/web-app-configs/node-windows.config.yml, server/src/workflows/2020-12-01/web-app-configs/python-linux.config.yml, server/src/workflows/2020-12-01/web-app-configs/python-windows.config.yml, server/src/workflows/workflow.controller.ts
=> [Workflow file update] Find + Replace workflow variables

client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/WindowsStacks.tsx
=> Show disabled stack dropdown when you have reader permissions

client-react/src/pages/app/app-settings/FunctionRuntimeSettings/RuntimeVersionBanner.tsx
=> [CRI 219774218] Fix the null check

client-react/src/ApiHelpers/GitHubService.ts, client-react/src/pages/app/deployment-center/DeploymentCenterCommandBar.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, server/src/deployment-center/github/github.controller.ts
=> [Deployment Center V2] GitHub Actions sync functionality

server/src/workflows/2020-12-01/WorkflowService.ts
The path is starting from the server root folder so a longer file path is needed + removing logging for errors.
=> [Workflow Files] Updating file path

client-react/src/pages/app/deployment-center/DeploymentCenter.styles.ts, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubWorkflowConfigPreview.tsx, client-react/src/pages/app/deployment-center/publish-profile/DeploymentCenterPublishProfilePanel.tsx
=> [DeploymentCenterV2][Accessibility] Close button for panels

client-react/src/pages/app/functions/common/ResourceDropdown.tsx
=> [Integrate] Remove the public cloud endpoint from the app settings check

client/src/app/shared/models/portal-resources.ts, client/src/app/site/container-settings/container-settings.component.html, client/src/app/site/deployment-center/deployment-center.component.html, server/Resources/Resources.resx
=> Add deprecation warning message for container settings and deployment center

server/src/stacks/2020-05-01/stacks/function-app-stacks/Node.ts, server/src/stacks/2020-06-01/stacks/function-app-stacks/Node.ts, server/src/stacks/2020-10-01/stacks/function-app-stacks/Node.ts
Resolves https://github.com/Azure/azure-functions-nodejs-worker/issues/353
=> Remove Node.js 14 from Preview

server/gulpfile.js, server/src/workflows/2020-12-01/WorkflowService.ts, server/src/workflows/2020-12-01/web-app-configs/java-war-windows.config.yml
=> [Workflow File Update] Workflow path update + including .config.yml files in static file bundling

client-react/src/pages/app/deployment-center/bitbucket-provider/DeploymentCenterBitbucketConfiguredView.tsx, client-react/src/pages/app/deployment-center/bitbucket-provider/DeploymentCenterBitbucketDataLoader.tsx, client-react/src/pages/app/deployment-center/dropbox-provider/DeploymentCenterDropboxConfiguredView.tsx, client-react/src/pages/app/deployment-center/dropbox-provider/DeploymentCenterDropboxDataLoader.tsx, client-react/src/pages/app/deployment-center/external-provider/DeploymentCenterExternalConfiguredView.tsx, client-react/src/pages/app/deployment-center/onedrive-provider/DeploymentCenterOneDriveConfiguredView.tsx, client-react/src/pages/app/deployment-center/onedrive-provider/DeploymentCenterOneDriveDataLoader.tsx, client-react/src/pages/app/deployment-center/publish-profile/DeploymentCenterPublishProfileCommandBar.tsx
=> [Deployment Center V2] Updating telemetry

client/src/app/shared/models/portal-resources.ts, client/src/app/site/container-settings/container-settings.component.html, client/src/app/site/deployment-center/deployment-center.component.html, server/Resources/Resources.resx
Reverts Azure/azure-functions-ux#5644
=> Revert "Add deprecation warning message for container settings and deployment center"

client-react/src/pages/app/deployment-center/DeploymentCenter.styles.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeBuildConfiguredView.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeBuildRuntimeAndVersion.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubWorkflowConfigPreview.tsx
Fixes AB#8179919
Before:
After:
Before:
After:
=> [Deployment Center V2] Increase spacing between sections

client-react/src/ApiHelpers/RuntimeStackService.ts, client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/WindowsStacks.tsx, client-react/src/utils/CommonConstants.ts
=> [Configuration] Update stack version to 2020-10-01

client-react/src/pages/app/SiteRouter.tsx
=> [Functions][Proxies] Absorb readonly state from generatedBy

client/src/app/shared/models/portal-resources.ts, client/src/app/site/container-settings/container-settings.component.html, client/src/app/site/deployment-center/deployment-center.component.html, server/Resources/Resources.resx
This reverts commit 27214347d05a124c224f7e0db9daa0f182774ebd.
=> Revert "Revert "add warnings (#5644)" (#5651)"

client/src/app/shared/models/portal-resources.ts, client/src/app/site/container-settings/container-settings.component.html, client/src/app/site/deployment-center/deployment-center.component.html, server/Resources/Resources.resx
This reverts commit 27214347d05a124c224f7e0db9daa0f182774ebd.
=> Cherry-pick: Revert "Revert "add warnings (#5644)" (#5651)" (#5663)

client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/DotNetStack.tsx
Co-authored-by: Krrish Mittal <takyyon@MININT-3BKVT16.northamerica.corp.microsoft.com>
=> [Cherry-pick] dotnet check update

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeBuildCallout.tsx, client-react/src/utils/scenario-checker/function-app.environment.ts, client-react/src/utils/scenario-checker/scenario-ids.ts
=> Disable all non GitHub Action options for Consumption Function Apps.

client/src/app/site/spec-picker/price-spec-manager/free-plan-price-spec.ts
Reverts Azure/azure-functions-ux#5678
We need to wait till ANT93 is done.
=> Revert "AB#9219848 [Spec Picker] Hide free sku from spec picker for all (Linux as well as Windows) FunctionApp creates"

client/src/image/slots.svg
=> [Slots] Update slots icon

client/src/app/shared/models/portal-resources.ts, client/src/app/site/console/bash/bash.component.ts, client/src/app/site/console/cmd/cmd.component.ts, client/src/app/site/console/powershell/powershell.component.ts, client/src/app/site/console/shared/components/abstract.windows.component.ts, server/Resources/Resources.resx
Fixes [#8753316](https://msazure.visualstudio.com/Antares/_workitems/edit/8753316)
BEFORE
AFTER
=> Show proper error message when console command fails

client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx, client-react/src/pages/app/functions/function/function-editor/FunctionEditorDataLoader.tsx
=> [FunctionEditor] Log data onSave

client-react/src/models/site/config.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.styles.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/DeploymentCenterCommandBar.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeBuildCallout.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceAndBuild.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSource.tsx, client-react/src/pages/app/deployment-center/devops-provider/DeploymentCenterVstsBuildProvider.tsx, client-react/src/utils/FwLinks.ts, client/src/app/shared/models/portal-resources.ts, client/src/app/site/spec-picker/price-spec-manager/free-plan-price-spec.ts, server/Resources/Resources.resx
Fixes AB#9228248
Code (WebApp):
Code (FunctionApp):
Container:
=> [Deployment Center V2] Adding Azure Pipelines as Build Provider

client/src/app/site/container-settings/container-settings.component.html, client/src/app/site/container-settings/container-settings.component.ts, client/src/app/site/deployment-center/deployment-center.component.html, client/src/app/site/deployment-center/deployment-center.component.ts, server/Resources/Resources.resx
=> Update messages and add links in the classic experiences

server/Resources/Resources.resx
=> [Deployment Center V2] DevOps configured view banner message update

client-react/src/pages/app/SiteRouter.tsx
=> Remove /functions call from SiteState

client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/DotNetStack.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> Update .NET Version label

client-react/src/ApiHelpers/AppInsightsService.ts, client-react/src/pages/app/functions/function/function-log/FunctionLog.constants.ts, client-react/src/utils/CommonConstants.ts
=> [Function][Monitor] Add quickpulse and appinsight endpoints

client/src/app/shared/models/arm/site.ts, client/src/app/site/slots/add-slot/add-slot.component.ts
Fixes AB#9277879
* Not cloning - Provide an empty config object
* Cloning Prod - Omit the config
* Cloning Non-Prod - Provide the source config
=> [Slots][Regression] Clone slots regression with VNet

server/Resources/Resources.resx
=> Update Resources.resx, update registries spelling.

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrDataLoader.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerFormBuilder.ts
fixes AB#9247637
fixes AB#9266351
=> Correctly show the value of continuous deployment based on app setting.

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrDataLoader.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerFormBuilder.ts
=> Cherry-pick: Correctly show the value of continuous deployment based on app setting.

client-react/src/components/DisplayTableWithCommandBar/DisplayTableWithCommandBar.tsx, client-react/src/pages/app/app-settings/AppSettingsCommandBar.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterCommandBar.tsx, client-react/src/pages/app/deployment-center/publish-profile/DeploymentCenterPublishProfileCommandBar.tsx, client-react/src/pages/app/functions/app-files/AppFilesCommandBar.tsx, client-react/src/pages/app/functions/app-keys/AppKeysCommandBar.tsx, client-react/src/pages/app/functions/function/function-editor/FunctionEditorCommandBar.tsx, client-react/src/pages/app/functions/function/function-keys/FunctionKeysCommandBar.tsx, client-react/src/pages/app/functions/function/function-log/FunctionLogCommandBar.tsx, client-react/src/pages/app/functions/function/integrate/BindingPanel/EditBindingCommandBar.tsx, client-react/src/pages/app/functions/function/integrate/FunctionIntegrateCommandBar.tsx, client-react/src/pages/app/log-stream/LogStreamCommandBar.tsx, client-react/src/pages/static-app/configuration/ConfigurationCommandBar.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> add overflow button aria label on the command bar.

client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/WindowsStacks.tsx
Co-authored-by: Krrish Mittal <takyyon@9889312-0513.northamerica.corp.microsoft.com>
=> [Cherry-Pick] Update onChange for dropdown (#5708)

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx
=> [Deployment Center V2] Update callout primary & default button order

client-react/src/components/CustomBanner/CustomBanner.tsx, client-react/src/components/CustomPanel/CustomPanel.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceAndBuild.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
fixes AB#8994746
Add tab selection for text in the message bar including the learn more link and add aria label for learn more link.
=> A11y changes for MessageBar and LearnMore link

client-react/src/pages/app/deployment-center/DeploymentCenterFormBuilder.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeFormBuilder.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodePivot.tsx
=> [Deployment Center V2] Update to validation and conditions for updating publishing user + dirty state for tabs

client-react/src/pages/static-app/configuration/ConfigurationCommandBar.tsx, client-react/src/pages/static-app/configuration/ConfigurationDataLoader.tsx
=> [SWA]Update command bar on state change and update app-settings on Save

server/src/workflows/2020-12-01/WorkflowService.ts, server/src/workflows/WorkflowModel.ts, server/src/workflows/workflow.controller.ts
=> [Workflow File Update] Updating runtime stacks for dotnet

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeDataLoader.tsx
Fixes AB#9278916
Before:
After:
=> [Deployment Center V2] Adding Loading for FTPS tab + logs

client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeLogs.tsx
Fixes AB#9315565
Before:
After:
=> [Deployment Center V2] Checkin message changed to message and JSON removed

client-react/src/pages/app/deployment-center/DeploymentCenterFtps.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterPublishingUser.tsx, client-react/src/pages/app/deployment-center/bitbucket-provider/DeploymentCenterBitbucketConfiguredView.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeBuildRuntimeAndVersion.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceAndBuild.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceKuduConfiguredView.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrSettings.tsx, client-react/src/pages/app/deployment-center/devops-provider/DeploymentCenterDevOpsProvider.tsx, client-react/src/pages/app/deployment-center/devops-provider/DeploymentCenterVstsBuildConfiguredView.tsx, client-react/src/pages/app/deployment-center/dropbox-provider/DeploymentCenterDropboxConfiguredView.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubConfiguredView.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubWorkflowConfigPreview.tsx, client-react/src/pages/app/deployment-center/onedrive-provider/DeploymentCenterOneDriveConfiguredView.tsx
fixes AB#8964935
fixes AB#8965051
=> Unique IDs for all message banners.

client-react/src/components/form-controls/DropDownnoFormik.tsx, client-react/src/components/form-controls/TextFieldNoFormik.tsx
=> Add ariaRequired tag on the control itself for a11y

server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts
@nertim let me know if this is what you had in mind
Fixes AB#9249218
=> [Stacks][Dotnet] Update value to be more informative of the type of dotnet

client-react/src/pages/app/deployment-center/DeploymentCenterPublishingUser.tsx, client-react/src/utils/FwLinks.ts, server/Resources/Resources.resx
Fixes AB#9278959
Documentation: https://docs.microsoft.com/en-us/azure/app-service/deploy-configure-credentials
Before:
After:
=> [Deployment Center V2] Update publishing username messaging + adding learn more link

server/src/stacks/2020-10-01/models/FunctionAppStackModel.ts, server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts, server/src/tests/Stacks/2020-10-01/function-app/validations.ts
@ankitkumarr please take a look
=> [Stacks][Function App] add .NET5 as hidden stack for function app

client-react/src/components/form-controls/TextFieldNoFormik.tsx, client-react/src/pages/app/functions/function/function-editor/FunctionEditorDataLoader.tsx
=> Fix Accessibility for Copy button on TextField Control

client-react/src/ApiHelpers/SiteService.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.data.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeLogs.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCommitLogs.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
fixes AB#9304383
Ability to redeploy a specific commit for a Kudu build.
=> Add redeploy functionality for specific commit.

client-react/src/ApiHelpers/GitHubService.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.data.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodePivot.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterGitHubActionsCodeLogs.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx, server/src/deployment-center/github/github.controller.ts
=> [Deployment Center V2] Adding GitHub Actions Logs to Deployment Center

client/src/app/shared/models/portal-resources.ts, client/src/app/site/container-settings/container-settings.ts, server/Resources/Resources.resx
This reverts commit 1dc7ccf78985748103da37710c6e410b38f43681.
=> Revert "disable docker compose in national clouds (#5614)"

client/src/app/shared/models/portal-resources.ts, client/src/app/site/container-settings/container-settings.ts, server/Resources/Resources.resx
This reverts commit 1dc7ccf78985748103da37710c6e410b38f43681.
=> CP: Revert "disable docker compose in national clouds (#5614)" (#5733)

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeLogsTimer.tsx
=> [Deployment Center V2] Clearing interval

client-react/src/pages/app/deployment-center/code/DeploymentCenterGitHubActionsCodeLogs.tsx
=> [Deployment Center V2] Adding support for source control workflow names

client-react/src/components/ActionBar.tsx, client-react/src/components/CustomPanel/CustomPanel.styles.ts, client-react/src/components/CustomPanel/CustomPanel.tsx, client-react/src/pages/app/functions/function/function-editor/function-test/FunctionTest.tsx, client/src/app/shared/models/portal-resources.ts
Update the alignment of the tabs in the functions test custom panel.
Before:
After:
Also tested Config and DC panels.
=> Update the alignment of the tabs in the functions test custom panel.

client-react/src/pages/app/deployment-center/DeploymentCenterFormBuilder.ts, client-react/src/pages/app/deployment-center/external-provider/DeploymentCenterExternalConfiguredView.tsx
Fixes AB#9398761
ssh with username
ssh without username
https with username
https without username
=> [Deployment Center V2] External Git ssh support

client-react/src/pages/app/deployment-center/DeploymentCenter.styles.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeLogsTimer.tsx
=> [Deployment Center V2] Removing refresh command bar in logs

client-react/src/pages/app/deployment-center/code/DeploymentCenterGitHubActionsCodeLogs.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> [Deployment Center V2] Cancel workflow callout

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSource.tsx
=> [Deployment Center V2]Update Container Settings radio button default selection 

client-react/src/pages/app/change-app-plan/CreateOrSelectPlan.tsx
Fixes AB#6169555
Before:
After:
=> [WCAG] Change ASP Blade

client/src/app/shared/services/scenario/azure.environment.ts
Fixes [AB#9413271](https://msazure.visualstudio.com/Antares/_workitems/edit/9413271)
=> Updating getSiteSlotLimits scenario check to handle IsolatedV2 SKU

client-react/src/utils/scenario-checker/national-cloud.environment.ts
=> enable external git for windows apps on national clouds

client-react/src/pages/app/deployment-center/bitbucket-provider/DeploymentCenterBitbucketProvider.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubProvider.tsx, client-react/src/theme/CustomOfficeFabric/AzurePortal/ComboBox.styles.ts
Fixes AB#9419445
Verified the style changes look good where ComboBox is used:
=> [Deployment Center V2] Searchable Dropdowns

client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/DeploymentCenterCommandBar.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterDataLoader.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterFtps.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeDataLoader.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeLogs.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodePivot.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterGitHubActionsCodeLogs.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerDataLoader.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerLogs.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerPivot.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSettings.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> DeploymentCenter - Add loading indicator for each tab

client-react/src/models/portal-models.ts, client-react/src/pages/app/SiteRouter.tsx, client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx, client-react/src/utils/CommonConstants.ts, client-react/src/utils/FunctionAppService.ts, client-react/src/utils/SiteHelper.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> Explicit check added for .NET 5 FunctionApps in FunctionEditor

client-react/src/pages/app/deployment-center/DeploymentCenter.styles.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerLogs.tsx
=> DeploymentCenter Container - auto scroll container logs to bottom

client-react/src/pages/app/deployment-center/DeploymentCenter.styles.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeLogs.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterGitHubActionsCodeLogs.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerLogs.tsx
=> [Deployment Center] Changing container logs refresh to button

client-react/src/pages/app/app-settings/AppSettings.utils.ts, client-react/src/pages/app/app-settings/AppSettingsCommandBar.tsx, client-react/src/pages/app/app-settings/ApplicationSettings/ApplicationSettings.tsx, client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStrings.tsx, client-react/src/pages/app/app-settings/SettingSourceColumn.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> Source component refactoring for Config blade

server/Resources/cs-CZ/Server/Resources/Resources.resx, server/Resources/de-DE/Server/Resources/Resources.resx, server/Resources/es-ES/Server/Resources/Resources.resx, server/Resources/fr-FR/Server/Resources/Resources.resx, server/Resources/hu-HU/Server/Resources/Resources.resx, server/Resources/it-IT/Server/Resources/Resources.resx, server/Resources/ja-JP/Server/Resources/Resources.resx, server/Resources/ko-KR/Server/Resources/Resources.resx, server/Resources/nl-NL/Server/Resources/Resources.resx, server/Resources/pl-PL/Server/Resources/Resources.resx, server/Resources/pt-BR/Server/Resources/Resources.resx, server/Resources/pt-PT/Server/Resources/Resources.resx, server/Resources/qps-ploc/Server/Resources/Resources.resx, server/Resources/ru-RU/Server/Resources/Resources.resx, server/Resources/sv-SE/Server/Resources/Resources.resx, server/Resources/tr-TR/Server/Resources/Resources.resx, server/Resources/zh-CN/Server/Resources/Resources.resx, server/Resources/zh-TW/Server/Resources/Resources.resx
=> Updating localized strings

client-react/src/pages/app/functions/common/BindingFormBuilder.tsx, client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx, client-react/src/pages/app/functions/function/function-editor/function-test/FunctionTestInput.tsx, client-react/src/pages/app/functions/function/integrate/binding-card/InputBindingCard.tsx, client-react/src/pages/app/functions/function/integrate/binding-card/OutputBindingCard.tsx, client-react/src/pages/app/functions/function/integrate/binding-card/TriggerBindingCard.tsx, client-react/src/utils/BindingManager.ts
=> Make the binding-type check case insensitive

client-react/src/pages/app/functions/common/BindingFormBuilder.tsx, client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx, client-react/src/pages/app/functions/function/function-editor/function-test/FunctionTestInput.tsx, client-react/src/pages/app/functions/function/integrate/binding-card/InputBindingCard.tsx, client-react/src/pages/app/functions/function/integrate/binding-card/OutputBindingCard.tsx, client-react/src/pages/app/functions/function/integrate/binding-card/TriggerBindingCard.tsx, client-react/src/utils/BindingManager.ts
* bindingtype check made case-insensitive
* update 1
Co-authored-by: Krrish Mittal <takyyon@V-CHRISMUIR-PC.northamerica.corp.microsoft.com>
=> Make the binding-type check case insensitive (#5769)

client-react/src/models/portal-models.ts, client-react/src/models/service-linker.ts, client-react/src/pages/app/app-settings/AppSettings.tsx, client-react/src/pages/app/app-settings/AppSettings.types.ts, client-react/src/pages/app/app-settings/AppSettings.utils.ts, client-react/src/pages/app/app-settings/AppSettingsCommandBar.tsx, client-react/src/pages/app/app-settings/AppSettingsForm.tsx, client-react/src/pages/app/app-settings/ApplicationSettings/ApplicationSettings.tsx, client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStrings.tsx, client-react/src/pages/app/app-settings/Sections/ApplicationSettingsPivot.tsx, client-react/src/utils/CommonConstants.ts
ServiceLinker feature is only for private preview and comes into picture using the feature-flag only.
Fixes AB#9459871
=> *Update* service linker feature added (and related refactoring)

client-react/src/models/portal-models.ts, client-react/src/models/service-linker.ts, client-react/src/pages/app/app-settings/AppSettings.tsx, client-react/src/pages/app/app-settings/AppSettings.types.ts, client-react/src/pages/app/app-settings/AppSettings.utils.ts, client-react/src/pages/app/app-settings/AppSettingsCommandBar.tsx, client-react/src/pages/app/app-settings/AppSettingsForm.tsx, client-react/src/pages/app/app-settings/ApplicationSettings/ApplicationSettings.tsx, client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStrings.tsx, client-react/src/pages/app/app-settings/Sections/ApplicationSettingsPivot.tsx, client-react/src/utils/CommonConstants.ts
* service linker refactoring
* service linker func
* address PR Comments
Co-authored-by: Krrish Mittal <takyyon@SYAMSCFELTP.redmond.corp.microsoft.com>
=> [Cherry-pick] *Update* service linker feature added (and related refactoring) (#5771)

client-react/src/pages/app/deployment-center/code/DeploymentCenterCommitLogs.tsx, server/Resources/Resources.resx
=> add redeploy for external git

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodePivot.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerPivot.tsx
=> [Deployment Center V2] Swap settings and logs tabs

client/src/app/site/deployment-center/deployment-center.component.html, client/src/app/site/deployment-center/deployment-center.component.ts
=> [Deployment Center] Removing Deprecation message for VSTS

client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx, client-react/src/pages/app/functions/function/function-editor/FunctionEditorDataLoader.tsx, client-react/src/utils/CommonConstants.ts
=> Enable Function-Editing for python linux consumption

client-react/src/pages/app/app-settings/AppSettings.tsx, client-react/src/pages/app/app-settings/AppSettings.types.ts, client-react/src/pages/app/app-settings/AppSettings.utils.ts, client-react/src/pages/app/app-settings/ApplicationSettings/ApplicationSettings.tsx, client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStrings.tsx, client-react/src/pages/app/app-settings/SettingSourceColumn.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> [Service Linker] Add delete capability and update name

client-react/src/ApiHelpers/RuntimeStackService.ts, client-react/src/pages/app/app-settings/AppSettingsDataLoader.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeBuildRuntimeAndVersion.tsx
=> [Stacks][Fusion] Update stack calls to ARM endpoint

client-react/src/ApiHelpers/RuntimeStackService.ts
=> [Stacks][Fusion] Update to parameter 'os' to 'stackOsType'

client-react/src/components/MarkdownComponents/MarkdownComponents.tsx, client-react/src/pages/app/functions/new-create-preview/FunctionCreateDataLoader.tsx, client-react/src/pages/app/functions/new-create-preview/local-create/LocalCreateInstructions.tsx
Fixes AB#9492501
Custom setting
Non-Custom
=> StackInstructions component added for Markdown

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeBuildConfiguredView.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeBuildRuntimeAndVersion.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceAndBuild.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.ts, client-react/src/utils/scenario-checker/kube-app.environment.ts
=> Update DC to load the GitHub Action based setup page including stacks for K8se apps.

client-react/src/pages/app/deployment-center/DeploymentCenter.styles.ts, client-react/src/pages/app/deployment-center/DeploymentCenterFtps.tsx, server/Resources/Resources.resx
=> [Deployment Center V2][Sad Mail] Adding Learn more link for application scope credentials

client-react/src/pages/app/deployment-center/utility/GitHubActionUtility.ts, server/src/workflows/2020-12-01/web-app-configs/aspnet-windows.config.yml
Fixes to the new workflow formats
=> Workflow fixes

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubConfiguredView.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.ts
=> Clean up the code to identify if github actions is set. We are able to set scmType by patch which helps.

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeLogs.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterGitHubActionsCodeLogs.tsx
Removing JSON Fixes AB#9540410
Kudu:
=> [Deployment Center V2] remove json from commit message column.

client-react/src/pages/app/deployment-center/DeploymentCenterConstants.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client-react/src/pages/app/deployment-center/utility/GitHubActionUtility.ts
=> Add app settings for python stacks if github action is selected

client-react/src/pages/app/app-settings/GeneralSettings/SlotAutoSwap.tsx, client-react/src/utils/CommonConstants.ts, client-react/src/utils/arm-utils.ts, client-react/src/utils/scenario-checker/linux-site.environment.ts
- Update isKubeApp() to check for both 'kubeapp' and 'kubernetes'.
- Treat all kube apps as Linux apps.
=> updating handling for kube app kind in React

client-react/src/pages/app/app-settings/AppSettings.styles.ts, client-react/src/pages/app/app-settings/AppSettings.types.ts, client-react/src/pages/app/app-settings/AppSettingsFormData.ts, client-react/src/pages/app/app-settings/SettingSourceColumn.tsx, client-react/src/utils/constants/IconConstants.ts
=> [KeyVault References] Add initialized state

client-react/src/pages/app/app-settings/AppSettings.tsx, client-react/src/pages/app/app-settings/AppSettings.utils.ts
=> [Service Linker] Delete operation updated

client-react/src/components/InformationLabel/InformationLabel.styles.ts, client-react/src/components/InformationLabel/InformationLabel.tsx, client-react/src/pages/app/app-settings/AppSettings.styles.ts, client-react/src/pages/app/app-settings/AppSettings.types.ts, client-react/src/pages/app/app-settings/AppSettingsFormData.ts, client-react/src/pages/app/app-settings/KeyVaultReferenceComponent.tsx, client-react/src/pages/app/app-settings/SettingSourceColumn.tsx, client-react/src/utils/constants/IconConstants.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes AB#9432857
Some of the changes are also cherry-picked directly from  - https://github.com/Azure/azure-functions-ux/pull/5814
=> [HOTFIX] Update keyvault initialized status message

client-react/src/components/InformationLabel/InformationLabel.styles.ts, client-react/src/components/InformationLabel/InformationLabel.tsx, client-react/src/pages/app/app-settings/AppSettingsFormData.ts, client-react/src/pages/app/app-settings/KeyVaultReferenceComponent.tsx, client-react/src/pages/app/app-settings/SettingSourceColumn.tsx, client-react/src/utils/constants/IconConstants.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> [Cherry-pick] Handle KeyVault initialized state explicitly

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrSettings.tsx
=> [Deployment Center V2] When ACR is selected, allow user to type in their image name

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrDataLoader.tsx
=> Update ACR DataLoader to skip credentials request if they exist appsettings.

client/src/app/site/container-settings/container-settings.component.html, client/src/app/site/container-settings/container-settings.component.ts, server/Resources/Resources.resx
=> [DC] Container settings banner update

client/src/app/site/container-settings/container-settings.component.html, client/src/app/site/container-settings/container-settings.component.ts, server/Resources/Resources.resx
=> [DC][Cherry Pick] Container settings banner update

client-react/src/utils/scenario-checker/national-cloud.environment.ts
=> [Deployment Center V2] Disable azure repos in national clouds

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerDockerHubSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerPrivateRegistrySettings.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes AB#9331095
Fixes AB#9340224
=> [Deployment Center V2] GitHub Actions & ACR/DockerHub do not ask for a tag, image is TextBox

client-react/src/pages/app/deployment-center/utility/GitHubActionUtility.ts, server/src/workflows/2020-12-01/container-configs/container-linux.config.yml
=> Fixes to container workflow

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx
=> [Deployment Center Vs] GitHub Actions + Containers should not update linuxfxversion

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210330214103631 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210330214103631 to dev

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerFormBuilder.ts
The tag for ACR does not need a value if it is being deployed with GitHub Actions.
=> [DC] Tag validation

client-react/src/pages/app/deployment-center/utility/GitHubActionUtility.ts, client/src/app/site/deployment-center/deployment-center-setup/wizard-logic/github.service.ts, server/src/workflows/2020-12-01/function-app-configs/python-linux.config.yml, server/src/workflows/2020-12-01/web-app-configs/python-linux.config.yml
Remove App Service Build action, use separate build and deploy jobs, and GitHub "environment" property
=> Update deployment workflows for Python

server/src/stacks/stacks.controller.ts, server/src/stacks/validations.ts, server/src/stacks/versions.ts
Fixes [AB#9649630](https://msazure.visualstudio.com/Antares/_workitems/edit/9649630)
=> Updating stacks APIs to handle API version 2020-12-01

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210401200837735 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210401200837735 to dev

server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210403132250783 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210403132250783 to dev

server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210403132308847 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210403132308847 to dev

server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210403132332285 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210403132332285 to dev

server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210403132407833 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210403132407833 to dev

server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210403132509225 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210403132509225 to dev

server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210403132701472 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210403132701472 to dev

server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210405131617727 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210405131617727 to dev

server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210405131636244 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210405131636244 to dev

server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210405131659820 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210405131659820 to dev

server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210405131738847 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210405131738847 to dev

server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210405131838927 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210405131838927 to dev

server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210405132026710 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210405132026710 to dev

server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210406131306745 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210406131306745 to dev

server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210406131326988 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210406131326988 to dev

server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210406131353447 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210406131353447 to dev

server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210406131431686 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210406131431686 to dev

server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210406131533815 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210406131533815 to dev

server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210406131720817 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210406131720817 to dev

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrDataLoader.tsx
=> Deployment Center ACR: Fix the casing for the key in dropdown so the default are auto selected.

server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210409132136919 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210409132136919 to dev

server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210409132155826 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210409132155826 to dev

server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210409132220987 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210409132220987 to dev

server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210409132257929 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210409132257929 to dev

server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210409132358864 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210409132358864 to dev

server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210409132549932 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210409132549932 to dev

client-react/src/pages/app/app-settings/SettingSourceColumn.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> AppSetting source column update 

client/src/app/shared/services/scenario/azure.environment.ts, client/src/app/site/slots/deployment-slots/deployment-slots.component.ts
Fixes [AB#9732044](https://msazure.visualstudio.com/Antares/_workitems/edit/9732044)
=> Enabling deployment slots for kube apps

client-react/src/pages/app/app-settings/AppSettings.tsx
=> Hide keyvault error for kube apps

client-react/src/pages/app/app-settings/AppSettings.styles.ts, client-react/src/pages/app/app-settings/AppSettingsForm.tsx, client-react/src/utils/scenario-checker/kube-app.environment.ts
=> Hide PathMappings for KubeApp

client-react/src/pages/app/SiteRouter.tsx, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/DeploymentCenterDataLoader.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerDataLoader.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerPivot.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> [DC] Container settings banner

client-react/src/pages/app/SiteRouter.tsx, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/DeploymentCenterDataLoader.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerDataLoader.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerPivot.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> [DC][CP] Container settings banner (#5912)

client-react/src/ApiHelpers/static-site/StaticSiteService.ts, client-react/src/pages/static-app/skupicker/StaticSiteSkuPicker.styles.ts, client-react/src/pages/static-app/skupicker/StaticSiteSkuPicker.tsx, client-react/src/utils/CommonConstants.ts
=> [SWA] Sku picker Fit and Finish updates + patch call for updating sku

client-react/src/ApiHelpers/static-site/EnvironmentService.ts
=> [SWA][Configuration] Update API endpoints

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerPivot.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> [DC] Adding GitHub Actions logs to Deployment Center for containers

client-react/src/ApiHelpers/RuntimeStackService.ts, client-react/src/utils/url.ts
Fixes AB#[9784927](https://msazure.visualstudio.com/Antares/_workitems/edit/9784927)
=> Adding useCanaryFusionServer query string parameter when calling stacks APIs

server/src/stacks/2020-06-01/stacks/web-app-stacks/AspDotnet.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts, server/src/tests/Stacks/2020-06-01/web-app/validations.ts, server/src/tests/Stacks/2020-10-01/web-app/validations.ts
AB#[9702734](https://msazure.visualstudio.com/Antares/_workitems/edit/9702734)
=> Adding .NET 6 as hidden

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210424130846642 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210424130846642 to dev

client-react/src/pages/app/app-settings/GeneralSettings/Platform.tsx, client-react/src/utils/CommonConstants.ts, client-react/src/utils/scenario-checker/kube-app.environment.ts, client-react/src/utils/scenario-checker/scenario-ids.ts
=> [ARC] Hide settings not supported 

client-react/src/pages/static-app/configuration/Configuration.tsx, client-react/src/pages/static-app/configuration/ConfigurationDataLoader.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> [SWA] Enable users to create app-settings without a function

client-react/src/pages/app/app-settings/GeneralSettings/ClientCert/ClientCert.tsx, client-react/src/utils/scenario-checker/kube-app.environment.ts, client-react/src/utils/scenario-checker/scenario-ids.ts
=> [ARC] Hide clients cert for Kube scenarios

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubConfiguredView.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.ts, client-react/src/pages/app/deployment-center/utility/GitHubActionUtility.ts
=> Reintroduce the usage of scmType for detecting GitHub Action for k8se apps.

client-react/src/ApiHelpers/RuntimeStackService.ts
Fixes AB#[9822573](https://msazure.visualstudio.com/Antares/_workitems/edit/9822573)
=> update stacks calls to use Fusion API for USNat and USSec

server/src/stacks/2020-06-01/stacks/web-app-stacks/Java.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Java.ts
Fixes AB#[9368837](https://msazure.visualstudio.com/Antares/_workitems/edit/9368837)
Fixes AB#[9512102](https://msazure.visualstudio.com/Antares/_workitems/edit/9512102)
=> enabling app insights for Java web apps on Linux and Windows

client-react/src/pages/static-app/skupicker/StaticSiteSkuPicker.tsx, client-react/src/utils/FwLinks.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> [SWA] Removing sku picker pricing

client-react/src/pages/app/functions/new-create-preview/FunctionCreateDataLoader.tsx
=> [ARC] "Add function" hidden for kube scenarios

client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx, client-react/src/pages/app/functions/function/monitor/tabs/logs/FunctionLogsDataLoader.tsx
Fixes AB#9814906
Fixes AB#9820881
=> [ARC][Logging] Enable only AI logging for arc scenarios

client-react/src/pages/app/app-settings/GeneralSettings/Platform.tsx, client-react/src/pages/app/app-settings/Sections/GeneralSettings.tsx, client-react/src/utils/scenario-checker/kube-app.environment.ts, client-react/src/utils/scenario-checker/scenario-ids.ts
=> [ARC][Configuration] Hide platform settings 

client-react/src/models/portal-models.ts, client-react/src/pages/app/SiteRouter.tsx, client-react/src/utils/SiteHelper.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> Add Readonly state for ARC apps

client/src/app/site/slots/swap-slots/swap-slots.component.html, client/src/app/site/slots/swap-slots/swap-slots.component.ts
=> [ARC][Slots] Hide diff UX until the API is working for ARC

client-react/src/pages/static-app/skupicker/StaticSiteSkuPicker.tsx
=> [SWA] Remove private link info from sku picker

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeDataLoader.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodePivot.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerPivot.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubDisconnect.tsx, client-react/src/pages/app/deployment-center/utility/GitHubActionUtility.ts, client-react/src/pages/static-app/skupicker/StaticSiteSkuPicker.tsx, client-react/src/utils/scenario-checker/kube-app.environment.ts
Fixes AB#9442123
Containers:
Code Apps:
=> [DC][ARC] Remove non GitHub Actions logs, Update GHA container deployment and GitHub Actions disconnect

server/LocProject.json
=> [Localization] Lang supported added

client-react/src/pages/static-app/skupicker/StaticSiteSkuPicker.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> [SWA] Sku picker updates

client-react/src/pages/static-app/skupicker/StaticSiteSkuPicker.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> [SWA][CP] Sku picker updates

client-react/src/pages/app/deployment-center/publish-profile/DeploymentCenterPublishProfileCommandBar.tsx
=> [DC]  Download publish profile should be ".publishsettings" instead of ".xml"

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx
=> [DC][ARC] GHA Sync updated to get repourl and branch data from configMetadata

client-react/src/pages/static-app/skupicker/StaticSiteSkuPicker.tsx, client-react/src/pages/static-app/skupicker/StaticSiteSkuPicker.types.ts, client-react/src/pages/static-app/skupicker/StaticSiteSkuPickerDataLoader.tsx
=> [SWA][Sku Picker] Type change to from string to StaticSiteSku

client-react/src/utils/scenario-checker/workflow-app.environment.ts
Fixes AB#9964173
This will be part of the Hotfix train for //BUILD.
**Screenshots:**
Before change:
Workflow standard sku
Elastic premium sku
After change:
Workflow standard sku
Elastic Premium sku
=> AB#9964173 [LAv2 apps on new Workflow Standard sku] Hide Always ON in general settings similar to Elastic Premium

client-react/src/utils/scenario-checker/function-app.environment.ts, client-react/src/utils/scenario-checker/workflow-app.environment.ts
=> Hide ARR Affinity for all function-apps

client-react/src/utils/scenario-checker/workflow-app.environment.ts
Co-authored-by: Shibani Medhekar <shibanimedhekar@Shibanis-MacBook-Pro.local>
=> AB#9964173 [LAv2 apps on new Workflow Standard sku] Hide Always ON in general settings similar to Elastic Premium (#5963)

client/src/app/edit-mode-warning/edit-mode-warning.component.html, client/src/app/edit-mode-warning/edit-mode-warning.component.ts, server/Resources/Resources.resx
=> Update readonly message on angular to match new experience and remove redundant link

client-react/src/pages/app/SiteRouter.tsx, client-react/src/utils/CommonConstants.ts
=> Enable portal editing for Linux Premium/dedicated for Python and Node apps for testing

client/src/app/api/api-details/api-details.component.ts
=> [Proxies] Step I - Open App Files on advanced editor click

client/src/app/api/api-details/api-details.component.ts, client/src/app/shared/models/portal.ts, client/src/app/shared/services/portal.service.ts
=> [Proxies] Switch menu item on advanced editor click

client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEditAdvanced.tsx, client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEditBasic.tsx, client-react/src/utils/arm-utils.ts, client-react/src/utils/scenario-checker/container.environment.ts, client-react/src/utils/scenario-checker/windows-code.environment.ts
[Task: 9538030](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s164?workitem=9538030)
1. Enabled BYOS on Windows Code
2. Disabled Azure Blob option for storage mounting on Windows Code/Container
3. Removed the banner from AzureStorageMountAddEdit blade for Windows Code/Container
4. Corrected the storage account label name from "storage account" to "storage accounts" on AzureStorageMountAddEditAdvanced blade to be consistent with the experience on AzureStorageMountAddEditBasic blade
5. At AzureStorageMountAddEditBasic blade, added null check on fetched blobs and files
=> [BYOS] Enable BYOS on Windows Code Apps

client-react/src/pages/app/app-settings/AppSettingsForm.tsx, client-react/src/pages/app/app-settings/Sections/PathMappingsPivot.tsx, client-react/src/utils/scenario-checker/linux-site.environment.ts, client-react/src/utils/scenario-checker/scenario-ids.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> [App Settings][BYOS] Remove the preview tag for BYOS on Linux

client/src/app/site/slots/add-slot/cloneSrcValidator.ts
Fixes [AB#10030991](https://msazure.visualstudio.com/Antares/_workitems/edit/10030991)
=> Include azureStorageAccounts when cloning site config for new slot

client-react/src/pages/app/deployment-center/utility/GitHubActionUtility.ts, server/src/workflows/2020-12-01/container-configs/container-linux.config.yml
=> [DC][GHA] Add publishserver to the tag

client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEditAdvanced.tsx, client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEditBasic.tsx, client-react/src/utils/CommonConstants.ts, client-react/src/utils/arm-utils.ts, client-react/src/utils/scenario-checker/container.environment.ts, client-react/src/utils/scenario-checker/linux-site.environment.ts, client-react/src/utils/scenario-checker/windows-code.environment.ts
Add a feature flag to hide the storage mount feature and another feature flag to hide the removing preview tag
=> Add feature flags for BYOS

client/src/app/site/spec-picker/price-spec-manager/dV3series-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/plan-price-spec-manager.ts
Fixes AB#10070816
Fixing the null ref that was caused due to my change yesterday.
=> AB#10070816 [ASP][create][canary]: Apply button is disable while changing Sku size

client-react/src/utils/scenario-checker/dynamic-linux.environment.ts, client-react/src/utils/scenario-checker/function-app.environment.ts, client-react/src/utils/scenario-checker/linux-site.environment.ts, client-react/src/utils/scenario-checker/national-cloud.environment.ts, client/src/app/shared/services/scenario/linux-site.environment.ts
Fixes AB#9799149
This excludes Linux Consumption Function Apps.
=> [DC] Enable External Git for Linux Web/Function Apps, excluding Dynamic Linux Function Apps

client/src/app/site/spec-picker/spec-list/spec-list.component.html, client/src/app/site/spec-picker/spec-picker.component.scss
Fixes AB#9578250
Dark mode:
Light mode:
=> AB#9578250 [Visual Requirement - App Services - Pricing Tier]: Luminosity ratio is less than as required (4.5:1) for available link.

client-react/src/components/form-controls/TextFieldNoFormik.tsx, client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEdit.tsx, client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEditBasic.tsx, client-react/src/utils/CommonConstants.ts, client-react/src/utils/constants/ValidationRegex.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes [AB#9589869](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s165?workitem=9589869)
=> AB#9589869 [App Settings][BYOS] Add mount path validations

client/src/image/app-service-environment.svg, client/src/image/app-service-plan.svg
Fixes AB#9592871
Basically what the issue is that we should not have "id" property for svg since they are shared and can be used in multiple places on the same page. Also the id property does not affect the image rendering itself.
You can see there is no visual change:
**Before**:
**After**:
=> AB#9592871 [Programmatic Access - App Services - Production]: Ensures every id attribute value is unique (:root)

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSettingsReadOnlyView.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> [DC] Update GitHub Actions Image and tag

client-react/src/pages/app/app-settings/AppSettingsCommandBar.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> [Configuration] Add feedback button

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerPivot.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.ts
=> [DC] Updating Container Command Bar check for dirty settings

server/src/stacks/2020-06-01/stacks/web-app-stacks/AspDotnet.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts
Fixes AB#[9947382](https://msazure.visualstudio.com/Antares/_workitems/edit/9947382) AB#[9702741](https://msazure.visualstudio.com/Antares/_workitems/edit/9702741)
=> Unhiding .NET 6 for web apps and enabling AI for .NET 6 for Linux web apps

client-react/src/pages/app/deployment-center/DeploymentCenterCommandBar.tsx
=> [DC] Disable save and discard when there is no write permission

server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210609213122645 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210609213122645 to dev

server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210609213140457 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210609213140457 to dev

server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210609213202719 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210609213202719 to dev

server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210609213236764 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210609213236764 to dev

server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210609213335148 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210609213335148 to dev

server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210609213522195 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210609213522195 to dev

server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210609214028039 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210609214028039 to dev

server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210609214251417 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210609214251417 to dev

server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210609214325894 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210609214325894 to dev

server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210609214408945 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210609214408945 to dev

server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210609214509261 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210609214509261 to dev

server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210609214701508 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210609214701508 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210610134748367 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210610134748367 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210610134814078 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210610134814078 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210610134841377 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210610134841377 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210610134920884 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210610134920884 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210610135024051 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210610135024051 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210610135216476 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210610135216476 to dev

server/src/stacks/2020-06-01/models/WebAppStackModel.ts, server/src/stacks/2020-06-01/service/StackService.ts, server/src/stacks/2020-06-01/stacks/web-app-stacks/StaticSite.ts, server/src/stacks/2020-10-01/models/WebAppStackModel.ts, server/src/stacks/2020-10-01/service/StackService.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/StaticSite.ts, server/src/tests/Stacks/2020-06-01/web-app/tests.ts, server/src/tests/Stacks/2020-06-01/web-app/validations.ts, server/src/tests/Stacks/2020-10-01/web-app/tests.ts, server/src/tests/Stacks/2020-10-01/web-app/validations.ts
Fixes [AB#9915300](https://msazure.visualstudio.com/Antares/_workitems/edit/9915300)
=> Adding staticsite stack as hidden

server/src/stacks/2020-05-01/stacks/web-app-stacks/config/linux/Php.ts, server/src/stacks/2020-05-01/stacks/web-app-stacks/create/Php.ts, server/src/stacks/2020-06-01/stacks/web-app-stacks/Php.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Php.ts, server/src/tests/Stacks/2020-05-01/web-app/validations.ts, server/src/tests/Stacks/2020-06-01/web-app/validations.ts, server/src/tests/Stacks/2020-10-01/web-app/validations.ts
Fixes [AB#9918229](https://msazure.visualstudio.com/Antares/_workitems/edit/9918229)
=> Adding PHP 8.0 as hidden for Linux web apps

server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210611134725397 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210611134725397 to dev

server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210611134746806 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210611134746806 to dev

server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210611134815231 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210611134815231 to dev

server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210611134854215 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210611134854215 to dev

server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210611134956861 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210611134956861 to dev

server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210611135147593 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210611135147593 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210613134741738 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210613134741738 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210613134808372 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210613134808372 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210613134846653 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210613134846653 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210613134949470 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210613134949470 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210613135139139 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210613135139139 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210614134648270 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210614134648270 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210614134709754 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210614134709754 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210614134735676 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210614134735676 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210614134814239 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210614134814239 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210614134917286 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210614134917286 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210614135107678 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210614135107678 to dev

client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEdit.tsx, client-react/src/utils/CommonConstants.ts, client-react/src/utils/scenario-checker/linux-site.environment.ts, client-react/src/utils/scenario-checker/national-cloud.environment.ts
Fixes #10148268
BYOS GA for Linux:
1. Remove preview tag of "Mount Storage" header
2. Enable mount path validation, including showing info bubble
=> AB #10148268 [App Settings][BYOS] Enable BYOS GA Feature for Linux

client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEdit.tsx, client-react/src/utils/CommonConstants.ts, client-react/src/utils/scenario-checker/linux-site.environment.ts, client-react/src/utils/scenario-checker/national-cloud.environment.ts
Merge this commit [https://github.com/Azure/azure-functions-ux/pull/6047](https://github.com/Azure/azure-functions-ux/pull/6047) to release-s165 for a hotfix.
=> Hotfix - Merge "[App Settings][BYOS] Enable BYOS GA Feature for Linux" to Release-s165

client-react/src/components/form-controls/ComboBox.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerFormBuilder.ts, server/Resources/Resources.resx
=> [DC] Add ComboBox Functionality for ACR/MSI, Get Image/Tag from FxVersion for ACR/MSI

client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx
=> [Function Editor] Log to ibiza on save-click

client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/DotNetStack.tsx, client-react/src/utils/stacks-utils.tsx
Fixes AB#10206693
Fixes AB#10208558
=> [Stack] Handle  >= .NET5 stacks for windows

client-react/src/pages/static-app/skupicker/StaticSiteSkuPicker.tsx, server/Resources/Resources.resx
=> [SWA] Currency update

client-react/src/pages/static-app/skupicker/StaticSiteSkuPicker.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> [SWA] Add Private Link to sku picker

server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210624134650422 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210624134650422 to dev

server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210624134708812 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210624134708812 to dev

server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210624134732043 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210624134732043 to dev

server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210624134808023 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210624134808023 to dev

server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210624134907856 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210624134907856 to dev

server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210624135056019 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210624135056019 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210625134736101 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210625134736101 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210625134758653 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210625134758653 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210625134827113 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210625134827113 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210625134906932 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210625134906932 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210625135010098 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210625135010098 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210625135203166 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210625135203166 to dev

server/src/deployment-center/github/github.controller.ts
=> [DC] Update token format

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210626134730925 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210626134730925 to dev

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx
Fixes [AB#10236156](https://msazure.visualstudio.com/Antares/_workitems/edit/10236156)
=> Remove ipSecurityRestrictions and scmIpSecurityRestrictions from payload when saving container settings

client-react/src/pages/app/functions/new-create-preview/FunctionCreateDataLoader.tsx
Fixes [AB#10184747](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/10184747)
=> [function-create] Update Add button to say Create

server/src/stacks/2020-06-01/stacks/web-app-stacks/Php.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Php.ts
Fixes [AB#10205940](https://msazure.visualstudio.com/Antares/_workitems/edit/10205940)
=> Fixing display text for PHP 8.0

client-react/src/pages/app/functions/new-create-preview/FunctionCreate.styles.ts, client/src/app/api/api-new/api-new.component.scss
Fixes [AB#10184708](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/10184708)
=> [Function Create][Proxy Add] Update panel paddings

client-react/src/utils/CommonConstants.ts, client-react/src/utils/FunctionAppService.ts
Fixes [AB#10304948](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/10304948)
=> Add Oryx build app-setting

server/src/stacks/2020-06-01/stacks/web-app-stacks/DotnetCore.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts
Fixes [AB#9878770](https://msazure.visualstudio.com/Antares/_workitems/edit/9878770)
=> fixing EOL date for .NET 2.1

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx, client-react/src/pages/app/functions/new-create-preview/FunctionCreateDataLoader.tsx
Fixes [AB#10071146](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/10071146)
=> [DC] Updating telemetry

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeLogs.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterGitHubActionsCodeLogs.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.ts
Fixes [AB#10315109](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/10315109)
=> [DC] Include GitHub commit message in the logs

server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210708134659764 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210708134659764 to dev

server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210708134729936 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210708134729936 to dev

server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210708134806093 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210708134806093 to dev

server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210708134852799 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210708134852799 to dev
