server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210708135005484 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210708135005484 to dev

server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210708135204881 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210708135204881 to dev

client-react/src/pages/app/app-settings/AppSettings.service.ts, client-react/src/pages/app/app-settings/AppSettings.types.ts, client-react/src/pages/app/app-settings/AppSettings.utils.ts, client-react/src/pages/app/app-settings/AppSettingsFormData.ts, client-react/src/pages/app/app-settings/ApplicationSettings/AppSettingAddEdit.tsx, client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStringsAddEdit.tsx
Fixes [AB#10123351](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/10123351)
=> [Configuration] Update keyvault references API to handle backend error

server/Resources/Resources.resx
Fixes [AB#9280918](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/9280918)
=> Update connection string name errorMessage for Linux apps

server/src/stacks/2020-06-01/stacks/web-app-stacks/Java.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Java.ts
Update stacks JSON to disable App Insights for Java 7 on creates
=> Disable AI for Java 7

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210715134827438 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210715134827438 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210715134855246 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210715134855246 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210715134934407 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210715134934407 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210715135037568 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210715135037568 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210715135228351 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210715135228351 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210715134804666 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210715134804666 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210717134801541 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210717134801541 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210717134820958 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210717134820958 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210717134846083 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210717134846083 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210717134921787 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210717134921787 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210717135022075 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210717135022075 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210717135210401 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210717135210401 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210718134734315 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210718134734315 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210718134753487 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210718134753487 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210718134818570 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210718134818570 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210718134854875 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210718134854875 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210718134956281 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210718134956281 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210718135145919 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210718135145919 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210719134703736 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210719134703736 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210719134725004 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210719134725004 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210719134749952 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210719134749952 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210719134826837 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210719134826837 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210719134927749 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210719134927749 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210719135116810 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210719135116810 to dev

client/src/app/shared/models/arm/site.ts, client/src/app/site/slots/add-slot/add-slot.component.ts
Fixes [AB#10220473](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/10220473)
=> Pass kind prop while creating-slot

client/src/app/controls/info-box/info-box.component.html, client/src/app/controls/info-box/info-box.component.scss, client/src/app/controls/info-box/info-box.component.ts, client/src/app/shared/models/portal-resources.ts, client/src/app/site/spec-picker/price-spec-manager/dV2series-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/dV3series-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/free-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/plan-price-spec-manager.ts, client/src/app/site/spec-picker/price-spec-manager/price-spec.ts, client/src/app/site/spec-picker/spec-picker.component.html, server/Resources/Resources.resx
Fixes [AB#10334282](https://msazure.visualstudio.com/Antares/_workitems/edit/10334282)
=> Updating spec picker to handle exception when georegions API calls fail.

client-react/src/models/portal-models.ts, client-react/src/pages/app/SiteRouter.tsx, client-react/src/utils/CommonConstants.ts, client-react/src/utils/FunctionAppService.ts, client-react/src/utils/SiteHelper.ts, client-react/src/utils/arm-utils.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes [AB#10410261](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/10410261)
=> Add read-only check for Consumption and premium function-apps

client-react/src/ApiHelpers/ArgHelper.ts, client-react/src/ApiHelpers/TagsService.ts, client-react/src/components/form-controls/ComboBox.tsx, client-react/src/models/portal-models.ts, client-react/src/pages/app/dependency/Dependency.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrDataLoader.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerFormBuilder.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSettings.tsx, client-react/src/portal-communicator.ts, client-react/src/utils/CommonConstants.ts, client-react/src/utils/dependency/Dependency.ts
Fixes [AB#8405188](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/8405188)
Fixes [AB#10201065](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/10201065)
=> [DC] Add Hidden Tags + Enable Cross Subscription ACR

server/src/stacks/2020-05-01/stacks/web-app-stacks/config/linux/Php.ts, server/src/stacks/2020-05-01/stacks/web-app-stacks/create/Php.ts, server/src/stacks/2020-06-01/stacks/web-app-stacks/Php.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Php.ts
Fixes [AB#10393060](https://msazure.visualstudio.com/Antares/_workitems/edit/10393060)
=> Unhide PHP 8.0

server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210723131229040 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210723131229040 to dev

client-react/src/models/hostingEnvironment/hosting-environment.ts, client-react/src/pages/app/deployment-center/DeploymentCenterContext.ts, client-react/src/pages/app/deployment-center/DeploymentCenterDataLoader.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeBuildCallout.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceAndBuild.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSource.tsx
=> [DC][GHA] Disable GitHub actions for ILB ASE

client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEdit.tsx, client-react/src/utils/scenario-checker/national-cloud.environment.ts
Fixes [AB#10437025](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s169?workitem=10437025)
Linux BYOS GA on national clouds:
=> AB#10437025 [BYOS] Enable BYOS linux on national clouds

client/src/app/site/spec-picker/price-spec-manager/isolatedv2-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/plan-price-spec-manager.ts, client/src/app/site/spec-picker/price-spec-manager/premiumv3-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/price-spec.ts
Fixes [AB#8725482](https://msazure.visualstudio.com/Antares/_workitems/edit/8725482)
**Existing App - JBOSS**
**Existing App - non-JBOSS**
**New App - JBOSS**
**New App - non-JBOSS**
=> [HOTFIX] Show combined cost of SKU and JBoss support in spec picker

client-react/src/pages/app/SiteRouter.tsx, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/DeploymentCenterDataLoader.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerDataLoader.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerPivot.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Removes the banner warning of deprecation of Container Settings
=> [DC] Remove container settings deprecation banner

client/src/app/site/spec-picker/price-spec-manager/isolatedv2-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/plan-price-spec-manager.ts, client/src/app/site/spec-picker/price-spec-manager/premiumv3-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/price-spec.ts
Cherry-pick from #6188
Fixes [AB#8725482](https://msazure.visualstudio.com/Antares/_workitems/edit/8725482)
**Existing App - JBOSS**
**Existing App - non-JBOSS**
**New App - JBOSS**
**New App - non-JBOSS**
=> Show combined cost of SKU and JBoss support in spec picker

client-react/src/pages/static-app/skupicker/StaticSiteSkuPicker.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes [AB#10526073](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/10526073)
=> [SWA] Fixing currency and normalizing cost

client-react/src/ApiHelpers/SiteService.ts, client-react/src/pages/app/app-settings/AppSettingsDataLoader.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx, client/src/app/shared/services/site.service.ts, client/src/app/site/container-settings/container-settings-manager.ts
Fixes [AB#10273125](https://msazure.visualstudio.com/Antares/_workitems/edit/10273125)
=> Exclude "ignored" properties by default when updating site config

client-react/src/pages/app/SiteRouter.tsx
Fixes [AB#10410261](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/10410261)
=> Update condition for Azure file check

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210806131037395 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210806131037395 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210813131045377 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210813131045377 to dev

client-react/src/pages/app/app-settings/AppSettings.service.ts, client-react/src/pages/app/app-settings/AppSettingsDataLoader.tsx
Cherry pick https://github.com/Azure/azure-functions-ux/pull/6209 to release-s169
=> Cherry pick - add storage mount to updateSite

server/src/stacks/2020-06-01/stacks/web-app-stacks/DotnetCore.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts
Fixes [AB#10469484](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/10469484)
=> Correct the date for .NET2.1 EOL 

server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts
Fixes [AB#10469484](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/10469484)
=> [Stack] Mark .NetCore 2.1 as deprecated

client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/DotNetStack.tsx, client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/PhpStack.tsx, client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/PythonStack.tsx, client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/WindowsStacks.tsx
Fixes [AB#10626909](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/10626909)
=> Update values on discard

server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts
Fixes [AB#10519952](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/10519952)
=> Unhide .NET6 stack

client-react/src/ApiHelpers/ACRService.ts, client-react/src/ApiHelpers/GitHubService.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.data.ts, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubDataLoader.tsx, server/src/deployment-center/bitbuckets/bitbuckets.controller.ts, server/src/deployment-center/dropbox/dropbox.controller.ts, server/src/deployment-center/onedrive/onedrive.controller.ts
Fixes [AB#10614743](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/10614743)
=> [DC] Removing passthrough API calls

client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client-react/src/utils/CommonConstants.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
FixesAB#[9884967](https://msazure.visualstudio.com/Antares/_workitems/edit/9884967)
Before
After
=> [DC] Add missing workflow_dispatch trigger detailed explanation

client-react/src/pages/app/deployment-center/DeploymentCenter.data.ts, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubDataLoader.tsx
=> [DC] Updating call to get repos in an organization

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210903131127714 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210903131127714 to dev

server/src/stacks/2020-06-01/stacks/web-app-stacks/AspDotnet.ts, server/src/stacks/2020-06-01/stacks/web-app-stacks/DotnetCore.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts
=> Enable AI for .NET 6, 5, 3.1 linux

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210917131146782 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210917131146782 to dev

client-react/src/utils/CommonConstants.ts, client/src/app/shared/models/constants.ts, client/src/app/shared/models/server-farm.ts, client/src/app/site/spec-picker/price-spec-manager/isolatedv2-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/plan-price-spec-manager.ts
I added a Feature flag to display Isolated v2 specs for Xenon apps.
**With Feature Flag:**
**Without Feature Flag:**
=> 9493126 [ASE][ASEV3][WebApp & ASP Create] Allow Xenon ASPs to be created in ASEV3s

client/src/app/shared/models/arm/arm-obj.ts, client/src/app/shared/models/arm/site.ts, client/src/app/site/slots/add-slot/add-slot.component.ts
Fixes [AB#10561737](https://msazure.visualstudio.com/Antares/_workitems/edit/10561737)
=> Copy extended location from main site when creating a slot

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210924130517755 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20210924130517755 to dev

server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts
Fixes [AB#10976193](https://msazure.visualstudio.com/Antares/_workitems/edit/10976193)
=> [HOTFIX] Unhiding .NET 6 for Linux Functions

client-react/src/utils/FunctionAppService.ts
Fixes [AB#9718593](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/9718593)
Re-replacing this since backend is not ready yet.
=> Replace flighting check with feature flag

server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20211001130505386 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20211001130505386 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20211029131159120 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20211029131159120 to dev

client-react/src/utils/FunctionAppService.ts, client-react/src/utils/flighting-util.ts
* enable with flighting
* update flag
=> [DO NOT MERGE UNITL 11/08] Enable portal editing for Linux apps with flighting (#6322)

client-react/src/pages/app/app-settings/GeneralSettings/DebuggingWindows.tsx
Fixes [AB#10876116](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/10876116)
=> Add VS2022 to remote debugging option

client-react/src/utils/FunctionAppService.ts, client-react/src/utils/flighting-util.ts
Reverts Azure/azure-functions-ux#6327
=> Revert "[DO NOT MERGE UNITL 11/08] Enable portal editing for Linux apps with flighting (#6322)"

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerFormBuilder.ts, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.ts
Fixes [AB#11109341](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/11109341)
=> [Deployment Center] Making image/tag case sensitive

client/src/app/shared/models/constants.ts, client/src/app/site/spec-picker/price-spec-manager/isolatedv2-plan-price-spec.ts
Removing Feature flag to let user create new ASEv3 when it is xenon.
**Image:**
**GIF:**
=> [ASE][ASEV3][WebApp & ASP Create] Remove FF to allow Xenon ASPs to be created in ASEV3s

client-react/src/pages/app/app-settings/GeneralSettings/LinuxStacks/LinuxStacks.tsx, client-react/src/pages/app/app-settings/GeneralSettings/stacks/function-app/FunctionAppStackSettings.tsx
Fixes [AB#11939746](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/11939746)
=> Remove startup command for function-app

client-react/src/components/CustomBanner/CustomBanner.tsx
Fixes [AB#8994839](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/8994839)
=> Add Aria label to close button on banner

server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20211105131341694 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20211105131341694 to dev

client-react/src/utils/FunctionAppService.ts, client-react/src/utils/flighting-util.ts
This reverts commit e8152b3e035bd03ef7bdd140877d275c2f024e75.
=> Revert "Enable portal editing for Linux apps with flighting (#6322)"

client-react/src/pages/app/app-settings/AppSettingsForm.tsx, client-react/src/pages/app/functions/function/function-editor/function-test/FunctionTest.tsx, client-react/src/utils/CommonConstants.ts
Fixes [AB#6169530](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/6169530)
=> Handle overflow behavior with new fluent version

client-react/src/pages/app/app-settings/GeneralSettings/DebuggingWindows.tsx
=> [DO NOT MERGE UNTIL 11/08] AB#10876116 Add VS2022 to remote debugging option (#6328)

server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts
Co-authored-by: Shibani Medhekar <shibanimedhekar@alfrankl-main.redmond.corp.microsoft.com>
=> [DO NOT MERGE - For 11/8 Hotfix] AB#12528307 [HOTFIX] - Unblock .NET 6 from Github actions on create (#6342)

client-react/src/pages/app/functions/app-keys/HostKeys.tsx, client-react/src/pages/app/functions/app-keys/SystemKeys.tsx, client-react/src/pages/app/functions/function/function-keys/FunctionKeys.tsx, client-react/src/pages/app/functions/function/invocations/FunctionInvocationDetails.tsx, client-react/src/pages/app/functions/function/invocations/FunctionInvocations.tsx, client-react/src/pages/app/functions/function/monitor/tabs/entities/FunctionEntities.tsx, client-react/src/pages/app/functions/function/monitor/tabs/entities/FunctionEntityDetails.tsx, client-react/src/pages/app/functions/function/monitor/tabs/orchestrations/FunctionOrchestrationDetails.tsx, client-react/src/pages/app/functions/function/monitor/tabs/orchestrations/FunctionOrchestrations.tsx, client-react/src/pages/app/log-stream/LogStreamCommandBar.tsx, client-react/src/pages/static-app/configuration/ConfigurationCommandBar.tsx
Fixes [AB#9308703](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/9308703)
=> AriaLabel added to command-bar items

client-react/src/components/form-controls/TextFieldNoFormik.tsx, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/DeploymentCenterFtps.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterPublishingUser.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerContinuousDeploymentSettings.tsx, client-react/src/theme/CustomOfficeFabric/AzurePortal/TextField.styles.ts, client-react/src/utils/CommonConstants.ts
Fixes [AB#10985610](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/10985610)
=> Use the default Show/Hide button from Fluent UI instead of custom creation

server/src/stacks/2020-10-01/stacks/function-app-stacks/Node.ts
Remove LTS label until LTS version is fully rolled out
=> Functions Stacks - Unhide Node.js 16

client-react/src/ApiHelpers/FunctionsService.ts, client-react/src/components/CustomBanner/CustomBanner.styles.ts, client-react/src/components/CustomBanner/CustomBanner.tsx, client-react/src/models/site/config.ts, client-react/src/pages/app/app-settings/AppSettingsForm.tsx, client-react/src/pages/app/functions/function/function-editor/FunctionEditor.data.ts, client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx, client-react/src/pages/app/functions/function/function-editor/FunctionEditorDataLoader.tsx, client-react/src/pages/app/functions/function/function-editor/function-test/FunctionTest.tsx, client-react/src/utils/CommonConstants.ts, client-react/src/utils/url.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes [AB#10581874](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/10581874)
=> Remove Passthrough APIs and handle accordingly

client-react/src/ApiHelpers/FunctionsService.ts, client-react/src/models/ajax-request-model.ts, client-react/src/models/portal-models.ts, client-react/src/pages/app/functions/function/function-editor/FunctionEditorDataLoader.tsx, client-react/src/portal-communicator.ts, client-react/src/utils/portal-utils.ts
Fixes [AB#10581874](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/10581874)
=> Make http request to run-function via portal

server/src/quickstart/coretoolsDirectPublish-react-localDevExperience.md, server/src/quickstart/cs-CZ/coretoolsDirectPublish-react-localDevExperience_cs.md, server/src/quickstart/de-DE/coretoolsDirectPublish-react-localDevExperience_de.md, server/src/quickstart/es-ES/coretoolsDirectPublish-react-localDevExperience_es.md, server/src/quickstart/fr-FR/coretoolsDirectPublish-react-localDevExperience_fr.md, server/src/quickstart/hu-HU/coretoolsDirectPublish-react-localDevExperience_hu.md, server/src/quickstart/it-IT/coretoolsDirectPublish-react-localDevExperience_it.md, server/src/quickstart/ja-JP/coretoolsDirectPublish-react-localDevExperience_ja.md, server/src/quickstart/ko-KR/coretoolsDirectPublish-react-localDevExperience_ko.md, server/src/quickstart/nl-NL/coretoolsDirectPublish-react-localDevExperience_nl.md, server/src/quickstart/pl-PL/coretoolsDirectPublish-react-localDevExperience_pl.md, server/src/quickstart/pt-BR/coretoolsDirectPublish-react-localDevExperience_pt-BR.md, server/src/quickstart/pt-PT/coretoolsDirectPublish-react-localDevExperience_pt-PT.md, server/src/quickstart/ru-RU/coretoolsDirectPublish-react-localDevExperience_ru.md, server/src/quickstart/sv-SE/coretoolsDirectPublish-react-localDevExperience_sv.md, server/src/quickstart/tr-TR/coretoolsDirectPublish-react-localDevExperience_tr.md, server/src/quickstart/zh-CN/coretoolsDirectPublish-react-localDevExperience_zh-CN.md, server/src/quickstart/zh-TW/coretoolsDirectPublish-react-localDevExperience_zh-TW.md
Fixes [AB#12427410](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/12427410)
=> Update CoreTools instructions to 4

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20211112141206282 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20211112141206282 to dev

client-react/src/ApiHelpers/FunctionsService.ts, client-react/src/components/CustomBanner/CustomBanner.styles.ts, client-react/src/components/form-controls/TextField.tsx, client-react/src/components/form-controls/TextFieldNoFormik.tsx, client-react/src/models/ajax-request-model.ts, client-react/src/models/portal-models.ts, client-react/src/pages/app/functions/function/function-editor/FunctionEditorDataLoader.tsx, client-react/src/portal-communicator.ts, client-react/src/utils/portal-utils.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx, server/src/quickstart/coretoolsDirectPublish-react-localDevExperience.md, server/src/quickstart/cs-CZ/coretoolsDirectPublish-react-localDevExperience_cs.md, server/src/quickstart/de-DE/coretoolsDirectPublish-react-localDevExperience_de.md, server/src/quickstart/es-ES/coretoolsDirectPublish-react-localDevExperience_es.md, server/src/quickstart/fr-FR/coretoolsDirectPublish-react-localDevExperience_fr.md, server/src/quickstart/hu-HU/coretoolsDirectPublish-react-localDevExperience_hu.md, server/src/quickstart/it-IT/coretoolsDirectPublish-react-localDevExperience_it.md, server/src/quickstart/ja-JP/coretoolsDirectPublish-react-localDevExperience_ja.md, server/src/quickstart/ko-KR/coretoolsDirectPublish-react-localDevExperience_ko.md, server/src/quickstart/nl-NL/coretoolsDirectPublish-react-localDevExperience_nl.md, server/src/quickstart/pl-PL/coretoolsDirectPublish-react-localDevExperience_pl.md, server/src/quickstart/pt-BR/coretoolsDirectPublish-react-localDevExperience_pt-BR.md, server/src/quickstart/pt-PT/coretoolsDirectPublish-react-localDevExperience_pt-PT.md, server/src/quickstart/ru-RU/coretoolsDirectPublish-react-localDevExperience_ru.md, server/src/quickstart/sv-SE/coretoolsDirectPublish-react-localDevExperience_sv.md, server/src/quickstart/tr-TR/coretoolsDirectPublish-react-localDevExperience_tr.md, server/src/quickstart/zh-CN/coretoolsDirectPublish-react-localDevExperience_zh-CN.md, server/src/quickstart/zh-TW/coretoolsDirectPublish-react-localDevExperience_zh-TW.md
https://github.com/Azure/azure-functions-ux/pull/6354
https://github.com/Azure/azure-functions-ux/pull/6353
https://github.com/Azure/azure-functions-ux/pull/6352
=> [Cherry-Pick] Fluent UI fixes + Other changes

client-react/src/pages/app/app-settings/GeneralSettings/stacks/function-app/FunctionAppStackSettings.tsx, client-react/src/utils/FunctionsRuntimeVersionHelper.ts
Fixes [AB#12547732](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/12547732)
=> Handle stack version dropdown for v4

tools/pipelines/angular-pr-test.yml, tools/pipelines/production-build.yml, tools/pipelines/server-pr-test.yml
Fixes [AB#12582421](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/12582421)
Pipelines are deprecating older versions.
=> AB#12582421 Update machines for Fusion deployment

client-react/src/pages/app/app-settings/GeneralSettings/stacks/function-app/FunctionAppStackSettings.tsx, client-react/src/utils/FunctionsRuntimeVersionHelper.ts
=> handle stack with v4 updates (#6359)

client-react/src/ApiHelpers/FunctionsService.ts, client-react/src/pages/app/functions/function/function-editor/FunctionEditorDataLoader.tsx
* re-add test data call
* behind ff
* add body
=> [s176] Re-add test data fetch through passthrough (#6371)

client-react/src/pages/app/SiteRouter.tsx, client-react/src/pages/app/spec-picker/specs/PriceSpec.ts, client-react/src/utils/BillingService.ts, client-react/src/utils/CommonConstants.ts, client-react/src/utils/FunctionAppService.ts, client-react/src/utils/billing-utils.ts
Fixes [AB#12619353](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/12619353)
Fixes [AB#12612269](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/12612269)
* file check behind ff
* update note
=> Update AzureFile check and put behind Editing portal FF (#6373)

client-react/src/models/app-setting.ts, client-react/src/models/functions/host-status.ts, client-react/src/pages/app/SiteRouter.tsx, client-react/src/utils/app-state-utils.tsx
Fixes [AB#12619367](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/12619367)
=> Add host status api check and refactor

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20211119141307780 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20211119141307780 to dev

client-react/src/pages/app/functions/function/function-editor/FunctionEditorDataLoader.tsx
Fixes [AB#10086096](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/10086096)
=> [FunctionEditor] PUT request on function should only be made if the editing is not disabled

client-react/src/utils/FunctionAppService.ts, client-react/src/utils/app-state-utils.tsx
Fixes [AB#12650841](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/12650841)
=> [Functions] Add premiumv2 check for portal linux editing

client-react/src/models/portal-models.ts, client-react/src/pages/app/SiteRouter.tsx, client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx, client-react/src/portal-communicator.ts, client-react/src/utils/CommonConstants.ts, client-react/src/utils/FunctionAppService.ts, client-react/src/utils/app-state-utils.tsx
Fixes [AB#12530694](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/12530694)
=> [Functions] Flighting check for Experimentation framework

client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/DeploymentCenterConstants.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrDataLoader.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrSettings.tsx, client-react/src/utils/CommonConstants.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Tasks [10234225 ](https://msazure.visualstudio.com/Antares/_workitems/edit/10234225) and [12451932 ](https://msazure.visualstudio.com/Antares/_workitems/edit/12451932)
Changes:
- Unhide ACR managed identities settings that were behind feature flag
- Add info and warning message
- Change orientation of Authentication settings from horizontal to vertical radio buttons
**Before**
**After**
**Info message**: when properties.acrUseManagedIdentities=true
**Warning message**: when acr.adminEnabled=true and properties.acrUseManagedIdentities=false
**Vertical orientation**:
=> [DC] Unhide ACR auth settings and add info/warning messages

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20211126140433852 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20211126140433852 to dev

client-react/src/utils/scenario-checker/container.environment.ts
[Ab#12573650](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s177?workitem=12573650) GA BYOS for windows container by removing the preview tag
=> AB#12573650 GA BYOS for windows container

client-react/src/pages/app/change-app-plan/CreatePlan.tsx
Fixes [AB#12724932](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/12724932)
=> Update onChange to handle delay in Text-field box

server/src/stacks/2020-10-01/stacks/web-app-stacks/Node.ts
Will cherry-pick to release after validating in next
=> Unhiding node 16 early access for Linux Web Apps

server/src/stacks/2020-06-01/stacks/web-app-stacks/AspDotnet.ts, server/src/stacks/2020-06-01/stacks/web-app-stacks/DotnetCore.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts
Fixes [AB#11147449](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/11147449)
=> [ANT96] Enable AI for .NET3.1 and .NET5

client-react/src/pages/app/app-settings/AppSettingsFormData.ts, client-react/src/pages/app/app-settings/FunctionRuntimeSettings/RuntimeVersion.tsx, client-react/src/pages/app/app-settings/FunctionRuntimeSettings/RuntimeVersionNew.tsx, client-react/src/pages/app/app-settings/GeneralSettings/stacks/function-app/FunctionAppStackSettings.data.ts, client-react/src/pages/app/app-settings/GeneralSettings/stacks/function-app/FunctionAppStackSettings.tsx, client-react/src/pages/app/app-settings/Sections/FunctionRuntimeSettingsPivot.tsx, client-react/src/utils/CommonConstants.ts, client-react/src/utils/stacks-utils.tsx, server/Resources/Resources.resx
[AB# 11908684](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/11908684)
=> Use stack api for versions - Iteration 1

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20211203141415335 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20211203141415335 to dev

client-react/src/models/portal-models.ts, client-react/src/pages/app/SiteRouter.tsx, client-react/src/portal-communicator.ts, client-react/src/utils/CommonConstants.ts, client-react/src/utils/FunctionAppService.ts, client-react/src/utils/app-state-utils.tsx
Cherry-pick of - 
https://github.com/Azure/azure-functions-ux/pull/6403
https://github.com/Azure/azure-functions-ux/pull/6388
=> Update app-setting check

server/src/stacks/2020-10-01/stacks/web-app-stacks/Node.ts
* Unhiding node 16 early access for Linux Web Apps
* Removing isHidden property
=> Unhiding node 16 early access for Linux Web Apps (#6399)

server/src/stacks/2020-06-01/stacks/web-app-stacks/AspDotnet.ts, server/src/stacks/2020-06-01/stacks/web-app-stacks/DotnetCore.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts
=> enable ai for .net3.1 and .net5 (#6400)

client-react/src/utils/scenario-checker/container.environment.ts
=> [BYOS] GA windows container on public azure

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20211210141357974 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20211210141357974 to dev

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx
FixesAB#[12834996 ](https://msazure.visualstudio.com/Antares/_workitems/edit/12834996)
Also, grouped ACR form settings into an if statement because errors were being logged even though ACR was not being used.
**For Private Registry settings:**
- Server url: https://yoonacr.io/
- Image and tag: nginx:latest
**Before:**
"properties": [
{
"name": "LinuxFxVersion",
"value": "DOCKER|**yoonacr.io//nginx:latest**"
},
**After:**
"properties": [
{
"name": "LinuxFxVersion",
"value": "DOCKER|**yoonacr.io/nginx:latest**"
},
Also tested with server URLs:
- https://///yoonacr.io
- https://yoona/cr.io
- https://yoonacr.io///
And regex only removes the end trailing forward slashes
=> [DC] Remove trailing forward slashes in server url and group ACR settings

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodePivot.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerPivot.tsx, client-react/src/utils/CommonConstants.ts
Fixes [AB#12863156](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/12863156)
Also to access:
let st=datetime(2021-12-14); let et=datetime(2021-12-18);
ExtTelemetry
| where TIMESTAMP between(st..et)
| where extension == "WebsitesExtension"
| where source == "DeploymentCenterFrameBladeReact"
| where action == "tabClicked"
| where actionModifier == "clicked"
| extend propertiesJson = parse_json(data)
| evaluate bag_unpack(propertiesJson, columnsConflict='replace_source')
| where tabName == 'ftps'
| where appType == 'functionapp'
| summarize dcount(subscriptionId)
=> [DC] Add logging for tab change

client-react/src/pages/app/deployment-center/DeploymentCenter.styles.ts, client-react/src/pages/app/deployment-center/DeploymentCenterFtps.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterPublishingUser.tsx
Fixes [AB#12871035](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/12871035)
Side by side:
Before:
After:
Other:
=> [DC] Updating FTPS Css

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20211217141224958 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20211217141224958 to dev

client-react/src/pages/static-app/skupicker/StaticSiteSkuPicker.tsx, client-react/src/utils/CommonConstants.ts
Fixes [AB#12920657](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/12920657)
=> [SWA][Azure Front Door] Remove feature-flag

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrDataLoader.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrSettings.tsx, server/Resources/Resources.resx
FixesAB#[12904306](https://msazure.visualstudio.com/Antares/_workitems/edit/12904306)
**Before:**
**After:**
=> [DC] Change wording and placement of ACR image/tag info message

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrSettings.tsx
Task [12938946 ](https://msazure.visualstudio.com/Antares/_workitems/edit/12938946)
After:
=> [DC] Hide managed identities dropdown when admin creds selected

client-react/src/components/form-controls/ComboBox.tsx, client-react/src/pages/app/deployment-center/DeploymentCenter.styles.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubDataLoader.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubProvider.tsx
Task [12724930 ](https://msazure.visualstudio.com/Antares/_workitems/edit/12724930)
**After:**
=> Add Spinner to loading ComboBox

client-react/src/utils/scenario-checker/kube-app.environment.ts
Fixes [AB#10362890](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/10362890)
=> [Configuration] Enable windows remote debugging for Kube 

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220107141300397 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220107141300397 to dev

client-react/src/ApiHelpers/FunctionsService.ts, client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx, client-react/src/pages/app/functions/function/function-editor/FunctionEditorDataLoader.tsx, client-react/src/pages/app/functions/function/function-editor/function-test/FunctionTest.tsx, client-react/src/utils/CommonConstants.ts, client-react/src/utils/FwLinks.ts, server/Resources/Resources.resx
Fixes [AB#12670226](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/12670226)
Banner and Run disabled
Disabled while adding
CORS added
=> Remove passthrough and add banner

server/src/stacks/2020-10-01/stacks/web-app-stacks/Python.ts
Fixes AB#[10469569](https://msazure.visualstudio.com/Antares/_workitems/edit/10469569)
=> Adding Python 3.10 (Early Access) as hidden

client-react/src/models/portal-models.ts, client-react/src/pages/static-app/skupicker/StaticSiteSkuPicker.tsx
Fixes [AB#13046638](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/13046638)
=> AB#13046638 [Fusion side] If customers are on standard SKU, we should refresh TOC to make sure all the right things are enabled

client-react/src/QuickPulseQuery/QuickPulseQueryLayer.ts, client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx, client-react/src/pages/app/functions/function/function-editor/FunctionEditorDataLoader.tsx, client-react/src/pages/app/functions/function/function-log/FunctionLogAppInsightsDataLoader.tsx, client-react/src/utils/CommonConstants.ts
Fixes [AB#12725573](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/12725573)
=> [Function Logs] Function logs behind FF

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220121141407375 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220121141407375 to dev

client-react/src/components/DisplayTableWithCommandBar/DisplayTableWithCommandBar.tsx, client-react/src/pages/app/app-settings/ApplicationSettings/ApplicationSettings.tsx, client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStrings.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
1. Update role of the Configuration command buttons from 'nav' to 'button'
2. Add aria label of the grid search results.
Fixes [AB#12464192](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s181?workitem=12464192) 
[AB#12470386](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s181?workitem=12470386)
=> AB#12464192 AB#12470386 Configuration Blade Accessibility Update

client-react/src/utils/scenario-checker/kube-app.environment.ts, client-react/src/utils/scenario-checker/xenon-site.environment.ts
Fixes [AB#10362890](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/10362890)
=> Enable Windows remote debugging

client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEditAdvanced.tsx, client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEditBasic.tsx, server/Resources/Resources.resx
Fixes [#6460 AB13055685](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s181?workitem=13055685) Update banner message and change the type from warning to info
=> AB#13055685 [BYOS] Update banner message

client-react/src/pages/app/app-settings/AppSettingsFormData.ts
Fix [AB#12364779](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s181?workitem=12364779)
=> AB#12364779 Add slash to the end of VA path when matching VD path to VA path

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220128141309489 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220128141309489 to dev

client-react/src/pages/app/functions/function/function-editor/FunctionEditorDataLoader.tsx
Http Trigger
Timer Trigger
Event Trigger
Queue Trigger
=> Fix request body for http trigger

client-react/src/utils/scenario-checker/kube-app.environment.ts, client-react/src/utils/scenario-checker/xenon-site.environment.ts
* enable windows remote debugging
* Remove result
=> Enable Windows remote debugging (#6458)

client/src/app/shared/services/cache.service.ts
Fixes [AB#13033694](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/13033694)
=> Remove cache service passthrough call

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220204140556707 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220204140556707 to dev

client-react/src/ApiHelpers/AppInsightsService.ts, client-react/src/utils/CommonConstants.ts
Fixes [AB#8888536](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/8888536)
=> [Functions][AI] Update generateLiveToken API version from preview

client-react/src/pages/app/app-settings/FunctionRuntimeSettings/RuntimeVersionNew.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes [AB#11908684](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/11908684)
=> [Function runtime settings] Add banner for non-supported or missing version

client/src/app/controls/group-tabs/group-tabs.component.html
[AB#12469985](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s182?workitem=12469985)
=> AB#12469985 Add description to aria label

client-react/src/pages/app/deployment-center/devops-provider/DeploymentCenterDevOpsDataLoader.tsx
FixesAB#[13075635](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s182?workitem=13075635)
Before:
After:
=> [DC] Sort dropdown items alphabetically for azure repos

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220211141804283 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220211141804283 to dev

client-react/src/pages/app/app-settings/FunctionRuntimeSettings/RuntimeVersionNew.tsx, client-react/src/pages/app/deployment-center/DeploymentCenter.styles.ts, client-react/src/pages/app/deployment-center/bitbucket-provider/DeploymentCenterBitbucketAccount.tsx, client-react/src/pages/app/deployment-center/devops-provider/DeploymentCenterDevOpsProvider.tsx, client-react/src/pages/app/deployment-center/dropbox-provider/DeploymentCenterDropboxAccount.tsx, client-react/src/pages/app/deployment-center/external-provider/DeploymentCenterExternalProvider.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubAccount.tsx, client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubDataLoader.tsx, client-react/src/pages/app/deployment-center/local-git-provider/DeploymentCenterLocalGitProvider.tsx, client-react/src/pages/app/deployment-center/onedrive-provider/DeploymentCenterOneDriveAccount.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.tsx, client-react/src/utils/FwLinks.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Task [10694668](https://msazure.visualstudio.com/Antares/_workitems/edit/10694668)
Adding description text under Source title for:
- GitHub + GHA 
- GitHub + App Service Build
- Bitbucket + App Service Build
- External Git + App Service Build
- Azure Repos + App Service Build
- DropBox
- OneDrive
=> [DC] Add description text for deployment scenarios

client-react/src/components/form-controls/TextFieldNoFormik.tsx, client-react/src/components/form-controls/formControl.override.styles.tsx, client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEdit.tsx, client-react/src/utils/CommonConstants.ts, server/Resources/Resources.resx
=> [BYOS] Remove gap between mount path prefix and text field + change info message for windows code app BYOS

client/src/app/api/api-details/api-details.component.ts
Fixes [AB#12386196](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/12386196)
Before:
After
=> [Functions] Open function app files blade from proxy blade

client-react/src/pages/static-app/configuration/Configuration.tsx, client-react/src/pages/static-app/configuration/Configuration.types.ts, client-react/src/pages/static-app/configuration/ConfigurationDataLoader.tsx, client-react/src/pages/static-app/configuration/ConfigurationFormBuilder.tsx, client-react/src/pages/static-app/configuration/ConfigurationGeneralSettings.tsx, client-react/src/pages/static-app/configuration/ConfigurationPivot.tsx, client-react/src/utils/CommonConstants.ts, client-react/src/utils/FwLinks.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes [AB#13419062](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/13419062)
=> [SWA] Unhide Password protection

client-react/src/models/site/site.ts, client-react/src/pages/app/app-settings/GeneralSettings/ClientCert/ClientCert.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
[AB#8644665](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s183?workitem=8644665) Add optionalInteractiveUser as an option for cetificate mode
=> AB#8644665 [Configuration] Add Optional option to client certificate mode radio groups

server/src/quickstart/cs-CZ/vscodeDirectPublish-react-localDevExperience_cs.md, server/src/quickstart/de-DE/vscodeDirectPublish-react-localDevExperience_de.md, server/src/quickstart/es-ES/vscodeDirectPublish-react-localDevExperience_es.md, server/src/quickstart/fr-FR/vscodeDirectPublish-react-localDevExperience_fr.md, server/src/quickstart/hu-HU/vscodeDirectPublish-react-localDevExperience_hu.md, server/src/quickstart/it-IT/vscodeDirectPublish-react-localDevExperience_it.md, server/src/quickstart/ja-JP/vscodeDirectPublish-react-localDevExperience_ja.md, server/src/quickstart/ko-KR/vscodeDirectPublish-react-localDevExperience_ko.md, server/src/quickstart/nl-NL/vscodeDirectPublish-react-localDevExperience_nl.md, server/src/quickstart/pl-PL/vscodeDirectPublish-react-localDevExperience_pl.md, server/src/quickstart/pt-BR/vscodeDirectPublish-react-localDevExperience_pt-BR.md, server/src/quickstart/pt-PT/vscodeDirectPublish-react-localDevExperience_pt-PT.md, server/src/quickstart/ru-RU/vscodeDirectPublish-react-localDevExperience_ru.md, server/src/quickstart/sv-SE/vscodeDirectPublish-react-localDevExperience_sv.md, server/src/quickstart/tr-TR/vscodeDirectPublish-react-localDevExperience_tr.md, server/src/quickstart/vscodeDirectPublish-react-localDevExperience.md, server/src/quickstart/zh-CN/vscodeDirectPublish-react-localDevExperience_zh-CN.md, server/src/quickstart/zh-TW/vscodeDirectPublish-react-localDevExperience_zh-TW.md
Resolves [this issue](https://github.com/Azure/azure-functions-core-tools/issues/2968) and updates installation instructions for Core Tools V4.
=> Update installation instructions for Core Tools V4

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220304141323409 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220304141323409 to dev

server/src/shared/logging/etw.service.ts, server/src/shared/logging/logging.service.ts
https://eslint.org/docs/rules/no-prototype-builtins
=> fix: Address `no-prototype-builtins` lint errors in /server

client/src/app/api/api-details/api-details.component.ts
This is a cherry-pick of this PR >>> https://github.com/Azure/azure-functions-ux/commit/70731310d656a11bc4b541f53f76d6648e3ee661
This is addressing this bug >> https://msazure.visualstudio.com/Antares/_workitems/edit/13766742
=> Revise: 13766742 [FunctionApp V1/V2][Stage]:Unable to Save the API Proxy after Editing

client/src/app/shared/models/portal-resources.ts, client/src/app/site/container-settings/container-settings.component.html, client/src/app/site/deployment-center/deployment-center.component.html, server/Resources/Resources.resx
Task#[13499439](https://msazure.visualstudio.com/Antares/_workitems/edit/13499439)
**Before:**
**After:**
=> [Old DC] Remove deprecation banner

client-react/src/ApiHelpers/BitbucketService.ts, client-react/src/ApiHelpers/DropboxService.ts, client-react/src/ApiHelpers/OneDriveService.ts, client-react/src/QuickPulseQuery/QuickPulseQueryLayer.ts, client-react/src/pages/app/SiteRouter.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrDataLoader.tsx, client-react/src/pages/app/functions/function/function-editor/FunctionEditorDataLoader.tsx, client-react/src/pages/app/spec-picker/specs/DV2SeriesPriceSpec.ts, client-react/src/portal-communicator.ts, client-react/src/utils/flighting-util.ts
Address [`no-this-alias`](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-this-alias.md#no-this-alias) warning in `QuickPulseQueryLayer.ts`
=> fix: Address `prefer-const` lint errors in /client-react

client-react/src/QuickPulseQuery/QuickPulseQueryLayer.ts, client-react/src/pages/app/functions/function/function-log/FunctionLogAppInsightsDataLoader.tsx
Current Logs API:
New Logs API:
=> [AI Logs] Update version on session id change

client/src/app/site/spec-picker/spec-picker.component.scss
[AB#12433474](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s184?workitem=12433474)
Add an underline to learn more link
=> AB#12433474 [Accessibility] Add underline to learn more

client-react/src/utils/scenario-checker/windows-code.environment.ts
Revert it because support team is not ready yet.
=> Revert "AB#13785281 [BYOS] Public preview windows code BYOS on public azure"

client-react/.gitignore, client-react/config-overrides.js, client-react/package.json
- Disable broken tests with comments about why they are broken
- Move Jest configuration into `config-overrides.js`
- Update `test:ci` npm script
=> test: Fix test configuration in /client-react

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220311141329638 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220311141329638 to dev

client-react/src/pages/app/app-settings/FunctionRuntimeSettings/RuntimeVersionNew.tsx, client-react/src/pages/app/app-settings/Sections/FunctionRuntimeSettingsPivot.tsx, client-react/src/utils/CommonConstants.ts, server/Resources/Resources.resx
Fixes [AB#13044799](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/13044799)
=> [Functions Config] Update Message + Remove FF

client-react/src/pages/static-app/skupicker/StaticSiteSkuPicker.tsx
Fixes [AB#13820977](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/13820977)
Before:
After:
=> [SWA][SkuPicker] Update Row type

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220318131400421 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220318131400421 to dev

client-react/src/ApiHelpers/StorageService.ts, client-react/src/models/storage-account.ts, client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEdit.tsx, client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEditBasic.tsx, client-react/src/utils/CommonConstants.ts
Fixes:[AB#13241891](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s185?workitem=13241891)  Change call to storage with calling from portal.azure.com to prevent networking restriction issue
Before:
After:
=> AB#13241891 [BYOS] Change call to storage by calling from portal.azure.com

client-react/src/components/form-controls/SearchBox.tsx, client-react/src/pages/app/app-settings/ApplicationSettings/ApplicationSettings.tsx, client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStrings.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes: [AB#12470386](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s185?workitem=12470386)
Add a search box control that has search result announcement functions. Replace the Announced component with it.
=> AB#12470386 use built-in search box arialabel

client-react/src/models/functions/function-binding.ts, client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx, client-react/src/utils/BindingManager.ts
=> Enable "Get Function URL" command for "authenticationEventTrigger"

client-react/config-overrides.js, client-react/src/pages/app/app-settings/ApplicationSettings/ApplicationSettings.utils.spec.ts
- Add `moduleNameMapper` entry to map `joi` to `joi-browser`
- Fix outdated tests
=> test: Fix and update tests using `joi`

client-react/src/components/form-controls/TextFieldNoLabel.tsx, client-react/src/pages/app/functions/function/integrate/FunctionIntegrateDataLoader.tsx, client-react/src/pages/app/log-stream/LogStreamDataLoader.tsx
Use `componentDidMount` instead of `componentWIllMount`.
=> fix: Replace deprecated lifecycle methods

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220325131313196 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220325131313196 to dev

client-react/src/utils/scenario-checker/windows-code.environment.ts
Fixes: [AB#13785281](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s185?workitem=13785281)
=> AB#13785281 public preview byos on windows code

client-react/src/components/MarkdownComponents/MarkdownComponents.tsx, client-react/src/pages/app/functions/new-create-preview/local-create/LocalCreateInstructions.tsx, server/src/quickstart/coretoolsDirectPublish-react-localDevExperience.md, server/src/quickstart/cs-CZ/coretoolsDirectPublish-react-localDevExperience_cs.md, server/src/quickstart/de-DE/coretoolsDirectPublish-react-localDevExperience_de.md, server/src/quickstart/es-ES/coretoolsDirectPublish-react-localDevExperience_es.md, server/src/quickstart/fr-FR/coretoolsDirectPublish-react-localDevExperience_fr.md, server/src/quickstart/hu-HU/coretoolsDirectPublish-react-localDevExperience_hu.md, server/src/quickstart/it-IT/coretoolsDirectPublish-react-localDevExperience_it.md, server/src/quickstart/ja-JP/coretoolsDirectPublish-react-localDevExperience_ja.md, server/src/quickstart/ko-KR/coretoolsDirectPublish-react-localDevExperience_ko.md, server/src/quickstart/nl-NL/coretoolsDirectPublish-react-localDevExperience_nl.md, server/src/quickstart/pl-PL/coretoolsDirectPublish-react-localDevExperience_pl.md, server/src/quickstart/pt-BR/coretoolsDirectPublish-react-localDevExperience_pt-BR.md, server/src/quickstart/pt-PT/coretoolsDirectPublish-react-localDevExperience_pt-PT.md, server/src/quickstart/ru-RU/coretoolsDirectPublish-react-localDevExperience_ru.md, server/src/quickstart/sv-SE/coretoolsDirectPublish-react-localDevExperience_sv.md, server/src/quickstart/tr-TR/coretoolsDirectPublish-react-localDevExperience_tr.md, server/src/quickstart/zh-CN/coretoolsDirectPublish-react-localDevExperience_zh-CN.md, server/src/quickstart/zh-TW/coretoolsDirectPublish-react-localDevExperience_zh-TW.md
Fixes [AB#12804738](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/12804738) 
Before:
Slot:
Main function app:
After:
Slot:
Main function app:
=> AB#12804738 [Functions] Instructions on how to deploy to a slot are incorrect

client/src/app/copy-pre/copy-pre.component.spec.ts, client/src/app/site/console/bash/bash.component.spec.ts, client/src/app/site/console/cmd/cmd.component.spec.ts, client/src/app/site/console/powershell/powershell.component.spec.ts, client/src/app/site/deployment-center/deployment-center-setup/step-build-provider/step-build-provider.component.spec.ts, client/src/app/site/deployment-center/deployment-center-setup/step-complete/step-complete.component.spec.ts, client/src/app/site/deployment-center/deployment-center-setup/step-configure/configure-bitbucket/configure-bitbucket.component.spec.ts, client/src/app/site/deployment-center/deployment-center-setup/step-configure/configure-dropbox/configure-dropbox.component.spec.ts, client/src/app/site/deployment-center/deployment-center-setup/step-configure/configure-external/configure-external.component.spec.ts, client/src/app/site/deployment-center/deployment-center-setup/step-configure/configure-github/configure-github.component.spec.ts, client/src/app/site/deployment-center/deployment-center-setup/wizard-logic/deployment-center-state-manger.service.spec.ts, client/src/test.ts, client/tsconfig.json
- Enable *downlevelIteration* TypeScript configuration to fix test build.
- Disable 127 broken tests.
=> test: Fix test build and disable broken tests in /client

client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeBuildRuntimeAndVersion.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.tsx
[AB#13811200](https://msazure.visualstudio.com/Antares/_workitems/edit/13811200)
=> handle Java17 in deployment center

client-react/src/pages/app/app-settings/FunctionRuntimeSettings/RuntimeVersionNew.tsx, client-react/src/utils/CommonConstants.ts
Fixes [AB#13911069](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/13911069)
Before:
With version ~3:
With version 0.4:
After:
With version ~3:
With version 0.4:
=> [Functions Runtime Version] Handle dotnet 3.1

client-react/src/pages/app/functions/function/function-editor/function-test/FunctionTest.tsx, client-react/src/utils/CommonConstants.ts
Fixes [AB#13500186](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/13500186)
Firefox:
Chrome:
document.referrer appears to be available on all browsers https://developer.mozilla.org/en-US/docs/Web/API/Document/referrer
=> [Code + Test] Change ancestororigins to referrer

client-react/src/pages/app/functions/function/function-editor/function-test/FunctionTest.tsx, client-react/src/utils/CommonConstants.ts
* change ancestororigins to referrer
* removing trailing slashes
* ?
* ??
* helper functions
=> [Code + Test] Change ancestororigins to referrer (#6613)

client-react/src/components/PlanPicker/PlanPicker.tsx, client-react/src/pages/static-app/skupicker/StaticSiteSkuPicker.tsx
Update Static Web Apps plan picker to use reusable components.
=> Reusable plan picker components

client-react/package-lock.json, client-react/package.json, client-react/src/ApiHelpers/ArmHelper.ts, client-react/src/components/InfoTooltip/InfoTooltip.tsx, client-react/src/components/InformationCard/InformationCard.tsx, client-react/src/components/InformationLabel/InformationLabel.tsx, client-react/src/components/Loading/LoadingComponent.stories.tsx, client-react/src/components/TooltipIcons/UpsellIcon.tsx, client-react/src/components/UpsellBanner/UpsellBanner.tsx, client-react/src/components/form-controls/ComboBoxnoFormik.tsx, client-react/src/components/form-controls/DropDown.tsx, client-react/src/components/form-controls/DropDownnoFormik.tsx, client-react/src/components/form-controls/Toggle.tsx, client-react/src/components/form-controls/ToggleNoFormik.tsx, client-react/src/components/shimmer/Shimmer.types.tsx, client-react/src/index.tsx, client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/PythonStack.tsx, client-react/src/pages/app/app-settings/Sections/CustomTabRenderer.tsx, client-react/src/pages/app/change-app-plan/CreatePlan.tsx, client-react/src/pages/app/functions/common/BindingFormBuilder.tsx, client-react/src/pages/app/functions/common/CreateFunctionFormBuilder.tsx, client-react/src/pages/container-app/console/ConsoleDataLoader.tsx, client-react/src/utils/i18n.ts, client-react/src/utils/stacks-utils.tsx
- Adding xterm package resulted in some build error, which were resolved after upgrading the typescript and react types versions.
- Editing ConsoleDataLoader to show a terminal
=> [ContainerApps] Create Console page terminal

client-react/src/components/PlanPicker/PlanPicker.tsx, client-react/src/pages/App.tsx, client-react/src/pages/logic-app/LogicAppRouter.tsx, client-react/src/pages/logic-app/planpicker/LogicAppPlanPicker.tsx, client-react/src/pages/logic-app/planpicker/LogicAppPlanPicker.types.ts, client-react/src/pages/logic-app/planpicker/LogicAppPlanPickerDataLoader.tsx, client-react/src/pages/static-app/skupicker/StaticSiteSkuPicker.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> [LA] Plan picker context pane

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220408131536770 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220408131536770 to dev

server/src/stacks/2020-06-01/stacks/web-app-stacks/AspDotnet.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts, server/src/tests/Stacks/2020-06-01/web-app/validations.ts, server/src/tests/Stacks/2020-10-01/web-app/validations.ts
Fixes [AB#13479547](https://msazure.visualstudio.com/Antares/_workitems/edit/13479547)
=> Adding .NET 7 as hidden for Web Apps

client-react/src/ApiHelpers/TagsService.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrDataLoader.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx
=> [DeploymentCenter][CRI] Fixes for cross sub ACR settings

client-react/.storybook/addons.js, client-react/.storybook/config.js, client-react/package-lock.json, client-react/package.json, client-react/src/components/Loading/LoadingComponent.stories.tsx
https://snyk.io/test/npm/%40storybook/react/4.1.11
=> Remove unused Storybook code and dependencies

client-react/src/pages/app/functions/function/function-log/FunctionLogAppInsightsDataLoader.tsx, client-react/src/utils/SiteHelper.ts
I added a site hidden tag check. If AI resource Id is stored in site hidden tag, we use the AI resource Id to get app insights data.
=> 13767704[Functions] [Edit]- Update how to get AI resource and hidden AI tag check and update

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerDockerHubSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerPrivateRegistrySettings.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Task#[14124162](https://msazure.visualstudio.com/Antares/_workitems/edit/14124162)
=> [DC] Rename Startup file to Startup file or command

client-react/src/pages/app/functions/function/monitor/AppInsightsSetup.tsx
Fixes [AB#14168486](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/14168486)
=> AB#14168486 [Fusion side] Update Application Insights blade from Enablement V1 to V2

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220422131624846 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220422131624846 to dev

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeBuildCallout.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceAndBuild.tsx, client-react/src/pages/app/deployment-center/onedrive-provider/DeploymentCenterOneDriveDataLoader.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.ts, client-react/src/utils/scenario-checker/onprem.environment.ts, client-react/src/utils/scenario-checker/scenario-ids.ts, server/src/deployment-center/bitbuckets/bitbuckets.controller.ts, server/src/deployment-center/dropbox/dropbox.controller.ts, server/src/deployment-center/github/github.controller.ts, server/src/deployment-center/onedrive/onedrive.controller.ts, server/src/shared/config/config.service.ts, server/web.config
Add new Deployment Center experience to OnPrem, @ms-maya Please review this PR
=> Add Deployment Center experience to OnPrem

server/src/stacks/2020-10-01/stacks/web-app-stacks/Java.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/JavaContainers.ts
1. add new java versions
Java17: 17.0.1, 17.0.2,
Java11: 11.0.12, 11.0.13, 11.0.14,
Java8: 1.8.0_302, 1.8.0_312, 1.8.0_322
2. add new Tomcat versions:
Tomcat8.5: 8.5.69, 8.5.72, 8.5.78,
Tomcat9.0: 9.0.52, 9.0.54, 9.0.62,
Tomcat10.0: 10.0.12, 10.0.20
And deprecate Tomcat 7 to in line with Azure.
=> Add new java and javacontainer versions into stacks

client-react/src/theme/CustomOfficeFabric/AzurePortal/Dropdown.styles.ts
[#14263437](https://msazure.visualstudio.com/Antares/_workitems/edit/14263437/)
Fix border color, border width, and text color styles to match text field error message styles.
=> Fix dropdown error message border and color styles

client-react/src/pages/app/functions/function/function-log/FunctionLogFileStreamData.ts, client-react/src/pages/app/log-stream/LogStream.types.ts
Fixes [AB#14238312](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/14238312)
Before:
After:
=> [Function Logs] Filtering for date in UTC time

client-react/src/pages/app/functions/common/BindingFormBuilder.tsx, client-react/src/pages/app/functions/function/integrate/FunctionIntegrateDataLoader.tsx, client-react/src/pages/app/functions/function/integrate/binding-card/BindingCardLink.tsx, client-react/src/pages/app/functions/function/integrate/binding-card/InputBindingCard.tsx, client-react/src/pages/app/functions/function/integrate/binding-card/OutputBindingCard.tsx, client-react/src/pages/app/functions/function/integrate/binding-card/TriggerBindingCard.tsx, client-react/src/pages/app/functions/function/integrate/binding-card/UnknownDirectionBindingCard.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
[#14240943](https://msazure.visualstudio.com/Antares/_workitems/edit/14240943/)
The text has been changed: "One or more bindings failed to load. Please try again later."
=> Handle "get bindings" errors in Function Integration blade better

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSettings.tsx, server/src/workflows/2020-12-01/WorkflowService.ts, server/src/workflows/2020-12-01/container-configs/container-windows.config.yml
Tasks#[12396626](https://msazure.visualstudio.com/Antares/_workitems/edit/12396626) and [10641391](https://msazure.visualstudio.com/Antares/_workitems/edit/10641391)
**Before:**
**After:**
=> [DC] Enable GHA and AzureDevOps for Windows Containers

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220429131656770 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220429131656770 to dev

client/src/app/site/spec-picker/price-spec-manager/isolatedv2-plan-price-spec.ts
**NOTE : Left is the new UX and right is old UX screenshots**
Existing Xenon App on ASEv3 (We do not provide option to create Xenon app on ASEv1 and v2. Needs to be v3)
**Create Flow**
When user selects Docker + Windows + Isolated V2, they see Hyper V card.
When user selects option publish type and operation system combination for Isolated V2, Hyper V card should not show up. Example below is Docker + Linux + isolated V2
=> 12513894[ASEv3] Hyper-v isolation should be included in the feature description for Xenon App

client-react/src/models/portal-models.ts, client-react/src/portal-communicator.ts
This will adjust theme depending on high contrast value. Still need to add different color theme depending on the high contrast and theme value.
Ibiza side PR :  https://msazure.visualstudio.com/One/_git/AAPT-Antares-AntUX/pullrequest/6014680
Once both Ibiza and Fusion side PR go in, it will look like this:
Left is what will looks like and right one is what it looks now.
=> 9759788 High contrast colors in fusion

client-react/src/ApiHelpers/DocumentDBService.ts, client-react/src/pages/app/functions/common/callout-content/BindingCalloutContent.style.ts, client-react/src/pages/app/functions/common/callout-content/BindingCalloutContent.tsx, client-react/src/pages/app/functions/common/callout-content/documentdb/CosmosDbControls.ts, client-react/src/pages/app/functions/common/callout-content/documentdb/CosmosDbCreator.styles.ts, client-react/src/pages/app/functions/common/callout-content/documentdb/CosmosDbCreator.tsx, client-react/src/utils/CommonConstants.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
[#14240740](https://msazure.visualstudio.com/Antares/_workitems/edit/14240740/)
=> Move Cosmos DB controls to Fusion

client-react/src/pages/app/functions/function/function-editor/function-test/FunctionTestInput.tsx
Fixes [AB#14337288](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/14337288)
Before:
After:
=> [Code+Test] Header/Query Grid typing is slow

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220506131434455 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220506131434455 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220513183721217 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220513183721217 to dev

client-react/src/pages/container-app/console/ConsoleDataLoader.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes [AB#14436559](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/14436559)
=> [ContainerApps] Add Aria-Label for Custom textField on Console

client-react/src/pages/container-app/console/ConsoleDataLoader.tsx
=> [ContainerApp] Prevent focus from getting trapped inside the console

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220520132154903 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220520132154903 to dev

server/src/stacks/2020-10-01/stacks/web-app-stacks/Node.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Php.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Python.ts, server/src/tests/Stacks/2020-10-01/web-app/validations.ts
Fixes [AB#13875358](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/13875358)
Fixes [AB#13875360](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/13875360)
Fixes [AB#13875367](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/13875367)
=> [Stack] Add Node, PHP, Python behind hide-key

client-react/src/utils/scenario-checker/linux-site.environment.ts
Fixes [AB#14130372](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s189?workitem=14130372)
=> AB#14130372 hide web sockets for linux code/containers

client-react/src/pages/app/app-settings/AppSettingsFormData.ts, client-react/src/pages/app/app-settings/GeneralSettings/Platform.tsx, client-react/src/pages/app/app-settings/Sections/GeneralSettings.tsx, client-react/src/utils/scenario-checker/kube-app.environment.ts, client-react/src/utils/scenario-checker/scenario-ids.ts
Fixes [AB#13811589](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s189?workitem=13811589)
=> AB#13811589 Show TLS settings for K8s

client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx, client-react/src/pages/app/functions/function/function-editor/FunctionEditorDataLoader.tsx, client-react/src/utils/CommonConstants.ts, client-react/src/utils/FunctionAppService.ts, client-react/src/utils/app-state-utils.tsx
Fixes [AB#14556115](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/14556115)
=> AB#14556115 [Fusion] Enable Portal editing for Linux (remove experimentation and enable for all users)

server/src/stacks/2020-06-01/stacks/web-app-stacks/JavaContainers.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/JavaContainers.ts
Fixes [AB#14210471](https://msazure.visualstudio.com/Antares/_workitems/edit/14210471)
=> Fixing Apache Tomcat 10.0.12 Java container in stacks API

server/src/stacks/2020-10-01/models/WebAppStackModel.ts, server/src/stacks/2020-10-01/service/StackService.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Golang.ts, server/src/tests/Stacks/2020-10-01/web-app/tests.ts, server/src/tests/Stacks/2020-10-01/web-app/validations.ts
Fixes [AB#14529692](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/14529692)
=> [Stacks] Add GO stack behind hide-key

client-react/src/pages/app/log-stream/LogStream.types.ts
=> [Function logs] Update Regx for additional log types

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220527143718176 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220527143718176 to dev

client-react/src/pages/app/app-settings/AppSettings.types.ts, client-react/src/pages/app/app-settings/AppSettingsForm.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeBuildRuntimeAndVersion.tsx
Task#[14568697](https://msazure.visualstudio.com/Antares/_workitems/edit/14568697)
=> [Configuration] Add constants for tab ids

client-react/src/pages/app/change-app-plan/ChangeAppPlan.styles.ts, client-react/src/pages/app/change-app-plan/ChangeAppPlan.tsx, client-react/src/pages/app/change-app-plan/ChangeAppPlan.types.ts, client-react/src/pages/app/change-app-plan/ChangeAppPlanCurrentPlanDetails.tsx, client-react/src/pages/app/change-app-plan/ChangeAppPlanDestinationPlanDetails.tsx, client-react/src/pages/app/change-app-plan/ChangeAppPlanFooter.tsx, client-react/src/pages/app/change-app-plan/ChangeAppPlanHeader.tsx, client-react/src/pages/app/change-app-plan/CreatePlan.tsx, client-react/src/utils/CommonConstants.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes [AB#14510382](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/14510382)
Before:
After:
=> [Functions Migration] Plan type radio button, fix Footers

client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.tsx
FixesAB#[14124247](https://msazure.visualstudio.com/Antares/_workitems/edit/14124247)
=> [DC] Change webhook url from 'docker/hook' to 'api/registry/hook'

client-react/src/pages/app/change-app-plan/ChangeAppPlan.types.ts, client-react/src/pages/app/change-app-plan/ChangeAppPlanDataLoader.tsx, client-react/src/pages/app/change-app-plan/ChangeAppPlanDestinationPlanDetails.tsx, client-react/src/pages/app/change-app-plan/CreateOrSelectPlan.tsx, client/src/app/site/spec-picker/price-spec-manager/plan-price-spec-manager.ts
Fixes [AB#14510106](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/14510106)
=> [Functions Migration] Choosing plan, reloading plans

server/src/stacks/2020-06-01/stacks/web-app-stacks/Ruby.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Ruby.ts
Initial change - https://github.com/Azure/azure-functions-ux/pull/6393
=> [Ruby] Hide patch level Ruby version

client-react/src/pages/app/change-app-plan/ChangeAppPlan.styles.ts, client-react/src/pages/app/change-app-plan/ChangeAppPlan.tsx, client-react/src/pages/app/change-app-plan/ChangeAppPlan.types.ts, client-react/src/pages/app/change-app-plan/ChangeAppPlanDestinationPlanDetails.tsx, client-react/src/pages/app/change-app-plan/CreateOrSelectPlan.tsx, client-react/src/pages/app/change-app-plan/CreatePlan.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes [AB#14712144](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/14712144)
=> [Functions migration] Functions migration warning + disable during update

client-react/src/pages/app/change-app-plan/ChangeAppPlan.styles.ts, client-react/src/pages/app/change-app-plan/ChangeAppPlan.tsx, client-react/src/pages/app/change-app-plan/CreateOrSelectResourceGroup.tsx, client-react/src/pages/app/change-app-plan/CreatePlan.tsx
Fixes [AB#14736650](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/14736650)
styling fix 
Before:
After:
=> [Functions migration] Update resource group

server/Resources/Resources.resx
Task#[14746364 ](https://msazure.visualstudio.com/Antares/_workitems/edit/14746364)
**Before:**
**After:**
=> [DC] Change repo combobox text to say Select or type

server/src/stacks/2020-06-01/stacks/web-app-stacks/Ruby.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Ruby.ts
Fixes [AB#14727185](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/14727185)
Co-authored-by: Krrish Mittal <takyyon@Krrishs-MacBook-Pro.local>
=> [Cherry-pick] Mark Ruby 2.7.3 as hidden (#6727)

server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts, server/src/tests/Stacks/2020-10-01/function-app/validations.ts
Issue in Dotnet worker - https://github.com/Azure/azure-functions-dotnet-worker/issues/926
- Updated display text
- Added IsPreview field
=> Updating display text of .NET 7 support in Stack API 

client-react/src/models/functions/function-config.ts, client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx, client-react/src/pages/app/functions/function/function-editor/FunctionEditorDataLoader.tsx, client-react/src/pages/app/functions/function/function-editor/useFunctionEditorQueries.ts
[#14093549](https://msazure.visualstudio.com/Antares/_workitems/edit/14093549/)
=> Ensure the portal gracefully handles the new Python programming model

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220701130651393 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220701130651393 to dev

client-react/src/models/BillingModels.ts, client-react/src/pages/app/functions/common/callout/storageAccountPivot/StorageAccountPivot.tsx, client-react/src/pages/app/spec-picker/specs/isolated/IsolatedPlanPriceSpec.ts, client-react/src/utils/CommonConstants.ts, client-react/src/utils/scenario-checker/national-cloud.environment.ts, client-react/src/utils/url.ts, client/src/app/shared/models/constants.ts, client/src/app/shared/services/scenario/national-cloud.environment.ts, client/src/app/site/site-manage/site-manage.component.ts, client/src/app/site/spec-picker/price-spec-manager/billing-models.ts, client/src/app/site/spec-picker/price-spec-manager/isolated-plan-price-spec.ts, server/src/constants.ts, server/src/shared/config/config.service.ts, server/src/types/config.ts
Fixes [AB#14886201](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/14886201)
=> AB#14886201 [Fusion] Remove BlackForest from codebase

client-react/src/pages/container-app/console/ConsoleDataLoader.tsx
=> [CP][ContainerApps][Console] fix console exec endpoint

client-react/src/models/site/config.ts, client-react/src/pages/app/app-settings/GeneralSettings/Platform.tsx, client-react/src/pages/app/app-settings/Sections/GeneralSettings.tsx, client-react/src/utils/CommonConstants.ts, client-react/src/utils/scenario-checker/linux-site.environment.ts, client-react/src/utils/scenario-checker/scenario-ids.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Option is visible when app is Linux + has feature flag 'showHttps20Proxy'=true
=> Add HTTP 2.0 proxy enable option

client-react/src/pages/app/SiteRouter.tsx, client-react/src/pages/app/app-settings/AppSettings.utils.ts, client-react/src/pages/app/app-settings/AppSettingsDataLoader.tsx, client-react/src/pages/app/app-settings/ApplicationSettings/AppSettingAddEdit.tsx, client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEditBasic.tsx, client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStringsAddEdit.tsx
[AB#14923024](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/14923024)
=> Fix logging on fusion - Config Blade (1)

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220708132651608 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220708132651608 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220715131118538 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220715131118538 to dev

client-react/src/pages/app/functions/common/CosmosDbFunctionFormBuilder.tsx, client-react/src/pages/app/functions/common/CosmosDbResourceDropdown.tsx, client-react/src/pages/app/functions/common/callout/NewCosmosDbAccountCallout.tsx, client-react/src/pages/app/functions/common/combobox-with-link/cosmos-db/CosmosDbContainerComboBox.tsx, client-react/src/pages/app/functions/common/combobox-with-link/cosmos-db/CosmosDbDatabaseComboBox.tsx
[#14260766](https://msazure.visualstudio.com/Antares/_workitems/edit/14260766/)
=> [Functions Collateral] Add telemetry to Cosmos DB new resource UX

client-react/src/ApiHelpers/SiteService.ts, client-react/src/pages/app/functions/common/CosmosDbFunctionFormBuilder.tsx, client-react/src/pages/app/functions/common/CosmosDbResourceDropdown.tsx, client-react/src/pages/app/functions/common/useAppSettingsQuery.ts, client-react/src/pages/app/functions/common/useCreateFunctionFormBuilderFactory.ts, client-react/src/pages/app/functions/common/usePermissions.ts, client-react/src/pages/app/functions/new-create-preview/FunctionCreate.data.ts, client-react/src/pages/app/functions/new-create-preview/FunctionCreate.styles.ts, client-react/src/pages/app/functions/new-create-preview/FunctionCreateDataLoader.tsx, client-react/src/pages/app/functions/new-create-preview/portal-create/TemplateDetail.tsx, client-react/src/pages/app/functions/new-create-preview/portal-create/TemplateList.tsx, client-react/src/pages/app/functions/new-create-preview/useCreateFunction.ts, client-react/src/utils/CommonConstants.ts, client-react/src/utils/rbac-constants.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
[#14565677](https://msazure.visualstudio.com/Antares/_workitems/edit/14565677/)
The new UX is hidden behind a feature flag to be enabled via experimentation by the Azure Portal.
=> [Functions Collateral] Create new Cosmos DB trigger (2)

tools/pipelines/production-build.yml, tools/pipelines/react-pr-test.yml
Fixes [AB#14660613](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/14660613)
=> Update pipeline to use Node 16.X

client-react/src/pages/app/functions/new-create-preview/useCreateFunction.ts
[#14260766](https://msazure.visualstudio.com/Antares/_workitems/edit/14260766)
2<sup>nd</sup> PR to add telemetry to Cosmos DB new resource UX. This adds logging in code added in #6760
=> [Functions Collateral] Add telemetry to Cosmos DB new resource UX (2)

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220722130803194 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220722130803194 to dev

client-react/src/pages/app/change-app-plan/ChangeAppPlanDestinationPlanDetails.tsx, client-react/src/pages/app/change-app-plan/CreateOrSelectPlan.tsx
Fixes [AB#14994141](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/14994141)
=> [Functions migration] Hide pricing tier + auto select new plans

tools/pipelines/production-build.yml, tools/pipelines/react-pr-test.yml
This reverts commit 0b6c9a2748d80ee5585f44ea4092e172c1fb919b.
=> Revert "Update pipeline to use Node 16.X (#6770)"

tools/pipelines/production-build.yml, tools/pipelines/react-pr-test.yml
Reverts Azure/azure-functions-ux#6770
=> Revert "Update pipeline to use Node 16.X"

client-react/src/utils/CommonConstants.ts, client-react/src/utils/scenario-checker/linux-site.environment.ts, client-react/src/utils/scenario-checker/national-cloud.environment.ts
=> Http20 Proxy: remove feature flag and only support in fairfax & mooncake (disable in national)

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220805131103133 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220805131103133 to dev

server/src/stacks/2020-05-01/stacks/function-app-stacks/Node.ts, server/src/stacks/2020-06-01/stacks/function-app-stacks/Node.ts, server/src/stacks/2020-10-01/stacks/function-app-stacks/Node.ts
Related to https://github.com/Azure/azure-functions-nodejs-worker/issues/562
cc @hossam-nasr, @alrod, @lilyjma
=> Unhide Node 18 preview for Functions

server/src/deployment-center/github/github.controller.ts
Added POST call for creating a Repo from Template Repo
=> [Starshot] Add GitHub Template Repo call

client-react/src/pages/app/functions/app-keys/AppKeys.styles.ts, client-react/src/pages/app/functions/app-keys/HostKeys.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> AB#14963624 Show confirmation dialog when deleting host app keys for functionApp

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220812130929633 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220812130929633 to dev

client-react/src/pages/static-app/configuration/ConfigurationDataLoader.tsx
[#15250643](https://msazure.visualstudio.com/Antares/_workitems/edit/15250643)
=> [SWA] Enable config file changes not getting reflected

client-react/src/ApiHelpers/AuthService.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.data.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrDataLoader.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerFormBuilder.ts, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.tsx, client-react/src/utils/CommonConstants.ts
FixesAB#[15215563](https://msazure.visualstudio.com/Antares/_workitems/edit/15215563)
- Set ACR Pull role assignments for system assigned identities that don't have it
- Refactored container form code
=> [DC] Set ACR Pull permission for System Assigned Identities

client-react/src/pages/static-app/configuration/ConfigurationDataLoader.tsx
Cherry-pick of #6816 to release-s194
=> [SWA] Enable config file changes not getting reflected (#6816)

client-react/src/pages/app/functions/common/callout/storageAccountPivot/StorageAccountPivot.tsx
#15268552 [Function Integration] Add Cancel button when creating new storage in add input
Before
After
=> [Function integration][Storage account] Added cancel button

server/src/stacks/2020-10-01/stacks/function-app-stacks/Java.ts, server/src/tests/Stacks/2020-10-01/function-app/validations.ts
This PR add java17 to azure functions stacks API, currently set isPreview and isHidden both to true.
=> add java17

client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Cherry-pick of #6803 to s194 release branch.
=> [Spec Picker] Undo resource string removal (#6803)

client-react/src/pages/app/functions/function/function-editor/FunctionEditorDataLoader.tsx
[AB#15273040](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/15273040)
=> [Function Editor] Metadata does not exist when making a call via the portal

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220819130944120 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220819130944120 to dev

client-react/src/ApiHelpers/ACRService.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrDataLoader.tsx
=> Fix tags/repos in Deployment Center ACR were not showing passed first 100 items; make api call pageable

client-react/src/pages/app/functions/app-keys/HostKeys.tsx, client-react/src/pages/app/functions/app-keys/SystemKeys.tsx
Co-authored-by: Shibani Medhekar <shibanimedhekar@Shibanis-MacBook-Pro.local>
=> MPAC reported bug - fix popup issue where confirm dialog  was not showing up and you were not able to delete any key (#6830)

client-react/src/pages/container-app/log-stream/LogStream.tsx, client-react/src/pages/container-app/xtermHelper.ts
Fix automatically fixable lint errors in /client-react
=> chore: Fix no-extra-boolean-cast lint errors in /client-react

client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.tsx
Fixes [AB#15362743](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/15362743)
=> [DC] Handle when inconsistent data make the version as null/undefined

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220826130602636 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220826130602636 to dev

client-react/src/pages/app/functions/function/function-log/FunctionLogFileStreamDataLoader.tsx
Fixes [AB#14923421](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/14923421)
=> [Function Logs] Opening and closing connections

server/src/stacks/2020-10-01/stacks/function-app-stacks/Java.ts
update java17 `isHidden` to `false` to be visible.
=> update java17 isHidden to false

client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx, client-react/src/pages/app/functions/function/function-editor/FunctionEditorDataLoader.tsx, client-react/src/pages/app/functions/function/function-editor/useFunctionEditorQueries.ts, client-react/src/pages/app/functions/function/function-log/FunctionLogAppInsightsDataLoader.tsx, client-react/src/utils/CommonConstants.ts
Fixes [AB#15193080](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/15193080)
=> [AI Logs] Remove ai experimentation

client-react/src/pages/app/deployment-center/DeploymentCenter.data.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx
Reverts Azure/azure-functions-ux#6822
Customer ran into issue where setting being automatically set causes their image pull to fail. Reverting for now to test separately.
=> Revert "[DC] Set VnetImagePullEnabled for ACR image pulls to true"

client-react/src/pages/app/deployment-center/DeploymentCenter.data.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx
* Revert "[DC] Set VnetImagePullEnabled for ACR image pulls to true (#6822)"
This reverts commit 38b48ba2ba1dbb2a8fdfbb54a3ded578fc3d2032.
* Add back siteStateContext and error message changes
=> [Cherry Pick] Revert "[DC] Set VnetImagePullEnabled for ACR image pulls to true"

server/package-lock.json, server/package.json
- `@types/node` 16.11.56
- `@types/react` 17.0.49
- `@typescript-eslint/eslint-plugin` 5.36.1
- `@typescript-eslint/parser` 5.36.1
- `eslint` 8.23.0
- `gulp-download-stream` 0.0.20
- `swagger-ui-express` 4.5.0
- `typescript` 4.8.2
=> chore: Update /server dependencies

client-react/src/pages/app/deployment-center/DeploymentCenter.data.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx
* Revert "[DC] Set VnetImagePullEnabled for ACR image pulls to true (#6822)"
This reverts commit 38b48ba2ba1dbb2a8fdfbb54a3ded578fc3d2032.
* Add back siteStateContext and error message changes
=> [Cherry Pick][S196] Revert "[DC] Set VnetImagePullEnabled for ACR image pulls to true"

package-lock.json, server/src/stacks/2020-10-01/stacks/web-app-stacks/Golang.ts, server/src/tests/Stacks/2020-10-01/web-app/validations.ts
Fixes [AB#15161736](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/15161736)
=> [Stacks] Add go 1.19 behind hide-key

server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts
Fixes [AB#15404283](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/15404283)
=> Enable AI for .NET7

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220909130928887 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220909130928887 to dev

server/src/stacks/2020-10-01/service/StackService.ts, server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts, server/src/stacks/2020-10-01/stacks/function-app-stacks/Java.ts, server/src/stacks/2020-10-01/stacks/function-app-stacks/Node.ts, server/src/stacks/2020-10-01/stacks/function-app-stacks/Python.ts
Add EOL dates for Functions Stacks as published here - 
https://docs.microsoft.com/en-us/azure/azure-functions/language-support-policy#retirement-policy-exceptions
=> [Functions][Stacks] Add EOL

client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStringsAddEdit.tsx
Fixes [AB#15052407](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/15052407)
=> [Configuration] Fix name, value pair with error-messages

server/Resources/Resources.resx
[#15570636](https://msazure.visualstudio.com/Antares/_workitems/edit/15570636/)
=> Change message about viewing app keys when function app is closed

client-react/src/pages/app/functions/app-keys/AppKeysDataLoader.tsx
[#15570636](https://msazure.visualstudio.com/Antares/_workitems/edit/15570636/)
Message shown after keys could not be fetched
Message not shown if keys were fetched despite the function app being stopped
=> [Functions][CRI] Show message only when keys could not be fetched

server/src/workflows/2022-10-01/WorkflowService.ts
Note: This API version change is not live
=> [Workflow Files] Pass secret names

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220923130611839 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20220923130611839 to dev

client-react/src/pages/app/app-settings/ApplicationSettings/ApplicationSettings.tsx, client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStrings.tsx
Fixes [AB#15628488](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/15628488)
=> [Configuration] Update otherAppSettings sent to AddEdit blade

client-react/src/pages/app/app-settings/ApplicationSettings/ApplicationSettings.tsx, client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStrings.tsx
* fix validation on edit
* update 1
Co-authored-by: Krrish Mittal <takyyon@gabasu-2.redmond.corp.microsoft.com>
=> [Configuration] Update otherAppSettings sent to AddEdit blade (#6888)

client-react/src/utils/CommonConstants.ts, client-react/src/utils/scenario-checker/national-cloud.environment.ts, client-react/src/utils/scenario-checker/windows-code.environment.ts
Fixes ([AB#14124208](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/14124208))[https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s198?workitem=14124208]
Enabe windows code BYOS public preview for national clouds
=> AB#14124208 Liuqi/enable windows code byos preview for national cloud

client-react/src/pages/app/app-settings/AppSettings.service.ts, client-react/src/pages/app/app-settings/AppSettings.types.ts, client-react/src/pages/app/app-settings/AppSettingsFormData.ts, client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMounts.tsx, client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEdit.tsx, client-react/src/utils/CommonConstants.ts
Fixes [AB#10901598](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/S199?workitem=10901598)
Add stick option for BYOS behind the feature flag
=> AB#10901598 Add sticky to BYOS

client-react/src/ApiHelpers/FunctionsService.ts
Co-authored-by: Krrish Mittal <takyyon@Krrishs-MacBook-Pro.local>
=> [CP][FunctionEditor] Remove direct calls to functions (#6901)

client-react/src/pages/app/change-app-plan/ChangeAppPlan.styles.ts, client-react/src/pages/app/change-app-plan/ChangeAppPlanDestinationPlanDetails.tsx, client-react/src/utils/FwLinks.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Solution for ([AB#15269005](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/15269005)) 
Simple info box with a link to documentation on why certain plans do not show up when changing an app plan.
=> AB#15269005 Add info box on why some plans may not show up on Change App Plan blade

client-react/src/pages/app/app-settings/VirtualApplications/VirtualApplicationsAddEdit.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes: [AB#14999778](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/S199?workitem=14999778)
=> AB#14999778 Update virtual directory validation

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20221007131924421 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20221007131924421 to dev

server/src/app.module.ts, server/src/server.ts, server/src/webJobs/webJobs.controller.ts, server/src/webJobs/webJobs.module.ts
* add webjob proxy
* update
* update
* update
* remove unused changes
* add input check
Co-authored-by: Qi Liu <liuqi@microsoft.com>
=> [Hotfix][S198]AB#15716105 Add Webjobs proxy (#6908)

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx, client-react/src/utils/FwLinks.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Solution for: [AB#15163801](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/S199?workitem=15163801)
=> AB#15163801 Inform user that OneDrive/Dropbox will be retired

client-react/src/ApiHelpers/FunctionsService.ts
Reverts Azure/azure-functions-ux#6902
=> Revert "[CP][FunctionEditor] Remove direct calls to functions (#6901)"

client-react/src/ApiHelpers/FunctionsService.ts
Reverts Azure/azure-functions-ux#6901
=> Revert "[FunctionEditor] Remove direct calls to functions"

client-react/src/pages/app/app-settings/VirtualApplications/VirtualApplicationsAddEdit.tsx, server/Resources/Resources.resx
=> Update virtual directory path 

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20221014131017050 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20221014131017050 to dev

client-react/src/models/portal-models.ts, client-react/src/pages/app/functions/function/function-log/FunctionLog.tsx, client-react/src/pages/app/functions/function/function-log/FunctionLogFileStreamDataLoader.tsx, client-react/src/pages/app/log-stream/LogStream.tsx, client-react/src/pages/app/log-stream/LogStreamCommandBar.tsx, client-react/src/pages/app/log-stream/LogStreamData.ts, client-react/src/pages/app/log-stream/LogStreamDataLoader.tsx, client-react/src/pages/app/log-stream/LogStreamLogContainer.tsx, client-react/src/portal-communicator.ts, client-react/src/react-app-env.d.ts, client-react/src/utils/url.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Reverts Azure/azure-functions-ux#6914
=> Revert "AB#15777298 Disable Log for requesting scm host names that are not white listed"

client/src/app/shared/models/portal.ts, client/src/app/shared/no-cors-http-service.ts, client/src/app/shared/services/portal.service.ts, client/src/app/site/console/bash/bash.component.ts, client/src/app/site/console/shared/components/abstract.console.component.ts, client/src/app/site/console/shared/components/abstract.windows.component.ts, client/src/app/site/console/shared/services/console.service.ts, client/src/polyfills/window.ts
Reverts Azure/azure-functions-ux#6916
=> Revert "AB#15829315 Use passthrough for console for untrusted domains"

client-react/src/pages/app/functions/app-files/AppFiles.tsx, client-react/src/pages/app/functions/app-files/AppFilesDataLoader.tsx, client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx, client-react/src/pages/app/functions/function/function-editor/FunctionEditorDataLoader.tsx, client-react/src/pages/app/functions/function/function-editor/useFunctionEditorQueries.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes [AB#15594426](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/15594426)
=> AB #15594426 [Fusion][MSRC] If hostruntime calls return 401 then block users to access source code and show banner

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20221021131144244 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20221021131144244 to dev

client-react/src/pages/app/app-settings/GeneralSettings/stacks/function-app/FunctionAppStackSettings.tsx
Fixes [AB#15808302](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/15808302)
=> [FunctionApp Stacks] Clicking Discard should show the initial values again

client-react/src/models/functions/function-binding.ts, client-react/src/pages/app/functions/function/function-editor/FunctionEditor.data.ts, client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx, client-react/src/pages/app/functions/function/function-editor/FunctionEditorCommandBar.tsx, client-react/src/pages/app/functions/function/function-editor/FunctionEditorDataLoader.tsx, client-react/src/utils/BindingManager.ts
[#14859202](https://msazure.visualstudio.com/Antares/_workitems/edit/14859202/)
[Functions] Rename AuthenticationEventTrigger to AuthenticationEventsTrigger
Related: [!6962659](https://msazure.visualstudio.com/One/_git/AAPT-Antares-AntUX/pullrequest/6962659)
=> [Functions] Rename ... to AuthenticationEventsTrigger

server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts
Resolves Azure/azure-functions-dotnet-worker/issues/1143
=> Removed preview tag from .NET 7 Isolated in Stacks API.

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20221028131332877 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20221028131332877 to dev

client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/JavaStack.tsx, client-react/src/utils/CommonConstants.ts
Fixes [AB#15282951](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/15282951)
=> [Java Stacks] Fix discard and remove redundant code (+ optimize)

client-react/src/ApiHelpers/SiteService.ts, client-react/src/pages/app/app-settings/AppSettings.service.ts, client-react/src/pages/app/app-settings/AppSettingsDataLoader.tsx, client-react/src/utils/CommonConstants.ts
Fixes [AB#15846542](https://msazure.visualstudio.com/Antares/_workitems/edit/15846542)
=> Add flighting to use PATCH instead of PUT for /sites API call in Config UI

client-react/src/pages/app/app-settings/GeneralSettings/LinuxStacks/LinuxStacks.tsx, client-react/src/utils/FwLinks.ts, client-react/src/utils/stacks-utils.tsx
1. Fix the bug that the banner does not show up for initial display.
2. Add a learn more link
=> Update eol banner message and add learn more link

client-react/src/components/CustomCallout/CustomFocusTrapCallout.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterFtps.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterPublishingUser.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
FixesAB#[15737931](https://msazure.visualstudio.com/Antares/_workitems/edit/15737931)
**Before:**
**After:**
=> [DC] Add ability to reset FTPS user-scope credentials

server/src/stacks/2020-10-01/stacks/function-app-stacks/Java.ts
update azure fucntion java17 isPreview to false preparing for GA
=> update azure function java17 isPreview to false

client/src/app/shared/models/serverFarmSku.ts, client/src/app/site/spec-picker/price-spec-manager/isolatedv2-plan-price-spec.ts, client/src/app/site/spec-picker/price-spec-manager/price-spec-group.ts
Post Create Scale up scenario - I updated the blade to show I4v2-I6v2 if the stamp supports it.
Create scale up scenario - I did not add a logic to decide whether we should hide or enable those new SKUs. That will be taken care by new spec picker.
=> 16203032[ASE][Spec] Update old post create scale up blade to display new SKUs

client-react/src/pages/app/functions/function/monitor/tabs/logs/FunctionLogsDataLoader.tsx, client-react/src/pages/app/functions/log-stream/LogStreamDataLoader.tsx
Fixes [AB#15584372](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/15584372)
=> [AI Logs] Update AI Logs to be default

client-react/src/pages/app/functions/function/function-log/FunctionLogCommandBar.tsx
Fixes [AB#16026203](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/16026203)
=> [Accessibility] Remove keyboard trap in logs command bar

server/src/stacks/2020-05-01/stacks/function-app-stacks/Python.ts, server/src/stacks/2020-06-01/stacks/function-app-stacks/Python.ts, server/src/stacks/2020-10-01/stacks/function-app-stacks/Python.ts
Co-authored-by: Krrish Mittal <krrishmittal15@gmail.com>
=> Unhide pythone 3.10 in stack (#6895)

server/src/stacks/2020-06-01/stacks/web-app-stacks/Php.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Php.ts
Fixes [AB#13479923](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/13479923)
=> Deprecate PHP 7.4

client-react/src/pages/app/functions/function/monitor/tabs/entities/FunctionEntities.tsx, client-react/src/pages/app/functions/function/monitor/tabs/orchestrations/FunctionOrchestrations.tsx
Changed Column's order and moved a link from date to Instance Id.
**NOW:**
**BEFORE:**
=> 15492780[Function][Orchestration] change column orders on Orchestration tab

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrDataLoader.tsx
FixesAB#[16473701](https://msazure.visualstudio.com/Antares/_workitems/edit/16473701)
**Before**
**After**
=> [DC] Do not fetch tags for ACR configured with GHA

client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubProvider.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
FixesAB#[16473695](https://msazure.visualstudio.com/Antares/_workitems/edit/16473695)
**Before**
**After**
=> [DC] Create separate placeholder text for github repos

server/src/stacks/2020-10-01/stacks/web-app-stacks/Python.ts, server/src/tests/Stacks/2020-10-01/web-app/validations.ts
Removing hide-key for Python 3.11
=> Removed hide key for Python 311

server/src/stacks/2020-10-01/stacks/web-app-stacks/Python.ts
* Removed hide key for Python 311
* Changing the validation test
=> Removed hide key for Python 311 (#6996)

client-react/src/portal-communicator.ts
Fixes [AB#16563548](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/16563548)
=> Add build version to console

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20221209141734471 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20221209141734471 to dev

server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts
Fixes [AB#16573527](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/16573527)
=> AB#16573527 [WebApps] Make AI on by default on stacks API for .Net7 Linux

client-react/package-lock.json
=> Update express to 4.18.2 in /client-react

server/src/stacks/2020-06-01/stacks/web-app-stacks/DotnetCore.ts, server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts
Fixes [AB#10469468](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/10469468)
=> Deprecate .NET 3.1

server/src/stacks/2020-06-01/stacks/web-app-stacks/DotnetCore.ts, server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts
Co-authored-by: Krrish Mittal <takyyon@Krrishs-MacBook-Pro.local>
=> Deprecate .NET 3.1 (#7012)

client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx, client-react/src/pages/app/functions/function/function-editor/useFunctionEditorQueries.ts
Added Node new programing model check. (At this point, we offer new programming model for Python and Node)
**BEFORE:**
**AFTER:**
Now, we can load the files.
=> 16474667Fix the broken view experience for Node new programming model

client-react/src/pages/app/app-settings/Sections/PathMappingsPivot.tsx, client-react/src/pages/app/app-settings/VirtualApplications/VirtualApplicationsAddEdit.tsx, client-react/src/utils/CommonConstants.ts, client-react/src/utils/scenario-checker/container.environment.ts, client-react/src/utils/scenario-checker/linux-site.environment.ts, client-react/src/utils/scenario-checker/scenario-ids.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes [AB#14120821](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s205?workitem=14120821)
1. remove (preview) title from mount storage title
2. unhide virtual path validations
=> AB#14120821 GA windows byos

client-react/src/pages/app/change-app-plan/ChangeAppPlan.types.ts, client-react/src/pages/app/change-app-plan/ChangeAppPlanDestinationPlanDetails.tsx, client-react/src/pages/app/change-app-plan/CreateOrSelectPlan.tsx
Fixes [AB#16675298](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/16675298)
=> [Change ASP]Change App Service plan doesn't update Pricing Tier when selecting new

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20230106141034299 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20230106141034299 to dev

client-react/src/ApiHelpers/FunctionsService.ts, client-react/src/models/functions/function-config.ts, client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx, client-react/src/pages/app/functions/function/function-editor/useFunctionEditorQueries.ts, client-react/src/utils/CommonConstants.ts
Set fine name specified in `scriptFIle` property as default
=> 16474741Show a default file for Node inside a Function

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20230113140921078 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20230113140921078 to dev

client-react/src/utils/stacks-utils.tsx
=> [Stacks] Update EOL messaging on Config to 6 months from 60 days

client-react/src/pages/app/deployment-center/github-provider/DeploymentCenterGitHubDataLoader.tsx, server/Resources/Resources.resx
Fixes [AB#16793983](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/16793983)
Before:
After:
=> [GHA] Filtering for repository write access

server/src/stacks/2020-10-01/stacks/function-app-stacks/Node.ts
Related to https://github.com/Azure/azure-functions-nodejs-worker/issues/562
cc @hossam-nasr, @lilyjma
=> Mark Node 18 as GA for Azure Functions

server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20230120013642918 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20230120013642918 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20230120141332342 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20230120141332342 to dev

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx
FixesAB#[16025737](https://msazure.visualstudio.com/Antares/_workitems/edit/16025737)
- Happening only in CodeForm 
- onClick was not being triggered from Enter keypress due to a function preventing default behavior
=> [DC][Accessibility] Enable enter keypress for onClick

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceAndBuild.tsx, client-react/src/utils/FwLinks.ts
FixesAB#[16869143](https://msazure.visualstudio.com/Antares/_workitems/edit/16869143)
=> [DC] Replace source and build learn more link documentation

client-react/src/pages/static-app/configuration/ConfigurationGeneralSettings.tsx, server/Resources/Resources.resx
Fixes [AB#16773715](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/16773715) -- Should be using the checkbox for instead of toggles for settings 
Fixes [AB#16773737](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/16773737) -- Password should not be shown if user select disabled password protection
Fixes [AB#16783363](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/16783363) -- Copy for staging environments should all be preview environments
Before:
After:
=> [SWA] SWA configuration changes

client-react/src/pages/app/change-app-plan/ChangeAppPlanDestinationPlanDetails.tsx
Fixes [AB#14994169](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/14994169)
Before:
After:
=> [Change App Plan] Change 'Plan type' to dropdown

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20230127141357451 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20230127141357451 to dev

client-react/src/pages/app/functions/function/function-editor/FunctionEditorDataLoader.tsx
Fixes [AB#16747040](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/16747040)
=> [Functions Code+Test] Fallback on runFromPassthrough if runFromPortal Fails

server/src/stacks/2020-10-01/stacks/web-app-stacks/Php.ts
* unhide php
* remove extra file commit
---------
Co-authored-by: Krrish Mittal <takyyon@Krrishs-MacBook-Pro.local>
=> Unhide PHP 8.2 on linux  (#7063)

server/src/constants.ts, server/src/deployment-center/azure-dev-ops/azure-dev-ops.controller.ts
FixesAB#[16976804](https://msazure.visualstudio.com/Antares/_workitems/edit/16976804)
- Validating url for now for MSRC case with plans to completely remove API in March
=> [DC] Validate url for api/setupvso

client-react/src/ApiHelpers/GitHubService.ts, client-react/src/pages/app/deployment-center/DeploymentCenterConstants.ts, server/src/deployment-center/github/github.controller.ts
Fixes [AB#16968264](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/16968264)
=> Dispatch workflow call url should be created on server-side

server/src/staticsites/staticsites.controller.ts, server/src/staticsites/staticsites.ts
[AB#15071032](https://msazure.visualstudio.com/Antares/_workitems/edit/15071032)
=> adding api/staticsites/github/callback APIs

client-react/src/pages/app/deployment-center/DeploymentCenter.styles.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodePivot.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterVSTSCodeLogs.tsx, client-react/src/pages/app/deployment-center/devops-provider/DeploymentCenterVstsBuildConfiguredView.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Task#[16877804](https://msazure.visualstudio.com/Antares/_workitems/edit/16877804)
**Before:**
**After:**
Settings Tab:
Logs Tab:
=> [DC] Add back React Deployment Center support for DevOps configured view

client-react/src/pages/App.tsx, client-react/src/pages/container-app/ContainerAppEnvironmentRouter.tsx, client-react/src/pages/container-app/ContainerAppRouter.tsx
* Logstream for Events in CA
* Fix container app environment log stream
* PR comments
=> [ContainerApp][LogStream] Add Events (#7057)

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeLogs.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterGitHubActionsCodeLogs.tsx
=> [DC] Make message column in code logs multiline and fix GHA messages

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20230203141035783 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20230203141035783 to dev

package-lock.json
[#16878397](https://msazure.visualstudio.com/Antares/_workitems/edit/16878397/)
=> chore: Update cookiejar to 2.1.4 in /

client-react/package-lock.json
[#16878397](https://msazure.visualstudio.com/Antares/_workitems/edit/16878397/)
- `json5` 1.0.2
- `ua-parser-js` 0.7.33
=> chore: Update dependencies in /client-react

server/package-lock.json
[#16878397](https://msazure.visualstudio.com/Antares/_workitems/edit/16878397/)
- `cookiejar` 2.1.4
- `json5` 1.0.2
=> chore: Update dependencies in /server

server/src/workflows/2022-10-01/container-configs/container-functions-linux.config.yml, server/src/workflows/2022-10-01/container-configs/container-webapp-linux.config.yml
This is not a live change -- these workflow files are in the new version and are only being used for internal testing.
=> [Workflow] Change container id-token permission placement

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20230217141727518 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20230217141727518 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20230224141349994 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20230224141349994 to dev

client-react/src/pages/app/app-settings/GeneralSettings/stacks/function-app/FunctionAppStackSettings.tsx
Fixes [AB#16631394](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/16631394)
=> Hide function app stack settings for Windows

client-react/src/components/CipherSuite/MinTLSCipherSuiteSelector.tsx, client-react/src/utils/CommonConstants.ts, client-react/src/utils/scenario-checker/elastic-premium.environment.ts, client-react/src/utils/scenario-checker/premium.environment.ts, client-react/src/utils/scenario-checker/workflow-app.environment.ts
=> Set min cipher suite config to empty if least secure; remove FF

server/Resources/Resources.resx
FixesAB#[17283756](https://msazure.visualstudio.com/Antares/_workitems/edit/17283756)
**Before**
**After**
=> [DC] Fix typo in container registry sources

client-react/src/pages/container-app/log-stream/LogStream.tsx
fixes [AB#16833234](https://msazure.visualstudio.com/Antares/_workitems/edit/16833234)
=> prevent focus trap in container app logstream UI

client-react/src/pages/container-app/log-stream/LogStream.tsx
fixes [AB#16833234](https://msazure.visualstudio.com/Antares/_workitems/edit/16833234)
=> [CP] prevent focus trap in container app logstream UI

client-react/src/pages/app/app-settings/AppSettings.types.ts, client-react/src/pages/app/app-settings/AppSettingsForm.tsx, client-react/src/utils/CommonConstants.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> [Custom Error Page] Feature flag and Tab

client-react/src/models/site/config.ts, client-react/src/pages/app/app-settings/AppSettingsForm.tsx, client-react/src/pages/app/app-settings/ErrorPages/ErrorPageGrid.contract.tsx, client-react/src/pages/app/app-settings/ErrorPages/ErrorPageGrid.tsx, client-react/src/pages/app/app-settings/Sections/ErrorPage.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> [Custom Error Page] Grid

client-react/src/pages/app/functions/function/function-editor/FunctionEditorDataLoader.tsx, client-react/src/pages/app/functions/function/function-editor/function-test/FunctionTest.tsx
* remove response headers in proxy call
* remove redirects
* add back headers
* fix portal test_data
* fetch from jqxhr
---------
=> Fix test_data response via portal (#7108)

client-react/src/pages/app/app-settings/AppSettingsDataLoader.tsx, client-react/src/pages/app/app-settings/AppSettingsForm.tsx, client-react/src/utils/scenario-checker/function-app.environment.ts, client-react/src/utils/scenario-checker/premium.environment.ts, client-react/src/utils/scenario-checker/scenario-ids.ts, client-react/src/utils/scenario-checker/workflow-app.environment.ts, server/Resources/Resources.resx
Web Apps and premium plans only
=> [Custom Error Pages] Scenario check

server/src/stacks/2020-10-01/stacks/web-app-stacks/Php.ts
Fixes [AB#17389347](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/17389347)
=> [GHA] Support PHP 8 in Creates

client-react/src/pages/static-app/configuration/ConfigurationPivot.tsx, client-react/src/utils/CommonConstants.ts
Hiding snippets while some API updates get made.
=> [SWA] Hide snippets

client-react/src/pages/app/app-settings/AppSettingsForm.tsx, client-react/src/utils/CommonConstants.ts, server/Resources/Resources.resx
=> [Custom Error Pages] flighting and description

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20230317131623525 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20230317131623525 to dev

client-react/package-lock.json, client-react/src/models/site/config.ts, client-react/src/pages/app/app-settings/AppSettings.service.ts, client-react/src/pages/app/app-settings/AppSettings.styles.ts, client-react/src/pages/app/app-settings/AppSettings.types.ts, client-react/src/pages/app/app-settings/AppSettingsFormData.ts, client-react/src/pages/app/app-settings/ApplicationSettings/AppSettingAddEdit.tsx, client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStringsAddEdit.tsx, client-react/src/pages/app/app-settings/KeyVaultReferenceComponent.tsx, client-react/src/pages/app/app-settings/ReferenceComponent.tsx, client-react/src/pages/app/app-settings/SettingSourceColumn.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Work items: [#17645493]( https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s211?workitem=17645493), [#14130342](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s211?workitem=14130342)
=> App config API icon and clean Up

client-react/src/components/UpsellBanner/UpsellBanner.tsx, client-react/src/pages/app/app-settings/AppSettings.tsx, client-react/src/pages/app/app-settings/AppSettingsDataLoader.tsx, client-react/src/pages/app/app-settings/AppSettingsForm.tsx, client-react/src/pages/app/app-settings/ApplicationSettings/ApplicationSettings.tsx, client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMounts.tsx, client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStrings.tsx, client-react/src/pages/app/app-settings/ErrorPages/ErrorPageGrid.styles.ts, client-react/src/pages/app/app-settings/ErrorPages/ErrorPageGrid.tsx, client-react/src/pages/app/app-settings/HandlerMappings/HandlerMappings.tsx, client-react/src/pages/app/app-settings/Sections/ErrorPage.tsx, client-react/src/pages/app/app-settings/VirtualApplications/VirtualApplications.tsx, client-react/src/pages/app/functions/app-keys/HostKeys.tsx, client-react/src/pages/app/functions/app-keys/SystemKeys.tsx, client-react/src/pages/app/functions/function/function-keys/FunctionKeys.tsx, client-react/src/pages/static-app/configuration/Configuration.tsx, client-react/src/pages/static-app/configuration/ConfigurationSnippets.tsx, client-react/src/utils/scenario-checker/premium.environment.ts, client-react/src/utils/scenario-checker/scenario-ids.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Upsell message custom error page [#17559414](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s211?workitem=17559414)
=> [custom error pages] upsell

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx, client-react/src/pages/app/deployment-center/devops-provider/DeploymentCenterVstsBuildConfiguredView.tsx, client-react/src/pages/app/deployment-center/devops-provider/DeploymentCenterVstsDisconnect.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
FixesAB#[17642865](https://msazure.visualstudio.com/Antares/_workitems/edit/17642865)
- Note: We modify scmType to None instead of deleting source controls because Azure Pipelines info is not stored in source controls
**Before**
**After**
=> [DC] Add disconnect button for DevOps configured apps

client-react/src/ApiHelpers/TagsService.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrDataLoader.tsx, client-react/src/utils/dependency/Dependency.ts
FixesAB#[17561073](https://msazure.visualstudio.com/Antares/_workitems/edit/17561073 )and [17561089](https://msazure.visualstudio.com/Antares/_workitems/edit/17561089)
=> [DC] Fix updating and deleting hidden ACR tags

client-react/src/ApiHelpers/TagsService.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrDataLoader.tsx, client-react/src/utils/dependency/Dependency.ts
Cherry picking hidden ACR tag changes
=> [CP][DC] Fix updating and deleting hidden ACR tags (#7134)

client-react/package-lock.json, client-react/package.json, client-react/src/components/form-controls/RadioButtonNoFormik.tsx, client-react/src/pages/container-app/console/ConsoleDataLoader.tsx
Fixes [AB#17520404](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/17520404)
=> Updating Fluent UI version 

client-react/src/components/DisplayTableWithCommandBar/DisplayTableWithCommandBar.tsx, client-react/src/pages/app/SiteRouter.tsx, client-react/src/pages/app/app-settings/AppSettingsCommandBar.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterCommandBar.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCommitLogs.tsx, client-react/src/pages/app/deployment-center/publish-profile/DeploymentCenterPublishProfileCommandBar.tsx, client-react/src/pages/app/functions/app-files/AppFilesCommandBar.tsx, client-react/src/pages/app/functions/app-keys/AppKeysCommandBar.tsx, client-react/src/pages/app/functions/function/function-editor/FunctionEditorCommandBar.tsx, client-react/src/pages/app/functions/function/function-keys/FunctionKeysCommandBar.tsx, client-react/src/pages/app/functions/function/integrate/BindingPanel/EditBindingCommandBar.tsx, client-react/src/pages/app/functions/function/integrate/FunctionIntegrateCommandBar.tsx, client-react/src/pages/app/log-stream/LogStreamCommandBar.tsx, client-react/src/pages/container-app/ContainerAppEnvironmentRouter.tsx, client-react/src/pages/container-app/ContainerAppRouter.tsx, client-react/src/pages/logic-app/LogicAppRouter.tsx, client-react/src/pages/static-app/StaticSiteRouter.tsx, client-react/src/pages/static-app/configuration/ConfigurationCommandBar.tsx
Fixes [AB#17549640](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/17549640)
Edit: Going to actually go ahead and fix this one too
Fixes [AB#17549672](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/17549672)
=> Fix accessibility issue with <main>

client-react/src/pages/app/app-settings/ApplicationSettings/ApplicationSettings.tsx, client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMounts.tsx, client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStrings.tsx, client-react/src/pages/app/app-settings/ErrorPages/ErrorPageGrid.tsx, client-react/src/pages/app/app-settings/HandlerMappings/HandlerMappings.tsx, client-react/src/pages/app/app-settings/VirtualApplications/VirtualApplications.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Work item[ #17487332](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s212?workitem=17487332)
=> [Accessibility Bug] [Configuration] Screen reader table announcements

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20230411231654799 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20230411231654799 to dev

client-react/src/pages/app/functions/new-create-preview/portal-create/TemplateList.tsx, client-react/src/pages/app/functions/new-create-preview/portal-create/useTemplateListColumns.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
[AB#17979057](https://dev.azure.com/msazure/Antares/_workitems/edit/17979057/)
Add "View Template" column to template list in Create Function.
- The new column should be used for the new programming model only.
- Hide the new column behind the `enableNewProgrammingModel` feature flag.
=> [Functions][Python] Add column to template list in Create Function

client-react/src/components/ConfirmDialog/ConfirmDialog.styles.ts, client-react/src/components/ConfirmDialog/ConfirmDialog.tsx
Fixes [AB#18330962](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/18330962)
Before:
After:
=> Fix Dialog footer

client-react/src/utils/CommonConstants.ts, client-react/src/utils/arm-utils.ts, client/src/app/shared/services/scenario/function-app.environment.ts
[18447743](msazure.visualstudio.com/Antares/_workitems/edit/18447743)
=> [Scenario Checker] new premium SKU's

client-react/src/pages/app/functions/function/hooks/useSiteConfigQuery.ts, client-react/src/pages/app/functions/new-create-preview/portal-create/TemplateList.tsx, client-react/src/pages/app/functions/new-create-preview/portal-create/useTemplateListColumns.tsx, client-react/src/pages/app/functions/new-create-preview/useProgrammingModel.tsx
[AB#17979057](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/17979057), [AB#18600483](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/18600483)
Remove "View Template" column.
- Enable v2 programming model for Python only and remove version check.
=> [Functions][Python] Remove View Template column

client-react/src/pages/app/deployment-center/DeploymentCenterFormBuilder.ts, client-react/src/pages/app/deployment-center/DeploymentCenterFtps.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeDataLoader.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeFormBuilder.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceAndBuild.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerDataLoader.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerFormBuilder.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSource.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
FixesAB#[19539728](https://msazure.visualstudio.com/Antares/_workitems/edit/19539728)
**After:**
Code Scenario
Container Scenario
=> [DC] Add error message and validation for basic auth

client-react/src/ApiHelpers/FunctionsService.ts, client-react/src/models/functions/function-template-v2.ts, client-react/src/pages/app/functions/new-create-preview/FunctionCreateDataLoader.tsx, client-react/src/pages/app/functions/new-create-preview/portal-create-v2/FormContainer.tsx, client-react/src/pages/app/functions/new-create-preview/portal-create-v2/useAppSettingsMutator.ts, client-react/src/pages/app/functions/new-create-preview/portal-create-v2/useFields.ts, client-react/src/pages/app/functions/new-create-preview/portal-create-v2/useFileMutator.ts, client-react/src/pages/app/functions/new-create-preview/portal-create-v2/useFormContainer.ts, client-react/src/pages/app/functions/new-create-preview/portal-create-v2/useFunctionCreator.ts, client-react/src/pages/app/functions/new-create-preview/useCreateFunction.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
[AB#19996457](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/19996457), [AB#19990692](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/19990692), [AB#19702064](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/19702064)
=> [Functions][Python] Make new function from user prompts and selected template (+2)

server/src/deployment-center/github/github.controller.ts
Fixes [AB#22531347](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/22531347)
=> Add Github Api to add variable

client-react/src/components/CustomPanel/CustomPanel.tsx, client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx
Fixes [AB#17520404](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/17520404)
=> Panel update

client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx, client-react/src/pages/app/functions/function/function-editor/FunctionEditorFileSelectorBar.tsx, client-react/src/pages/app/functions/function/function-editor/useFunctionEditorQueries.ts
[AB#22113812](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/22113812)
List app files when viewing .NET Isolated functions:
- Show function app name only in the file selector bar.
- Show `functions.metadata` by default.
**Screenshot**
=> [Functions] Fix code editor for .NET Isolated functions

server/src/workflows/workflow.controller.ts
* add variable api (#7201) (#7202)
* add api
---------
=> Add getAndCreateWorkflow file api (#7215)

server/package-lock.json, server/package.json, server/src/data/data/frameworks.json, server/src/deployment-center/github/github.controller.ts
=> Add Frameworks detection api

client-react/src/pages/app/functions/new-create-preview/useProgrammingModel.tsx
[AB#23673425](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/23673425)
Remove feature flag hiding the v2 programming model Create Function UI for Python.
Improve legibility of programming model dropdown when disabled.
Light
Dark
=> [Functions][Python] Remove feature flag hiding v2 Create Function UI

client-react/src/pages/app/app-settings/GeneralSettings/stacks/function-app/FunctionAppStackSettings.tsx
Fixes [AB#7826738](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/7826738)
=> Function app settings shouldn't be visible for Linux function container app

client-react/src/pages/app/app-settings/ApplicationSettings/ApplicationSettings.tsx, client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMounts.tsx, client-react/src/pages/app/app-settings/ConnectionStrings/ConnectionStrings.tsx, client-react/src/pages/app/app-settings/HandlerMappings/HandlerMappings.tsx, client-react/src/pages/app/app-settings/VirtualApplications/VirtualApplications.tsx
Fixes [AB#21955114](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/21955114)
Fixes [AB#18144245](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/18144245)
Fixes [AB#17948392](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/17948392)
Before:
After:
=> Fix dirty state styling

server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20230602130937332 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20230602130937332 to dev

client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEdit.tsx, client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEditBasic.tsx, server/Resources/Resources.resx
Fixes [AB#24126320](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/24126320)
=> [AB#24126320][BYOS] Filter NFS storage file shares for linux only

client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEdit.tsx, client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEditBasic.tsx
Reverts Azure/azure-functions-ux#7232
=> Revert "[AB#24126320][BYOS] Filter NFS storage file shares for linux only"

client-react/src/pages/app/functions/new-create-preview/useProgrammingModel.tsx
Do not show v2 Create Function UI in national clouds.
=> [Functions] Put back feature flag hiding v2 Create Function UI

tools/pipelines/production-build.yml
Fixes [AB#17409977](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/17409977)
=> Update loc system to use feed instead of PAT

client-react/src/pages/static-app/configuration/ConfigurationAddEdit.tsx
Fixes [AB#24215915](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/24215915)
=> [SWA] Add required label

client/src/app/site/slots/deployment-slots/deployment-slots.component.ts
fixes [AB#24388169](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/24388169)
=> updating slots UI to open FunctionAppOverview.ReactView and AppsOverview.ReactView instead of AppsOverviewBlade

client-react/src/pages/app/functions/function/function-log/FunctionLogAppInsightsDataLoader.tsx
Fixes [AB#24128947](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/24128947)
=> Add exception message

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20230630131222299 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20230630131222299 to dev

server/package-lock.json, server/package.json, server/src/deployment-center/github/github.controller.ts
Removing this as the feed isn't global but specific to public cloud
=> Remove framework detect api

client-react/src/pages/app/app-settings/GeneralSettings/Platform.tsx, server/Resources/Resources.resx
[#24298456](https://msazure.visualstudio.com/Antares/_workitems/edit/24298456)
Before:
After:
=> [Configuration] Basic Auth and FTP State controls

client-react/src/pages/app/functions/new-create-preview/useProgrammingModel.tsx
[AB#24403064](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/24403064)
=> [Functions] Remove feature flag for GA Python new programming model

client-react/src/models/hostingEnvironment/hosting-environment.ts, client-react/src/pages/app/change-app-plan/ChangeAppPlanDestinationPlanDetails.tsx
[Bug 21870997](https://msazure.visualstudio.com/Antares/_workitems/edit/21870997): [Change ASP][ASE] Change ASP shows both Linux and Windows plans for ASE
=> [ASE] Filter out server farms with different OS

package-lock.json
=> chore: Update dependencies in /

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20230714131223732 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20230714131223732 to dev

server/src/stacks/2020-10-01/stacks/web-app-stacks/Node.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Python.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Ruby.ts, server/src/tests/Stacks/2020-10-01/web-app/validations.ts
Fixes [AB#24508080](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/24508080)
Fixes [AB#24508118](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/24508118)
Fixes [AB#24508170](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/24508170)
=> Deprecate EOL Stacks 

client-react/src/components/InfoTooltip/InfoTooltip.tsx
Fixes [AB#24198494](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/24198494)
=> Fix Accessibility issues on Tooltip

client-react/src/models/site/config.ts, client-react/src/models/site/site.ts, client-react/src/pages/app/app-settings/AppSettings.tsx, client-react/src/pages/app/app-settings/GeneralSettings/Platform.tsx, client-react/src/utils/scenario-checker/scenario-ids.ts, client-react/src/utils/scenario-checker/workflow-app.environment.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes [AB#19451752](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/19451752)
Logic App
Function App
Web App
=> Add Vnet Port prop for LA

client-react/src/pages/app/functions/function/function-editor/FunctionEditorDataLoader.tsx
Fixes [AB#24520881](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/24520881)
=> [Code+Test] Run 1x

server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts, server/src/tests/Stacks/2020-10-01/function-app/validations.ts
Reverts Azure/azure-functions-ux#7300
=> Revert "updating Functions .NET EOLs and preparing for .NET 8 isolated"

server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts, server/src/tests/Stacks/2020-10-01/function-app/validations.ts
Reverts Azure/azure-functions-ux#7304
=> Revert "Revert "updating Functions .NET EOLs and preparing for .NET 8 isolated""

client/src/app/shared/models/constants.ts, client/src/app/shared/validators/slotNameValidator.ts, server/Resources/Resources.resx
* update validation
* slot name validation update to show the characters correctly
* add return
* unstage changes
---------
=> [Hotfix] Update slot name validation message to support utf-32 character. (#7303)

client-react/src/ApiHelpers/ContainerAppService.ts, client-react/src/utils/CommonConstants.ts
Updating an instance of 2022-11-01-preview to 2023-04-01-preview
=> AB#24595371 [ACA] [Ibiza] Retirement of API versions 2022-06-01-preview and 2022-11-01-preview

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20230728131346178 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20230728131346178 to dev

server/src/functions/functions.controller.ts, server/src/shared/resourceDescriptors.ts
Fixes [AB#24698415](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/24698415)
=> [MSRC] Make the resourceId check strict for function apis

client-react/src/pages/app/app-settings/AzureStorageMounts/AzureStorageMountsAddEditAdvanced.tsx, client-react/src/utils/CommonConstants.ts, server/Resources/Resources.resx
Fixes: [AB#24735275](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/UX/s220?workitem=24735275)
=> AB#24735275 Roll out BYOS keyvault support on public azure

server/src/functions/functions.controller.ts
* update 1
* remove log
---------
=> [Cherry-pick] ResourceId can be either function or site level (#7321)

client/src/app/shared/models/arm/site.ts, client/src/app/site/slots/add-slot/add-slot.component.ts
Fixes [AB#17643905](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/17643905)
=> include publicNetworkAccess property when creating a new slot

client-react/src/pages/static-app/configuration/Configuration.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes [AB#24189056](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/24189056)
=> [SWA][Config] Add App Settings checkbox aria labels

client-react/src/utils/i18n.ts, server/gulpfile.js
Fixes [AB#24821331](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/24821331)
=> Fix localization issue where it is not picking up different langs

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20230811130612603 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20230811130612603 to dev

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrDataLoader.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSettings.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.tsx
This reverts commit 46cda8d02b64250ddbc12526e4666ce038d0a531.
=> Revert "[DC] Show cross-sub ACR with no read access as private registry (#7320)"

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20230825131639990 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20230825131639990 to dev

client/src/app/site/console/console.component.scss
Fixes [AB#17534541](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/17534541)
=> [Accessibility] Fix the blinking cursor for high contrast themes

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerPivot.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSource.tsx, client-react/src/pages/app/deployment-center/devops-provider/DeploymentCenterVstsBuildConfiguredView.tsx, client-react/src/pages/app/deployment-center/devops-provider/DeploymentCenterVstsBuildProvider.tsx, client-react/src/pages/app/deployment-center/devops-provider/DeploymentCenterVstsDisconnect.tsx, client-react/src/utils/FwLinks.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
FixesAB#[24887476](https://msazure.visualstudio.com/Antares/_workitems/edit/24887476 ) and [24906210](https://msazure.visualstudio.com/Antares/_workitems/edit/24906210
)
**Before**
**After**
=> [DC] Show DevOps configured view for container app services and add links to DevOps portal

server/src/stacks/2020-10-01/stacks/function-app-stacks/Node.ts
But make sure Node 18 stays the default.
=> Unhide Node 20 preview for functions

client/src/app/site/console/shared/templates/abstract.console.component.html
Fixes [AB#17536554](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/17536554)
=> [Accessibility] Prevent Azure message callout using keyboard navigation

client-react/src/pages/static-app/configuration/ConfigurationPivot.tsx, client-react/src/pages/static-app/configuration/ConfigurationSnippetAddEditForm.tsx, client-react/src/pages/static-app/configuration/ConfigurationSnippets.tsx, client-react/src/utils/CommonConstants.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes [AB#24595669](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/24595669)
Fixes [AB#17869607](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/17869607)
=> enable snippets + fixes

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20230915131220718 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20230915131220718 to dev

server/package.json
Address the `dicer` High severity security vulnerabilities with this PR and #7387.
=> [MQ] Remove redundant dependency on `multer`

server/src/stacks/2020-10-01/stacks/web-app-stacks/Php.ts
Fixes [AB#25213366](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/25213366)
=> [Stacks] Update EOL dates for PHP 

server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts
Fixes [AB#25266902](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/25266902)
=> [Functions] Unhide .NET8 on Windows

client-react/src/pages/app/app-settings/GeneralSettings/Platform.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
[#25265842](https://msazure.visualstudio.com/Antares/_workitems/edit/24298456/?workitem=25265842)
Before: 
After:
=> [Web Apps][Configuration] FTP disabled read from the API than to show disabled

server/Resources/Resources.resx
Fixes [AB#25246708](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/25246708)
=> [Configurations] Update Affinity string

client-react/src/pages/app/deployment-center/DeploymentCenter.styles.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrDataLoader.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrSettings.tsx
- Content in ComboBox Footer must not be interactive for accessibility
**Before**
**After**
=> [DC] Use ManagedIdentitiesDropdown for ACR

client-react/src/ApiHelpers/AuthService.ts, client-react/src/ApiHelpers/ManagedIdentityService.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.data.ts, client-react/src/pages/app/deployment-center/DeploymentCenterFormBuilder.ts, client-react/src/pages/app/deployment-center/authentication/DeploymentCenterAuthenticationSettings.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerForm.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
- Turned authType field from ComboBox to RadioButton
- No longer show Identity dropdown and just create new identity each time
- Make basic auth the default, and make user-assigned identity preview
=> [DC] Make authType field radio buttons and auto create identity

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerAcrSettings.tsx
FixesAB#[25401354](https://msazure.visualstudio.com/Antares/_workitems/edit/25401354)
=> [DC] Fix visibility of identities dropdown in ACR settings

server/src/workflows/2020-12-01/function-app-configs/node-linux.config.yml, server/src/workflows/2020-12-01/function-app-configs/node-windows.config.yml, server/src/workflows/2020-12-01/web-app-configs/node-linux.config.yml, server/src/workflows/2020-12-01/web-app-configs/node-windows.config.yml, server/src/workflows/2022-10-01/function-app-configs/node-linux.config.yml, server/src/workflows/2022-10-01/function-app-configs/node-windows.config.yml, server/src/workflows/2022-10-01/web-app-configs/node-linux.config.yml, server/src/workflows/2022-10-01/web-app-configs/node-windows.config.yml
Fixes [AB#23044549](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/23044549)
=> Update setup node version

server/src/stacks/2020-10-01/stacks/web-app-stacks/Php.ts
Fixes [AB#24839475](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/24839475)
=> AB#24839475 EOL for PHP 8.1 (Nov 26/2023)

server/src/functions/functions.service.ts
=> [Functions] Update header to remove arm token

server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts
Fixes [AB#25434583](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/25434583)
=> [Stacks] Update ssh flag for linux dotnet web apps

client-react/src/models/site/site.ts, client-react/src/models/stacks/app-stacks.ts, client-react/src/pages/app/app-settings/AppSettingsDataLoader.tsx, client-react/src/pages/app/app-settings/GeneralSettings/LinuxStacks/LinuxStacks.data.ts, client-react/src/pages/app/app-settings/GeneralSettings/LinuxStacks/LinuxStacks.tsx, client-react/src/pages/app/app-settings/GeneralSettings/Platform.tsx, client-react/src/pages/app/app-settings/Hooks/useStacks.ts, client-react/src/utils/scenario-checker/function-app.environment.ts, client-react/src/utils/scenario-checker/kube-app.environment.ts, client-react/src/utils/scenario-checker/linux-site.environment.ts, client-react/src/utils/scenario-checker/scenario-ids.ts, client-react/src/utils/scenario-checker/workflow-app.environment.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes [AB#25434718](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/25434718)
Not visible for Windows Web app
Not visible for Linux Function App
Enabled and Visible for Linux Web App
Disabled but Visible for Linux Web App on unsupported Stack Version
=> Add control for Enabling/Disabling SSH on Linux web apps

server/src/stacks/2020-10-01/stacks/web-app-stacks/Golang.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Node.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Php.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Python.ts
Fixes [AB#25496835](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/25496835)
=> Added support disableSsh to Go, Node, Php and Python

client-react/src/pages/app/deployment-center/DeploymentCenterCommandBar.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodePivot.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerPivot.tsx
Task#[25261524](https://msazure.visualstudio.com/Antares/_workitems/edit/25261524) 
**Before**
**After**
**Code**
**Container**
=> [DC] Disable manage publish profile button and hide ftps tab if basic auth is disabled

client-react/src/pages/app/functions/function/function-log/FunctionLogAppInsightsDataLoader.tsx
Fixes [AB#25407766](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/25407766)
=> function name

client-react/src/pages/static-app/configuration/Configuration.types.ts, client-react/src/pages/static-app/configuration/ConfigurationForm.tsx, client-react/src/pages/static-app/configuration/ConfigurationPivot.tsx, client-react/src/utils/CommonConstants.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes [AB#25484755](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/25484755)
=> AB#25484755 Add banner to Configuration blade that App Settings moved to Environment variables and hide App Settings Pivot for the experiment

server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20231013131021040 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20231013131021040 to dev

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSource.tsx
Fixes [AB#25379997](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/25379997)
=> [DC] Show Basic Auth for ACR

client-react/src/pages/app/app-settings/GeneralSettings/Platform.tsx
Fixes: [AB#24902438](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/Germanium/CY23Q4/2Wk/2Wk02%20(Oct%2008%20-%20Oct%2021)?workitem=24902438)
=> AB#24902438 Update Http2.0Proxy enabled value to 2

server/src/stacks/2020-10-01/stacks/web-app-stacks/Golang.ts, server/src/tests/Stacks/2020-10-01/web-app/validations.ts
Fixes [AB#25535734](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/25535734)
=> Deprecate GoLang

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20231027131000464 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20231027131000464 to dev

server/Resources/Resources.resx
Fixes [AB#25221257](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/25221257)
=> [Configuration] Update on save dialog box message

client-react/src/pages/app/functions/function/function-log/FunctionLogAppInsightsDataLoader.tsx
Reverts Azure/azure-functions-ux#7437
=> Revert "function name"

client-react/src/pages/app/functions/function/function-log/FunctionLogAppInsightsDataLoader.tsx
This reverts commit bd51b53a7bb34bfc32b7e002221716866e055560.
=> Revert "function name (#7437)" (#7457)

server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts
This will fix https://github.com/Azure/azure-functions-dotnet-worker/issues/1958
=> defaulting new dotnet-isolated apps to support placeholders

server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts, server/src/stacks/2020-10-01/stacks/function-app-stacks/Java.ts, server/src/stacks/2020-10-01/stacks/function-app-stacks/Node.ts, server/src/stacks/2020-10-01/stacks/function-app-stacks/Powershell.ts, server/src/stacks/2020-10-01/stacks/function-app-stacks/Python.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Java.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Node.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Php.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Python.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Ruby.ts
Fixes [AB#25472405](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/25472405)
=> [Stacks] Change EOL Date format to prevent month issues

server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20231103130950167 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20231103130950167 to dev

client-react/src/pages/app/functions/function/function-editor/useFunctionEditorQueries.ts
Fixes [AB#25752866](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/25752866)
=> Fixes AB#25752866 Repair item 439467292 - Make sure banner is shown in case of unauthorized error and code editor is not in never ending loading state

server/src/stacks/2020-10-01/stacks/function-app-stacks/Powershell.ts
This PR contains the following change:
* Add `hidden` and `preview` PowerShell 7.4 Function App Stack definition
=> Add PowerShell 7.4 Function App Stack definition

server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Node.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/Python.ts
Fixes [AB#25661937](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/25661937)
Fixes [AB#25794206](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/25794206)
Fixes [AB#25794207](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/25794207)
=> [Stacks] Unhide Node, Python and update .NET8 Early Access

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20231110173036221 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20231110173036221 to dev

client-react/package-lock.json, client-react/src/ApiHelpers/SiteService.ts, client-react/src/models/site/site.ts, client-react/src/pages/app/app-settings/GeneralSettings/Platform.tsx, client-react/src/pages/app/app-settings/Sections/GeneralSettings.tsx, client-react/src/utils/CommonConstants.ts, client-react/src/utils/FwLinks.ts, client-react/src/utils/arm-utils.ts, client-react/src/utils/scenario-checker/linux-site.environment.ts, client-react/src/utils/scenario-checker/scenario-ids.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes: [AB#25475110](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/Germanium/CY23Q4/2Wk/2Wk04%20(Nov%2005%20-%20Nov%2018)?workitem=25475110)
=> AB#25475110 Add end to end encryption for linux app with standard or higher sku

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20231117141013468 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20231117141013468 to dev

client-react/package-lock.json, client-react/package.json, client-react/src/ApiHelpers/ACRService.ts, client-react/src/ApiHelpers/ArmHelper.ts, client-react/src/ApiHelpers/HttpClient.ts, client-react/src/ArmHelper.types.ts
[AB#25891035](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/25891035)
Address [security vulnerability ](https://security.snyk.io/vuln/SNYK-JS-AXIOS-6032459) by updating `axios` to 1.6.2.
#7471
=> Update axios to 1.6.2 in /client-react

client-react/src/utils/dependency/Dependency.ts
FixesAB#[25911493](https://msazure.visualstudio.com/Antares/_workitems/edit/25911493)
=> [DC] Update ACR hidden tag to only include subscriptionId

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSource.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.tsx
Task#[17296425](https://msazure.visualstudio.com/Antares/_workitems/edit/17296425)
**Before (save button would also be disabled when making changes)**
**After**
=> [DC] Handle case where scmType on container is not valid

client-react/src/ApiHelpers/ResourceManagementService.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.data.ts, client-react/src/pages/app/deployment-center/DeploymentCenterConstants.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.tsx, client-react/src/utils/CommonConstants.ts
FixesAB#[25837727](https://msazure.visualstudio.com/Antares/_workitems/edit/25837727) and [25910552](https://msazure.visualstudio.com/Antares/_workitems/edit/25910552)
=> [DC] Fix federated credential name generation and register ManagedIdentity provider

client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/DeploymentCenterFormBuilder.ts, client-react/src/pages/app/deployment-center/authentication/DeploymentCenterAuthenticationSettings.tsx, client-react/src/utils/FwLinks.ts, client-react/src/utils/rbac-constants.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
* [DC] Check for both managed identity and role assignment write permissions on resource group
* Update error message
=> [CP][DC][OIDC] Check for both managed identity and role assignment write permissions on resource group (#7499)

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20231201141610382 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20231201141610382 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20231205141251443 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20231205141251443 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20231219140922060 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20231219140922060 to dev

server/src/workflows/2020-12-01/WorkflowService.ts, server/src/workflows/2020-12-01/web-app-configs/wordpress-linux.config.yml, server/src/workflows/2022-10-01/WorkflowService.ts, server/src/workflows/2022-10-01/web-app-configs/wordpress-linux.config.yml, server/src/workflows/WorkflowModel.ts, server/src/workflows/workflow.controller.ts
Adding GitHub workflow file for WordPress. This is required for enabling continuous deployment for WordPress App Service.
=> Adding GitHub workflow file for WordPress

client-react/src/pages/app/deployment-center/DeploymentCenterFormBuilder.ts, client-react/src/pages/app/deployment-center/authentication/DeploymentCenterAuthenticationSettings.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, server/Resources/Resources.resx
=> [DC][OIDC] Remove preview tag and default to user-assigned identity

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20240109141525559 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20240109141525559 to dev

client-react/src/ApiHelpers/ArmHelper.ts, client-react/src/ApiHelpers/ManagedIdentityService.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.data.ts, client-react/src/pages/app/deployment-center/authentication/DeploymentCenterAuthenticationSettings.tsx
FixesAB#[26394227](https://msazure.visualstudio.com/Antares/_workitems/edit/26394227)
Was not getting all results for list user-assigned identities call
Also switching to use ComboBox instead of Dropdown for autocomplete feature and to keep UI consistent on form
=> [DC] Make paged arm call to list user assigned identities

client-react/src/components/IconGridCell/IconGridCell.tsx, client-react/src/pages/app/deployment-center/DeploymentCenter.styles.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeLogs.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceKuduConfiguredView.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCommitLogs.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterGitHubActionsCodeLogs.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterVSTSCodeLogs.tsx, client-react/src/pages/app/deployment-center/devops-provider/DeploymentCenterVstsDisconnect.tsx, client-react/src/utils/constants/IconConstants.ts
Task#[13016324](https://msazure.visualstudio.com/Antares/_workitems/edit/13016324)
=> [DC][ProjectSpotlight] Add error icons for failed logs

client-react/src/SiteState.ts, client-react/src/pages/app/SiteRouter.tsx, client-react/src/pages/app/app-settings/GeneralSettings/LinuxStacks/LinuxStacks.tsx, client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeBuildConfiguredView.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeBuildRuntimeAndVersion.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceAndBuild.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.tsx, client-react/src/utils/CommonConstants.ts, client-react/src/utils/arm-utils.ts
… (#7532)
* Adding GitHub workflow file for WordPress
* Adding comment for WordPress workflow feature
* Enabling code integration view for WordPress linuxFxVersions
* adding comment with wordpress runtime stack option
=> Enabling code integration view for WordPress App in Deployment Center

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx
https://portal.microsofticm.com/imp/v3/incidents/details/459419665/home
=> [DC] Only do OIDC deployment for GHA

client-react/package-lock.json, client/package-lock.json, server/package-lock.json
=> Bump follow-redirects to 1.15.5

client-react/src/components/form-controls/formControl.override.styles.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterFormBuilder.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceAndBuild.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.tsx, server/Resources/Resources.resx
* [DC] Check on GHA BuildProvider and punycode non-ASCII characters
* Fix styling for combobox error message and change wording on validation error
* Update form validation
* Push update to validation
=> [CP][DC] OIDC permissions on release s231

client-react/src/components/form-controls/formControl.override.styles.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterFormBuilder.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceAndBuild.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.tsx, server/Resources/Resources.resx
* [DC] Check on GHA BuildProvider and punycode non-ASCII characters
* Fix styling for combobox error message and change wording on validation error
* Update form validation
* Push update to validation
=> [CP][DC] OIDC Permissions on release-s228 (#7546)

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20240123141232432 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20240123141232432 to dev

client/src/app/shared/services/scenario/function-app.environment.ts
fixes [AB#26135023](https://msazure.visualstudio.com/Antares/_workitems/edit/26135023)
=> disable TIP for workflow apps

client-react/src/ApiHelpers/AppInsightsService.ts, client-react/src/models/app-insights.ts
Implemented new functions orchestrations query
Link to backend PR: https://github.com/Azure/azure-functions-durable-extension/pull/2302
=> [Functions] Orchestrations New Query

client/src/app/shared/models/portal-resources.ts, client/src/app/site/slots/deployment-slots/deployment-slots.component.html, client/src/app/site/slots/deployment-slots/deployment-slots.component.ts, server/Resources/Resources.resx
fixes [AB#26134876](https://msazure.visualstudio.com/Antares/_workitems/edit/26134876)
=> add deployment slots preview tag for workflow apps

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20240130174344566 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20240130174344566 to dev

client-react/src/pages/app/app-settings/GeneralSettings/Platform.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
FixesAB#[26631629](https://msazure.visualstudio.com/Antares/_workitems/edit/26631629)
**Before**
**After**
=> [Configuration] Create separate toggles for FTP and SCM basic publishing credentials

server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20240202140946814 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20240202140946814 to dev

client-react/src/pages/app/deployment-center/DeploymentCenterFormBuilder.ts
FixesAB#[26800311](https://msazure.visualstudio.com/Antares/_workitems/edit/26800311)
=> [DC] Add validation for Azure Repos set up

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20240213180930575 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20240213180930575 to dev

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeBuildRuntimeAndVersion.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.tsx
FixesAB#[26568592](https://msazure.visualstudio.com/Antares/_workitems/edit/26568592)
=> [DC] Add client changes to detect dotnet isolated for windows function apps

client/src/app/shared/services/scenario/azure.environment.ts, client/src/app/site/slots/add-slot/add-slot.component.ts
Fixes [AB#26875368](https://msazure.visualstudio.com/Antares/_workitems/edit/26875368)
Fixes [AB#26875363](https://msazure.visualstudio.com/Antares/_workitems/edit/26875363)
=> updating slots quota and removing slots opt-in for Workflow Standard SKU

server/src/workflows/2022-10-01/WorkflowService.ts
This reverts commit 5dc60a44d148d897f212d9c640a643af6a4ce4a4.
=> [CP] Revert "[DC] Add punycode encoding for site and slot name in GHA workflow file" (#7588)

client-react/src/components/EditModeBanner/EditModeBanner.tsx, client-react/src/models/portal-models.ts, client-react/src/pages/app/functions/common/VsCodeForTheWebHelper.ts, client-react/src/pages/app/functions/function/function-editor/FunctionEditor.tsx, client-react/src/utils/SiteHelper.ts, client-react/src/utils/app-state-utils.tsx, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
- Added clickable banner for VS Code Web editing
- Applicable only to python and flex consumption function apps
=> [Functions] [Code + Test] Edit in VS Code Web

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20240305190711835 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20240305190711835 to dev

client/package-lock.json
- `es5-ext` 0.10.64
- `ip` 1.1.9
=> chore: Update dependencies in /client

server/Resources/Resources.resx
Fixes [AB#27112866](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/27112866)
=> AB#27112866 [SWA] [Snippets] Remove preview tag

client-react/src/mocks/ArmMocks.ts, client-react/src/models/site/config.ts, client-react/src/pages/app/app-settings/FunctionRuntimeSettings/RuntimeScaleMonitoring.tsx
Cherry-pick #7624 to dev
[AB#27264546](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/27264546)
=> [Functions] Unable to enable/disable runtime scale monitoring

client-react/package-lock.json
Resolve merge conflict in #7629
=> Bump webpack-dev-middleware from 5.3.3 to 5.3.4 in /client-react

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeLogs.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterGitHubActionsCodeLogs.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterVSTSCodeLogs.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.tsx
FixesAB#[26888716](https://msazure.visualstudio.com/Antares/_workitems/edit/26888716)
**After**
Double checking GHA logs and VSTS logs
=> [DC] Sanitize log messages to redact sensitive info

server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20240405130851363 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20240405130851363 to dev

gulpfile.js, package-lock.json, package.json
Remove `gulp-inline-source` and gulp task using it to fix two High severity vulnerabilities.
=> Bump gulp to 5.0.0 in /

server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20240412130855559 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20240412130855559 to dev

client-react/src/pages/app/app-settings/Sections/GeneralSettings.tsx, client-react/src/pages/app/deployment-center/DeploymentCenterConstants.ts, client/src/app/shared/models/portal-resources.ts
FixesAB#[27454993](https://msazure.visualstudio.com/Antares/_workitems/edit/27454993)
**Before**
**After**
=> [Configuration] Hide Stack Settings for sitecontainers

client-react/src/utils/CommonConstants.ts
Backend Wi link:
[Task 25839625](https://msazure.visualstudio.com/Antares/_workitems/edit/25839625): Add support for 5k character limits
=> Increase snippet size to 5k character to match backend

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20240416133726729 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20240416133726729 to dev

client-react/src/pages/app/app-settings/GeneralSettings/Platform.tsx, client-react/src/utils/scenario-checker/container.environment.ts, client-react/src/utils/scenario-checker/linux-site.environment.ts, client-react/src/utils/scenario-checker/scenario-ids.ts, client-react/src/utils/scenario-checker/windows-code.environment.ts, client-react/src/utils/scenario-checker/workflow-app.environment.ts
Fixes: [AB#26994391](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/Dilithium/CY24Q2/2Wk/2Wk02%20(Apr%2021%20-%20May%2004)?workitem=26994391)
Enable gRPC for windows but add 'gRPC only' for linux only
=> AB#26994391 Enable gRPC for windows

server/src/stacks/2020-10-01/stacks/function-app-stacks/Powershell.ts
Unhide PowerShell 7.4 runtime for Linux
=> Unhide PowerShell 7.4 runtime for Linux

server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20240430131458375 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20240430131458375 to dev

client-react/src/pages/app/app-settings/GeneralSettings/Platform.tsx, client/src/app/shared/models/portal-resources.ts
FixesAB#[27931187](https://msazure.visualstudio.com/Antares/_workitems/edit/27931187)
**Before**
**After**
=> [Configuration] Fix FTP basic auth radio button

server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts
fixes [AB#24839495](https://msazure.visualstudio.com/Antares/_workitems/edit/24839495)
=> Adding EOL date for .NET 7 in web app stacks

server/src/deployment-center/github/github.controller.ts
=> 27798416[Starshot][Route] Store app location and use the location to find static config file

server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts, server/src/tests/Stacks/2020-10-01/function-app/validations.ts
This is preparing for where we will have this stack in the future. I have used `isHidden` to prevent this from actually going out too early, but please let me know if another mechanism is preferred.
=> Preparing for Functions .NET 8 in-proc

client-react/package-lock.json
Address https://security.snyk.io/vuln/SNYK-JS-EJS-6689533
=> Bump ejs to 3.1.10 in /client-react

server/src/stacks/2020-10-01/stacks/function-app-stacks/Powershell.ts
Add end of life date for PowerShell 7.4
=> Add end of life date for PowerShell 7.4

client-react/src/utils/CommonConstants.ts
=> [DC] Remove unused experimentation variable

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx
FixesAB#[26013865](https://msazure.visualstudio.com/Antares/_workitems/edit/26013865)
=> [DC] Pass in slot name for federated credential id subject for web app

server/src/functions/functions.service.ts
- Improved handling passthrough api error
=> [Functions][Code + Test] Handle Passthrough API Error

client-react/src/models/site/site.ts, client-react/src/pages/app/app-settings/GeneralSettings/Platform.tsx, client-react/src/utils/scenario-checker/azure.environment.ts, client-react/src/utils/scenario-checker/scenario-ids.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Fixes: [Ab#28108663](https://msazure.visualstudio.com/Antares/_workitems/edit/28108663)
=> AB#28108663 Support ipmode for premium, workflow standard and elstic premium sku apps

client-react/src/utils/CommonConstants.ts, client-react/src/utils/arm-utils.ts, client-react/src/utils/scenario-checker/premium.environment.ts
Task: [27589955](https://msazure.visualstudio.com/Antares/_workitems/edit/27589955/)
After Removing custom error pages  Premium banner: 
Please ignore the string name. My build wasn't working with spring right/
Before:
=> [environment] Add Isolated MV2 SKU

client-react/package-lock.json
Address [SNYK-JS-BRACES-6838727](https://security.snyk.io/vuln/SNYK-JS-BRACES-6838727) by updating from 3.0.2 to 3.0.3.
=> Bump braces to 3.0.3 in /client-react

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20240614131706671 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20240614131706671 to dev

client/package-lock.json
Address [SNYK-JS-BRACES-6838727](https://security.snyk.io/vuln/SNYK-JS-BRACES-6838727) by updating from 3.0.2 to 3.0.3.
=> Bump braces to 3.0.3 in /client

server/package-lock.json
Address [SNYK-JS-BRACES-6838727](https://security.snyk.io/vuln/SNYK-JS-BRACES-6838727) by updating from 3.0.2 to 3.0.3.
=> Bump braces to 3.0.3 in /server

client-react/src/pages/app/app-settings/AppSettings.tsx
Fixes: [AB#28520007](https://msazure.visualstudio.com/Antares/_workitems/edit/28520007)
=> AB#28520007 [Accessibility] - add aria label for link

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20240702132518350 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20240702132518350 to dev

client-react/src/pages/app/deployment-center/external-provider/DeploymentCenterExternalProvider.tsx
=> [DC] Fix other case for private external git repos

client-react/src/AzureDevOpsService.ts
FixesAB#[28549018](https://msazure.visualstudio.com/Antares/_workitems/edit/28549018)
=> [DC] Update DevOps API version from 2 to 7

server/src/deployment-center/acr/acr.controller.ts, server/src/deployment-center/bitbuckets/bitbuckets.controller.ts, server/src/deployment-center/github/github.controller.ts, server/src/shared/http/http.service.ts
* Parse error message in sendHTTPRequest and GitHub failure logs
* Add cancelWorkflow error handling
* Revert "Add cancelWorkflow error handling"
This reverts commit 59dd69c718458753959b247eb30cff3b3dee4d0e.
* Revert "Parse error message in sendHTTPRequest and GitHub failure logs"
This reverts commit bd40b0ba16be746f75e3c7edba98bd1d7942519e.
* Add axios error handling on deployment center server code
=> [CP] Handle AxiosErrors on Deployment Center server code (#7722)

server/package-lock.json, server/package.json, server/src/home/home.module.ts, server/src/home/home/home.controller.ts
[AB#28634824](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/28634824)
- Add `@nestjs/cache-manager` 2.2.2
- Fix `test` script
=> Update @nestjs npm packages from 8.4.7 to 10.3.10

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, server/src/workflows/2022-10-01/web-app-configs/aspnet-windows.config.yml, server/src/workflows/2022-10-01/web-app-configs/dotnetcore-linux.config.yml, server/src/workflows/2022-10-01/web-app-configs/dotnetcore-windows.config.yml, server/src/workflows/2022-10-01/web-app-configs/java-jar-linux.config.yml, server/src/workflows/2022-10-01/web-app-configs/java-jar-windows.config.yml, server/src/workflows/2022-10-01/web-app-configs/java-war-linux.config.yml, server/src/workflows/2022-10-01/web-app-configs/java-war-windows.config.yml, server/src/workflows/2022-10-01/web-app-configs/node-linux.config.yml, server/src/workflows/2022-10-01/web-app-configs/node-windows.config.yml, server/src/workflows/2022-10-01/web-app-configs/php-linux.config.yml, server/src/workflows/2022-10-01/web-app-configs/php-windows.config.yml, server/src/workflows/2022-10-01/web-app-configs/python-linux.config.yml, server/src/workflows/2022-10-01/web-app-configs/python-windows.config.yml, server/src/workflows/2022-10-01/web-app-configs/wordpress-linux.config.yml
Reverts Azure/azure-functions-ux#7709
=> Revert "[Workflow File] Add RG to Workflow File"

server/src/deployment-center/github/github.controller.ts, server/src/deployment-center/github/github.ts
… files anywhere in the repo instead of just the root (#7727)
* 28562886[Starshot][Routes] We need to detect staticwebapp.config.json files anywhere in the repo instead of just the root
=> [CP] 28562886[Starshot][Routes] We need to detect staticwebapp.config.json files anywhere in the repo instead of just the root (#7727) 

server/package-lock.json, server/package.json, server/src/home/home.module.ts, server/src/home/home/home.controller.ts
This reverts commit bb647c6bedb733e02c681973d9eb8d37465ffbe9.
=> Revert "Update @nestjs npm packages from 8.4.7 to 10.3.10 (#7724)"

client-react/src/pages/static-app/configuration/ConfigurationDataLoader.tsx
A small change so that the experimentation value for the new configuration and snippets blade is retrieved correctly
=> [SWA] Fixing Snippets Experimentation

server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts
=> unhiding .NET 8 in-proc for Linux (#7723)

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20240726131835486 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20240726131835486 to dev

server/gulpfile.js, server/package-lock.json, server/package.json
Revert gulpfile.js changes from these commits:
- 158501910
- ead457fb0
Revert " Update gulp from 4.0.2 to 5.0.0 (#7743)"
=> Revert gulpfile.js changes

client-react/src/models/site/site.ts, client-react/src/pages/app/app-settings/AppSettingsDataLoader.tsx, client-react/src/pages/app/app-settings/GeneralSettings/Platform.tsx, client-react/src/pages/app/app-settings/Sections/GeneralSettings.tsx, client-react/src/utils/FwLinks.ts, client-react/src/utils/scenario-checker/dynamic-linux.environment.ts, client-react/src/utils/scenario-checker/flex-consumption-site.environment.ts, client-react/src/utils/scenario-checker/scenario-ids.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> [Functions] Update functionsRuntimeAdminIsolationEnabled in settings

server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20240802135021158 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20240802135021158 to dev

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20240806131612134 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20240806131612134 to dev

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx
Task#[28962117](https://msazure.visualstudio.com/Antares/_workitems/edit/28962117)
=> [DC] Add telemetry to differentiate public vs private external git

tools/pipelines/production-build.yml
Update vmImage and localization to fix onprem-dev pipeline
=> Fix pipeline for onprem-dev

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeDataLoader.tsx
Cherry pick of https://github.com/Azure/azure-functions-ux/pull/7795
=> [CP][DC][Code] Fix initial values settings in CodeForm (#7795)

client-react/src/pages/app/change-app-plan/ChangeAppPlanDestinationPlanDetails.tsx
=> [Change ASP] Adding sku picker inputs

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx
- When using a FlightVariable, you have to use getBooleanFlight instead of hasFlightEnabled
=> [DC] Fix experimentation check for removing deploy environment

server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts
Initially preparing as a draft PR while we wait for this to be ready.
This is the set of changes required to enable the preview for Linux on Azure Functions.
=> Unhiding .NET 9 on Functions for Linux

server/Resources/Resources.resx
A localized stirng was missing
=> [Configuratiion] Add session affinity proxy label

client-react/src/pages/app/app-settings/GeneralSettings/Platform.tsx, client-react/src/utils/scenario-checker/dynamic-linux.environment.ts, client-react/src/utils/scenario-checker/flex-consumption-site.environment.ts, client-react/src/utils/scenario-checker/function-app.environment.ts, server/Resources/Resources.resx
Fixes [AB#29512308](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/29512308)
=> [Functions] Show warning for admin isolation change

client-react/package-lock.json, client-react/package.json
- `rollup` 4.22.4 (1 high severity vulnerability)
- `vite` 5.4.7 (2 medium severity vulnerabilities)
=> Bump npm packages in /client-react to address security vulnerabilities

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20240927131302135 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20240927131302135 to dev

client-react/src/pages/app/app-settings/GeneralSettings/WindowsStacks/JavaStack.tsx, client-react/src/utils/CommonConstants.ts
Cherry pick java component change to fix discard button, and minor version doesn't auto select auto-update version when making selection on major version
=> update component (#6943)

client-react/src/pages/app/deployment-center/DeploymentCenterCommandBar.tsx
Task#[29652129](https://msazure.visualstudio.com/Antares/_workitems/edit/29652129)
=> [DC] Differentiate feedback between FunctionApp and AppService DeploymentCenter

server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20241001130621803 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20241001130621803 to dev

server/src/stacks/2020-10-01/stacks/function-app-stacks/Node.ts
Related to https://github.com/Azure/azure-functions-nodejs-library/issues/252
cc @vrdmr @MadhuraBharadwaj-MSFT
=> Unhide Functions Node.js 22 Preview

server/src/stacks/2020-10-01/stacks/function-app-stacks/Node.ts
=> Unhide Functions Node.js 22 Preview (#7841)

server/src/stacks/2020-10-01/stacks/web-app-stacks/Dotnet.ts
=> set onprem dotnet 6 EOL

client-react/src/pages/app/app-settings/AppSettingsDataLoader.tsx, client-react/src/pages/app/app-settings/GeneralSettings/Platform.tsx, client-react/src/utils/arm-utils.ts, client-react/src/utils/scenario-checker/scenario-ids.ts, client-react/src/utils/scenario-checker/xenon-site.environment.ts, client/src/app/shared/models/portal-resources.ts
Fixes: [AB#17741947](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/Selenium/CY24Q4/Monthly/10%20Oct%20(Sep%2029%20-%20Oct%2026)?workitem=17741947)
=> AB#17741947 Show SSH for windows container 

server/Resources/Resources.resx
Fixes: [AB#29788483](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/Selenium/CY24Q4/Monthly/10%20Oct%20(Sep%2029%20-%20Oct%2026)?workitem=29788483)
=> AB#29788483 [AppService][GeneralSettings]GA Min TLS Cipher Suite

client-react/src/models/site/site.ts, client-react/src/pages/app/deployment-center/DeploymentCenter.styles.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSettings.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.tsx, client-react/src/utils/CommonConstants.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Task#[28936510](https://msazure.visualstudio.com/Antares/_workitems/edit/28936510)
=> [DC][Sidecars] Add migration to sidecar banner

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSettings.tsx, client-react/src/utils/CommonConstants.ts
https://msazure.visualstudio.com/Antares/_workitems/edit/29927214
=> [AppService][OIDC] Use Production instead of production for default environment subject

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSettings.tsx, client-react/src/utils/CommonConstants.ts
* [AppService][OIDC] Use Production instead of production for default environment subject
* Use constant
---------
=> [Cherry-pick][AppService][OIDC] Use Production instead of production for default environment subject (#7858)

client-react/src/SiteState.ts, client-react/src/models/portal-models.ts, client-react/src/pages/app/SiteRouter.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSourceAndBuild.tsx, client-react/src/utils/CommonConstants.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
Task#[29830004](https://msazure.visualstudio.com/Antares/_workitems/edit/29830004/)
=> [DC][Code] Add migration banner between old and new DC

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20241022131456121 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20241022131456121 to dev

server/src/workflows/2022-10-01/web-app-configs/dotnetcore-windows.config.yml
Fixes [AB#29939346](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/29939346)
=> [Workflows] Add quotes for dotnet root

client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeForm.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterCodeSettings.tsx, server/src/workflows/2022-10-01/WorkflowService.ts, server/src/workflows/2022-10-01/web-app-configs/node-linux-oryx.config.yml
Fixes [AB#29996401](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/29996401)
Would address https://github.com/Azure/webapps-deploy/issues/229
=> node oryx workflow

server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20241025130606561 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20241025130606561 to dev

client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSettings.tsx, client-react/src/pages/app/deployment-center/utility/DeploymentCenterUtility.tsx
FixesAB#[29961111](https://msazure.visualstudio.com/Antares/_workitems/edit/29961111)
=> [DC][Sidecars] When using private registry with no credentials, treat it as public

client-react/src/pages/app/deployment-center/DeploymentCenter.types.ts, client-react/src/pages/app/deployment-center/code/DeploymentCenterVSTSCodeLogs.tsx
FixesAB#[29610236](https://msazure.visualstudio.com/Antares/_workitems/edit/29610236)
=> [DC] Fix VSTS source version link

client-react/package-lock.json, client-react/package.json
[AB#30051935](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/30051935)
Since migrating to vite, we no longer use webpack for the builds so remove this vulnerable package.
=> [Fusion] Remove monaco-editor-webpack-plugin

client-react/src/components/CustomBanner/CustomBanner.styles.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSettings.tsx, client-react/src/utils/FwLinks.ts
FixesAB#[29975561](https://msazure.visualstudio.com/Antares/_workitems/edit/29975561)
**Before**
**After**
=> [DC][Sidecars] Add learn more link to sidecar migration banner

client-react/src/components/CustomBanner/CustomBanner.styles.ts, client-react/src/pages/app/deployment-center/container/DeploymentCenterContainerSettings.tsx, client-react/src/utils/FwLinks.ts
=> [Cherry-pick][DC][Sidecars] Add learn more link to sidecar migration banner (#7892)

client-react/src/pages/app/app-settings/GeneralSettings/Platform.tsx, client-react/src/utils/FwLinks.ts, client/src/app/shared/models/portal-resources.ts, server/Resources/Resources.resx
=> AB#27821357 Add warning if min TLS version is 1.0 or 1.1

server/src/stacks/2020-10-01/stacks/web-app-stacks/Java.ts, server/src/stacks/2020-10-01/stacks/web-app-stacks/JavaContainers.ts
Update new Java and Java container stacks for OnPrem
=> Update Java and Java container stacks

client-react/src/pages/app/app-settings/GeneralSettings/LinuxStacks/LinuxStacks.tsx
Fixes: [AB#28899917](https://msazure.visualstudio.com/Antares/_sprints/taskboard/ANTUX/Antares/Selenium/CY24Q4/Monthly/11%20Nov%20(Oct%2027%20-%20Nov%2030)?workitem=28899917)
=> AB#28899917 [Linux][Configuration][Stack] filter out deprecated stack options

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20241112140922085 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20241112140922085 to dev

server/src/stacks/2020-10-01/stacks/function-app-stacks/Java.ts
Reverts Azure/azure-functions-ux#7900
=> Revert "azure functions: java21 GA"

server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20241115140928916 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20241115140928916 to dev

client-react/src/pages/app/app-settings/Sections/GeneralSettings.tsx, client-react/src/utils/scenario-checker/scenario-ids.ts, client-react/src/utils/scenario-checker/workflow-app.environment.ts
* disable stack settings version update for logic app
* update stack error string
* update siterouter
* hide stack settings for logic app
* use a scenario instead
* remove unused imports
---------
=> [Cherry-pick] AB#30275542 Hide stack settings for logic app (#7912)

client-react/src/pages/app/change-app-plan/ChangeAppPlanDestinationPlanDetails.tsx
Before:
After:
Note: Have another PR to show EP skus
=> Add p0v3 to forbidden sku list

server/src/workflows/2022-10-01/WorkflowService.ts
Fixes [AB#30327402](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/30327402)
W/ Exp
Oidc
Publishing profile
W/O Exp
Oidc:
Publishing profile
=> [DC] Move environment check

server/src/workflows/2022-10-01/WorkflowService.ts
=> Fix workflow file indent

server/Resources/cs-CZ/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/de-DE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/es-ES/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/fr-FR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/hu-HU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/id-ID/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/it-IT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ja-JP/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ko-KR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/nl-NL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pl-PL/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-BR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/pt-PT/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/ru-RU/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/sv-SE/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/tr-TR/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-CN/LocProject/lcl/Server/Resources/Resources.resx.lcl, server/Resources/zh-TW/LocProject/lcl/Server/Resources/Resources.resx.lcl
LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20241203141228236 to dev with localized lcls
=> LEGO: Pull request from users/csigs/hb_452267ed-f3ea-4b18-a9d2-7c2ed17cef14_20241203141228236 to dev

client-react/src/pages/app/deployment-center/bitbucket-provider/DeploymentCenterBitbucketConfiguredView.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterGitHubActionsCodeLogs.tsx, client-react/src/pages/app/deployment-center/code/DeploymentCenterVSTSCodeLogs.tsx, client-react/src/pages/app/deployment-center/devops-provider/DeploymentCenterVstsBuildConfiguredView.tsx, client-react/src/pages/app/deployment-center/external-provider/DeploymentCenterExternalConfiguredView.tsx
Cherry-picking from [DC] Use href and target instead of onClick for opening URLs #7923
=> [Cherry-pick][DC] Use href and target instead of onClick for opening URLs
